package org.apache.batik.parser;
public interface LengthListHandler extends org.apache.batik.parser.LengthHandler {
    void startLengthList() throws org.apache.batik.parser.ParseException;
    void endLengthList() throws org.apache.batik.parser.ParseException;
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Ye2wcxRmfu/MbJ36E2K5DnNclqpNwp7SliDq0JMbGDuf4" +
                                          "ZAcoTuEytzvn23hvd7I7a59NU0IkSsQfESKmpVXjv4JaEC9VRSBVRKkqFRB9" +
                                          "iBS1PFRo1T/6jET+aVqlLf2+mb3bvbUdKlWqpZubm/nmm+/5+77xs5dIveuQ" +
                                          "rZxaOk2Jec7cVBbnWeq4TB80qesegtWc9ujvzjx45ZfND8VJwxRZW6TumEZd" +
                                          "NmwwU3enyEbDcgW1NOYeZEzHE1mHucyZpcKwrSmy3nBHS9w0NEOM2TpDgrup" +
                                          "kyEdVAjHyHuCjfoMBNmUkdKkpTTpfVGCgQxp1Ww+HxzorTkwGNpD2lJwnytI" +
                                          "e+YonaVpTxhmOmO4YqDskF3cNuenTVukWFmkjpo3+YY4kLlpmRm2vtj2t6uP" +
                                          "FdulGdZRy7KFVNGdYK5tzjI9Q9qC1SGTldxj5GskkSHXhYgFSWYql6bh0jRc" +
                                          "WtE3oALp1zDLKw3aUh1R4dTANRRIkC21TDh1aMlnk5UyA4cm4esuD4O2m6va" +
                                          "VtwdUfGJXenFb97f/v0EaZsibYY1ieJoIISAS6bAoKyUZ467T9eZPkU6LHD4" +
                                          "JHMMahoLvrc7XWPaosKDEKiYBRc9zhx5Z2Ar8CTo5niasJ2qegUZVP6v+oJJ" +
                                          "p0HXrkBXpeEwroOCLQYI5hQoxJ5/pG7GsHQZR7Unqjom7wQCONpYYqJoV6+q" +
                                          "sygskE4VIia1ptOTEHzWNJDW2xCCjoy1VZiirTnVZug0ywnSE6XLqi2gapaG" +
                                          "wCOCrI+SSU7gpd6Il0L+uXRw7+kHrBErTmIgs840E+W/Dg71RQ5NsAJzGOSB" +
                                          "Oti6M/MN2vXqqTghQLw+QqxoXv7q5dt29114XdFsWIFmPH+UaSKnncuvfeuG" +
                                          "wf5bEihGE7ddA51fo7nMsqy/M1DmgDRdVY64mapsXpj4yb0nnmF/iZOWUdKg" +
                                          "2aZXgjjq0OwSN0zm3MEs5lDB9FHSzCx9UO6PkkaYZwyLqdXxQsFlYpTUmXKp" +
                                          "wZa/wUQFYIEmaoG5YRXsypxTUZTzMieENMKHxOCzm6i/PhwEOZou2iWWphq1" +
                                          "DMtOZx0b9UeHSsxhLsx12OV2Og/xP3PjntTNadf2HAjItO1MpylERZGpTcxR" +
                                          "gMV0hlnToogANAJsQMMUxhz/v95WRt3XzcVi4JYboqBgQj6N2KbOnJy26O0f" +
                                          "uvx87k0VcJgkvtUE6YcrU+rKlLwypa5MLbuSxGLypuvxauV8cN0MgADQtPZP" +
                                          "3nfgyKmtCYg6PleHhi/LrNxQ+QEHIyLK/L91kp995+d/+mycxAOoaAth/CQT" +
                                          "A6HwRJ6dMhA7AjkOOYwB3W+ezJ554tIjh6UQQLFtpQuTOA5CWALWAmY9/Pqx" +
                                          "dz/84Nzb8argCQH47OWh1AnSRPMAblQTgjRXUUopdv3H8BeDz7/xgzrigoq4" +
                                          "zkE/7DdX457zkDlict4jyPZrW9+3PBpv42pwIqHw3MnFJX38qT0q6TtrU3QI" +
                                          "KtBzv/rXT1NP/vaNFSKgWdj8RpPNMjMkYRyu3LKspxiTaFupzTnt5otXEu8/" +
                                          "3tMqndeah3YiqOnJmpquWhLH1pgORWW16l6pcDtXr+dREV47+efeQ18sHpEi" +
                                          "hCs08qqH4oIns1hXq9w3RUwZZfn02LNv3LFDezwuSwrC8wqlqPbQQNiocKnD" +
                                          "oHZaqBaurCljgxbJz6gtctrOzfSl3KvHk3FSBzUG6qqggINQsvqil9eUhYFK" +
                                          "3uBVTWCEgu2UqIlblbrYIoqOPResSODoUGEMzpYZ2gufpA+c8ht3uziO3Qpo" +
                                          "JH2fHLfgkFSRgtPtOOyQZJ+GyNkRpCYgvQn4hx5J3mWBs42CQfMmQ9D4Z9v2" +
                                          "PS/99XS7CkoTViou2v3JDIL1T+0nJ968/0qfZBPTsNMI4CMgU+VrXcB5n+PQ" +
                                          "eZSj/NDFjd96jZ6FQgjFxzUWmKwnxIcuFGq/VPtWOe7DDK7N4x2r5bHszYbK" +
                                          "GuMogmR1Ow63AMiB3x0RwCwI13+NPtYxSgCAs34nkD7e+eHMd/74nEr4aNsQ" +
                                          "IWanFh/9OHV6UdlZ9VbblrU34TOqv5LitkunliUeXOMWeWL4Dy8c/+H3jj8S" +
                                          "962WEqRu1jZ0OJxcRbVQt5zTHnv7ozV3f3T+shS0tt0Ol4QxypVsHTh8AWXr" +
                                          "jhalEeoWge5zFw5+pd28cBU4TgFHDYqsO+5AUSzXFBCfur7xvR/9uOvIWwkS" +
                                          "HyYtpk31YYqNLbQnkEHMLUI9LfMv3aayZK4JhnYZIqQaGJWgwVjbtHIUD5W4" +
                                          "kHG38Er3D/Z+d+kDWXskh8/U5mQPfHb5Obnrf8rJ2ugNR/Z9K0c2/hySBDkc" +
                                          "vizwJaMH0YqLd8pD4zjcq4rixH9nG1y4pyxIx7ImA83Ws+x9o3py7fmltqbu" +
                                          "pbt+LQGy2je3QndQ8EwzhL9hLG7gDisYUpNWFTRcfhUE6V4la7EBkBMpOVP0" +
                                          "Bjw9o/SC1MvvMB0Ui5aADlipSZjEFiQBJDjlnJdjtY1S1abrP8mmod5qW016" +
                                          "yXdkpbp56iWZ015YOnDwgcuff0q1WvACXViQ7w54RqmSUa2QW1blVuHVMNJ/" +
                                          "de2Lzdsrmd6hBA5ickMoxO6BeOLo2d4I+LrJKga/e27v+Z+dargIiXqYxKgg" +
                                          "6w6HXnHqyQII7kFWHc6EG5PQfyNkXRho+f2RX/z9vVinzCoJ0giQ1ziR086c" +
                                          "fz9b4PzbcdI8SuoByFh5Cp6l7u3z1gTTZiH/mzzLOOaxUXjxNuRtz6o+Oddi" +
                                          "GFJ8Y0rL+AZdU13FOi/I1uVou7wVAsCZY85+5C67hkhP4XEe3i3jU2wFrcA3" +
                                          "e87+48GvvzMOaVIjeJhbo+vlq+1J+EWreIeAX3W0iVxmjHO/w23cK70KsYvf" +
                                          "J6XSJxQ1UggS28n5fwCMqCJhmRIAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05e+zrVnm+v/u+fdzbAm1XaEvbW7Ti8nMcOy9dXnk4cRIn" +
                                          "juMkTszGrWM7fr/t2DHrBJWAakwMbS1jEvQv0DZUHpqGNmli6jRtgECTmNBe" +
                                          "0gBNk/ZgSPSPPTS2sWPn98jvd3tboUmL5JPjc77zvb/vnPP5pR9C5wMfgl3H" +
                                          "3CimE+7LSbivm6X9cOPKwX6PKo0EP5ClpikEwQSM3RQf+/LVf/vxJ9Rre9AF" +
                                          "HnqDYNtOKISaYwdjOXDMtSxR0NXjUcKUrSCErlG6sBaQKNRMhNKC8AYF3bGz" +
                                          "NISuU4csIIAFBLCA5Cwg9WMosOgu2Y6sZrZCsMPAg34ROkNBF1wxYy+EHj2J" +
                                          "xBV8wTpAM8olABguZe8zIFS+OPGhtx7JvpX5FoFfgJHnf/39137nLHSVh65q" +
                                          "NpuxIwImQkCEh+60ZGsp+0FdkmSJh+6xZVliZV8TTC3N+eahewNNsYUw8uUj" +
                                          "JWWDkSv7Oc1jzd0pZrL5kRg6/pF4K002pcO38ytTUICs9x3LupWwnY0DAa9o" +
                                          "gDF/JYjy4ZJzhmZLIfTI6RVHMl7vAwCw9KIlh6pzROqcLYAB6N6t7UzBVhA2" +
                                          "9DVbAaDnnQhQCaEHb4s007UriIagyDdD6IHTcKPtFIC6nCsiWxJCbzoNlmMC" +
                                          "VnrwlJV27PPD4Ts//gGbtPdyniVZNDP+L4FFD59aNJZXsi/borxdeOfbqU8K" +
                                          "9331uT0IAsBvOgW8hfm9X3jlvU89/PLXtzBvfhUYeqnLYnhT/Ozy7m+/pflk" +
                                          "7WzGxiXXCbTM+Cckz91/dDBzI3FB5N13hDGb3D+cfHn8p4sPfl7+wR50pQtd" +
                                          "EB0zsoAf3SM6lquZst+RbdkXQlnqQpdlW2rm813oIuhTmi1vR+nVKpDDLnTO" +
                                          "zIcuOPk7UNEKoMhUdBH0NXvlHPZdIVTzfuJCEHQRPNAZ8DwFbX8PZ00I6Yjq" +
                                          "WDIiiIKt2Q4y8p1M/sygtiQgoRyAvgRmXQdZAv833oHuV5DAiXzgkIjjK4gA" +
                                          "vEKVt5NZjAayj1CyrYRqlhlIgAZIuJ/5nPv/Si3JZL8WnzkDzPKW00nBBPFE" +
                                          "OqYk+zfF56MG8coXb35z7yhIDrQWQk8Ckvtbkvs5yf0tyf1bSEJnzuSU3piR" +
                                          "3hofmM4ASQDA3Pkk+/O9p5977CzwOjc+lyk+yaPygfzlLFj35O1TdjvLF908" +
                                          "R4rAhR/4T9pcPvt3/5Gzu5t1M4R7rxImp9bzyEuffrD57h/k6y+DBBUKwKFA" +
                                          "7D98OlhPxFcWtafVCPLuMd7i561/3Xvswp/sQRd56Jp4kNRnghnJrAwS6xUt" +
                                          "OMz0IPGfmD+ZlLYReOMg+EPoLaf52iF74zCDZsKf3zUf6GfQWf9K7gp35zD3" +
                                          "/AT8zoDnf7Ins0Q2sA2Fe5sH8fjWo4B03eTMmRA6X9yv7Bey9Y9mNj6t4IyB" +
                                          "d7HuZ/7qz/4J24P2jrP61Z19Eijhxk4myZBdzXPGPccuM/HlTFl/+6nRr73w" +
                                          "w4++L/cXAPH4qxG8nrUZx2BbBNvLh7/u/fX3vvvZ7+wd+djZEGyl0dLURNAJ" +
                                          "8l0OSLLSbMHMFfJYCN2vm+L1Q6lnYNcDjF3XzUquqjeBfT5nLbPK/naryGMK" +
                                          "cHT9Nu66s73fFD/xnR/dNfvRH75yi6eeVMxAcG9sLZRzlQD095+OIlIIVACH" +
                                          "vzz8uWvmyz8GGHmAUQRZIaB9EMXJCTUeQJ+/+Dd/9Mf3Pf3ts9BeG7piOoLU" +
                                          "FrKdGOTTUAWbtwoSQOK+573bfBhfAs21PDahXP43b9nJw/ruY0VQDtgxP/b3" +
                                          "n/jWrzz+PcBHDzq/znwYcLCjrWGUHSI+8tILD93x/Pc/ltsEZN/RJ4lr782w" +
                                          "VnMCT+Ttz2YNvLVY1n0qa96RNfuHZnowMxObZ0FKCMKBI2ngECHllnrN1DHy" +
                                          "NQt42/pgh0Seufd7xqf/8Qvb3e90njgFLD/3/C/9ZP/jz+/tnDkev2Xb312z" +
                                          "PXfkTN91ZMpHX4tKvqL9D1965g9+65mPbrm69+QOSoAD4hf+4r+/tf+p73/j" +
                                          "VRL0OdM5dMqsLR6Qzf5Kr2/Y8I6nSTzo1g9/FLqQi7GYjK1VhAyWPaxMFPul" +
                                          "lj0EZxB3GLsV1tRaXqE3WHZa0Qrn66IziYhNmK7tIqaupUq3IpRqw2mha7AB" +
                                          "syLYvuXO5voa7wlEszYbs43ZuG947XGjpjVYdNQeO+gEKevEBBZmnkmtirC1" +
                                          "xJbr5VTqm5zn8tHSQmzLgpESXKkkQUnqruWI8flEoI1iTxYr4qyxtDnZwyeN" +
                                          "asGTA1kJObEW6etUT/ASvxq2qrNenIx5rjyJLIKXhlYcTzHZ3hDLlqhw6JBe" +
                                          "yDyRkgRqkZG44V2xH/ustcHsBsnW4sKQoAfFidtS/Mg1NoQ0q+vkhoya+soZ" +
                                          "NIbW1JD6hjuZuKtZp6kwiYtyMUwmqeNPjLgzdFtFsxfbm7ArwwvHFmbuJFEt" +
                                          "2qLxhdcKjDYmDiPZnswig2tbhu46GLxY4AZlutbYKq5DvRiWo1FbisyOxI83" +
                                          "lX57NuxIi34pTPVujal5TZTtTEAU66VOYBgsOVcXSpvlFp5ZXqoFfSxyIYE5" +
                                          "dcpF0xbVjzFhqqJjXJrUh+Nx12gW0UlLRYWBaRul6aaOixYuB1ELp4tWeS3M" +
                                          "wliarjq9uWy3l7XKClkXCIEPtOVigWpyz+l22TpbXtad/mbK4+XKpCbzI2Na" +
                                          "psgW3iMHA0F1qLUvVubcSHCCfovoa4vGWKylalLii3W/2pw4JVsTgl7Rk5Up" +
                                          "PxuV17DT67kFcu4bjbkrE7Hv0E2KWXRLKuMkvRLidiqdgGT4cWVqe7pjVWKm" +
                                          "SQ/dxcLrObMy7AUbJTAIfNbVBNQN6QlBptyw1+KKSbOpOxt0xmuaP7FnfKQU" +
                                          "NrHNEuU55WlFBRxyOnGTbvpdmGWnFcWVyl2zQMHRfBxXYIP0G4Q/sbpKUMUL" +
                                          "BMwhLaWCjpnSMKj30g7NNuhQKw+QwbC4nnveRFEZKoYZL3Hm64pXksJiDUXx" +
                                          "udQOuG7bGpHwVGD7ti1G65UcdeJVaUloaoeoSFK9hK6cij0IvA0yQFuW0hpL" +
                                          "s0UZtwQ3mLs6vlkWbNtqIxpPcyBKlKLAzxVd9wp0zA4LqYUNiKBkthq1Nsmm" +
                                          "zaQ2pcsjwxAWfLyhPGmeMEHbXLiTqTXvuzEvIPGUaS+6hCU4ndJiPA82bjKZ" +
                                          "8pN0oMnEcNAnE7qZWmUNGakxQfNOVNQ4zlU9tDUIaT4pLGtTmWSDRKWCBC3S" +
                                          "syKtIMkIG+l2OBkK0qpI1vVuSKMDd2MSY77jTkB2UQazgmraE8dR6sN6L2AG" +
                                          "g2mipsi6VuLGITZPxZmG9xZLx2sojF4eFvtL2u5timW6sIrWSbViFGZiTzHW" +
                                          "4ZQoL0R/Cvt9k4o3rlAaUMuITTrUxgWAQjSrisPCQKm3mHDEjzB7pWz6Vthc" +
                                          "KOWRKZOqhlD+MGFghiC7G6qPUDXUcGu1EiwhsLURkzrtCPVQRZrMpF4m43Gv" +
                                          "LA3UeqWuGzS9iBsYB8tpr1TCw66ulqcMQ7VDl4kmdL3U5OoUV7cWNWTkJVKK" +
                                          "VPFhuqwKvtJkSLxCcypat9nxaFBfmsxE0cfz6dRxpTVGVhtyK60giZL6muJ4" +
                                          "eGoQSKUlzfFSJTVa2VkG1zcj3udqMDZquGu86MZdj4yxgd3uzbGqNyl45Uno" +
                                          "TzGm2w8b6Rrx5xN0OELWwrDN9hVO0qtjdzQc6ANjMd5EGNUP3ESbCO3ITSd2" +
                                          "WHLCORFVESwceLYkCyq20Dygfcv1Ik6lSNRV6DHHoWWz7IqtcO7D0piY4RUY" +
                                          "nJUZtBqQLvDkZlCoeh6JO+CYiqpzrxZj42nM8yu7UKSGa4xqt+Q0jtjYb1Zj" +
                                          "z/RGS4YZao7Yt1sOyQteQ4j8pqkrybKXlpVQDH06XbEm1l+TBtZmG+m0U/Y8" +
                                          "RekOmWDtaWZNnqqLdh+LGrMJ1ySUqDj1uubSXPqLruPRo7EcsHTLmXaIQeou" +
                                          "+KISrdw6LFbVEItSjcYY1+mRxRVJrRSjzY6VcBTS9Ibhe3BnMzTGLnCYNWPj" +
                                          "IG31MItrBHixyawGFlNr4XxtXRyxSK02ZytNw5nMNBAja6zX6lLoBC7YvVq5" +
                                          "ihS8Fd8YTYLhoIs3B8oUnvlzsVGy4REj86yODFttXaqVdb7cZhS9naRTzurH" +
                                          "dtIVo3bHQ2ajkKPlSqvVrwzxpOiXlmSQLpb9TjRwFGuM0nEZqw+0BpYUxnEz" +
                                          "7qIYPByFi4RVmvUAw22jVZFhmRxISAW3CR8XhgHT5QS7rSI1mpyVp5LJ12bL" +
                                          "pQm8Bp/Q3rpEaaER2aY2lef0gJM5Cm9tqiICk5iuV9laucgR3jhCdb5A9xJx" +
                                          "vJwxYSmdkPa64qQzbIVN4EBlC2FYoE2cSTbuLCAnarXOzX1dFUxCdjhFLqXt" +
                                          "uAS7UrEqNqb4RGmTrYUX0HCpPmXTebvRXEV+JVmPkVpEr7tcDHa3zSJ0DQwF" +
                                          "yX5ILRnbIMgBNe3WqNVgjQnChu/jPdVe8F2PETo9Toln+jIku9NWicMNsoNV" +
                                          "CR9rITwswUaLmweGWkWmJYsZrchliV7a/qrq94qRMhwjfK1fEIuIumEbLUNc" +
                                          "a2ncEwZkYeFRUtVt4akuerivJWTN7qAb3N0k3aTStepVjAvgpOZg7qaysszQ" +
                                          "W0buMoQpprMp6jLG2BJTJeJUpWoq1akoLS1YTN0h156MxZUKctkMN4UK0TAa" +
                                          "A5eejQoNPa45CNtEB+v1oFGYaiWhDlKAy/I60daYRq+lm3ZP0sMFyqLC0h9V" +
                                          "LcuRSh5XQMubuWS4S7dU1ji+gJYWtN2KFTFarQoeyq3rzflMYypxCR97FjsV" +
                                          "igyHLs1ZRM4Gwx4iyUUqlQLfkspqo17SRGPgJHS5IdOUU5TwLkz5vb4iIHKx" +
                                          "soaBOkFa62pzb5H0FaUcl8m5TXobptutGG2OFMtEpzRiViCQ5mPVgVfF8RxJ" +
                                          "a+uZZqdNp1dQNAZNtXGhWhZXaW2Jj9KlKHWrbOQ0Nm211HTLZiXCUlSZTHiN" +
                                          "RKw0pWhaSKZzPRlG4zAtOzAtSVqn3asuCj4F13lpimJtWkO6aDRzoko8qwdN" +
                                          "flEtwaVmuaIa6gifEzKmYfq0GLd9sY7J1QqMVzvrdTqghVlXl3vq0oHXpgej" +
                                          "PZjgfLkr1+cYV9BmiaWTNBIXMbFfKfSDxXrVK8/ZXsKgU0Vhi1W7tIqbA6/Z" +
                                          "U61xdqx+17uyo3b3p7vt3JNfSo+KmeCSk00UfopTfvJaBEPokrAMQh9cBUPo" +
                                          "8lF1dUt9pypz5vAS/MRrF4EOCkDZXeeh21U183vOZ599/kWJ/hya3XMy1C1A" +
                                          "PnTcd5jyWjZ3CO8BTG+//Z1ukBd1j+suX3v2nx+cvFt9Oi883FIPoqAr2cpR" +
                                          "Vjs/qpE/corP0yh/e/DSNzpvE391Dzp7VIW5pdx8ctGNk7WXK74cRr49OarA" +
                                          "+NBjt1wEHVGWIuBdR3Tf/lbhKze/+sz1Pejcbmkqw/DQqULPHSvHtwQzI3BY" +
                                          "374CLvVOfDyyW/UBas3Lbg+C5/pBATT/z2bf4GbtG5NjD7vFdfaOfHV84Cg+" +
                                          "9LbjgkPTMU1ZzLV+fWpb+f1cWJpyVvz7r6tPoF/5l49f295eTTByaIanXh/B" +
                                          "8fjPNKAPfvP9//5wjuaMmH0xOC6hHINty9BvOMZc931hk/GRfOjPH/qNrwmf" +
                                          "OQud6ULnAi2V87owdFCPzJhSc7HFvFWyEDgZCG+7XSDk31iIRJTdjIUclZ41" +
                                          "N0PoKrCtHx6XS3Nc79kJ4Ca4xK8dTTqO7Kdf7/6u7LCdD7zvpJEfAA98YGT4" +
                                          "/2Tkk+rYVdXm1VWVvRo5wAeyBmSYu7Ii/pH42aB9LGr004iagNR4S905s/YD" +
                                          "t3zy2n6mEb/44tVL9784/cs8no4+pVymoEuryDR3S6U7/QuuL6+0XIbL2xBy" +
                                          "879nQ+j+2zhAVmjMOznPH9rCfziErp2GD6Hz+f8u3HMhdOUYDqDadnZBPhZC" +
                                          "ZwFI1v3lrCK7kywPPCDX5r2vp82jJbsl1SzB5p8WD5NhtP24eFP80ou94Qde" +
                                          "KX9uW9IVTSFNMyyXKOjiNvscJdRHb4vtENcF8skf3/3ly08cJv+7twwfe+MO" +
                                          "b4+8el4gLDfMIzn9/ft/952/+eJ387Li/wK1MGoF8x0AAA==");
}
