package org.apache.batik.dom.svg;
public interface SVGTextContent {
    int getNumberOfChars();
    java.awt.geom.Rectangle2D getExtentOfChar(int charnum);
    java.awt.geom.Point2D getStartPositionOfChar(int charnum);
    java.awt.geom.Point2D getEndPositionOfChar(int charnum);
    float getRotationOfChar(int charnum);
    void selectSubString(int charnum, int nchars);
    float getComputedTextLength();
    float getSubStringLength(int charnum, int nchars);
    int getCharNumAtPosition(float x, float y);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188908000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVaC3BU1Rk+u3mQhJAXJLzDK9AGcVewajFUCSFAYIEliXEM" +
                                          "j+Xm7kly4e69l3vPhg2KRWcs2CmIiM8qtlMcH1WxTh3t+Bg6fShVOyNlFHx3" +
                                          "bOuTKnX6mKHV/v85d/fevdlskGQzc//cPec/5/znO//rnHMfPU0KLJPUUo0F" +
                                          "WL9BrUCzxsKSadFokypZVjuUReQ786QvN320ZqGfFHaSsl7JWi1LFl2mUDVq" +
                                          "dZKpimYxSZOptYbSKLYIm9SiZp/EFF3rJNWK1RIzVEVW2Go9SpGhQzJDpFJi" +
                                          "zFS64oy22B0wMjUEkgS5JMFGb3VDiJTKutHvsE9wsTe5apAz5oxlMVIR2iL1" +
                                          "ScE4U9RgSLFYQ8IkFxi62t+j6ixAEyywRb3EhmBl6JIBEMx8ovxfZ/f3VnAI" +
                                          "xkqapjM+PauVWrraR6MhUu6UNqs0Zm0j15O8EBntYmakLpQcNAiDBmHQ5Gwd" +
                                          "LpB+DNXisSadT4cleyo0ZBSIkRnpnRiSKcXsbsJcZuihiNlz541httNTsxWz" +
                                          "HDDF2y8IHrxzU8WTeaS8k5QrWhuKI4MQDAbpBEBprIuaVmM0SqOdpFKDxW6j" +
                                          "piKpyg57passpUeTWByWPwkLFsYNavIxHaxgHWFuZlxmupmaXjdXKPtXQbcq" +
                                          "9cBca5y5ihkuw3KYYIkCgpndEuid3SR/q6JFGZnmbZGaY90qYICmo2KU9eqp" +
                                          "ofI1CQpIlVARVdJ6gm2geloPsBbooIAmI5MG7RSxNiR5q9RDI6iRHr6wqAKu" +
                                          "Yg4ENmGk2svGe4JVmuRZJdf6nF6zaN+12grNT3wgc5TKKso/GhrVehq10m5q" +
                                          "UrAD0bB0bugOqeb5PX5CgLnawyx4nr7uzOJ5tUdfEjyTM/Cs7dpCZRaRD3eV" +
                                          "vTalqX5hHopRZOiWgoufNnNuZWG7piFhgIepSfWIlYFk5dHW31+z6xH6qZ+U" +
                                          "tJBCWVfjMdCjSlmPGYpKzeVUo6bEaLSFFFMt2sTrW8goeA8pGhWla7u7Lcpa" +
                                          "SL7Kiwp1/hsg6oYuEKISeFe0bj35bkisl78nDELIKHiID57bifibhoSRzmCv" +
                                          "HqNBSZY0RdODYVPH+VtB8DhdgG1vsAu0fmvQ0uMmqGBQN3uCEuhBL7Uronos" +
                                          "aPWBKnUsbwcD4nYEXhZ1zMhp7wmc29jtPh/APsVr9CrYywpdjVIzIh+ML2k+" +
                                          "83jkZaFQaAQ2Kox8CwYMiAEDfMAADBiAAQPpAxKfj48zDgcWSwsLsxVMHHxs" +
                                          "aX3bxpWb98zMA50ytucjrAluc5OTP6ChR0Bu3d9rM+47+cePL/YTv+MIyl0e" +
                                          "vI2yBpfyYZ9VXM0qHTnaTUqB7527wrfdfnr3ei4EcMzKNGAd0iZQOvCk4JFu" +
                                          "emnbqffePXzCnxI8j4H3jXdBEGOkSOoC1yXJjJHilA8SExv3Nfz54PkKH5wj" +
                                          "Fgh9qmqylXp6SqsNwwvH1MHMn7uuwzcePBRd+8B8YaRV6SbVDBHjsdf/90rg" +
                                          "rvePZVjRYqYbF6q0j6quMatwyLTYv5p7xmQcjcjvlB344Fd1PUv8JD9EqmDS" +
                                          "cUnFKN5o9kB8kLfaLrS0CxICJy5Pd8VlTChMXaZRCAuDxWe7lyK9j5pYzsg4" +
                                          "Vw/JrAH949zBY7ZX9Bdv/GRS+xW9m7kWuaMwjlYAAQRbhjF2pmLkNA/83i4f" +
                                          "Xv3oseVz5AN+HjbQBWcIN+mNGtwLAYOaFOKjhtPBkjEw6EyvjXrRishzp0tP" +
                                          "RZ7fWcdXoRhiJ5PA10FYqvUOnub6G5LWg0MVAQjduhmTVKxKQl7Cek19u1PC" +
                                          "nUelUGZQkCJUzAnw1NvOkf/H2hoD6XjhbDh/LaczkNRx7fLj62wkczjbt0Hb" +
                                          "5jgGCt5cBZ+HK1J3lQbLrnQrUpdK0XX8t3z2/Kc+21chFFmFkuQSzRu6A6d8" +
                                          "4hKy6+VN/67l3fhkzCYcJ+KwiRA11um50TSlfpQjccPxqXe/KN0HwQ4CjKXs" +
                                          "oDxmENtiUahGPu1FnC721DUh+S5knz2UrYlj+rS2u6kXFB6Gm+nYHSp4Wxy8" +
                                          "SthUYuDR+uzAvSC8Wd5TF/6LsPeJGRoIvuqHgns73tjyCtf0IjTFlH65DA1M" +
                                          "1rXGFXxF0OfUZ0mD0+UJ7qx6b+u9Hz0m5PFmHR5muufgD78O7DsollCkZrMG" +
                                          "ZEfuNiI980g3I9sovMWyD4/sfPahnbv9NujzGMlT7KwZF8THF4RHqXQEhZxL" +
                                          "by5/bn9V3jKwrRZSFNeUbXHaEk232lFWvMsFqZPJCRt2SYz+HqLiXMNA4esG" +
                                          "gdaV7Efk/Se+GNPxxQtnOFDpuwV3zFstGQKbSiQLsfvx3qi7QrJ6ge87R9ds" +
                                          "qFCPnoUeO6FHGTIIa60JMT+RFiFt7oJRb/76NzWbX8sj/mWkRNWl6DIJ83LI" +
                                          "rsA5UKsX0oWEceVi4QC2o0uo4BpOBuj8gAK0q2mZLbY5ZjBuYzueGf/LRQ8e" +
                                          "epdHWxERL0o5oIpkRrbIdkCLhuWA0k3V1gz8uZwzdGWx5SiSjbAmYMvNCUx+" +
                                          "bFvG8gmMTOTTlLazQA+FXKkV5gk7CZUuWMo52pBsEgh1nCeYWLDBi1Ap1s2E" +
                                          "J2wjFM4lQtuyIMQLISLWAEKQHJgsmeWnA1WdDlRYB2N1gxTLFUjT4aE2SDSX" +
                                          "IO3KAtKNSK6FBAfVSIumQ4R1cQeJ63KARAnWTYZnl43ErlwisTcLErcg2cNI" +
                                          "JSDRavs8l6Y02yEA/61wvYcYJjW6NMDB4891CQe9m3OAHq+bD88+G719I4ie" +
                                          "3+Fa7kB4fxYIf4rkHvBJFkW/CimBOLjIBFp+n65EHXR+nCvdQme930Zn/wii" +
                                          "4573kSx1v0DyCLgZUCvccsVho4U7VthQ9Ih9/60OCj/PFQpT4Dlgo3Ag5zry" +
                                          "XBY8XkDyNOw/0SsnFSQjGM/kAIyiJBgHbTAO5gaMWznhXMeygPEykt8K74ue" +
                                          "BpLyxlSY4ng6cPxupOHgZwGZDwdqnKNHcc4W4Ee9kEUOA55k4ou/Ie5W8LiL" +
                                          "YwTEGLzRG1nQektIj+Q4LziZWRDuemcLGZC8juRNJG8zUki3xSXVyuSSRnXp" +
                                          "ukolzcH8+FCYZxb0b4PBj/Q9JO8j+QDJX5F8mLY8zgRHwDd9lqXu7+cIqBgP" +
                                          "A52iSaoD7KdITiP5nJEi1GHUkgGHOHxr6Do5/vOaKSX61nCl2LdlOULxNtyr" +
                                          "HHr1D/8sv0E0TN8o8lsHu6m33amTeQtGs7pb+IY0HzekKPPoECmwkBMPiAa9" +
                                          "weB9iZ1O2ZB2U+3YDR8+ZTZJpS93lJ4zYPHZ9K1gErCInKhuH1dfuu59Md0Z" +
                                          "Q+AUkVtikbanTu2+lO/cyvsUcCPiAkzcOdWk3TklT0Ub0u5iMiIZkT86svel" +
                                          "GZ90jOWH7AI0lLw9ITT2ats+fNw+/ERsbyenzcmWg5+IRORX5imXFb194mEx" +
                                          "tdmDTC29zXX3fvXqxzvfPZZHCkOkBE+7JJNGWzRGAoPdYrk7qGuHt6XQqiFE" +
                                          "ykRriDypVQBtqEqVps68GLlwsL75ecTAg0TYsW6n5hI9rvEd2mWe87a4Ybhr" +
                                          "uV6Vn79eXW+SeecAXmrudtQjVRz3Mkcb8bjWXWkwMrYp1NjWFmm/Jtwc6Whs" +
                                          "bWlcEuJJ8FkDKn3tg/txa/AVvVpRo02SGRV2+cDXxbMWjz92ObfLgcCNNFjc" +
                                          "yZ5MeA79h+nsfROzOfsvkfwH2WqQTEAyKWfO3jctS92M84uevlok05HMBCff" +
                                          "K1m9TXqU6/OqYWNXnwU7H5/zKnybg4QLM/ebYZfnYAeRX5PwoG5IEC/KUrfg" +
                                          "HEF0Bv4HNgs4cAaRzEdyMYqkM6W7Hyt/NmwwL88G5qV8DHy7DMlCJA3nDaZr" +
                                          "TlkEWpylbsmwgbwSSSOSJkaKBZCNqjoyWK7MhuWyFJa45/G1IFmVO6MOZ6lr" +
                                          "PU+jXotkHZI2MGqmu/bp6S7dVTEcPDdkw7MDydVIrkGyHsnGHOum92jVszmp" +
                                          "dRBowTtVM25ALtWckKmBWzPeRXTYKiwhkZH0MJK/XVLYyGivlg3tLSntxdtS" +
                                          "XwyJPrLa6wbTe+yj6loPF5JlboRV3Ef7+r/R7oTj60CLTD7ezQ5n0sMGdte5" +
                                          "AbsTyfeR3JADNXaOGXxxLFvFRfvBUHDuGba63oRkN5KbRxDTW84N0x8h2Ydk" +
                                          "v12fYKQs/fMPvN6ZMOC7MvEtlPz4ofKi8YeueoNfWqe+VyoNkaLuuKq6cnR3" +
                                          "vl5omLRb4RCUitsufgTiu42RCYN9k8JIHlCugAcE9x2MjMvEDZxA3Zx3g/P1" +
                                          "csK+m/93893LSInDB4mEeHGz3A+9Awu+/gSSX2GNA7Pe6qFWzfU5yKxB94mr" +
                                          "4+JLv4h85NDKNdeeufQB8bEMpN470ABxezVKXPfzTvMGbGjdvSX7KlxRf7bs" +
                                          "ieLZyavUSiGwY0CTHT0iG0DbDdSASZ6Lc6sudX9+6vCiF17dU3gcdsjriU+C" +
                                          "Pc76kPeoqyFhxE0ydX1o4O1scjvVUH9P/xXzuj9/i98RErHdnTI4f0Q+8eDG" +
                                          "Px2YcLjWT0a3kAJFi9JEJylRrKX9WiuV+8xOMkaxmhMgIvSiSGra1W/m3eqY" +
                                          "tN0qIzMHXmYPuTsdEyKjnRKxMlk3rNjAKbGXEmlYuHlcDdC7SGi1YSR3ZAXP" +
                                          "Gtxi12XwTWQd11V+SM7TkSf/D0+uNvIDLAAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188908000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALV7C7DkaHWe7sw+Z5ed2Vn24YV9DzhLw1W/pO72EkCtllpq" +
                                          "Sf2QulvdimHQs1tvtR7d6obFGIcsNmG9xrMJroJNuQrKjmsNJBXiVLlIkbgS" +
                                          "2PiRcuIkJq4ASZwK2CYxlWCnTAL5pb7vnbkLO7O3Sueq/8f5z/n+c87/1Ivf" +
                                          "hm6OQqgQ+M565vjxrp7Gu5aD7MbrQI92OyzSl8NI13BHjqIhSLusPv7583/x" +
                                          "vefmF85At0jQPbLn+bEcm74X8XrkO0tdY6Hzh6mEo7tRDF1gLXkpw0lsOjBr" +
                                          "RvFTLHTHkaoxdIndFwEGIsBABDgXAcYOS4FKr9O9xMWzGrIXRwvoA9AOC90S" +
                                          "qJl4MfTYcSaBHMruHpt+rgHgcFv2ewyUyiunIfToge5bnV+m8PMF+Mrffc+F" +
                                          "f3gWOi9B501PyMRRgRAxaESC7nR1V9HDCNM0XZOguz1d1wQ9NGXH3ORyS9DF" +
                                          "yJx5cpyE+gFIWWIS6GHe5iFyd6qZbmGixn54oJ5h6o62/+tmw5FnQNf7DnXd" +
                                          "akhm6UDBcyYQLDRkVd+vcpNteloMPXKyxoGOlxhQAFS91dXjuX/Q1E2eDBKg" +
                                          "i9u+c2RvBgtxaHozUPRmPwGtxNCD12SaYR3Iqi3P9Msx9MDJcv1tFih1ew5E" +
                                          "ViWG7j1ZLOcEeunBE710pH++3X37s+/zKO9MLrOmq04m/22g0sMnKvG6oYe6" +
                                          "p+rbine+hf078n1f/MgZCAKF7z1ReFvmN97/nXe99eEvfWVb5g1XKdNTLF2N" +
                                          "L6ufVu76/TfiTzbOZmLcFviRmXX+Mc1z8+/v5TyVBsDz7jvgmGXu7md+if+X" +
                                          "0w/+mv6nZ6BzNHSL6juJC+zobtV3A9PRw7bu6aEc6xoN3a57Gp7n09Ct4J01" +
                                          "PX2b2jOMSI9p6CYnT7rFz38DiAzAIoPoVvBueoa//x7I8Tx/TwMIgm4FD7QD" +
                                          "nueh7d8jGYkhCZ77rg7LquyZng/3Qz/TP4J1L1YAtnNYAVZvw5GfhMAEYT+c" +
                                          "wTKwg7m+l6H5LhwtgSmN20PgQLkfeSDoABsLXlPuaabbhdXODoD9jSed3gH+" +
                                          "QvmOpoeX1StJk/jOZy//9pkDJ9hDJYZ+HDS4u21wN29wFzS4CxrcPd4gtLOT" +
                                          "t/P6rOFt14KOsYGLg+B355PCuzvv/cjjZ4FNBaubMljT3OceyH+cBfWevHZA" +
                                          "JrNoQOcRUAUG+sBf9RzlQ//l/+TCHo2pGcMzV3GCE/Ul+MVPPoi/40/z+reD" +
                                          "8BPLwFyAZz980hWPeU/mkydBBFH1kG/519zvnnn8ln9xBrpVgi6oeyF7LDuJ" +
                                          "LuggbJ4zo/04DsL6sfzjIWfrX0/tuXYMvfGkXEeafWo/PmbK33y088B7Vjp7" +
                                          "P5cbwl15mbt/AP52wPP97Ml6IkvYGvpFfM/bHj1wtyBId3Zi6Obybm23mNV/" +
                                          "LOvjkwBnAvx1IfjUH/7etypnoDOHMfv8kVEQgPDUkTiRMTufR4S7D01mGOoZ" +
                                          "WP/pE/1ffP7bz/yN3F5AiSeu1uCljGYSg0EPDB4f/sriq1//2qf/4MyBjZ2N" +
                                          "wUCZKI6pgpcoH8OAJobpyU4OyOMxdL/lqJf2tR6DMQ0IdslyajlU94JRPBct" +
                                          "65Xd7UCQexSQ6NI1zPXI4H1Zfe4P/vx14z//p995maUeB4aTg6e2PZRLlQL2" +
                                          "95/0IkqO5qBc9Uvdn7zgfOl7gKMEOKogIkS9EPhwegzGvdI33/of/9lv3ffe" +
                                          "3z8LnSGhc44va6ScjbMgWsZzMDTPgfunwTvftY12q9sAuZD7JpTr/4atOLlb" +
                                          "33UIBOuD8fCjf/zc7/z8E18HcnSgm5eZDQMJjqDVTbIpwt968fmH7rjyjY/m" +
                                          "fQJi6/hn/0HtGxnXet7Am3L61zJS2PZY9vrWjLwtI7v73fRg1k1CHgFZOYo5" +
                                          "XzPBFEHLe+rU0NEPTRdY23Jv/IOfvvh1+5Pf/PXt2HYyTpworH/kys/9YPfZ" +
                                          "K2eOzCieeNmgfrTOdlaRC/26g6587LRW8hrkf//c07/5q08/s5Xq4vHxkQDT" +
                                          "v1//9//vd3Y/8Y2XrhKeb3L8faPMaHmv2ewf8sodG18sUtWIxvb/2LGMV5qj" +
                                          "Em8Xkoo7mHewSYfdtJgG1lbH+kq2yBEukNiUJhxzQnBWYeLWbGdd1dGGU1n2" +
                                          "57Myw4tqVMZd2uTqi9jhVKokpsN5JS40Z6ghzMe9ddchqbSi9JIh401Ql6HG" +
                                          "8LKOaLChLzUnstuDjQrDal9XYQTeeD0YDj2KM/qjIsN2+qORXyRFttEMR/gm" +
                                          "jRgB2LRvrwNpbCUjXh/U6uhg2a2Ui9KibZCULEROrSOaJZZ0yu6oNV5oEhOY" +
                                          "7jQVpF4QTxWBYae02xBMKYAJkqyEna7IlHh6MybGYrntN4SgPR9sOq2A7Jgb" +
                                          "UkCr/rpcbhZXnDUi7JmAdDiyrVTGLbMzZJKYWkZEYxUNdUQOsA3ipw43pvmy" +
                                          "yZYElaiOGvxMYMnpoE7bZGqi5bhgoWaKEev1ilcqxNxtOmiHbhJcWveXqSHB" +
                                          "RmXsYXRqL+TA4gp9ORmLYSjzKDcfJeiou4iKklu0SkivTjS9eOrKNhsM1C5m" +
                                          "tpouNUDaK40NmoVWd2JGAKlhVXX0tV+UmgJt817g8abAqJNIiTqqlJhzs+ts" +
                                          "kGppHsfdYZSKG6rVIsvrOk2F6WZUF4e6LNRtZBCK84Shq9yghSlBk2gGIZ3I" +
                                          "Y5crCoueFpBMKxVRKzCZYD1DagGYtQYjfSg212J/ZbNkNO3KSzql5HRGiWQi" +
                                          "OambBK48sbQJ048nA0VdNNSmKiNrxJzbyarCTKe0jc8CTyMSU6sIPLxAO2Rb" +
                                          "8lxFasvTRnExpXHXLzOjhr4IfIMu4YOAdsYYP9Y66Mwtz3TH70dNxfdpzKUR" +
                                          "rl3jhbRr8siiwbdo1OSpEF0tMCaZzqpE123b5WjZ1qudsZvwUkczUI9EN3K3" +
                                          "UCrPwu6wspqpyJBhIh9uz8GYMV+Uii6yGIVYq6g0i0oy6y10BelPEHzGevJq" +
                                          "nVa9sJZseh0kHmkGYa2HHIxHNS3AJV7mWxV9vBzKzmKCzCk/4KWeKc78xOh6" +
                                          "3UQS27XAJOczWg8EQ6SdKWkjGiVWSoUNmlLoQiqM4k4TF8eGxWm4JThuvz0N" +
                                          "mI0+HvmoQsisQJIkF5ejYSjWZ76O1YE1i45cS2qsGsgCW2PMVVCC59EM9acJ" +
                                          "wdCCTupFxaogim0C16l7LYKlGcqkW0hNAUFXmfsCv3HxJbXoNgVpWuS1Xms6" +
                                          "7lOFcdyst+barF1aRlhSNNzloJhw7qLdHHQrCU4k8yZbG4W+50dyX2wy3ihS" +
                                          "Vmqr6k2JyVwqbbh5UFu5arlhxf05jPWjcdjAw+l6FWjWmN7Q8wLHlu1CvWLZ" +
                                          "kkwOZGxQZvy0jq+mnIkRLYPDsFbTxLBBP8BSxrCq9U1rporCKmKjdMxRVBrJ" +
                                          "k4qSBqLSqG84DCmu40S1QsxJVKQ37KP4nC82k4rWCLlCtVZQ9T4LT4fLAkev" +
                                          "naK+pMvrZmCsp1JjPOGKC2roycPRollDyrVVaGiGF1Z0s0qo3IbptjGtaEqD" +
                                          "3hK3qx0y0V1PWRiG3p9scC+l61aVqlgTrUm0e7bQ8/HSetKxOpTpYHWBSJeV" +
                                          "rgHcsG8zFLKyyNm8sXAXa2cSoMIi6q5WS6rEUZxXS5LVBgjZ5LVCvVmfyvwY" +
                                          "FZRxq0lZkWbAjWI4C5d6HwRGfrqYKiS6KFroIuHkeLVmh9MlEtRSd6BaqrV0" +
                                          "mpVqldRK/dGy3mk1iIXbEtSRRzJdxG/YzbrNGjIbCkU8pfHOGulr9bEzxOfc" +
                                          "RJZ4HEuAv+s1Z800LCSYbqJZdbyCOyFGNaqNTXNakyaNpraE27xQSMUGGDDE" +
                                          "ROZWljMFfcUrc4ssBy5rdzG4XjGrxmRZ8SN9vEGwboGylEFTVOluwe224xWL" +
                                          "TXsy2WOsedxv2haxQon10pqEvBnNN0Ex7vNSzRBVbeLzc7OD9LFSkZwulqOe" +
                                          "lyhoG2HFWZEbYwNLS+bucMykzMCp4bpdaiSlPu6NdGfUlgY23hltMG9V6i57" +
                                          "tgFT5bnfQifWXGnNYVZWN3aXT2sGa6Hlla1uLCUuUgpizdp4jKhNqUAxpU7F" +
                                          "GShs6A3CUaAxxcmkHlc2ZZhRC+WSOidJl7STgbDhExRDtXp1zqzRwrgLozWn" +
                                          "YsztDT5VOwVmZfJYqZS4SHEoOEYwsFS1ny4mOsx0i9RqUMUtZhL5rdQlurE5" +
                                          "kuftflIiPbxWLrVG84KA2N6mPAqnjlUIhXKC2hOyibbdgjelhKAqpuu6EM9H" +
                                          "06TFF5INthTwuqghQxJG2aivd9q8Ty+TBTXzololttZ4bBRpa0g6FIq0sBJX" +
                                          "CidtcpKSxZ4xkopuq1gYdWqLFFUKSYPagGjYJ12KR9wkMWatWr1Xa0W+4+C2" +
                                          "FHJtiTCSrkk36sVZhW5E/pIT160qHBl9ee4py0Y3sTZtzhnWmJVE1ocUWeWp" +
                                          "xWRAzKWUVdYIrHiNccViViEvCWRXHykTSibscqXskOKSi8iF1O/gfFwWppsC" +
                                          "tWDNCdfFqnrUnmnyuEYYNliGFNrdfpoOYq9HtoJkNa5syChuDxhFMAdsZCzT" +
                                          "ysKsDUIwduj1Gt/QogWJ9z1/pPdQkmoPaVpGix1uWOBJk4xrfodX4Bra3YjK" +
                                          "pB5ZsCvafFd00BbdqVdYOowwZMREk6IvEqo+NqsDvOwXE7/aDHrNxKrPMKa4" +
                                          "KLsSq0wRyWom002itw2Y5Qd1XQ9AsE8Jni36iE8HNh8qtGbj7DwRsaJdGZdm" +
                                          "m3oirTZaW0wRwRQsBXOn3LKLj9KCQi7b9ZnLDXvDocPKmwFWICeMPUZmdg2X" +
                                          "RonI+Ug5aEbEbF7ycH0qsiB6lrCgFJWJThnEHa7qDOJkTXMDlhZYESOYAdWZ" +
                                          "Ra4uelhJ1FoOP22Wu6VZOmTJkTWsykRZaAkTuldhsJjpCgxKNjFjLNCJO6jy" +
                                          "JXWgd1CQxWOeOJxKnlOtEKGzMqOhyhKhOiurXbojtHh5GdUddFosrwkMRkur" +
                                          "5VSddiwR7XKtZrXeAGO73nArPYxaFJRWvV5o10oNumrqlQIp1+xm1UintFEN" +
                                          "bWrZ7JC2COOm2+yxFt0kg4KHIgQ14QsevtQGrt6oFCUPXplmFalVbCEtLYut" +
                                          "Nc7OpBG+VNVoPPero9o4ng8a9LwBo8UebsF9chAMqy1n5lewGbIJ15PmtD6x" +
                                          "W+tubwUXhcgjhYHV5mAbo9dmpzmjlCHWQ2YyJ268+YTT17M+sbbjOlOrJnoz" +
                                          "YNepI0yr3gwF7p0EPWomrdpSa6UtPKZLqWpVrBJ6wyZGPQxB7KqfwLSOiHXW" +
                                          "ZKerIdFmN3y75A10O6atwqDKbkxJ5FtgvFHZtoTXrYTvdtr1zcg2K6kwGa8T" +
                                          "QeC9SZDYvrNRqXqBxKdSqhSVar9pwYNGp1cHbFqdCULWXXZa38x4atXSGmBy" +
                                          "koABkV40Z30MKZuC7LdqjEYPzT7idQiz1KZG9qxN9ag0RFs+Ai97MiNMUGBY" +
                                          "TpnVnN6ITbvxOqSosNSC69GySBSH3bpfdyIqQd1KRXaH+iBuR7VAKdDTIrXR" +
                                          "babf9wncXdlNrm9icmOlNxumVOqVpWZ5VKhMW3y9IA2lTiA0Kk6nupn2KanB" +
                                          "lGZEiNMeM0+okmYkCdLgtKI0KGAjexybtiJ7w6RccHqwul5GIxUHrO2N2tNE" +
                                          "uzK0nWFxpBQTxORMWrKHdTRa6k5bahStnkjVMLrosKsGPRyW5TgqGN1VASb4" +
                                          "SFnr3kZ1xRlSoPkeP0FMd0IqpUbVJdJYc1tDvNzYTCYVYzlZpJul0ZckCrd7" +
                                          "dpMo1DqdblsEXYj5fW0a2rVFO6FidDJYmCQwEj40W+tgPGjGC2IxDiK03mYd" +
                                          "MJupIbo6xGbF4TQSUQ+Z041wSWhlVwTRSq5OlXmYjNGxV2voE7Eg6LqKTdww" +
                                          "0eKBNeY3Fc5WlbpiiRPRXnHhNCh1LZF0XbgTr1RUnEeK6KhE0unUSbvFeJV4" +
                                          "BsepDGPj5Tjg/WJZaPPjckFtTVKFE61No9xTDHam4t0uaalrCeF0rNaYF7zI" +
                                          "4HubnhEtbWNFlcXFYEhga0Y0ehVLjYVGmasD+186vl1EKK6JGwZTchvDyWKE" +
                                          "wr3FVOxOvNWoRoEFIOOtlVl1wHKwrkwlw5tiOgC5v/LbCE3gMDMKjRlFkMXm" +
                                          "skp1Z1FVxWR+Q2hrbrqwOVSsUesY7rqrFVuvt5HFuN6i1rUW5+AdrOK1ZCkc" +
                                          "OjYhBmtHidzVTFkJgtATOrbMNCW8u7D8tcjUOBBv12RHriJwu0ST7riHcj0J" +
                                          "dcL+qGBN/NimJLrMtRduAitgklbTxkNC7bc0e1XjWmttTId2e01FHnCQxG2U" +
                                          "rXG0cQONb/qrYTzmygjGxqJqM25T3PSBcsMpmJTPbYkqch0GnozZ6bptLp1Z" +
                                          "JWYFL061WJis1p1+yMroShnqhbWFgvUNiXQcxefHFcKoFUKYr/lDCy3i7LBV" +
                                          "0zcDxCtGXFuLdQRTouHa0PlKBwPLQrnXnqQpSy5J3lg2R1QraSsyWvF5u4sw" +
                                          "Cp+2hmK92i2m9Xl5qtnLUtmYMoMINrj+sotKXA+vcUsidvqbqm8wZn2qJ7rf" +
                                          "NcSFXhiv/a4ts0nCLFDV4ytLB/FdlleqPD4y4wjMDIZmUi3z+LTbsOsdmnLw" +
                                          "ZIapRCMtcxZg2pJSrCKllRncL6kRU3DhRqXeqLAC7YGBwCV0qr2pYIUGtkoK" +
                                          "8EwQJuV2F6v1dXRBihtjhKyZtAmcMKwWOuyyOq8j3RbT1XQ9MQbNukJwQbda" +
                                          "K2LNVN+MmUnf2AyXXFtpW9pSmNQYJ+WNmhKZOiut5eVIMNuraREfUsOi2S62" +
                                          "lJYmYIKEsioaJdqkUUCXuEmWatqoMlO1yArNUQHvqzXU7uv+Yk3OU6K41iYl" +
                                          "v9orRWC6PR5RjT6cTjaJ1YDNRp0nQkrzhnTVKA4Kdb3V7qflqcpa4rAoV2ys" +
                                          "Q5qNDtFZO3zITBqimYwL9bTH2XLqzrkZvQQDfzuUSyLsVvTFNO4WF/SGoybu" +
                                          "tJ8MI41YM5bHMynn2JWwa2GM0p4QrjNNKEdtaXhNaJulqcBXJGzSb8epWSpP" +
                                          "VkNxoJVK44LA1Ya2YMBggpd0l3SLxTAs2zqif7Tdu7vzTdaDozfLqWUZxR9h" +
                                          "1yo9rcEYuk1WojiU1TiGbj84C9y2fuSUAcp24x661qlavhP36Q9deUHrfaaU" +
                                          "7cRlFVuAYewHb3N0MBIcYXURcHrLtXcdufxQ8fBk4Msf+pMHh++YvzffGn/Z" +
                                          "iQULnctq9rOz24Mz2kdOyHmS5d/nXnyp/Wb142egswfnBC877jxe6anjpwPn" +
                                          "Qj1OQm94cEYQQo+/bKvSV3UtCfXDdt/yqPyFy198+tIZ6KajhycZh4dOHEXc" +
                                          "YfihKztZA/vnq+fieQii3kHK0XMJAGvW49AD4Hly7wAu/5/l3hNk9PXpoc28" +
                                          "zBjOHFgfv9f1IfTmwy1xHKxAdDVH/dLIc/MdZFlx9Ox46v+ef1PpC3/27IXt" +
                                          "/qoDUva74a2vzOAw/cea0Ad/+z1/+XDOZkfNTqwPN/kPi22PQe855IyFobzO" +
                                          "5Eh/+t889Etflj91FtqhoZsic6Pn55LQnvlmQhm52nJO9RN5+VHmu2PowkyP" +
                                          "t/vvPQOfy2GUl37nESfDY+isuXedIHe+97zSlvHRtvKE6UGvXdg/Kn37Xq+9" +
                                          "/bp67bh+O3mpneynlRdITgFglZEghs4DAMDsS/fiPQD2TnN+LMdcXsW7M913" +
                                          "d3nQH7I3c/Ry6xCJxXUgcWeW+Dh4+ntI9F9LJH7mFCQ+nJEPAAsESAixHMb7" +
                                          "x+zHAbn3OCB9HxjFUTB+6nrBeBQ8+h4Y+msJxi+cAsYvZuRvx9DrM7PwtONQ" +
                                          "ZHnPHGr8sevQ+FyW+AbwfHBP4w++lhp/6hSN/15GPgFGXqAxvzfYHOn5E6EA" +
                                          "RG1fPhIMfuk6MMgTS+B5dg+DZ28gBmcOS1mHQLx4ChCfzcivgIgQ6Vn0FRJl" +
                                          "e4x7NRhuWvqmdojCr16vJWQh8bk9FJ67gSgc1e83T8n7Ykb+MXByYATZEXcS" +
                                          "61p2YYPVvdn22ssvH2r7G9er7RvB8/E9bT/+mvf5l0/R+6WM/PMYupjFvv0O" +
                                          "v6rSv3UdSt+2r/SVPaWvvDZK/3JO8lL/9hSl/11Gfm8b4zI/B+M/dhD0c9wO" +
                                          "1f7Xr1bt/KbI1a+O3Hfy+spufkMxCG5AzNsfrY5cL9i2kVf6ximo/PFW+oz8" +
                                          "UZ7wn68uSB5W37qVISNfz8h/zch/i6Fb");
    java.lang.String jlc$ClassType$jl5$1 =
      ("9EUiO1edRN2q+L6jy94htn/0StheXdD/mZFvZuRbGfmzjPyPk8LfgHjxv0/J" +
       "+4sfEqzD9nYPEftfGfluRv4SrMcyI8y6//RlEnDOKD5yrfFj5gu/+6++e/6n" +
       "t/cgjt/qyG+27lU9We+rf3i2fEd86efz5dVNihzlC5rbwHIkykrG0KPXviWb" +
       "89pe2bjjFY383kMjz5s/sPF9Cz1/aKF5AZCc35557BVAuKzS7mXhC199Bs3X" +
       "DueXJnBcEK33Lu4eX0kcXqt76thl3qvCdFn95uc+9pXH/mR8T35Lc4tIJm0F" +
       "rEKy/+iepe7klnom97cQetM1BN6TKF/4XFbf/8nv/+63nv7aS2ehW8DaLluE" +
       "yqEO1psxtHuty81HGVwagrcWqAVWpndta4NIvQ9c1oEXD1IPlqIx9LZr8c7v" +
       "+5xYsWbXgx1/pYdNP/G0jO1DJ5bBSRAczc1N4c5XbwofAIvGHwK8A933Rg/o" +
       "Ym70R65ZZRd/jmaCdc09OIsJwuXhtE9cHmM8jTVZIjexAGTuDHOfTU/pPdF0" +
       "NFwOta3bfOYHtz/xrvtf+oncbV4O0qsE5toDQbCV7+jFz73h5Toi505+l+mv" +
       "MvL97OcDGXnwxkfOnUdPyXv81Q0zO49k5LGMPAGC5lyO5riv5YZpXTcub8nI" +
       "m3Ne2duPZ+TJHxKXw408Hgx/npzdVntFgIqn5JV/SIAOG97Nqh2OLztwRkoZ" +
       "qWQi+bFprLPMz183UD+RETTnlb1le5M7jR8dqCPyntLYO0/Jw64bpHdk5F0Z" +
       "acbQ7VuQMMe5MTjRGSEOcCIzQr0GjtY9Ja//Kh2Ny0gvIwPgaLF/eJe3eN24" +
       "TDKSx95sR3tnlBHxtbKfd58+Q374cPigs33wMAnANIJIVT3I1gE5i8vXbWY/" +
       "mZH3ZEQBq+aVbMY3xsLMjOgHFmZkZH6DLOzI9kkzb8y7ZoGd9+YFguuYDu+4" +
       "Gck+M9lZHCp13QCtjgOUwb6zvJGmdmTd2cxIvtjeef8rQfWB6zap92Xk6Yz8" +
       "1A3E68PH8fpQRv5mGkN3Hf90JduOf+Bl38Rtv+NSP/vC+dvuf2H0H/IDj4Nv" +
       "rW5noduMxHGOfm1x5P2WINQNM1fv9u0ZR74O3vlIDD1wre9pYugsoPmS4Zlt" +
       "6Y+C5fzVSoOSgB4t+SxYHJ8sGUM35/+PlvuFGDp3WA4MpNuXo0WuAO6gSPb6" +
       "fPbxxzVmaxdfqUeOnLk9cc0lCpdsv1K8rH7uhU73fd9BP7P9egRMGTebjAtY" +
       "A9y6PUbKmWZHMo9dk9s+r1uoJ7931+dvf9P+Kd5dW4EPneOIbI9c/YCHcIM4" +
       "P5LZ/JP7/9Hbf+WFr+VfMPx/x9nszTw6AAA=");
}
