package org.apache.batik.parser;
public interface Parser extends org.apache.batik.i18n.Localizable {
    void parse(java.io.Reader r) throws org.apache.batik.parser.ParseException;
    void parse(java.lang.String s) throws org.apache.batik.parser.ParseException;
    void setErrorHandler(org.apache.batik.parser.ErrorHandler handler);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVYa2xcVxE+u+t3nfiRxjZJ47w2UZK2uzLQhOIUmrh27LCO" +
                                          "TZxWig3dnL171nvju/ee3HvWXjukbSKVRv0RVYkLBRH/SsVDfQlRgYQaBSHR" +
                                          "VuWhhgr6EC2IHzwjNX8IKECZmbOPu9ePglAt3bP3njMzZ2bOzHxz/Mw1Vuu5" +
                                          "bIvkdprH1KwUXmwU30e564l0n8U97wjMJo3Hf3fh4Ru/bDwdZnXjbHWWe8MG" +
                                          "98SAKay0N842mLanuG0I75AQaeQYdYUn3GmuTMceZ2tNbygnLdMw1bCTFkjw" +
                                          "AHcTrI0r5ZqpvBJDRQGKbUyQNnHSJr4vSNCbYM2GI2crDOuqGPp8a0ibq+zn" +
                                          "KdaaOM6neTyvTCueMD3VW3DZ7dKxZictR8VEQcWOW3cVHXEwcdciN2x5oeVv" +
                                          "N5/ItpIb1nDbdhSZ6B0WnmNNi3SCtVRm+y2R806wh1gkwW7xESsWTZQ2jcOm" +
                                          "cdi0ZG+FCrRfJex8rs8hc1RJUp00UCHFNlcLkdzluaKYUdIZJDSoou3EDNZu" +
                                          "KltbOu6AiU/eHp//6oOt342wlnHWYtpjqI4BSijYZBwcKnIp4Xr70mmRHmdt" +
                                          "Nhz4mHBNbplzxdNu98xJm6s8hEDJLTiZl8KlPSu+gpME29y8oRy3bF6Ggqr4" +
                                          "VZux+CTY2lGxVVs4gPNgYJMJirkZDrFXZKmZMu00xVE1R9nG6OeAAFjrc0Jl" +
                                          "nfJWNTaHCdauQ8Ti9mR8DILPngTSWgdC0KVYW0Yo+lpyY4pPiqRiXUG6Ub0E" +
                                          "VI3kCGRRbG2QjCTBKa0LnJLvfK4d2nvupD1oh1kIdE4Lw0L9bwGm7gDTYZER" +
                                          "roA80IzNuxJf4R0vnQ0zBsRrA8Sa5vtfun7vHd1XXtE065egGUkdF4ZKGpdS" +
                                          "q1+/rW/n3RFUo0E6nomHX2U5ZdlocaW3IKHSdJQl4mKstHjl8E+OPvId8Zcw" +
                                          "axpidYZj5XMQR22Gk5OmJdwDwhYuVyI9xBqFne6j9SFWD+8J0xZ6diST8YQa" +
                                          "YjUWTdU59A0uyoAIdFETvJt2xim9S66y9F6QjLF6eFgInj1M/23EQbFkPOvk" +
                                          "RJwb3DZtJz7qOmg/HijVHOHBexpWpRNPQfxP3dkT2xP3nLwLARl33Mk4h6jI" +
                                          "Cr2IOQplMU5J58Yw0ORHv0UBrVwzEwrBAdwWTH8LMmfQsdLCTRrz+f39159L" +
                                          "vqZDC9Oh6B/FumGfmN4nRvvE9D66frgsFCLxt+J++mzhZKYgx6HINu8c++LB" +
                                          "Y2e3RCCo5EwN+rVASbe+9AGMAb0ove8Zkxff/PmfPhFm4UolaPGV8DGhen3R" +
                                          "hzLbKc7aKnoccYUAut88NXrhyWuPTZASQLF1qQ2jOPZB1EEphZL06Csn3nrv" +
                                          "3UtvhMuKRxSU33wKkEyxBp6C2sUNpVhjuQhpw279AP5C8PwbH7QRJ3RAtfcV" +
                                          "o3pTOayl9LkjRO9dUN4Xudzs+ZQdSzgG1dqUJdBxG5arFFTlLp2ZX0iPPN2j" +
                                          "87m9Ovv6AVye/dW/fhp76revLnHkjcqRd1piWlg+7SKw5eZF7cIwFdIS7CaN" +
                                          "PVdvRN4539VMB9ecgk6hAtfRKrjW3YbrGCINeLEccJfAa9fyUB1U4eUzf153" +
                                          "5DPZY6SCH3xRVi3gBnKOImSWpW8MuDIo8tvDz7x6YLtxPkxogZV3CZSpZur1" +
                                          "OxU2dQXAoo1m4cyqAvZegYQM+iJp7NrEX0y+dCoaZjUAHwCZikOJAzTqDm5e" +
                                          "VfF7SzmDWzWAEzKOm+MWLpUgr0llXWemMkOVok2HMBw2ZWcXPFuLNZF+cbVD" +
                                          "4tipKwvRd9O4GYcoRUoYX7fhsJ3IdkDkbK+kJRRxC6ocnkj0fhsO28yYGNNY" +
                                          "MP7Zsq3nxb+ea9VBacFM6Yju+HABlfmP7WePvPbgjW4SEzKwiaiUjgqZRqY1" +
                                          "Fcn7XJfPoh6F01c3fO1lfhEwDnDFM+cEQUWoOk9XE6fpAN5yKKNk7H5avIfG" +
                                          "fYtZtq9YTfsLhpCoGYkawOFuxWqJBDTduUK/6po5qITTRcSPn2p/b+obf3xW" +
                                          "Z3+wPQgQi7Pzj38QOzevna57qK2L2hg/j+6jSMlWOuECFYcVdiGOgT88f+qH" +
                                          "3zr1GGqFbDHFaqYdMw3M0WVM83XFSeOJN95f9cD7l6+TotVttR8bhrnUurXh" +
                                          "8GnUrTOIToPcywLdJ68c+kKrdeUmSBwHiQbgqjfi4llWIUmRurb+7R/9uOPY" +
                                          "6xEWHmBNlsPTAxwbWGhDIJ2ElwU0LcjP3qtTZqYBhlaCOVYOB1YEPgy8jUuH" +
                                          "dH9OKgrCuR90fm/vNxfeJRAiCR9fnKA7igm64/9K0BVjtpX0xLY4pttiYkou" +
                                          "zYSfB4jAwGG8FL74MUzEn8dhQsPlkf/OWThxdCkPxODZXfTA7o/OA9Hlsrbf" +
                                          "dR13EJDMKqZ/LiCoZAJ+n8AhC7EK3amfMeAa8393TQGaE92OYVx1Lbro6cuJ" +
                                          "8dxCS0Pnwv2/JjgpXyCaoY/K5C3Lh1Z+5KqTrsiYZECzzipJP7Bn5zJuwVaJ" +
                                          "XkjdGU1/EgIpSA/BQb9+uocUa6rQgSj94ic5rVgESPD1jJSFUHVLWXbk2g9z" +
                                          "pK8L3VpVf+hCXeoF8vpKnTSeXzh46OT13U/rphSu4nNzdAGD+6QG2HI/sXlZ" +
                                          "aSVZdYM7b65+oXFbqRS2aYUrIbveFzhHIRQlnuy6AFR50TJivXVp7+Wfna27" +
                                          "CpVsgoW4YmsmfNdZfXcDvMtD2ZlI+Ns4379lCEV7m35/7Bd/fzvUTmWHsgAR" +
                                          "ZAWOpHHh8jujGSm/HmaNQ6wWKr0ojMP93Ltv1j4sjGkokA152zyRF0Nw9a9L" +
                                          "OXm7fPdejWHIsaqQZ4oOXVWexa5IsS2L4Whx4wgVeUa4+1E69ViBDiwvpX+1" +
                                          "gHfSJayCs+m5+I+Hv/zmCKRJleJ+afVePlVu5vxXey3bh4y6948kE8NSFu8C" +
                                          "9ffRqUpJ2TtPRp/X1EihWGiXlP8BAnwsUaITAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5e+zrVnm+v/u+Lb23Bdqu0Ja2F0QJ/JzEieOovBLn4ThO" +
                                          "7NixnZiNWz9jO37Fj9gJ67R12kBDYoy1jGnQv4q2ofLQNLRJE1OnaQMEmsSE" +
                                          "9pIGaJq0B0Oif+yhsY0dO7/X/d3eVogtkk+Oz/nOd773d87nF74HnY9CqBT4" +
                                          "zmbh+PG+nsX7tlPfjzeBHu2TVJ2Rw0jXcEeOoikYu6E++oWr//aDj5rX9qAL" +
                                          "EvRa2fP8WI4t34tYPfKdta5R0NXj0a6ju1EMXaNseS3DSWw5MGVF8RMUdMeJ" +
                                          "pTF0nTokAQYkwIAEuCABbh1DgUWv0b3ExfMVshdHK+hnoDMUdCFQc/Ji6JGb" +
                                          "kQRyKLsHaJiCA4DhUv4uAKaKxVkIvemI9x3PtzD8bAl+5tfef+13zkJXJeiq" +
                                          "5XE5OSogIgabSNCdru4qehi1NE3XJOhuT9c1Tg8t2bG2Bd0SdE9kLTw5TkL9" +
                                          "SEj5YBLoYbHnseTuVHPewkSN/fCIPcPSHe3w7bzhyAvA673HvO447OXjgMEr" +
                                          "FiAsNGRVP1xybml5Wgw9fHrFEY/XhwAALL3o6rHpH211zpPBAHTPTneO7C1g" +
                                          "Lg4tbwFAz/sJ2CWGHrgt0lzWgawu5YV+I4buPw3H7KYA1OVCEPmSGHr9abAC" +
                                          "E9DSA6e0dEI/3xu/8yMf8Ahvr6BZ01Unp/8SWPTQqUWsbuih7qn6buGdb6M+" +
                                          "Lt/7pQ/tQRAAfv0p4B3M7/30S+99+0MvfmUH84aXgaEVW1fjG+rzyl3feCP+" +
                                          "ePNsTsalwI+sXPk3cV6YP3Mw80QWAM+79whjPrl/OPki+6fzn/2M/t096MoA" +
                                          "uqD6TuICO7pb9d3AcvSwr3t6KMe6NoAu656GF/MD6CLoU5an70Zpw4j0eACd" +
                                          "c4qhC37xDkRkABS5iC6CvuUZ/mE/kGOz6GcBBEEXwQOdAU8D2v0ezpsYugGb" +
                                          "vqvDsip7lufDTOjn/OcK9TQZjvUI9DUwG/iwAux/+Y7KfgOO/CQEBgn74QKW" +
                                          "gVWY+m4y99FID+HC6cL93NCC//8tspzLa+mZM0ABbzzt/g7wHMJ3ND28oT6T" +
                                          "tLsvfe7G1/aO3OFAPjH0ENhnf7fPfrHP/m6fXfwIoTNnCvSvy/fb6RZoZgl8" +
                                          "HES/Ox/nfop88kOPngVGFaTncrlmhdPdX7ycBesev31E7uXhYFCEQBVY6P3/" +
                                          "STvK03/3HwWNJ4NqjnDvZbzg1HoJfuGTD+Dv/m6x/jKIP7EM7AW49kOnffEm" +
                                          "98md8rTsQFg9xlv9jPuve49e+JM96KIEXVMPYrYgO4nO6SBuXrGiw0AO4vpN" +
                                          "8zfHnJ2DPXHg2zH0xtN0ndj2icMAmTN//qTOQD+HzvtXCv3fVcDc/UPwOwOe" +
                                          "/8mfXBP5wM7S78EP3O1NR/4WBNmZMzF0vrrf2C/n6x/JdXxawDkB7+KCT/3V" +
                                          "n/0TsgftHQftqyfSIBDCEycCRY7sahES7j42mWmo58L6208wv/rs9z74vsJe" +
                                          "AMRjL7fh9bzNKQZZD2SPX/jK6q+//a3nv7l3ZGNnY5ApE8WxVNCJiiQGODEs" +
                                          "T3YKgTwaQ/fZjnr9kGsBJDVA2HXbaRSiej1I4wVpuVb2d5mgcCRA0fXbmOuJ" +
                                          "7H1D/eg3v/8a4ft/+NItlnqzYEZy8MROQwVVGUB/32kvIuTIBHC1F8c/ec15" +
                                          "8QcAowQwqsD/IzoErpvdJMYD6PMX/+aP/vjeJ79xFtrrQVccX9Z6cp5oQbiM" +
                                          "TZCbTeD1WfCe9+7CXXoJNNcK34QK/t+wI6dw67uOBUH5ICF++O8/+vVffuzb" +
                                          "gA4SOr/ObRhQcEJa4yQ/I/ziC88+eMcz3/lwoRMQXJmPd6+9N8eKFRu8uWjf" +
                                          "mjelncby7tvz5h15s3+opgdyNXFFvKPkKB75mgXOCFqhqVcMHUxoucDa1gcJ" +
                                          "EH7qnm8vP/mPn90lt9Nx4hSw/qFnfumH+x95Zu/EkeKxW7L6yTW7Y0VB9GuO" +
                                          "VPnIK+1SrOj9w+ef+oPfeuqDO6ruuTlBdsH577N/8d9f3//Ed776MlH5nOMf" +
                                          "GmXeVg+2zf/qr67Y+I7niVo0aB3+KGEuVzNVyLqlpBQjnmGxmS2RtUZa5aVh" +
                                          "NdlSE5Me8G5oVhsUTk+lTLQWiOZRlUbFW9sJrOsIsRZndrJUuKHArsusMF9S" +
                                          "bZaAuUjoGBOHXcwncpsjWCERTXMRol28OiC2qT2eYYNhF5dchWaSps4snFaM" +
                                          "KAzi2aOtVFXoLZFt4VFaEZKkrgzWSy0Iicow5WduyiNlvY7WnLKH8c1Gao9I" +
                                          "HyEMxDBrbAIrnVSTvJmtEKKoY6N+E+NaQ3lTHmO1qkvJXtIvDxr11kTWJ3Nt" +
                                          "zntI302mI1WXqvFY2Sw8SgObKvi0t7TTFqFOw0E5rEurYN0mO+ykP1T4zWTs" +
                                          "ERwZ1tbcGFfmo2p/UFXDDp2s+kyAyWVLWZW23lCTZXqEekDt6yme6KMOIohI" +
                                          "R2pow0wCgYnFhO5EFWkRUQVi1k1VTbXG1azu68J6XIcHcTBQKl5H0UxOQttl" +
                                          "0XPHYwvh8Fhg3dKmymJlNDUri2UqNrIuF4lTaVK1VdpVNass9Us9PGQNUs+w" +
                                          "MMJMtcKSfFAu8zjRGzsqtdS2TiIP57w2kMgO5/sJ0u2MpWToxAqdoC2Lh3Ui" +
                                          "gGHUp2OkVk0djxDncWCvBrU2Z9lzqZ2qQ28Q1GZho+y6LOFq8djc1lyiPVYC" +
                                          "Z5tp46SJZaSLgs27HZKaWpKDDR2GS0qLYNStNjeYz24QpYf2F6uwJkhJVsKn" +
                                          "86rTzwQhqi2Y8WJOjkgrXEqdsDeThq40SsrlTOhW2KbXR2m91erZoVomHc8g" +
                                          "xfFUJnBNTibY1Gq6LNYZUIy3mHLiQsPLQ2Eulud+yQk281rAWCvWmvF9lFfK" +
                                          "XWGALPE+yyr96sTGp+2hXKY8klobw5pW9dZJ0Kn4ZmU50Lo1Ki1TTSXtu41F" +
                                          "ZzqXumzot7DyYDtOMtKoseW1Nylv2xEbtjBOrq9jI/Eaa0KrzGZxt4zW9UWf" +
                                          "X2q9mjTsBxq3qpTgUIQ9hO3xfrmLer5LzKp8XdIcX5VFZDAkOI2cODV3GMWE" +
                                          "7WDdEs2sBxomqamcBZY2l+z6bDRhq9X+sk67pJZ2UnOeCJtBM2uvep6O2k2u" +
                                          "J3ZKGFnOJFSzuCkG/HBu8+JU4+vNVjnZ+K2B1utO12RczSy3yaHoptlDJzbV" +
                                          "Q/XeYuDZlRFcRboTpbdk6PWSJVMFmG9Mbhsr2l3AhGULBE209SwQA3bMTIyM" +
                                          "QbTltAr+PCqlWqyDIKNlzUTtAR5WB/QkcEZ8naxj87RMs8S6zLdDId1207Dd" +
                                          "0lJxSmDUyDUmkUbhUzbclgykWak3qfVK6uBN2kTbcC9x+4Y7rnnset1tdlDU" +
                                          "CBdRD6eyuESWSu7WlIbzRYYSg3GCqaUS1Z5XdYTFcb/eTcelUGhxil5qtvqj" +
                                          "llL21zomLTPDgBnXYMyeW+N9R2b6AtbpmzrQjLmllKHakIeer6pzvpXEGDae" +
                                          "heZGTJip1OImVK+yAi5HM1K70u0GpkSVUTzyEC9cI3y8NkfJkM04HkHS4bK7" +
                                          "ydoBilcjfhwIpp1MzCCtNpotpo5jTKoQjQlLImwrNlTBR4IpLW+cJrW0Wbqp" +
                                          "8ePaLNG2UUmaaNx20a9oK57U2lm/Loe93tShgqo0K1sMM67aWMNt0us12hI2" +
                                          "OqyJsGEGDTTU15RHLG11xWqVwBKdRanBDdO6LvUa6iDtaQOugctjRtDW7LhW" +
                                          "R5rCqN3U1cUSNQFB7DC0RWSuhH18MNaprqqSRktuGhu+XeFrOr81KnWk3mGk" +
                                          "OcrhBJKxgoUs2t6QHricGIjYKOkMfCxed7aNDJ1TccYsM38hCQgucYGUhBU6" +
                                          "46vaZNby/YpbUzer1lrSQc4YlSwyaIzD7qy8KYH7nyzZfItIccla0mRrO111" +
                                          "3LouGL0Gt3U74lZsdbdD2i2NRCrgF2HZcWai7o6WtOAvq8SonVYlUZ0xvYQa" +
                                          "S72SqgidWmwFw3TNak261p+rPsv781nDMCMSGWjLzlIZlpYky2Y46qve0i6D" +
                                          "GbqKbeb98Xg+YhpStEK8TCnpclNoy2pvhM7tpES02o7hMg1RZ9aMsrDFGgfo" +
                                          "Si3Z4u3FSmJX80pP9Roz0mB8E+2VKypi0BXHMLtpx+v0RiW1O+FFn142Z13U" +
                                          "CFrj+mY4HC8bRF1eD4y+MY+leNWcT42IMgPc78+Xckr3kkxcke3OVEv4IYwG" +
                                          "fn01mE5ZlWO8agArJV8xkEyUkFLKTBYTq8FsbQSb0Ft97cn1xmpYparmArZL" +
                                          "qM2NHJFOunhvrgqa1acXUwwzSisC2YaVfn/VUzpET17NQYZERmVRGGHIrMfp" +
                                          "NDlu1o2m2mk4aGnqx0IMkptihh6fhDMT63t8OKUHU59RNymlkSjwzeUQnGF5" +
                                          "l2unhDVRFivbsGqOI4KTBpuESqnBws2EZuZo1hUJtz12ImbaylJF7JudAVnt" +
                                          "OilfplSbQVbxVFrN26Yj47Qwp9uVeZdZbDCbTwiNaNLDRYgnbLNsuPB6nBk6" +
                                          "ybYsnG0a3rDVsBYuWoObw3JbsONgVs4okB3i2Jov/WQ754x2zW6l/T7Woxq1" +
                                          "Eb/tephmTiLGWRowLU7NTMOXTEZ3pJkxbTV8mG41CScKFUNjK0iX7IyGKwmm" +
                                          "LNyXWmTJw1om3ugOEdk1RnpLxpAmMp305W6zSs+FrEIpoY+qCYlpGc6VGS9d" +
                                          "V2HSXgSzDS77c3hYxxHKrEil+nA1BVcWkH7w7dYKSKbR9upbMkkFmZwtba3P" +
                                          "V+DuYhBwLbg9UZqlxFd5GQ0nC85u1iy1HgqLLsd0KjbJ9XhCoMSZsqwumttg" +
                                          "iFGIEAhGycRnut/D1sHQm3L6bGvWUHpaQXg4DEwuqXnjrdbqd0ropF8lBnA0" +
                                          "cySZEyRtPmooaL3kz3rKiuWq8pwPB8pa721NYsBOHC/ZoK0eWy9PSWs9E4JG" +
                                          "STQ8udrAAyFa+GJt7kauMdYkY6Z21qO4U5WcQWkc1ZBG08G7QsNF6nCjrcHG" +
                                          "ds1PXZGIFi1Waol0QBAmZid2n3NhwpXHEzQVh2HZt0dME6HidcWuRXZ/6S9b" +
                                          "lXp1u2F75XHalJsUPXMbBqPptkgMInk1kWo+PRNEPZPrg4irUjXRzGrpQtB5" +
                                          "uVaqdNGmYLU7VroOZqXKgjA4Ut7gUcmtlwYlYg1vXXzIko5OlmRD0BlHSOrr" +
                                          "bKaD441Z26DNGrbsYmOul2B40zDYFR+Q1WnMsAE8q3QtU+xbM4fB2i0vjXh5" +
                                          "MAWn8nflx/XBj3Zjuru42B7VO8FFKZ8o/wg3heyVNoyhS7ISxSG4TsbQ5aMC" +
                                          "7G73E5WdM4cX6UduqR5ZFcwDd0m1KBsrjp7flR68XdGzuCc9//Qzz2n0pyv5" +
                                          "PSlH2wFbx37wDkdf686pctLbbn8nHBU13+O6zZef/ucHpu82nywKF7fUkyjo" +
                                          "Sr6SyUvrRyX0h0/ReRrlb49e+Gr/LerH9qCzR1WcW6rRNy964ubazZVQj5PQ" +
                                          "mx5VcELo0Vsukr6qa0moH+/7tjfJX7zxpaeu70HnTpa2cgwPnioU3WH4oSs7" +
                                          "+QaH5e8rsRn66fHIyaoREGtRtrsfPI8d1EeL/3z2tUHevi47tq5bzGbvyE7Z" +
                                          "AyMJobccFyxw33F0tZD6dd5zi/t9bhR58fC/rr658sV/+ci13e3XASOHanj7" +
                                          "qyM4Hv+JNvSzX3v/vz9UoDmj5h8Ujkswx2C7KvVrjzG3wlDe5HRkP/fnD/76" +
                                          "l+VPnYXODKBzkbXVi7LxmZsNfVcosfx9Vpfzukw+bBaTatEubl3yllesrHYz" +
                                          "VQ9yygpURan/RgydL0AKDO854cl4DJ1b+5Z27OJPvloxYFGMnqjJvu9Wjb/1" +
                                          "QONv/bE0/rJCKMJSAfCB2wO4BcBTebM+5D1/CY75TH9cPvfBgx7wif7f83mo" +
                                          "7Ou3U3Y3DP2QkD3NObCaD55CdEh8/v7hvHk6hq5Genxy4Smh/PyPIpQshi7s" +
                                          "avm5B9x/y1fC3Zct9XPPXb1033P8XxYx5ujr02UKumQkjnOy/HyifyEIdcMq" +
                                          "SL+8CytB8fexGLrvNgLJi7dFpyD0V3bwz8bQtdPwwCCK/5Nwn4ihK8dwANWu" +
                                          "cxLkN2LoLADJu5/Mq9wnEsiBgRQivOfVRHi05GSZOk86xdfYwwSR7L7H3lA/" +
                                          "/xw5/sBL6Kd3ZXLVkbfbHMslCrq4i8hHSeaR22I7xHWBePwHd33h8psPE+Jd" +
                                          "O4KPjfUEbQ+/fKzsukFcRLft79/3u+/8zee+VZRq/xfigdL7Jh8AAA==");
}
