package org.apache.batik.gvt.text;
public interface TextSpanLayout {
    int DECORATION_UNDERLINE = 1;
    int DECORATION_STRIKETHROUGH = 2;
    int DECORATION_OVERLINE = 4;
    int DECORATION_ALL = DECORATION_UNDERLINE | DECORATION_OVERLINE | DECORATION_STRIKETHROUGH;
    void draw(java.awt.Graphics2D g2d);
    java.awt.Shape getDecorationOutline(int decorationType);
    java.awt.geom.Rectangle2D getBounds2D();
    java.awt.geom.Rectangle2D getGeometricBounds();
    java.awt.Shape getOutline();
    java.awt.geom.Point2D getAdvance2D();
    float[] getGlyphAdvances();
    org.apache.batik.gvt.font.GVTGlyphMetrics getGlyphMetrics(int glyphIndex);
    org.apache.batik.gvt.font.GVTLineMetrics getLineMetrics();
    java.awt.geom.Point2D getTextPathAdvance();
    java.awt.geom.Point2D getOffset();
    void setScale(float xScale, float yScale, boolean adjSpacing);
    void setOffset(java.awt.geom.Point2D offset);
    java.awt.Shape getHighlightShape(int beginCharIndex, int endCharIndex);
    org.apache.batik.gvt.text.TextHit hitTestChar(float x, float y);
    boolean isVertical();
    boolean isOnATextPath();
    int getGlyphCount();
    int getCharacterCount(int startGlyphIndex, int endGlyphIndex);
    int getGlyphIndex(int charIndex);
    boolean isLeftToRight();
    boolean hasCharacterIndex(int index);
    org.apache.batik.gvt.font.GVTGlyphVector getGlyphVector();
    double getComputedOrientationAngle(int index);
    boolean isAltGlyph();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188907000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVcC5gU1ZW+3fNkZpgXDO+HwGgCwW5BjcER4jAzwEDPw5lh" +
                                          "/DIIbU11TU9BdVVZdXumB0Uj+QxEg/GBmoeZuCsqGtDExMQkStgHKov4fVHW" +
                                          "aLKKMZpoXL/Vb9fN7rqre8691V3V1T01yEzxfXWmuu7z/Pecc8+5Dw69T4pM" +
                                          "gyyQVBqiI7pkhlpU2ikYphRrUgTT7IFvUfGeAuHft73TvipIivtI5aBgtomC" +
                                          "Ka2TJSVm9pH5smpSQRUls12SYlii05BMyRgSqKypfaRONlsTuiKLMm3TYhJm" +
                                          "6BWMCKkRKDXk/iSVWq0KKJkfgZ6EWU/Cje7khgipEDV9xM4+y5G9yZGCORN2" +
                                          "WyYl1ZHtwpAQTlJZCUdkkzakDPIFXVNG4opGQ1KKhrYrF1sQbIxcnAPB4h9V" +
                                          "/efHtw1WMwimCaqqUcae2SWZmjIkxSKkyv7aokgJ8xpyPSmIkHJHZkrqI+lG" +
                                          "w9BoGBpNc2vngt5PldRkoklj7NB0TcW6iB2iZFF2JbpgCAmrmk7WZ6ihlFq8" +
                                          "s8LA7TkZbjmXOSze9YXw/nu2VT9eQKr6SJWsdmN3ROgEhUb6AFAp0S8ZZmMs" +
                                          "JsX6SI0Kg90tGbKgyDutka415bgq0CQMfxoW/JjUJYO1aWMF4wi8GUmRakaG" +
                                          "vQEmUNavogFFiAOvM2xeOYfr8DswWCZDx4wBAeTOKlK4Q1ZjlCx0l8jwWL8J" +
                                          "MkDRkoREB7VMU4WqAB9ILRcRRVDj4W4QPTUOWYs0EECDkjljVopY64K4Q4hL" +
                                          "UZRIV75OngS5pjAgsAglde5srCYYpTmuUXKMz/vtl916rbpBDZIA9DkmiQr2" +
                                          "vxwKLXAV6pIGJEMCPeAFK5ZF7hZmPL03SAhkrnNl5nl+ft2Hly9fcPQ5nmdu" +
                                          "njwd/dslkUbFA/2Vv5nXtHRVAXajVNdMGQc/i3OmZZ1WSkNKBwszI1MjJobS" +
                                          "iUe7nvnKVx+R3guSslZSLGpKMgFyVCNqCV1WJGO9pEqGQKVYK5kiqbEmlt5K" +
                                          "SuA9IqsS/9oxMGBKtJUUKuxTscZ+A0QDUAVCVAbvsjqgpd91gQ6y95ROCCmB" +
                                          "hwTg+RPh/5YjoWRLeFBLSGFBFFRZ1cKdhob8m2GwOP2A7WC4H6R+R9jUkgaI" +
                                          "YFgz4mEB5GBQshLiQzC2qJ49QLp1QY0IIyBMIRQy3d/qU8jdtOFAAICf51Z7" +
                                          "BTRmg6bEJCMq7k+ubfnw0egJLlKoBhYulHweWgzxFkOsxRC0GMIWQ9ktkkCA" +
                                          "NTQdW+ajC2OzA7QczGzF0u6tG6/eu7gAxEofLkRkU0zt5rIfhdjBrLmHTSpp" +
                                          "Mx4VH3npkn9+6Pa7h7lYLh3bYLvKzfqfDqV/95v/xRhzWmBsuyiPyrjK94UP" +
                                          "3Tunac17rPwUMFZUAOECO7DArbhZuoYa7AYcbLBd78pHEh8FFxcfC5KSPlIt" +
                                          "Wga+V1CSUrcERrZMNtNWHyaBrPRsA8W1scEyBJTMc/fL0WxD2poi86XOgYZ3" +
                                          "zI3vU5nQ1LA803FocKyWwBOy1IL9xdQZOtKZKTbqNWzUsUuhVrDHccmoffO+" +
                                          "A3+9cc+XALpWUjSEXQdUqu187UmcR75+6K755fvfuAVHFtUwgJWei3LkHhns" +
                                          "+epu/fuvvPDuhUEStKeGKsecDug1OMwRVlbLDE+NLZY9hoQov/btzjvven/P" +
                                          "FiaTkGNJvgbrkTaBGYK5Feaom5675tXTrx84FczIcQGF+TjZD24NvJhsqqTQ" +
                                          "M1kVFC7h0z+FfwF4PsEHwcMP3LbUNlkG7pyMhdNB56Y3tzR1dDX2tHa0Rze3" +
                                          "N7d0RVrbW6CHi20VQQ+qO9lv0k5DTgCrQ5aNX9l5tbi3vvMtriiz8xTg+eoO" +
                                          "hvf1/nb78wzI0n5w43rSAuDwmRqNuOU3IK1GclHK9FRAV3/Cu2pP77j3ncO8" +
                                          "P25tc2WW9u6/+dPQrfu5GeKz+JKcidRZhs/krt4t8mqFlVj358d2/ergrj28" +
                                          "V7XZc1ILuFyHX/6/50PffuN4HoNYAP4GNDLNlqdGwxBG0Mqlbnxx/neeFb5f" +
                                          "gCJfaMo7JS7STFCYbcweD8518zeqnrqttmBdkBS2ktKkKl+TlFpj2epZYib7" +
                                          "HQNkuxC2ylr8o3CBLV6m69z6Q6v1Y4yWw9WMired+mBq7wdHPsyxlNn61Sbo" +
                                          "HO4aJOch3DPdBn+DYA5CvouOtl9VrRz9GGrsgxpFmL7MDgPmm1SWNlq5i0p+" +
                                          "93f/MOPq3xSQ4DpSpmhCbJ2AXiHM7XQQHMlBmKpS+pcv50ZouBRINZtGCJPQ" +
                                          "BdkG63PwhC2DFc5jsPAF8wTxpY39XMbo+Ugu4JqNryuQrERyIWP7InBwHNrZ" +
                                          "3dPVuqmlZ0NXx+b1GzB9FQcd6Xok7dwIbDzTji+G5wKr4xd4dLwQXzZ/to5P" +
                                          "c3S8o5dblXx97v2MfV4Fz4VWn1d49LkEX7Z+tj5XOvrcGInk6+42j+6mvFqj" +
                                          "pFQAg2iAnFEyJRNG8KYd3glBKZ8/lkPODMqB3ftHYx0PrECDggW/DBVSTT9f" +
                                          "kYYkxVHVYqwpy9FpYyGI7Rm8VnnHH39RH18L1iBCaqFrSUFBWwGmGAIxcYcV" +
                                          "q1SgybYD4HMcATBG7oYmSjGIv8YKhK1aSrUhycDvMOc4akjbJnRjlo1t6t1d" +
                                          "f3b3X+b0rBm8ms0pOc4WRGpYshOD1EwwutCFqrvKh9sOHV9/nnhHkMVn3MXJ" +
                                          "ieuyCzVkW84yQ4JAVLVtJUyjOfODC62ouOwc4Yno07vq2SjYfh/WsMjlRZUP" +
                                          "aEZCULCBNKxlYLG0YftLPpdqPjyXWkpzqVtpbAnPEd1gRlHilqAa5DzbmkJo" +
                                          "pIBDiKjXb1ZhaOUBWehXJJye/rfq3BVP/Out1XxSU+BLehiWj1+B/X32WvLV" +
                                          "E9v+uoBVExAxNLfnBzsbxntY/1rHDIi/Z1Fr7hSGaWi9IeiDsmiubGbM7GI5" +
                                          "RjLliKV/+PtGJBBmFMYMYZjluNSa8fHPGkgY0uSYbRaGxrNizgZyPqBDuDA/" +
                                          "Ki0JnbLpfueTM3962UOjrzNnkDOrZga5DKtZAE+zNcjNExrkbFwsPJk1ZBlu" +
                                          "9wDuTiTfBA2PS7RZEjWDKWVHkmKcnB6SysyQdA8KltwyGPdNDEb8cIsbG1Z8" +
                                          "LjybLGw2TSI2Ttbv80j7WyTfo6QcYFmrJdUYCGEajdkZNOKSlgh1wdBDxKJI" +
                                          "Vg4GzL1+AYMuwBUWMFf4BMxjHmk/RvIIBCcAzHpgX6KGLHKEMOWADcEPfYCA" +
                                          "6Q2+XGlBcKVPEDzlkXYEyc8pKQMILEXBL3fZrD/pA+sVmDYLnqjFetQn1o97" +
                                          "pJ1A8o+UVADrjbEhnA5tvajL1otODZwmp04c8wGVqZiGs2XMQiXmEyqveKT9" +
                                          "DslLlFSjTigj+qAFjZm9aZIJsllIyMO7q8qf+bV5/58e57FmvhDetUx78KFS" +
                                          "8feJZ95K+5JfykAxB/uzkPDwhqT/UnLlBNcQoVgCZ27NaIQ3Nj2klyf9qhpd" +
                                          "6nPHdi0d+I0+uOSFG0aX/IGFkaWyCe4r+MJ5lsgdZT44dPq9F6fOf5S5b4Xo" +
                                          "KiOEU917C7lbB1k7Agz9KiSnubBewkQolc/5AJdQE2i+Cbol5f7KYyheb4Aw" +
                                          "IX5vPPHNBETFiqTG+br1aiRv6Xb9QV4o281ia21NiqZK6Mal0/gqrayFMls3" +
                                          "kJi/pyrvKWssfzcZnyvGVbD/9kj7GMlHgKOIPeWMeWT/ZCzj4bAzuWPAbNQp" +
                                          "H2wUPmyRVLYUU55EG+V29gJlYwMTqEBSRElV2lC1senbTI/70rzL+QMQ4ITW" +
                                          "9/bklEDEAsU+IDYN0xbBo1qIqf5Y9cBsj7S5SKaD8wtg4T6SC6v8Wx9prNwF" +
                                          "GFR1frkFGEnoFlS6T1B93iNtGZIl3CnEfZ9OgabnQMx+0oag3i8I6jCXBcGw" +
                                          "TxBc7JGG1j9wASVT0Clke4suzlf4wDlLa4Rnt8X57knkvMBeDHubkfFmuZJ+" +
                                          "TVMkQc1vYxlKaz0QbEWympJSwK5bFPiu7NdsANf4BSCGVDdbAN48iQA62D/J" +
                                          "OOzx4L4XSQfIj+mUHwf7nX6FUxhq77fY3z+J7AftXGxRlk9PggcGIpKrKKkB" +
                                          "HdogxwcVeChbccDcdnwV2OqXFZkJz6iFxag/WHBdYvyqHlhgmwGZkvJBGUyq" +
                                          "SZsGrYVZmHoWee+6b5CpDdV2v6CaAc/9FlT3TyJUThA8VvwCNyBJUdwM75UM" +
                                          "KoPFwC9NNusjfrE+G56DFusHfWL9Zo+0byK5iZKpstmhNqYnXBf3X/eBe6yC" +
                                          "zbSHLe4P+8T9PR5p30FyB3CfdmKbtKTKrOUqm/s7/eIex/5nFvc/m0Tu81vL" +
                                          "Ax44PIjkB9xaonUQRAhX82Fxn5+ScNTC4ugkYpET0/zYA4afIDnkEIdWNcZ3" +
                                          "6RwQHPbTFByzIDjmkzIc8Ug7iuQXzBREpAHao3XhnOkyBb/0i3tceHvB4v4F" +
                                          "PwXghAcEJ5E8A3owKJgZPUgLgROGZ/2MVF+2YHjZJyHwWH8M4Ppj4CUeqTIV" +
                                          "6JUyR2bHjVTdBRhUfiyDlGPaefCctqA67afE/NkDr3eRvEnJXLScWkJPUinW" +
                                          "YciSynekG3EzhxX0CHaKY1oyvWI29npS4I9+ul9vW0C+7ZPMeSzJBXBJLvAf" +
                                          "zP1qVLjUudTto8lmnZ2My39Ubob7zGOIHYLPHHOaiEyl1chxOJG3gYWCJWNj" +
                                          "FCznvcfXIPtQmr8jzhVSzFaMpAxJBQiadE1SYKdEAvZeCtQ3Drj5ezRtLJwx" +
                                          "sYq1gW94WixYi2R61jhkOJkE6Qp6rL0F554hcjlL4Jh3FpI5SOZRUoo6jrKQ" +
                                          "c7aG7a44Ts7/oX1embajs4ZvxXicbHEX3CePnvynj6pu5AWzTz+yWxdWUXe5" +
                                          "V18pWFlO67/FTsRk9iHKI6TIxJx4bmfMGxysLn7WrnJc7aiztYM1n1GOtGhX" +
                                          "OfcCBLZiGfxc9onENGBRMVXXM31pxRVvcHYXjYNTVGxNRLufeHXPF9mJkKoh" +
                                          "2ZQpvwDE79zMyLpzkz4S3pB1FyUvklHxncf2PbfoL73T2CUDDhoytME6W7LJ" +
                                          "Uo4AU44g4acs52bxZPWDHWKJis8vly8p/ZdTD3PWxtqByi5z3b2fnHx31+vH" +
                                          "C0hxhJThISTBkGKtKiWhsW7xOCuo74G3ZijVECGVvLSsxtOjgNJQm/maOYpE" +
                                          "yflj1c0O2eae7ypTtGHJYPv0WO0i1zGopK47U/ne1tnL1fUGWX4G4GV4t+Yx" +
                                          "Ustwr7SlEU/bOhN1SqY1RRq7u6M9X+lsifY2drU2ro20MHnFs9HWEltea+2x" +
                                          "p3ilrMSaBCPG9fKBT6csuXzm8UuZXuYCN9lgMdtbmnLeeCCpCVv6Fi9LvxBJ" +
                                          "PZK1SJjNX+efpd/kkdZ2lnPkRiR44jPYDkYeXP/BJi3G5Hn1hLHb7IXdFawN" +
                                          "fOtC0oOk97NhZx9njcP8rgp4+nxcEK/ySNt2hiDaDV+IufpsOLcg2Yokil3S" +
                                          "qDwwgolfmzCYA15g9rM28A3XfoM4fsH4WYPp4MmjQ4pHmjphIPEIbjCBRKNk" +
                                          "CgeyUVEmB8shLyyNDJZs/k4iGfZPqa/zSLv+LJX6WiS7kNwASk01fsEyj0l3" +
                                          "JEwEz71eeO5GwvC8CckeJN/wWTZv9Q5BFmTfozKMpA6+VEtKlHQMXFkVt01Y" +
                                          "hPch+RaSOykpHBZk11bU2aL9XS+0785I7z1IcJE3+L3JlV4nmO7TwYqmskJB" +
                                          "96FQO64P3s4yPDCR0OQHSA4gedBmesLAHjozYB9G8kMkh30QY3sBO/g3+G01" +
                                          "69rj48H50wmLK55IDf4EyROTiOmvzgzTJ5H8EslT6TNGlFRm333F0+Kzcu7V" +
                                          "87vg4qOjVaUzRzf/lh9GS9/XroiQ0oGkojjvYDrei3VDGpAZBBWM1rCFjuCv" +
                                          "KZk95t4gSDn+YZPDEZ7/7ymZni8/JQVAnTmPgfl156SkiP115nuOkjI7H7gS" +
                                          "/MWZ5QTUDlnw9XlwfwP5/V4y7mEZx/WbJWNGim1J/n8dRMXHRje2X/vhFx/g" +
                                          "l0PB+d65E2uBAKuE39FglRbkhLTO2tJ1FW9Y+nHlj6acG+TCwq+71TlUaK4t" +
                                          "SeQWkHcdZWCO61KgWZ+5G/jqgcuOnNxb/CLEyFtIQIAoZ0vuNd6UnjTI/C2R" +
                                          "3GuC6YCqYel3R9YsH/i332PH2OXC7KvT7vxR8dRDW1+6Y9aBBUFS3kqKZFw1" +
                                          "Z/eLm0fULkkcMvpwZ6ElBV2EWmRBybqDmD9enZoVr1KyOPeO5rjx6dQIKbe/" +
                                          "8JHxDFmxgP3FGkqkzdzQ42iA3EUjbbqejskKn9aZzrbksU6khcnqa+wV317/" +
                                          "f0BdmW4FRQAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188907000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALV8CbDr2Fmm3329d6fXdDoL3UkvyUzi5MmyZctKhxBJtmRb" +
                                          "si1btmQLyIt2a5e12LJJA+kZyEKRdEGzFaGhhmQITBIY9pkpoKeYAGHJFEsx" +
                                          "ZGqgWQdCJjNkplgzk8yRfLd333v3pXPfu1X6r6yz/d9//v8/5+j8Oh/9XOnm" +
                                          "OCqVw8DdmG6QXNCz5ILt1i8km1CPL/TYOidHsa6RrhzHE/DsovrYT9zzd194" +
                                          "ZnHvXukWqfSA7PtBIidW4MdjPQ7cla6xpXuOnrZd3YuT0r2sLa9kKE0sF2Kt" +
                                          "OHmSLd15rGhSeoI9YAECLECABahgAcKPcoFCL9H91CPzErKfxMvSN5bOsaVb" +
                                          "QjVnLyk9emkloRzJ3n41XIEA1HBb/lsAoIrCWVR6zSH2HebLAH9XGXr2e95+" +
                                          "70+eL90jle6xfD5nRwVMJKARqXSXp3uKHsW4pumaVLrP13WN1yNLdq1twbdU" +
                                          "uj+2TF9O0kg/FFL+MA31qGjzSHJ3qTm2KFWTIDqEZ1i6qx38utlwZRNgfdkR" +
                                          "1h1CKn8OAN5hAcYiQ1b1gyI3OZavJaVXnyxxiPEJBmQARW/19GQRHDZ1ky+D" +
                                          "B6X7d33nyr4J8Ulk+SbIenOQglaS0iuvWmku61BWHdnULyall5/Mx+2SQK7b" +
                                          "C0HkRZLSgyezFTWBXnrliV461j+fG7zl/d/gd/y9gmdNV92c/9tAoUdOFBrr" +
                                          "hh7pvqrvCt71Bva75Zf9wnv2SiWQ+cETmXd5fu6dn3/bGx95/td2eV51hTxD" +
                                          "xdbV5KL6IeXu3/4q8vXY+ZyN28IgtvLOvwR5of7cfsqTWQgs72WHNeaJFw4S" +
                                          "nx//yvybf0z/7F7pjm7pFjVwUw/o0X1q4IWWq0e07uuRnOhat3S77mtkkd4t" +
                                          "3QruWcvXd0+HhhHrSbd0k1s8uiUofgMRGaCKXES3gnvLN4KD+1BOFsV9FpZK" +
                                          "pVvBVToHrv9e2v29MSdJ6WuhReDpkKzKvuUHEBcFOf4Y0v1EAbJdQArQegeK" +
                                          "gzQCKggFkQnJQA8W+n6CuQJ9m5vnBBA+lH1W3gBlupArWXhjq89ydPeuz50D" +
                                          "gv+qk2bvAovpBK6mRxfVZ1Oi/fmPX/yNvUMz2JdLUvrnoMULuxYvFC1eAC1e" +
                                          "yFu8cGmLpXPnioZemre8613QNw6wcuD/7no9//W9d7znsfNArcL1Tblks8Ls" +
                                          "Xl78uBWUe/3VfTKVO4Ru4QRVoKMv/6ehqzz9p/9QcHvcreYV7l3BDk6Ul6CP" +
                                          "fvCV5Fs/W5S/HXigRAYaA4z7kZPWeIkB5WZ5UorAsR7VW/0x72/3HrvlE3ul" +
                                          "W6XSveq+1xZkN9V5HXjOO6z4wJUDz35J+qVeZ2diT+5bd1L6qpN8HWv2yQMX" +
                                          "mYO/+Xjvgfs8d35/R6EJdxd57gPyLjrgcXBd2Nf14n+e+kCY05dmRVfeV3Rl" +
                                          "ztKFLnCyph7d/6c/9KG/f9e7m0B03dLNq5x1IJV7j/IN0nxw+NaPftfDdz77" +
                                          "x9+We5Hcts7llT6aK8fJnsk5/2o+/IE/+NRnanulvSN/f8+xERRI78ljPiav" +
                                          "7J7Cm9x3pGuTSM+l/Iffy33nd33u3V9bKBrI8fiVGnwipyTwLWDABAPPt/za" +
                                          "8tMv/NGHfm/vUDnPJ2CQTRXXUsFNXIx/CeDM8mV3p7b3fQn8nQPXF/MrF17+" +
                                          "YOcw7if3vdZrDt1WCAzppa02ORzjk+5wcHE6aLXHbHfQPl3vucjyAOLVvv+G" +
                                          "nrr/BeeDf/WxnW8+qeQnMuvvefZ9X7rw/mf3jo2Ij182KB0vsxsVC015SU4q" +
                                          "GeDu0dNaKUpQf/njT/2Hjzz17h1X91/q39tg+vKx3/9/v3nhe//4k1dwLufB" +
                                          "2F34KNDSE1eRw7EJ0UX1md/7m5cIf/OLn7/M9C9VmL4c7oDcnZPHciAPnXRL" +
                                          "HTlegHzI84Ovu9d9/gugRgnUqAInGw8j4BWzS9RrP/fNt/7X//jLL3vHb58v" +
                                          "7VGlO9xA1ig5n7uAEShZgOnOAjjULPyat+2san0bIPcWzq5UqM2rLrXAfwYu" +
                                          "aN8CoStYYH6TW+lefoMXP19X0Nfn5I07Vc1v35STCzmBCtgVMAwfUzd+Mu4y" +
                                          "7UlnPJzSnTy9sRN6Tp/MCbHT6rd+uYw/Bq7KPuOVUxi/Kb/pvjjGHzjG+FDY" +
                                          "mcmVeO69SJ4xcNX2eYZP4fnW/Gb04ni++xjPOMteid3xNdnd2dy5c8DTVC+g" +
                                          "Fyr57/mL4+Mh21WfOHA/ApikA9N4wnbRovyDyXFHvZvZnmCy8mUzCSzq7qPK" +
                                          "2ABMkr/tz5/5zQ88/gIwpN7B0JDnfgK4f+G9/7b2D/kP5cXheWWOhy+mPqwc" +
                                          "J/1As8DiQDuEVDvGNJqAmV9wBkjJyz/SQeIufvDHCipZN6ewJJZrxsCRQnPW" +
                                          "GpY7a9ok12KdsNX2GLHx7brd4tZ1dwG1ul1lCsOTKUZogiBps9QjKlO7PMra" +
                                          "JkQTXqBLKRkv6aTVzvojh0/MDhOsEEPoiDLLMH0pDGYsJCiYMUCjZaQ3Gxgs" +
                                          "1AR4UoE37W1mzEQvTdEtxOmq2izXW+sGNkHCvrnZjARiaXXR0Fm44bRqOfNw" +
                                          "MY6m5mSCdqnV1KB1PO0YCVqbrKywa62Sbl0mzCTwSEauTnq84GFhpx57IT8a" +
                                          "T90YrvJz17IqdaK/GZv8ktmEhjweDtx4kloM2/dqk/mi5zUIsU8yzphpzRzI" +
                                          "4gVxWWGYnmOYUqMtTiHS1lFnYVphuyVgWR8pb+o0tpFoYCeDqriZu7DUSdYh" +
                                          "Ppq4PYmcao6zlZ0W16VmwoBGgpAewQyziOYRBccjpZupPs4RyAITIN0ABWGx" +
                                          "v7Y8Ul4up6qsV3lR8uyuk/GMs1mhcuCYvWYWbjje6zqdXkdyomW37NJrjAho" +
                                          "Ihyo1ZVvJnXO1cZO4Lg2OiAqE1VsWETVkiiq2lNCk8S9yHNQUWpYC5daNuMm" +
                                          "i6MTR1Jsbzbktzo2n60hP60KE0wfMVGD74mx5g1q46HZXkyVBk7hYYVvSpLX" +
                                          "j3vxrMF3K4yJVRJaYcxNK00cGYHrirmskKO+kQUi1LOnvfkQlsU+haytJj31" +
                                          "xrIj06tR25sO5FVgUpSFD1f9aqYP50bUbMVrkZRaGbImcH0yZFwGGcGS7ZJZ" +
                                          "xW3aa5Ft9vpOCwActwlU6E8RcYkTWJcdq+Ox0LIRERlxk+lQnMeVdptsObZr" +
                                          "C0E4byCgHmTBTqVxV0DrQ9/k66GNmzFugsVCPY7I+TyceOl0xvS30CpxMbgR" +
                                          "KSHRkro41nI8axRVV9maYWe40Ai7dK/dJzkdp5i6RKELyePYSo3HF07kD9y6" +
                                          "75aNpNpxN5ihcqO672mpb681SItdZ6pQOFQVVnV/lnTGAj6TbWGg9emRClm1" +
                                          "oSdJsMg7A4ZYx9su3Ld7gcJbUx31Vz4jZOVxzUz52JV4lg6ZvkltBHKwJAVY" +
                                          "7NFDLGwv6REjzJm6Yy2VtucmdYZPcay7jHkIC7I+TTBJbzpl0mwSq1IZr4xa" +
                                          "U1wgBVxZxfbSDDUMNkeNDVYfD0nSIxbriVkecwuoPrcDcczqFMHyNEVQ1FiC" +
                                          "VUZbBErTq9LrIVfFUZFEOo1xeYzZU8eUu3PK3CJem6jTxChesNZoS1aXPQQb" +
                                          "sSE8mle63Q3R745Hm5oGLadNW0uGFI53SaMOSygxGXtmQ2n3yP4SdcqpYvjr" +
                                          "im72WJcJiMU8dTtrXTS3GeUM42xMVuh+VxxhTuI4JD6YjDSxLNtkdbjF0ZG6" +
                                          "pbdUJW0kdAPSU9TEs3ZgsM7YmVa2ST3qGgvNJiLW60z4MOxniNCp+aHjY+UG" +
                                          "J6ML1J2zi5oyZ1fM1lgaraUAYfUVlI0XW9Ej4nRjcZvIZjBkytUmqS+rMBpx" +
                                          "62mfkqb4EIydaAuPlIWUBnMZxeeqwhIa2gw77UWTojLVIEH3cG43EU25LMAk" +
                                          "P42A842k/iAZiJ2NTETcOMabIhyr7Q3Rm/RVyGArYtaqhoHVbMyG5lyqbbu1" +
                                          "1bTuj2AWb1ZqVKAyG3FNDDdwl8UybSQNE0ZiJspyIG6n8TRdCFGro6peYBjD" +
                                          "Ml4rY6panuFsKE5tvj0badNlCjfRqaeO0Xq5waD1urEyUlzoUMl0bfZE3aqx" +
                                          "Tmfhx2U9TCEjXa24VrqYtvmE0Wkm1tVWasLD/nosuArbapcHrDTHFsEoWEFK" +
                                          "srVXK92HOMqSJw496K1MJXImMkEDjaV0OfDqDbSezCZR1kQoddtVRzRVnthS" +
                                          "q4oMVr1FvFxORn3YESgSXVS2ZcpYUwgXtztrtc/VWGU6cB0aDTf9hTYg6o15" +
                                          "LdmOYa01qyYduTLe6rUBqlXGQqSIDbJjVSvCaFReDjF3VXHqrYlJRqO6PJhh" +
                                          "bj1RrNpq1QdTCWvbzIAN6MFwsTJgyFfQ5nrbrfj1NVKLeDxtrb3xcpAOp7Uu" +
                                          "A9Oq22EwaowLNYhMqyGHonbNV4dNrlpP1KooYmkDKmvcKDLSOq0z23KPUS1t" +
                                          "LC1iyIkSJGl6S8oV7Fq9qVUhPTIju9oU0Jmkgs5MqU1nBjWgeoUzjHSAdILB" +
                                          "HOcQetBiB+5So9cZQVf6S1fxswzydZ1S6oZJ9gy5H6A9HuUnFDlX1LXeatbh" +
                                          "5lZf+tEySTxCcwi+6iSMw7jliUuFdlUPpbmloJ3RwEkzsrpxo2ZQIwlWaHgN" +
                                          "bNsYNVbwHAE6hol9K9K1skcs0bXW4eJN5g78BswrQWeIyL2huqi1OI3wy605" +
                                          "XidXQToETlWIxluMpqPYzELKY9F+y+Q8D+ZFAKJuVcIyVjOg/pBb1jJ+hLRC" +
                                          "PvQWpNKr4jOr00dno1Gn7xIeE/LlUF3VK1KQEuPuQEposseNABq6UePWC7La" +
                                          "otS6HXM41VxPsnBew2Z9JShPzRTpLQfRJh1F7fGmK3Jo1yfWnUEk1TROSJee" +
                                          "K1UGs6yswPSWwKiRqjVmgYNq667S2k5sq0zX10yEZBqisevRbCtBSVDn1Brf" +
                                          "DOqa4s4yDF1V+4aAUFtEEH1YQzDWac9QqZzY9dlwFal013caZaRqlxveilra" +
                                          "ITXCzaqF+1R70xsP6CYz12qmSzBSE3IdbtjqL4makXTmWYWLwHhmmiLUIgR+" +
                                          "MsEMZz53MqEjzJfrcINR4XxDd9Gx1xR8v9OpYeMO3GRhiwDTCSripxQhrmmP" +
                                          "xsGkY64KS5g3N8q8hXT6Kj4haDSYe7xNd1fNObNgYJmPpouN2lr1hyoiO7bS" +
                                          "88e2G8BJI4E1o6bUZmWlEhFe04srIcgijulwHi+GLbi9XqcJSS2jFbPA4mFH" +
                                          "wCDfX3ScvuDX+rOepacbcis4YhPZjJAeLrACGJI29tAYtshGFWjJWkXmflBB" +
                                          "V8sqb8+NBSTGfdsdS1NOboMpFUsSAyYDjpmuzI2E5UJtydmbmeiE26WQhAru" +
                                          "c20NNsdux3KXuFxvbRXP6QVhl2hZjD1TYGkhD6eEqC9mvd5GhyJjWSMEDhqm" +
                                          "CTzL+GmZYPWFJdpwmYBmtaq4YoU2tiqnASG0MzwbsIZPbGMl85M5BEedVteC" +
                                          "JJiK0AVPy6KFdXWrFXtWqtBKH6W79bHNuhYjQGUuoXsE4VH9eX8OpjPpgJeb" +
                                          "RoejHXNeSfm5MpbpLBpYW1PacEuilbZwiLEqPV9hQyPVJ/0a1qhOh3a0HfhO" +
                                          "axhJJoDGJBLeLm8Hqj1oZ5GjUOuY6zmwRLgptm6lE2tiEHiV49Gx1LbFFiMK" +
                                          "HcdjVJ9o8Jt4M9LwJuMm6w3NaYNWW2mq3VihYanJ2huFpdfVCd+tThJl1azY" +
                                          "qLiZGEFjpM4pL+pp0zlJt2Vbc6TBkOFdcwGvNaKVMb2uYCL0loXL+Lyfrokp" +
                                          "mPUZCNHP7I7nQONVt0uQKr7tgEVHg6HZDtPuD0W8pbY5Y07ijVG1PKNdQmUE" +
                                          "rt3aus5s3t6ozZAZ9btse0awNUOKWlCIl2PBa81Zf2lTejLy4QBDwx6MN4GF" +
                                          "C3grspX2wsfryUq2WThIhi1p7YUVRG2uaWEpWXRcnfVH1sxrb5YrnZlgrdhl" +
                                          "XYq3J5Zpl5c4ZUseJkvdXuy63U1/iC6bS6OsCHWo3tTrKOWtFi09mWZok6H4" +
                                          "pqH3JKzOlOs9Y+PgGQGlW4drrRfLCTT1WZcYqKNAMEmpig7k7qg2sKuOuzGw" +
                                          "5SLUGj7X0ayKVu5WyumQp+iKPIO6NOXI4obUkajc79Xd2NSkCYJo3BKjGsbQ" +
                                          "qPN1BZkFjDVsTzEYJVFXIWAHxc0txli8nyqEvnZGgatCdbynjdpVq0wqgVs3" +
                                          "UGa+WegKgq+7s/qK4zoDoj2hrOWELisRLFvjVWOmYCMBCapN2JKr8MBaSkyj" +
                                          "L7sVyFxG8obqu3HN6VlQuAHGLcaxsVUlf7OiBaUFYY6N0n23YzLDLqeLfV2c" +
                                          "QBK5tREF36YihyuDUdiprqectxkL7Hw6rdfbdFmoYmbPna/7k2Wb4MdtV6i6" +
                                          "JBzrvjLpQmgl2rLlUX+EdCciBimO22618Xha7rbmg0qmEAG87C6N+hxTidhG" +
                                          "+TrPyK3mOjGRSYMnG6ummGFhNFhTNDWGjcih6LYfUC7fmMAEVrMGCS113Rrp" +
                                          "tw0JG5qy4o/6WbkSyGbNanYbNjkjVBqMHoSK9mgatrE1zguTCuk6OhKnW9dA" +
                                          "1i2XlZGxnzRnddTxnVWf0FudVHEMykulXnki9J2RCq/mmcvI28pIaYsbL+zx" +
                                          "a6auUJyVogMtxgfAPniSFlqagg+QpjXCG9UW1BsOtxnCIjN+ZHTtsjftrA3U" +
                                          "nzWoabZYoqgxr4HZA4obyYzOxq6DcaYJhpaQiRjGITpaYGZrVdDJhaKqLVXz" +
                                          "10J1uJxRktPbNiwqk01I7BDafLVZdtyF6a1pyVn1CHq6WfJSTEdzQfI6gajr" +
                                          "5YZSJ8OWJlRXDVLGVQij3EltsulNJwu8KazW5ADMTKfauo/Wp30m4Kg1iQ0G" +
                                          "aWwbURsMlo0WlcYdQ2QxKShXlA1TtyQmjBNvMVjO/Rlh1GaQTugNMCQofIfV" +
                                          "Ea7cnGDcuB7WKtSGqJGG5jFKwkyYaDhdelCMQnpXz6C6T61UyKtM0ia8YvEM" +
                                          "Qbiu7RBYJgf+dDTGF7Nmlcr8eplXBxMSSU1nHrYnFWg7xxHZ6LZ8p93VxIEq" +
                                          "1Rrj9ajDKROK2Gy7LdtzwLSzOTVRKwXDOzFuh3hHDmqzhT90NoQCVaxaouqd" +
                                          "FYGsEIpbz8wFrrZ79XYTrwVrpmdK3NRkzfGQlqBqX6DK1XnHlnqbzlrsNPsI" +
                                          "F9oIOdWXk67QAIPeuKp0bGGiEePF1LA2LZfmZN0g1WSJN1DZaEMDpxXV9PGq" +
                                          "7fdmLK+KTo+bWr44Vy1+4+sOXWtvF9msQnZkZg4Hm5XYrWJ+yCNdrJy62Eqs" +
                                          "kGVU4vo6v+0RM6LHrnBjy8FLgbWnqTZJgqbr+VK1v6lhUyVQ0C097HbmLNfp" +
                                          "DGWrvXFhdZENe3TNnItkTxzYFLn1V6ox63LJyIua9nYh8FtK7od41iNGlqy1" +
                                          "YX7OaG18JelkMqoBT1zXt+OE7a2zeL6ETRFDRCubW9VxA7YXzrDntBujsBGx" +
                                          "FapeRxaq7bJIb1Gjwm6dH0rjaRA07IgZqahMozKCTED3BzNY9xTZjhFplc0s" +
                                          "Vem0ZzVS5/zVxrcbYVrHxe1kW96ImSZOZ3pdgJuhSLnDBgpRk3jsYFaH6TYm" +
                                          "3ayXIYpn9OlsE7M+KkZ+DzRjbZN5H/ZhepjQi9nQUMHEFwwYRqZigd8e0MS4" +
                                          "L8xm/RocZmNhpXbmM3s+mAh0NhizqaF3ZhyFeT2HCRZVaRSu1q02im37Gzbc" +
                                          "OluEr4UETG2mK8ftZL5qVDnFCFi0NqmS01ZrEWySfrshomxvGiD4FEFMRFbj" +
                                          "elXJJE5sdUSmZ8XNlbtphpCkTVo1TsySJbGx6tuaUjX8TlaDy6sOWVlki95k" +
                                          "0eUnhEMzCWOJi1hEsyGZBihC1yTLFtrA3axYPs6SoW0OeiMP8uQhMJCN4dqw" +
                                          "WhlWdVlHN+EkoTu9ObeqiMOKBW/pIGQQdAoWF3Dis7AxpcUZQiO0gCTleTaN" +
                                          "k3WE8m57CinDxQDml3N4PF6iaaOPzcpubBnzqhZNq1FQrfQ7PhVjHbHtJrpc" +
                                          "rmZhzXKjPi8TJEdjBkNMGmqczrZec5pKs3RODjDX7GuJ4vmsrpNkSAqrBmVh" +
                                          "7CojepzEwHzPHszKuhFqkONoUtX1OWdsjRHE5uYtZ67POIjoWTW63vHhBdtR" +
                                          "0O5Mo+T1wBgmZCUYOhg6WEgZ5tsq14zMECn7mdpmoA0/SKoLqyW3hHI3NcJ4" +
                                          "yKpmdR44llvjl6312gxcw9uScxyum1jU");
    java.lang.String jlc$ClassType$jl5$1 =
      ("rwInMDOCPmLEHUSccyHS9+wREnY8O1x0uXZXsUlizAwc0tQ3U6HtEc14wW42" +
       "g1ZPAitABOiZxC1laMuzqzLbmzVEi0edARh2nApsxO2NXXFrvfa6vUVhXR/W" +
       "6fWKbJKqo/cG0FqcSCtsVCcoD8zTtgywyUZZaCeM2xn1Z5QjJBV4vuDURXks" +
       "88ONE3YIyYFhZVqVWWzGlytos95Ft3BX7bVrZbbWcwXE94boZD1ferHTI7AG" +
       "NRo2EK4WIxuuRY4rw1GHxxFT1whPj1m8YwfbOYHRTafvLGqV0bwWE0PIrJXp" +
       "CtzAIhtpduqVtccy9Xq3ZSDtzXg4sYbeamtuJ716p9mO3UljMqBdauzVajWq" +
       "Uma2aooKTXRlIsuhLcjT7XhrQO4Co3kMmkWBNaoEtBPY9mreinSrJrToEJcI" +
       "QuzDEUnZKbliJAerJ4jJt/zyXOJabQmF0I0n+VYT6o0E3J94nGm4cL3BOxYH" +
       "w3U/HTp2F+2gJg/1Rak+mkxbrr/GZu7aWHN1SEA2qNeWMkhUgD+kLQ/uQX5T" +
       "G/dnnbGtV2fQakFlkOlWOKKsNertakrgTNquYZTpjhVnwU6G1aQHUyI2L/sd" +
       "127IKl2ekOtlGYUn7lRmkITXR6LTUTVJJIcNmDFFqVynIXtpqunQH2QKRLLt" +
       "DZV0R108kCqrdKA1pr4NZktkdVyjU7IxJ5dz3a2NsXncgaxarcp1qsMZiTKr" +
       "CbrKxoDblgiXG3NMJogpxdecJSNRa1iCdNarGFPWcdT+KlxLjbZLCNW26I2J" +
       "jbJseS1M96VAiGBmM+SA9kV21tBGXUbRoWavk7UoLzO5GkU7S2erbUcIWNPW" +
       "2lNbUZa6HTuMD2bU20hx4mnDWaj+Ui6vhRqMQkaF0DwRocYjHM+3LLwXt5Vy" +
       "X7E1dBgBZbtonvD2F7Fbkp3WYFK6TVbiJJLVJCndfhiStWv9WKRHKd+Lffhq" +
       "wU3FhvKHnn72OW34YTjfUM4LNkGFSRC+ydVXunusqsdATW+4+uZ5v4jtOorO" +
       "+NWn//qVk7cu3lFEGVwWNcKW7shLcnkI3WGo3KtP8Hmyyh/tf/ST9OvU79gr" +
       "nT+M1bgs6uzSQk9eGqFxR6QnaeRPDuM0otJjl+24B6qupZF+1O4bXiP/zMVf" +
       "eOqJvdJNxwNY8hoePhEOcqcRRJ7s5g0chLndkSyiYH305EqxIQ+D6837m6Vv" +
       "PrlZeqQzlynD3qH2rfa7Piq97mgXnQxcV1cLqT8x9b1iO09WXD0PEfq/97wW" +
       "/pn/8f57d2ECLnhy0A1vvHYFR89fQZS++Tfe/vePFNWcU/PAwaO4gKNsu2i0" +
       "B45qxiOwcMv5yN71Ow9/36/KP3A+D3G5Kba2+i6EpcB37mAndVdSXicX6EgO" +
       "F5YaV1sF4vcVOb6loO8tTGin9vnv9+fkXQlQlUheX3EDcxVY2pE1Pn2tvcvj" +
       "DRQPnjrsxjvyh4+Aq7Xfja0zdeOloPaFUexzFxm+/xTUP5CT705KLzX1pKWr" +
       "QVSY3TBN8ji9A3nefShPfiHva2Yhg+85gwyKbK8CF7MvA+Y6yuA4xB89Je3f" +
       "5ORDSelOAJ8IUl8DmnKA+hWHqE098C6MgW7Kvunq+zkKAXz4rALIgzVG+wIY" +
       "3SAB/Nwpaf8uJz+ZlO4HAqABTD2JLHUniTzlY0dQf+qs+v5ScIn7UMUbBPWX" +
       "T0n7RE5+MSndAaDuK3j+5AePIP7SGSDelT98Obgu7kO8eIMg/udT0n47J7+e" +
       "lO4CEHFtlQ9IR/r84KX6zAVgInBcl3/jDOhfkj/MxyVtH712g9D/4SlpL+Tk" +
       "D5LSvbkuu5twsS+CGAwmr736XKQYXHZxec/968c/9U3PPf4nRbzZbVYsyBEe" +
       "mVeI+D5W5m8++sJnf+clD3+8GO9vUuR4N1k4GSp/eST8JQHuBYC7DuX5yhzU" +
       "q0u7KLTSwf+kJJ4xIBkU8/KBNohwcFf4+oNY5xtVdXalsRRMgwI5OTlkHYX8" +
       "/Hl2rlQozmevpTKHc+hbXN03dzHjRXjXn4XZYf17u0KXzg+K4CjSDXw9n6Qc" +
       "pO0ipK3gwuFnEyAxuyKnT+04LRq7MpvFIPymayr1P56S9oWc/C2QmJpzugN2" +
       "SvYv7ttqYdGfPoNF5966CLmz9jXQuo4WfXKKcu7Wq0M6d3tO9pLSPQdm3S8G" +
       "qfigx15/xSB4A0y8L9DC5LISuWTOnT+DZB7IHz4KLn9fMv6N8XXnHjwl7aGc" +
       "3AumZkAo+VcWJ2Ry5Q8DDmRyskAhkvvOOvjl89lwXyThDRLJ46ekvTYnj+ym" +
       "MvnXD5ycHIwAefbfPYL66rNCfTBP3oe6vkFQoVPS4Jy8ASy986lM8SXNCYTl" +
       "MyAsHuLgenof4dPXEeH5o9cSf1mQK40OtypB4OqyX2B98hQ5vC0njaR0G5AA" +
       "r8q7L4meORIDelYx5NPz9+2L4X3XUQzHHODvFkh6p6DMQ5bPtUFvx8d7+xhM" +
       "6qxT83wZ9uw+zGevI8y9o1zFmLxz9sIpWGc5GSWl+4Bmdyxz4YIrKVadee6j" +
       "ufq5a4ZsX8uGHwLXc/uYn7sxmHcaXuBSTsGs5eTrwSJ0YQHHFSfkYv+LUODI" +
       "Hz39C6+OlRyJ5O1nFcnLwPXD+yL54esokuNgT5m8nMtfkp1zkvxbLEGPEgtY" +
       "dP7kLUcQ3bNCfAW4PrIP8SM3COI7T0n7xpysk9JLrHjo4wfD1AmU2RlQ5lmL" +
       "8elj+yg/doNQvueUtPfl5F8AlAdTNjJIdx8TNY5Q/suzosz78mf3Uf7sjbHg" +
       "Y17r2VPwfndOPrDzWrn1yipY610J8zPXo2ef38f8/HXEfNmM/IdOgfuvcvL9" +
       "x7q362u73YRjUD94PUz1E/tQP3GDlPijp6R9PCc/UpgqqxvJJBjnY9EJU/3I" +
       "WVHmL00+tY/yUzeyQ3/+FKj/Pic/BfR3IceH+nvQqcfh/vT1WDf9/j7c379B" +
       "nfqfTkn7lZz80m7dVKiuoB8eb3DNddPJAoVInj+DSO7MH74OXC/si+SFG6kB" +
       "v3OKXH4vJ7+VlF6Ve7DAC9NE14aRpfu7fTg8f/FdFKwVTR1O1W/RgvTg7Ukh" +
       "jk9dj0nIX+yL4y9ukIb8ySlpf5aT/1ZMQnB3pyMnjOAPv1KIxWfIV/4u+WUn" +
       "PzC/UBwjEobXQQMOlPvYB4a7Ngq8//MUWfzvHff57WeKB//ryowcf8+VZ/tc" +
       "Tj6fk/8DVERfpnKxN3xciJ+5lhCvzNE/5eTvirpy8vc5+ccTXF4PDfnS1dP2" +
       "zn2ZUrnsJWWe94t5DblO7+2BdWtubXk/n75bzqdKnBw7ZOTbred+69f/9p53" +
       "7b7qvvQb9eKcmf2iJ8t9+g/OV+9MnvhAsct++Kr6NrZ0c5znTEqvufqZNUVd" +
       "u++277ymNj94pM1F84fKfKCK9xx/AysXb6H27rrki/YrC+Gi2vUu8j/z6Xc3" +
       "ii3ke1ZWbAFPNdk/RufSDeWjEy6evORonSuK6aL6Vz/+7b/26F8LDxRnpuwk" +
       "knP7lmy3ZPmafU09V2jqXmFYV99X2Oeo2P++qL7zg1/8rc889UefPF+6hS3d" +
       "kcciyJGudf2kdOFqRw0dr+CJCbhrgVJPsqW7d6Ut3zwQXN6B9x8+PYxISEpv" +
       "ulrdxekFJwIX8sN63GCtR8XmX17twyeiIdIwPJ56fMfiK1GFb4xKb/wyhHeI" +
       "fX9IKN1fKP2x75vzYwyOJ4ZJ6QGSxXn+4mTOtS8K+LiLE2y7ULH8rIdzk8Jm" +
       "s1N6T7RcjZQjbWc2H/7S7Y+/7aFPvrkwm8uF9BUK5uoeP9zxd/wMlv1x5Aye" +
       "c+91Obk5J/kL9b3Hc/La6+8598qnpL3pKxtP9t6Qkzfm5AJwmmCSChaUWqGY" +
       "jTPLpZ4TuKgrv6vmBPky5XIUz7UC45wv52dvXFNAp7zQ3PvqL1NARw1DeTHs" +
       "SFRvzkk+Nu69NWcpSCxjkyc+c2ZBFRZURLc9k98ROWm9eEEd4/eUxk55H7rH" +
       "nllI3ZwwOeknpdt3QsJd9/rIKXcve9yhnEY54W+Aoc1PSfvar9DQ8teve1JO" +
       "vg4YWhIcHUTx9jPLRc3JxaKu/O4dOVFulP4sTp8KP3Lp4UlRlIZgGtHOVD3M" +
       "lztFFfaZ1SwX3J6VEy8p3bSWrZMv7r9CSebV7IWHGrbMSXydNOzYqnFRNLa5" +
       "aoY9p8jwDWeYDu8VNWxz8s4jUGcW0NOXCuibcvKu66lqx14R7iIOimbffS1R" +
       "vffMKvWtOXlPTt53HeX1zKXy+vacfCBLSndfeopcHpX58stOqNydqqh+/Ll7" +
       "bnvouel/2cXBHJx8eDtbus1IXff4wWfH7m8JI92wCni3F/TuYsG7951J6RVX" +
       "3fkAtpT/KxYN37HLn0cwXil/UjoP6PGc3wfWwSdzJqWbi//H830wKd1xlA8M" +
       "pbub41l+ENQOsuS3PwSmbeeuPF8r3X+tPjkWfP34VRcp/XR3auhF9cef6w2+" +
       "4fOND+9OZAOTxm1uP/kq4NZdPHFRaR6b++hVazuo65bO679w90/c/tqDcO67" +
       "dwwfmccx3l595UjfthcmRWzu9ucf+um3/Mhzf1Sc1Pb/AZbdy37MVQAA");
}
