package org.apache.batik.gvt.event;
public interface GraphicsNodeKeyListener extends java.util.EventListener {
    void keyPressed(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    void keyReleased(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    void keyTyped(org.apache.batik.gvt.event.GraphicsNodeKeyEvent evt);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188907000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Ya2wcVxW+u+t3/E5ih6R2Xk6Ek3RHKRSpOIQmjp04XTuW" +
                                          "nVbKmmZzd/bu7sSzM5OZO+u120AJQk35EUWp0wZE/ctVAfUlRHkIWgUh0VYF" +
                                          "pJYIKKgtEj8oj4hGSPAjQDnn3tmd2bE3Rbws7d3ZO+ee9znfuX76Oql3bNLP" +
                                          "DB7n8xZz4iMGn6S2wzLDOnWc47CXUh+P0T+ffHfirihpSJL2PHXGVeqwUY3p" +
                                          "GSdJ+jTD4dRQmTPBWAZPTNrMYXaRcs00kmS95owVLF1TNT5uZhgS3EftBOmi" +
                                          "nNta2uVszGPASV8CNFGEJsqB8OuhBGlVTWveJ98QIB8OvEHKgi/L4aQzcZoW" +
                                          "qeJyTVcSmsOHSjbZbZn6fE43eZyVePy0fqfngqOJO1e4YNvzHX+5eTHfKVyw" +
                                          "lhqGyYV5zhRzTL3IMgnS4e+O6KzgnCGfJrEEWRMg5mQgURaqgFAFhJat9alA" +
                                          "+zZmuIVhU5jDy5waLBUV4mRrNROL2rTgsZkUOgOHJu7ZLg6DtVsq1korV5h4" +
                                          "ebey+PjJzq/HSEeSdGjGNKqjghIchCTBoayQZrZzIJNhmSTpMiDY08zWqK4t" +
                                          "eJHudrScQbkL4S+7BTddi9lCpu8riCPYZrsqN+2KeVmRUN6v+qxOc2Brj2+r" +
                                          "tHAU98HAFg0Us7MU8s47UjerGRlONodPVGwcuAcI4GhjgfG8WRFVZ1DYIN0y" +
                                          "RXRq5JRpSD0jB6T1JiSgzcnGmkzR1xZVZ2mOpTAjQ3ST8hVQNQtH4BFO1ofJ" +
                                          "BCeI0sZQlALxuT6x78IDxhEjSiKgc4apOuq/Bg71hw5NsSyzGdSBPNi6K/EY" +
                                          "7XnxfJQQIF4fIpY033rwxt17+q++Imk2rUJzLH2aqTylLqfbX79tePCuGKrR" +
                                          "ZJmOhsGvslxU2aT3ZqhkQYfpqXDEl/Hyy6tTPzzx0NfYH6KkZYw0qKbuFiCP" +
                                          "ulSzYGk6sw8zg9mUs8wYaWZGZli8HyON8JzQDCZ3j2WzDuNjpE4XWw2m+A0u" +
                                          "ygILdFELPGtG1iw/W5TnxXPJIoQ0wodE4LOXyL8+XDhhSt4sMIWq1NAMU5m0" +
                                          "TbTfUaDjpMG3eSUNWT+rOKZrQwoqpp1TKORBnnkvckWoziL2p8M2tfKa6kxA" +
                                          "R7qHzWP7QbvimG7W/0tQCS1eOxeJQDBuC7cCHaroiKlnmJ1SF92DIzeeTb0m" +
                                          "0wxLw/MVJ3eA7LiUHRey4yA7LmTHa8gmkYgQuQ51kLGHyM1CDwCC1sHp+4+e" +
                                          "Or8tBklnzdWh30uiKDeVf8DBkK6i/D8xbT3xi5/87iNREvU7RUegxU8zPhTI" +
                                          "TuTZLfKwy9fjuM0Y0L11ZfLRy9cfnhFKAMX21QQO4DoMWQmtFlrW51858+Y7" +
                                          "by9fi1YUj3Foz24aUI6TJpqG3kZVzklzpUlJw9a9D38R+PwDP2gjbsiE6x72" +
                                          "sn5LJe0tK+COiHjewEmvb8MI+r7sa3RXX63+IXrf8rnFpcyxJ/fKKu+urskR" +
                                          "gJxnfvb3H8Wv/PrVVYLfzE3rdh2CrQd0iqHIquFhXLTWMhCn1LfaL/3mOwO5" +
                                          "g1FSlyDd4BSX6jgGHLBzADDqrNeDW9MwUfjAviUA7DiR2KbKMoArtQDe49Jk" +
                                          "FpmN+5ysC3Aojx3YYHfVBv2w6i+f+/3G4/vzp0SWBWEcpdUDAuHJSQTfCshu" +
                                          "Drk/zPKr40+/enineikqcAd7+Cp4VX1oKBgIEGozAFgDzcGdNhC6LVzOYW+l" +
                                          "1F1b6AupF88OiCg0A/hyCs0ScK0/LLwKO4bK1YWimsAJWdMuUB1flV3ewvO2" +
                                          "OefviD7TJZMdEkTU8e3w2e51V/GNb3ssXHtlXxL0/WLdisuAyK4oPu7AZacg" +
                                          "+zBk204/+QEOdOiUGJGBew0Iu5bVaFpnWA9/69ix94U/XuiUiazDTjlEez6Y" +
                                          "gb//oYPkoddO/rVfsImoOI74TcYnkxi31ud8wLap6IGlz77R98WX6ROAloBQ" +
                                          "jrbABOhEqita+dcbq6h44Y1hcXq/WA+iV72mib8P4/JxTlpm2TxO4zDpgYKD" +
                                          "txh4ba0ArbLojQzK2e53Zr/87jOyUYTnixAxO7/4hffjFxalr+UQtn3FHBQ8" +
                                          "IwcxoWmnCCy2rq23kiJOjP72ubPf/crZh6OelXFO6oqmhqYN1DAtMFan1IvX" +
                                          "3mu7772XbghFq+fyIHiMU0vq1oXLEOrWG4avI9TJA91Hr058qlO/ehM4JoGj" +
                                          "CgDtHLMBR0tVUONR1zf+8vs/6Dn1eoxER0mLbtLMKMUJGOYYqCLm5AGCS9Yn" +
                                          "75aVMtcES6cIKVkR5BUbmICbV0/tkYLFRTIufLv3G/ueWnpbwJaEljuqKzUO" +
                                          "n0GvUgf/o0qtzk0v3/HnIUGQukXyUlySnKyB5J1iOgNkyOBWQlBP4jIjHTD9" +
                                          "b/oKN06s6oDd8FE8Byj/Swfot3CAmFdyMEiAAzD5w9bn/xvWl2CQqDG0YS5t" +
                                          "WHFdlFcc9dmljqbepXt/LqCkcg1pBfDNuroeQKogajVYNstqwrhWWVqW+CrC" +
                                          "zap27+OkXnwLE1x5Yh6gfbUTnMRgDVI+CLf+MCVwFN9Bus9Am/TpYI6TD0GS" +
                                          "c8AdSPDxc5ZVilQPqZW4rP+guATm2u1VDUtc4cszgysv8Sn1uaWjEw/c+NiT" +
                                          "csyFy//CgrjywQ1WAnFl7thak1uZV8ORwZvtzzfvKPfOLqmwn9KbAgl4AlLV" +
                                          "wizYGII0Z6CCbG8u73vpx+cb3oDWN0MilJO1M4ELtLwtAi66MCDOJPwRMfAv" +
                                          "IIG1Q4Nfmt+/J/unX4mmJEARLii16VPqtafu/+mlDcuAyWvGSD3AAislSYvm" +
                                          "HJo3pphatJOkTXNGSiKXuUb1MdLkGtoZl41lEqQdE5bi5V74xXNnW2UXZydO" +
                                          "tq1Er5UDKDTwOWYfNF1D1GcbQIq/U/W/hfLo5lpW6IC/UwnlupW2p9RDj3R8" +
                                          "72J3bBSKrsqcIPtGx01XxsLgvxvknBgAW3nfiKUS45ZVvn/UfdNDhEclDe5z" +
                                          "Etnl7YZ62GOC3WXxiMuVfwIQx5ZjSRQAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188907000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05a8zrZnk+37n0nNPSc1qg7QottD2gFcPnOHFuOlzmxInj" +
                                          "xImT+JaEjVPf7cS3+BI7Zp0AicGG1rGtDLZBf4G2oXLZNLRJE1OnaQMEmsSE" +
                                          "dtMGaJq0C0OiP7ahsY29dr7b+U5PO4S2SH5jv36e533uz/s+fvbb0PkwgGDf" +
                                          "s7eG7UX7WhrtL+3qfrT1tXC/T1fHUhBqatuWwpADczeURz975d++90Hz6h50" +
                                          "YQG9XHJdL5Iiy3PDqRZ69kZTaejK8WzH1pwwgq7SS2kjIXFk2QhthdF1Grrz" +
                                          "BGoEXaMPWUAACwhgASlYQPBjKID0Ms2NnXaOIblRuIZ+CjpDQxd8JWcvgh65" +
                                          "mYgvBZJzQGZcSAAoXMyfBSBUgZwG0GuPZN/JfIvAH4KRpz/8jqu/fRa6soCu" +
                                          "WC6bs6MAJiKwyAK6y9EcWQtCXFU1dQHd42qaymqBJdlWVvC9gO4NLcOVojjQ" +
                                          "jpSUT8a+FhRrHmvuLiWXLYiVyAuOxNMtzVYPn87rtmQAWe87lnUnYTefBwJe" +
                                          "tgBjgS4p2iHKuZXlqhH0mtMYRzJeGwAAgHqHo0Wmd7TUOVcCE9C9O9vZkmsg" +
                                          "bBRYrgFAz3sxWCWCHrwt0VzXvqSsJEO7EUEPnIYb714BqEuFInKUCHrlabCC" +
                                          "ErDSg6esdMI+3x69+al3uj13r+BZ1RQ75/8iQHr4FNJU07VAcxVth3jXG+hf" +
                                          "lu77/Pv3IAgAv/IU8A7md3/y+R9748PPfXEH86oXgGHkpaZEN5SPy3d/9dXt" +
                                          "x5tnczYu+l5o5ca/SfLC/ccHb66nPoi8+44o5i/3D18+N/2T+bs+qX1rD7pM" +
                                          "QRcUz44d4Ef3KJ7jW7YWkJqrBVKkqRR0SXPVdvGegu4A97TlartZRtdDLaKg" +
                                          "c3YxdcErnoGKdEAiV9Ed4N5yde/w3pcis7hPfQiC7gAXdAZcKLT7PZQPEaQh" +
                                          "pudoiKRIruV6yDjwcvlDRHMjGejWRGTg9Ssk9OIAuCDiBQYiAT8wtYMXxgZE" +
                                          "5wZAI2Qg+aalhCNP1QbaNs8LuVz7ubv5/18LpbnEV5MzZ4AxXn06Fdgginqe" +
                                          "rWrBDeXpuNV5/tM3vrx3FBoHuoqgMlh7f7f2frH2Plh7v1h7/zZrQ2fOFEu+" +
                                          "IudhZ3tguRXIAQDgrsfZn+g/8f5HzwKn85Nzud7TIigfKB7OArzHb5+xu3m6" +
                                          "oIoUqQAPfuA/GFt+z999t+D7ZNLNCe69QJScwl8gz370wfZbv1XgXwL5KZKA" +
                                          "P4HQf/h0rN4UXnnQntYnSLvHdMufdP5179ELf7wH3bGArioHOV2Q7FhjNZBX" +
                                          "L1vhYaIHef+m9zfnpF0AXj+I/Qh69Wm+Tix7/TCB5sKfP2lHcJ9D5/eXC5+4" +
                                          "u4C55/vgdwZc/51fuSXyiV0k3Ns+CMfXHsWj76dnzkTQ+fJ+fb+U4z+S2/i0" +
                                          "gnMG3sL6H/vLP/2nyh60d5zUr5wok0AJ108kkpzYlSJl3HPsMlyg5cr624+M" +
                                          "f+lD337f2wt/ARCPvdCC1/Ix5xhURVBd3vvF9V994+sf/9rekY+djUAljWXb" +
                                          "UsBNWBQ5IIluuZJdKOTRCLp/aSvXDqUWQNEDjF1b2vVCVa8EZb5gLbfK/q5S" +
                                          "FMEFOLp2G3c9Ud1vKB/82ndeJnznD56/xVNvVsxQ8q/vLFRwlQLy95+Oop4U" +
                                          "mgAOe27041ft574HKC4ARQXkiZAJQDinN6nxAPr8HX/9h3903xNfPQvtdaHL" +
                                          "tiepXSkvxCCdRiao3SbIBKn/th/bpcPkIhiuFrEJFfK/asdOEdZ3HyuC9kDB" +
                                          "/MDff/ArP//YNwAffej8JvdhwMEJbY3ifA/x089+6KE7n/7mBwqbgOQr/Mxv" +
                                          "Vb6bU20UC7yuGH80H+CdxfLbN+bDm/Jh/9BMD+ZmYou8SEthNPRUC+wh1MJS" +
                                          "L5o6xoHlAG/bHBRI5Ml7v7H66D9+alf8TueJU8Da+5/+2e/vP/X03oktx2O3" +
                                          "VP2TOLttR8H0y45M+ciLrVJgdP/hM0/+/m88+b4dV/feXEA7YH/4qT//r6/s" +
                                          "f+SbX3qBTH3O9g6dMh/LB8vmf9WXNmx059/0sJDCD380OpfKiSKkIhzDUQXp" +
                                          "VC2zNi3PVrXOqjLtDaasz1ATZ+mXsBkXi64gDxxnkamIHNdDNhtWmQUDx2i5" +
                                          "hPcnq0q1w4t+KVl0ECUScJ23p70VJRq8WRLmXb8/pwYDI+osG94SM0l2jC8n" +
                                          "hOtWIkcty53KVE7CuloB9DStmbl6PKvXmLVdkUf0mGjV3Ua6yDBrSLo1tpxk" +
                                          "NMG4ooLV2zPehMclDtb1nm4Flumzfbo87s1IQVsn/Lzik6zah5ccganTicON" +
                                          "WyK+GHOjYDifSVMlLJVWDtuseolAd1FuxFXjhWmwlY4etRjHckeRVI6FMCPH" +
                                          "OCs02qMu2emH61aDic0WaQucuNH6zcaEAjObTm9gWAiNSZNMWXjiWutvOUFh" +
                                          "nZDpsUt5IS/cmt7BKtpiK2jjbUlf68CQTJ9BNWw+2mS9GVzVuJ4+ELaJba7J" +
                                          "7VyoZuY04+gKNTRcFtNgpjbIDLdN6v2g0xGnQ6PqTAx+Kq2NLt41+1LUlGwc" +
                                          "zhZOTAkmX10S22oi0S1ewJxpMJoydDngjHCx4hmD6fXj+oI2akQkhGt05QVC" +
                                          "1cQ0WdvC42U/WyM9tqOxKrkkR4P10jApxWxzLU/aThbBIqP6I9NhOX9oEfNS" +
                                          "IxPXAyzS+r1YDVhlIq9ojIXrLU5Vrabd9uNGYLXH8wU4Dozg8kATnCk/qm3g" +
                                          "dcoo5VawLMNB1MP5ZqOHd40SH9aHfCPE6vwS7BKnNgO2HWOBTJQYVyiMNJeG" +
                                          "TjbEaVdYoMScGpW209l0Xe1PfZYoLVs1Du1brJEpLumssimaLoRF2WF8Dvha" +
                                          "heUapjAZTaIe1uoyqKf3W22NKoWLiY3TaczV0nqDIlKzs2StgaFgks/Ea6Rl" +
                                          "1FEzqY5CdpuRKtsaj6zaAOnM6zM31fuTCdXFdMqflyqVIEkjtA6vYZhyVuWA" +
                                          "72d0ryytua1Nr3V5Vm9G2rgdk4Nguug7jBmSm9BO+bLEVRZrczWZ6/56RnRs" +
                                          "pLfd1iJunGVpaaTPe7XBajFPSuuBHHeBImObzebkqhYmjcxoOnzYSOaSuCAX" +
                                          "ttXobZlRo59NiPaisiyLGRGPln4Hm4lJ2YHxUrw1KFrtdugxGZGolSBilXPT" +
                                          "2bhPeZNS4qkdjGZmW7oBzwjTZCMsHFLiGh3hQ77qlDiZ03mJWPpDsqKx/Ejk" +
                                          "4IAZLIJJ4q19H+UGzLTluquNshK9zKLLfmNYjvSBVFul+LS+7mXiuD6RN5ZD" +
                                          "1kWkFE3aLKoxqdafEK24XVfaPSnwrIHtOn2U7TbLBJVpGieXnFKS0gkyFPoV" +
                                          "Da/TFt+baltsC24dric1DGc1NybxpIquaLK3HaJtImm30bDnwxisMUEjaq1s" +
                                          "N1NFs1KKrQGhCXqDaK0GNQshGqnMVVKrijTq1mja2fD1Ka8ZKd/IxiZHcTG3" +
                                          "oPVBsm3qy3hYmpdoFF3o9HTbVHTX7A7w4ayMTiYMRnhDceJEXTsQq2ij2oDn" +
                                          "dRkgWeicX1a6XlbGJJ6qcX1/TVZWCyFb2ZnP2/2kKTWJSmMKjxNiXDaWcmh1" +
                                          "gAeWQ7dK97VSNIDbjNVbaknH2ciNIQUH9VCqTGezWgWmZoHeCNyur2zTPqIP" +
                                          "BjEcB+FqavRTV9/IlV5D3IBKJQhzWs86lUA1y+1gopasdY9ax11zRnPi0Gy7" +
                                          "KK1LNFJxmISpGmiXtbeEirXYWW1pkD26leEEsQ5GGiE2hwmvL/GNxeN1wpqW" +
                                          "B/Jg6OFBNCE0rNlfdX1nBFe3YbuCe8u0Mp/3dKG1KSc1C9ZhpEJiyCbzS6zY" +
                                          "EjuKr/IEHvf67ITT26EZE8EKycaDACvB4GAENubWaq3gah1u+5gwQ71By6A6" +
                                          "pJeB5EBkCqmOzHaNFjJmLsI22kXlGh773UaDsdpGCUfMbTssscqghNB0MmAw" +
                                          "eYDORcsJ8b6oDmO+heq2UNGSDVNmNH1jEXWuvxiqnRXHN7RKUtaqqICQI7kS" +
                                          "hrNeZM9SuoSItGqFMb4dYN44ruMLSTHgrLUqlzAEnnQYlbF4sk+2tKRExVVZ" +
                                          "kLq+K+JNpNa00ibGI7PY4i0pI7il3dGy2tyQEcSbj1eeqjJIIOgh5XgMVcc4" +
                                          "Ze6uUquCxmojoSW/RpF2Vq9Pmw1xVpsyuO21JstAxluM2VlbkQSriryumRg2" +
                                          "R01ltkZEHLaEetmx5MYYQ/opZ/tOmUsZLCN8Yz4gotTEZKmEBzLtLSfZAMha" +
                                          "WQTA95fMlp9zrpXiKVNHMFPXl91UsgOYn0RupdtrTRpUoqSe6Ljt9rYcrMuV" +
                                          "ldVnluN6OZbHOqIEC7PGaPasy9S8tWOu5yOUwKNhV3JRajOrOHG9Xi/PZMPs" +
                                          "rmF9S/WsIV/arFFvRneYQCQxaUM1uT7eRHtBqdpY2wyimUOs75HLtkFEPXrY" +
                                          "mpYigWdGUzTT4cYmRGqEi2pe2pmWHFqO6OFgyPdJZj5ft2mnipNttjl361VJ" +
                                          "GEZKh60p1EBYTastXnaotiyUkGg1p7tTjop1elMhkVgTXV9O+lLHXsbrQcYz" +
                                          "bonc8IaOeKV1lK1KmwrScymenMSr2Za3t6w72LaqfdRijNFqy7TEid0aY0tq" +
                                          "2eOIpox4g1GpFtY8Qm10O43Wdomwie5FlTbudNXtsGPheEZUk6bsIulGtMvt" +
                                          "yZogS3O2Gom9rmp3FaWpOvZyLWv+LELodXulGKjf0olRHHjaZOAZ0lKYj8Jo" +
                                          "nQSmKAprEW4H7Uzyy3WYWc3chO6gaXVu1gxd5jl3ODUIgYLbtA4P20LSHTVb" +
                                          "cdjEHYTz5yAvESWSVRq4yo6JVKkuBMuejNcLEQvGsBHjnFOOUYHgIwVTwszY" +
                                          "hpsG66KxJC47CaLAI4tTwm13iyBtI1hukwkq4m7XrkemtELjhdBgpsliE2WZ" +
                                          "vhmMdYZeO4nbHMi4YWO4TQuJBUoZRZUWtXZbJhtxvbLxU1iRKx4hjkpDywa7" +
                                          "oyHWoSM6iXCrVhu2CaY/TqZDHd9QFIlOsJHuRDDSR2J3hjlOv4NPactCa8J4" +
                                          "HUl6jMCOTYCdw1bckCxRwXErtNn5xun1vYrvm1LUZ1bcbESCej+LeRkdqvSK" +
                                          "jLyFjaF2Zz1RO1XZqgp1LJ2NXLHMzxZblYnWaCeo8sSA4BJGnOujLkqgpCJP" +
                                          "qDXCIyJi6rRXtX2xRrURPnHt2BfLfnNKLCvTRr3cr8gtdgC2Qgo1jsi0hM7S" +
                                          "kDY26WbltgxcrLi6NeBZDNhh4yK8ro4Is6PYhFbNOpFr1+eLWplk2hVxllrD" +
                                          "WNATapJWF0t2OgGb+be8Jd/mUz/YSeue4kB81EcFB6z8RekHOGGkL7ZgBF2U" +
                                          "5DAKwDE0gi4dNXZ3q5/oCJ05PICfOAh38vbTYbspP1k9dLsWanGq+vh7nn5G" +
                                          "ZT6B5qeqnBgBFow8/022ttHsU82nN9z+BDksOsjHXZ4vvOefH+Teaj5RtDlu" +
                                          "6T7R0OUcc5w36o8a8q85xedpkr85fPZL5OuVX9yDzh71fG7pbd+MdP3mTs/l" +
                                          "QIviwOWO+j0B9Ogtx05P0dQ40I7XfcNrpc/d+PyT1/agcycbYTmFh061le7U" +
                                          "vcCR7HyBw2b65cgMvOR45mSPCai1aPK9CVyPHXRbi//87cv9fHxFeuxTtzjL" +
                                          "3pF3Tg9cI4Bef+wJbc+2NaXQ+jXedYpugCTbWu4c/3nldejn/uWpq7uzsg1m" +
                                          "Ds3wxpcmcDz/Iy3oXV9+x78/XJA5o+SfJ44bNsdgu573y48p40EgFT3R9N1/" +
                                          "9tCvfEH62FnoDAWdC61MK5rQZ252b+R/32gt3L/QhllgK8VoFOG366jmz8Wn" +
                                          "ghsRdHmlbceBFoba7uvH206EbTuCzm08Sz2O5ydeqmNwcpli4u03G3ofXI8f" +
                                          "GPrxH8rQN4t2oK780SoAti8i+zvzAeSVO4HsU83WJCB8PuUeCxr/sILC4EIO" +
                                          "BEX+LwV974sI+r58eBfIpUDQPABPS/nuH0TKFCTZ2/T0c99+4JavibsvYMqn" +
                                          "n7ly8f5n+L8ossfRV6pLNHRRj237ZBv6xP0FP9D0nYCXdgnDL/6eiqAHbx8K" +
                                          "EXS++C94/7kdxi9E0CteCCOCzoLxJOTTEXT1NCSgWPyfhPswiJpjuAi6sLs5" +
                                          "CfKrgDoAyW9/Le+MnygjB+5S6P/el9L/EcrJ1nZeeoovvIdlIt59472hfOaZ" +
                                          "/uidz9c+sWutK7aUZTmVizR0xy4vH5WaR25L7ZDWhd7j37v7s5ded1gW794x" +
                                          "fOy6J3h7zQtnzI7jR4WPZL93/++8+def+XrR3v0fGH3tFHofAAA=");
}
