package org.apache.batik.parser;
public interface TimingSpecifierListHandler extends org.apache.batik.parser.TimingSpecifierHandler {
    void startTimingSpecifierList();
    void endTimingSpecifierList();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAMUYa2wcR3nuzu868SONHZLGiZNzRNL2VimUqjiFJm5cXzjH" +
                                          "pzgJwqa9zO3O+Tbe253sztpnl7RpJWjUH1HVuFAQ8a9UPNSXEBVIqFEQEm1V" +
                                          "HmqooA/RgvjBM1Lzh4AClO+b2bvbW/vSSvzA0s3NzXzv9/iZy6TZc8k2Tm2D" +
                                          "psQCZ14qi/ssdT1mjFjU8w7DaU5/7PdnH7r6q/aH46RliqwtUm9cpx4bNZll" +
                                          "eFNks2l7gto68w4yZiBG1mUec+eoMB17iqw3vXSJW6ZuinHHYAhwlLoZ0kOF" +
                                          "cM28L1g6ICDIloyURpPSaHujAMMZ0qk7fKGGsLEOYSR0h7ClGj9PkO7McTpH" +
                                          "NV+YlpYxPTFcdsnN3LEWZixHpFhZpI5btweGOJC5fYUZtr3Q9fdrjxe7pRnW" +
                                          "Udt2hFTRO8Q8x5pjRoZ01U73W6zknSAPkkSG3BACFiSZqTDVgKkGTCv61qBA" +
                                          "+jXM9ksjjlRHVCi1cB0FEmSwnginLi0FZLJSZqDQJgLdJTJou7WqbcXdERWf" +
                                          "vFlb+tr93d9LkK4p0mXakyiODkIIYDIFBmWlPHO9vYbBjCnSY4PDJ5lrUstc" +
                                          "DLzd65kzNhU+hEDFLHjoc+ZKnjVbgSdBN9fXheNW1SvIoAp+NRcsOgO69tV0" +
                                          "VRqO4jko2GGCYG6BQuwFKE2zpm3IOKrHqOqY/BwAAGpriYmiU2XVZFM4IL0q" +
                                          "RCxqz2iTEHz2DIA2OxCCroy1BkTR1pzqs3SG5QTZEIXLqiuAapeGQBRB1kfB" +
                                          "JCXw0saIl0L+uXxwz5kH7DE7TmIgs8F0C+W/AZAGIkiHWIG5DPJAIXbuynyV" +
                                          "9r10Ok4IAK+PACuYH3zpyt23DFx8RcFsWgVmIn+c6SKnn8+vff2mkZ13JlCM" +
                                          "Nu54Jjq/TnOZZdngZrjModL0VSniZapyefHQT79w6rvsr3HSkSYtumP5JYij" +
                                          "Ht0pcdNi7r3MZi4VzEiTdmYbI/I+TVphnzFtpk4nCgWPiTRpsuRRiyN/g4kK" +
                                          "QAJN1AF70y44lT2noij3ZU4IaYUPicFnB1F/m3ARxNOKTolpVKe2aTta1nVQ" +
                                          "f3SorDnMg70Bt9zR8hD/s7fuTt2heY7vQkBqjjujUYiKIlOXmKNQFrXDZgni" +
                                          "apIz3YRod7ESjQE9UDWFwcf/P2zLaI1187EYOOqmaJmwIMPGHMtgbk5f8vft" +
                                          "v/Jc7jUVgpg2gR0FuQ14pxTvlOSdUrxTjXmTWEyyvBFlUHEBXp2F+gAwnTsn" +
                                          "7ztw7PS2BAQkn29Cn5Rlwm6q/ADEiKyyNNw1yc+9+Ys/fyJO4rUq0hUq/5NM" +
                                          "DIciF2n2yhjtqclx2GUM4H77VPbsk5cfnZZCAMT21RgmcR2BiIUyDOXsy6+c" +
                                          "eOu9d8+/Ea8KnhBQuv08dEFB2mge6h7VhSDt1QKmFLvxA/iLwec/+EEd8UAF" +
                                          "Y+9IkBFbqynBecgcMbnfIEjqI7ohcAFacXOjkiPL5flHlpaNiad3q8LQW5/G" +
                                          "+6FLPfvrf/8s9dTvXl0lJtqFw2+12ByzQqLGgeXgirljXFbkSv/O6Xdcupp4" +
                                          "54kNndKLnXkYOWp9P1nX99XY4jo6M6DxNJoAKl1wV+OeHxXh5Uf+svHwZ4rH" +
                                          "pAjhLo60mqEBIWYWe2+V+paIKaMkvzP+zKv37tCfiMu2gyV8lXZVjzQcNiow" +
                                          "dRn0VxvVwpM1ZRziIhkbtUVO37WVvph76WQyTpqgD0HvFRRqJbS1gSjzutYx" +
                                          "XEkgZNUGRig4bolaeFXpnR2i6DrztRNZSnpUPIOzZapuh8/WoLjKb7zt47j2" +
                                          "q9Ij4QfkOohLUkUKbodw2SHBPg6Rs6OWo9ANLCiN6JHkERucDYFN8xbD6vGv" +
                                          "rqHdL/7tTLcKSgtOKi665cMJ1M4/to+ceu3+qwOSTEzHaaRWR2pgqsWtq1He" +
                                          "67p0AeUoP3xp89dfpuegWUKD8sxFJnsOCWoYCrVPqn2XXPdG7u7B5U7oreBI" +
                                          "V6xSSYHtzutMsS5gCHMumAO0k73vzX7zT8+qVI4ODRFgdnrpsQ9SZ5aUBdVk" +
                                          "tX3FcBPGUdOVlLtbuqssM/06XCTG6B+fP/mjb598NB7onBKkac4xDUBONlAt" +
                                          "NCvn9MffeH/N0fcvXJGC1g/b4ao/TrmSrQeXT6Ns/dG+M0a9IsB98uLBL3Zb" +
                                          "F68BxSmgqENn9SZcaIDluh4RQDe3vv3jn/Qdez1B4qOkw3KoMUpxrIXhBHKD" +
                                          "eUXonWX+2btV/M+3wdItHUxWuByjaMvq8bm/xIWMqMUf9n9/z7eW35XtRVK4" +
                                          "rT7bBuEzFGTb0P+UbY3jcvo6d/fhchRSBUazVSIWb9MScRyXz6vel/1o9sGD" +
                                          "I2WYxhsPFWjDDSueOmo8159b7mrrXz7yG1kHqyN0J0wDBd+yQmU2XHJbuMsK" +
                                          "ptStU0UQl1+QEP0Nui02fLmRKugKfgZeoVF4QZrldxjuuCAdNTggpTZhkJIg" +
                                          "CQDBrc15OVY/GFWNu/7DjBuapbbX5Zp8UlaamK8elTn9+eUDBx+48qmn1WgF" +
                                          "j9HFRfkEgReV6gzVRjjYkFqFVsvYzmtrX2gfqqR9jxK4FqCbQjF1BCYcjp7d" +
                                          "GKmxXrJaat86v+fCz0+3XIKsnSYxKsi66dCDTr1eoFD7kGLTmfD8EfrHhCz/" +
                                          "wx1/OPbLf7wd65UpJocrrJbXwcjpZy+8ky1w/o04aU+TZqhqrDwFL1TvngX7" +
                                          "ENPnoBi0+bZ5wmdpePy25B3frr4+12IYUnxuSssEBl1TPcV2Lsi2laV35cQD" +
                                          "1WeeufuQuhwOIqODz3n4toyvslW0At/sPvfPh77y5gSkSZ3gYWqtnp+vTiHh" +
                                          "x62iHeoCaoJN5DLjnAcTbeuE9CrnMqNPSaUfVNAIIUhsF+f/BQueGnSkEgAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAMU5ecwjV32z3+5mj4TsJkCSBhJybFDDwDee8TG2ltJ4bI9n" +
                                          "7LHHnsPH0LIZz+W5bx9D01KqAgWJojZQKkH+ArVF4VBV1EoVVaqqBQSqRIV6" +
                                          "SQVUVepBkcgfPVTa0jfj79pvd5Oi/lFL8/z83u++3ryfX/wedD6OIDjwna3h" +
                                          "+Mm+tkn2Lae6n2wDLd7vMdWRHMWa2nLkOBbA2g3liS9c+dcffGR5dQ+6S4Je" +
                                          "K3uen8iJ6Xsxp8W+s9JUBrpyvNpxNDdOoKuMJa9kJE1MB2HMOLnOQHefQE2g" +
                                          "a8yhCAgQAQEiIIUISPMYCiC9RvNSt5VjyF4Sh9DPQmcY6K5AycVLoMdvJhLI" +
                                          "kewekBkVGgAKF/PfE6BUgbyJoMeOdN/pfIvCH4WR53/tXVd/+yx0RYKumB6f" +
                                          "i6MAIRLARILucTV3oUVxU1U1VYLu8zRN5bXIlB0zK+SWoPtj0/DkJI20IyPl" +
                                          "i2mgRQXPY8vdo+S6RamS+NGRerqpOerhr/O6IxtA1weOdd1pSObrQMHLJhAs" +
                                          "0mVFO0Q5Z5uemkBvOo1xpOO1PgAAqBdcLVn6R6zOeTJYgO7f+c6RPQPhk8j0" +
                                          "DAB63k8BlwR6+I5Ec1sHsmLLhnYjgR46DTfabQGoS4UhcpQEev1psIIS8NLD" +
                                          "p7x0wj/fG779w+/2KG+vkFnVFCeX/yJAevQUEqfpWqR5irZDvOctzMfkB770" +
                                          "gT0IAsCvPwW8g/ndn3n5mbc++tJXdjBvuA0Mu7A0JbmhfGpx7zfe2Hq6cTYX" +
                                          "42Lgx2bu/Js0L8J/dLBzfROAzHvgiGK+uX+4+RL3J/P3fEb77h50mYbuUnwn" +
                                          "dUEc3af4bmA6WtTVPC2SE02loUuap7aKfRq6AOaM6Wm7VVbXYy2hoXNOsXSX" +
                                          "X/wGJtIBidxEF8Dc9HT/cB7IybKYbwIIgi6ABzoDnjdDu88b8iGBYmTpuxoi" +
                                          "K7Jnej4yivxc/9yhniojiRaDuQp2Ax9ZgPi334bu40jspxEISMSPDEQGUbHU" +
                                          "dpt5jsZahAimC+KKDzTFBNEe5SWCAvSAqvt58AX/P2w3uTWurs+cAY564+ky" +
                                          "4YAMo3xH1aIbyvMp0Xn5cze+tneUNgd2TCAM8N7f8d4veO/veO/fmTd05kzB" +
                                          "8nW5DLu4AF61QX0AMPc8zf9079kPPHEWBGSwPpf7ZFMk7EPFj7MA7+k7V3My" +
                                          "LyV0UT4VEN0P/QfrLN77t/9eyH2yIOcE926TQafwJeTFTzzcesd3C/xLoHYl" +
                                          "Mog1UBYePZ3HN6VentCn7QlK8jFd7DPuv+w9cdcf70EXJOiqclDvJ7KTarwG" +
                                          "au5lMz48BMCZcNP+zfVql5zXD+pCAr3xtFwn2F4/LK658udP+hHMc+h8frmI" +
                                          "iXsLmPt+CD5nwPPf+ZN7Il/YZcn9rYNUfewoV4Ngc+ZMAp3H9vH9Uo7/eO7j" +
                                          "0wbOBfgJPvjkX/7pP5b3oL3jgn/lxBEKjHD9RJHJiV0pysl9xyEjRFpurL/5" +
                                          "+OhXP/q997+ziBcA8eTtGF7Lx1xicGKCk+cXvxL+1be/9alv7h3F2NkEnLLp" +
                                          "wjEVMImLAxBoopue7BQGeSKBHrQc5dqh1hNwIALBrlkOXpjq9eAVoBAt98r+" +
                                          "7hQpkgtIdO0O4Xri5L+hfOSb33/N5Pt/8PItkXqzYQZycH3noUKqDSD/4Oks" +
                                          "ouR4CeAqLw1/6qrz0g8ARQlQVECdiNkIpPPmJjMeQJ+/8Nd/+EcPPPuNs9Ae" +
                                          "CV12fFkl5fyQBqU2WYJzfQkqwSb4yWd2pXJ9EQxXi9yECv3fsBOnSOt7jw3B" +
                                          "+OAw/dDffeTrv/zkt4EcPej8Ko9hIMEJaw3T/P3ifS9+9JG7n//OhwqfgMI8" +
                                          "+ljn6jM51XrB4Kli/PF8gHcey6dvzYe35cP+oZsezt3EF3WRkeNk4Kt5+VEL" +
                                          "T71i6RhFoGAl5urg8ESeu//b9if+4bO7g/F0nTgFrH3g+Q/+cP/Dz++deB15" +
                                          "8pY3gpM4u1eSQujXHLny8VfiUmCQf//5537/N597/06q+28+XDvg3fGzf/5f" +
                                          "X9//+He+eptKfc7xD4MyH7EDtvlX9dUdm9z9DFWJ6ebhZyDOZWytcGUvzdJ6" +
                                          "rc6zQ0piuqY0zLghg01MVwwtk+y5VWWWWVSQGb11KDcytszCwkLDquU4SwLP" +
                                          "wbmgN7VECqUmKdkc1+WGOBrysw4xoUOyM+646IRyQ99vIpyxsogBymTLSrPl" +
                                          "sPACW6wWU2TF86usWYrLw2yWrRqIKW1rgqTUbUxwsXYQj1sSWglNJI5VAXUt" +
                                          "0hLra7wti1UEH6kehUe1EJGpSo1zzHCdiG5DCTaVxVByHI0c2jHm4Ebi1+rr" +
                                          "ylYyiS7qipoCa/6AQHEAX17N+N60JqWmR1Hz5nLtML5UsllSGWB1BjVqdKtN" +
                                          "O/5W5IIRL1Op1RwMpFJo43q/242ZDjvnudISbzldqzGyWXygCAE1nMBzJ5hv" +
                                          "RgKpqLE3LDOdqWRuqIBcSgFdXSRrrcv2WlV9LkpJVB43dDWyNhoecN5UVBNs" +
                                          "SQocWx/XN9XA4oA4qIiXp7XM9vjmyLb5bplotkiTl0KhPTH6dldorWpoSDRh" +
                                          "azZo2LFlORw1aZmoQpTIjsuvPcP0GLNESkwPILXHPYNRe0LPT/FpuFBmaoeb" +
                                          "6ivSWcBJ1CirDcbuV4KSO5Ptrcm2bZqet2mScKfOiGIbq/mCsFoeP6+M2r2q" +
                                          "E4lxorSZTK1V7Wy4FOFlp00ylOUrsNT3rMnC4FVi2NBnS204RfkV7TcDeMgp" +
                                          "MWuwtUYyKU24kK1Yto91u615t0aM0zXZ72BZ4JZpth9RIRvOEWLdbHaDyJy7" +
                                          "pojNJhI5qNBMKeRamzDDTKFDZVibbmLsptWK/C1K2AKHBlkYl/ludSxIHXrG" +
                                          "hGbalAOtOyY4ArV1otearUuxTDslBk5nm3VWtSm83cEFlzbiOllqwVOkKTW7" +
                                          "tG1SU7pbbY96TXq2SLfedtKI0BJrV+hmHx41W+mcKmfBNsHKbXJT5xQynhoT" +
                                          "l/Zgpcb3Pa8Or3Qdc20JLfec1mCYVis9K0QEj5Uk1TOkyAIljilNeM+U5GCr" +
                                          "6dRYwBvrWrSKozLF2/w8Sd1RtTc3LSopBYo6NPGoPJDMyiTrmILqzhc0QsPC" +
                                          "JFh6GZkEdsVrGdORKXBBnHKcuR0iRsXuj5u9Idok8dK2UnEEzPNNqyyJFVqe" +
                                          "iyNTIT0CJRG33OQ2Q7Yv+E4w6WuYLCQy6k3Gepn3o7Y3MPASkTQyrr5sIzGu" +
                                          "pwIIVW2Or8Y2EVpWaolzs0877MztD8dkNGtLhmfKAZ2V55yv4h3eGncaYntK" +
                                          "rhUdGWEZI9MoWsc7c5YNXbnnrunBqEsNEmNhV/X6Sk9WSE/BLXFiBAZmcCUy" +
                                          "HaOVYCOsHJZXxWgjWDNXmHa22xVBOiLVIWYBRsJGc+0JsYdnyRof8RjRHNse" +
                                          "1mh5Vc5Zu6BUNNsds7/dDodrdKvADXgeI/q2x1YiMSwtxRCpDgdtWjFJzMO2" +
                                          "SysJFWeDdcVBhcLxyWgR21VF9ySp1RwIGMoZrsJhhEmL2zY7i7c1WNHYtKHW" +
                                          "YaQj1/veEoTzqlRXOySBuYZWW+KTJd9O0HHfJZnVpomYzFpTELjTUetik5zD" +
                                          "DdomyEW49QhNMZTBwtPpjhXSuL9UmuA8n7GWbY6Yqu5QTiAPTVkth3VmPK0i" +
                                          "XbhGMiN9FelIPW6owmrmlJxeEpJrDEYxYpuNQ6ZraDPDjBxrRi5sfoWwtZmq" +
                                          "pEFQqVbsoaf2GW9mz9lp0Bih3qzRmM0rll8b1NqbYc9v9h10PYFZjdrMllVR" +
                                          "h+MVtZYqERU0rSXj10pu2CHo6XyqYfAEDmS6Lw/sVTaCs/6qjCct3RykmLGd" +
                                          "1J2ZNLGysTI0/bXKeaXJZjVZBwNU4jKTXtqLRJywZXw6WQVLvDYdb4UgNNol" +
                                          "akVyXNhb8KjBW1mazDezjm1IQ7HLmUZl4TuyRs4Cj8PMWjvKEm4o8V4gjmg2" +
                                          "AzmVLuvI1Ges/gIERQW3sLBBW5WxbrP+khFtsb/w1TXGU8TIqHFxjZ36jeaQ" +
                                          "aZnDWo+yO1yqtOfksL5ZtGur7ioKKZVB8ERglD5vJGzfrNWqyqCHDipI4gP/" +
                                          "p2U4XLO80MkoWeamHBYYYTxNQpTSanhQamqiPypvgnpD1YNUM6Ziv12PN2TP" +
                                          "i9nW1J+3osko9LDZbKR28RQnqiLuRxpBT2obnp9TCVB+EPNVo0UNUrfJlmy8" +
                                          "vMpmeCbU4XBCV9g2RxqqF4Fjs8FLVVkk1ImdzMqkQoy6ospOHCZZpGEcD5BS" +
                                          "bdYSQMWF9RHiWotqoz4kcN8j+rasVDZtkWCHTjMZtlZeY6DrGoUMS7qymvW6" +
                                          "LdRAFhXZR4TI5aOxNhNqQ3C37cKDktygY6JRTxmCKUsLslYnNrxrhJ2hB6RR" +
                                          "ZLrtpMsKN25r5dWqbHnIWNUylKiErL0u9/2BGGwierYkqH5bE2e+N53B2CKZ" +
                                          "IAO4vFbphBI305TYWvJgFdYXLrKhp4NwIOoNr4FkuDYtV2cJN+lXIgFfEGkn" +
                                          "I7vCojSCxcW8bCkrv6Yi+lJZcjwhytmEp6eLxoBXuO0sq600B0H9Rtxt09h0" +
                                          "vlnGI3Jqtdt8qrGuX0erjQXuRtEsw7dd1KbC7bDUK63bhApvxy44kajeIh3E" +
                                          "/SDhE7Ekjh0UHndGpWFqljCdcbl+avR1Q9L8CVkZSxF4EbfStNVUh4JhBIK0" +
                                          "tHu00Rq3iUhBq+xkjnTJ6TBF8LZFpHKwWMyqUlAXHVl2+3XNEbwGrIltYgNX" +
                                          "6qHroVODtBoUyel2x+C0Sc3IJpxlzW0yJCfxap65STTDDD0MuYa16VfIsLUY" +
                                          "WyRKtOaKFeBqt+9uZlFPlpN6bQXrrawEl2d0PwYn/KYfg+BWW20hQjWfbON2" +
                                          "lxFcvV3v6BG1bGXIeoMi7GjB6PganP9i0POVKOotZmtAWdrCdXuLrhG/VJFF" +
                                          "WJDCZRi11ySDCivPmOGd4cjzCbMEL6Tq2lUDbbTFqkRZj6IKKFj0XPQ2KR/H" +
                                          "HcJBhZEywZjYxBx5Uq4q4zY61bRUT8fpcs3SIdvOyl4l8ber2JmWmgkSj1b6" +
                                          "aInj26oBjk+pbMynYeIF8EowqeWmhpmU5rdkvzesthnLayrgbTbtNFqRNwiH" +
                                          "4CVP1CfDJk2Ly5iEdQRUcK3r8cC4zWb+Kk3/aLeZ+4pL51EfE1xi8o3Sj/AW" +
                                          "v3klhgl0UV7ESQSuegl06aixuuN+outy5vCSu/+/7PYcdHryS80jd+psFhea" +
                                          "T733+RdU9tNofqHJebSBHIkfvM3RQE6dkGAPUHrLnS9vg6Kxe9xg+fJ7/+lh" +
                                          "4R3LZ4sOwy2NHwa6nGOO8v75UZ/8TafkPE3ytwYvfrX7ZuVX9qCzR+2WW1rO" +
                                          "NyNdv7nJcjnSkjTyhKNWSwQ9ccuNz1c0NY20Y75veUz+4o0vPXdtDzp3sgeV" +
                                          "U3jkVEfnbt2PXNnJGRz2uC+D27u/Pl452d4BZi36a0+C57GDJmjxne++NsjH" +
                                          "122OQ+2WGNo7ClruIGIi6M3HnYWWD65QSmH1a6LnFhdxeeFoeZfvP688hX7x" +
                                          "nz98dXdNdcDKoRve+uoEjtd/jIDe87V3/dujBZkzSv6vwXGv5Bhs14p+7THl" +
                                          "ZhTJ21yOzc//2SO//mX5k2ehMzR0LjYzregNQweNx1yoZaG2UozGqT0rH/Lu" +
                                          "P3BWlNym41lg/eSJHG2Be/jKN9Xj5H321a7gJ5kWC++82X2Pg+epA/c99X9y" +
                                          "350VXb/C3jYfImB7zVNvY4J81zlWN/5R1N0k0MN37iPnTn3oln+3dv/IKJ97" +
                                          "4crFB18Q/6JIm6N/TS4x0EU9dZyTrc8T87uCSNPNQqtLu0wJiq/3JNCDd6h8" +
                                          "eeOwmBTC/9wO/hcS6Opp+AQ6X3yfhHtfAl0+hgOkdpOTIL+UQGcBSD79YN5h" +
                                          "PVETD8KhMOv9r2bWI5STLdK8jhb/Ih7WvHT3P+IN5fMv9Ibvfrn26V2LVnHk" +
                                          "LMupXGSgC7sic1Q3H78jtUNad1FP/+DeL1x66rDG37sT+Dg0T8j2ptunf8cN" +
                                          "kiJhs9978Hfe/hsvfKtoE/4PwyOQEt4dAAA=");
}
