package org.apache.batik.bridge;
public interface PaintBridge extends org.apache.batik.bridge.Bridge {
    java.awt.Paint createPaint(org.apache.batik.bridge.BridgeContext ctx,
                               org.w3c.dom.Element paintElement,
                               org.w3c.dom.Element paintedElement,
                               org.apache.batik.gvt.GraphicsNode paintedNode,
                               float opacity);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188907000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVXe2wcRxmfu/P7bSe20zwc27lEOAl3CqVIxSE0du3E4eyc" +
                                          "4sRSHZLz3O7c3cZ7u5vZWfvsElQqqrpIRFFwaUHUf7lqQX0JUQGCVkFItFUL" +
                                          "UktEKagtEkiUR0QjJPgjQPlmZvd2b+0Lf3HSzc3NfPPN9/x93zxzA9XaFPUR" +
                                          "gyXYkkXsxJjB0pjaRB3VsW2fhrWM8lgM//38B1N3R1HdLGorYHtSwTYZ14iu" +
                                          "2rNol2bYDBsKsacIUfmJNCU2oQuYaaYxi7o1e6Jo6ZqisUlTJZxgBtMU6sSM" +
                                          "US3rMDLhMmBoVwokSQpJkkfD28Mp1KKY1pJPvi1APhrY4ZRF/y6boY7UBbyA" +
                                          "kw7T9GRKs9lwiaIDlqkv5XWTJUiJJS7od7kmOJG6a4MJBl9o/8etK4UOYYIt" +
                                          "2DBMJtSzTxHb1BeImkLt/uqYTor2RfRFFEuh5gAxQ/GUd2kSLk3CpZ62PhVI" +
                                          "30oMpzhqCnWYx6nOUrhADA1UMrEwxUWXTVrIDBwamKu7OAza9pe1lVpuUPHR" +
                                          "A8nVx853fDeG2mdRu2ZMc3EUEILBJbNgUFLMEmofVVWizqJOA5w9TaiGdW3Z" +
                                          "9XSXreUNzBxwv2cWvuhYhIo7fVuBH0E36ijMpGX1ciKg3H+1OR3nQdceX1ep" +
                                          "4ThfBwWbNBCM5jDEnXukZl4zVIZ2h0+UdYx/DgjgaH2RsIJZvqrGwLCAumSI" +
                                          "6NjIJ6ch9Iw8kNaaEICUoe1VmXJbW1iZx3mS4REZokvLLaBqFIbgRxjqDpMJ" +
                                          "TuCl7SEvBfxzY+rw5fuN40YURUBmlSg6l78ZDvWFDp0iOUIJ5IE82LI/9XXc" +
                                          "89JKFCEg7g4RS5rvf+HmPQf7rr0qaXZsQnMye4EoLKOsZ9ve3Dk6dHeMi9Fg" +
                                          "mbbGnV+huciytLszXLIAYXrKHPlmwtu8dupn9z3wHfKXKGqaQHWKqTtFiKNO" +
                                          "xSxamk7oMWIQihlRJ1AjMdRRsT+B6mGe0gwiV0/mcjZhE6hGF0t1pvgPJsoB" +
                                          "C26iJphrRs705hZmBTEvWQiheviiCHwPIfnp5wNDM8mCWSRJrGBDM8xkmppc" +
                                          "fzsJiJMF2xaSWYj6+aRtOhRCMGnSfBJDHBSIu5Glmpon4H+I0xExT/D4sv5v" +
                                          "nEtcpy2LkQiYe2c42XXIk+OmrhKaUVadkbGbz2Vel4HEg9+1BkN74LKEvCwh" +
                                          "LkvIyxKBy1AkIu7Yyi+V7gRnzENaA662DE2fOzG3MhiDOLIWa7gpSyLPdnh/" +
                                          "4GBIOJHRn5m2nvj1L/50ZxRF/eRvD6D2NGHDgYDjPLtEaHX6cpymhADdu4+n" +
                                          "v/bojYfPCiGAYs9mF8b5OAqBBugJKPTQqxffef+99evRsuAxBojrZKFwMdSA" +
                                          "swBXWGEMNZZxRyq29SP4ROD7H/7lOvIFGUNdo24g95cj2bIC5oiI+TaG+qrZ" +
                                          "XZqcW21XNWQQqLb+4OqaevLJQzJ/uyqzbQyKybO/+vcbicd/99omTm9kpvVx" +
                                          "nSwQvUI0uLKiLZgUoOmV2IzybtvV3/8wnh+JopoU6gLbOFjnBf4ozUPpUOZd" +
                                          "dG3JQq/gl+z+QMnmvQY1FaJCxahWul0uDeYCoXydoa0BDl5DwaFzf/VyHhb9" +
                                          "lQf/vP30kcKcCLZggea31UJt4SfTvKyWy+fukPnDLL89+cxrx/YpV6OionB0" +
                                          "3qQSVR4aDjoCLqUESqfB1eErrXDpYDiNw9bKKPv78YuZly7FhRcaoawyyFRe" +
                                          "sfrCl1dUhWEvyfhVDWCEnEmLWOdbnsmbWIGai/6KwJdOGfMQIE08xLvhe8DF" +
                                          "TfHLd3ssPvZKPBL0fWIc4ENcRFeUT/fyYZ8g+xhE2z4/jwHodYBE7pH4GQPc" +
                                          "ruU0nNUJR5h/te899OJfL3fIQNZhxXPRwf/NwF+/YwQ98Pr5f/YJNhGFNxo+" +
                                          "1vhksnpt8TkfpRQvcTlKX3pr1zdewU9AHYTaY2vLRJSTWqFfrZfYe2+f2G53" +
                                          "5VFv4dSLdyoJ1SwmeBMJkc63xj2CgQ3s8gsscYxiq6Ap9hRkA0g76Kctz49p" +
                                          "B7ArTbUi4OaC2xJ8Ij2nrMTTf5BwcccmByRd99PJr868feENkSgNPJPL4RnI" +
                                          "U8j4QIh0CIdyyBq6TYNdKU/yUtf789/64FkpT7ifCRGTldWvfJS4vCojQDZ9" +
                                          "ezb0XcEzsvELSTdwu1vEifE/Pn/pR09fephLxY8lGE8aE0t/jXCULGPl1kob" +
                                          "SknvfaT9x1e6YuOQnBOowTG0iw6ZUCvTvt52sgGj+l2iBIGAzLyuMBTZb1kl" +
                                          "sTwqxDhSFga5JZb/v48Pn2aoWaEEyo4o314QtYloxotMVnUQPl7FUYFHSUa5" +
                                          "cv3D1pkPX74pzF75qgnW6UlsSUt38mGYW7o33Ckcx3YB6D55berzHfq1W8Bx" +
                                          "Fjgq0O3YJyn0KKWKqu5S19b/5ic/7Zl7M4ai46gJ3KCOY/5+gC4QkIrYBWhv" +
                                          "StZn75FotNgAQ4ewB9pgoQ0LPMl3bw4fY0WLiYRf/kHv9w4/tfae6BCsEtg2" +
                                          "0BRxBts2vLDkq0B5bq29oXftzNsCo8udewtkVM7R9UAsBOOizqIkpwlLtkh7" +
                                          "WuJHY6i3CqhAwyInQr+CpIc61BGmhzgWv0E6k6Emnw5YyUmQBKpKDEj41AYL" +
                                          "RCobO/7nHB+65XyuqisCveCeisgTL1kvixz5ls0oz6+dmLr/5qeelK0hvIGX" +
                                          "l8XLB3JHVq1ykR6oys3jVXd86FbbC417vZTulAL7pWpHIIlykNoW9+z2EP7b" +
                                          "8XIZeGf98Ms/X6l7C2L4LIpgwPCzgXekfDRBEXGgmzqb2ogR0OKIwjQ89M2l" +
                                          "Iwdzf/utiC4XU3ZWp88o158698ur29ahgDVPoFpAK1KahUexfe+ScYooC3QW" +
                                          "tWr2WAlEBC7wSq8AoDYehJi/cYVdXHO2lld5o8HQ4EZQ3ditQSYuEjpiOobq" +
                                          "Qlizv1LxxPb6HMeyQgf8lUAdOSNRT3bSsUxq0rK8zrrmvCV6jJkwEItFcfrL" +
                                          "YsqHh/4L3boJoOUSAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188907000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5aazs1ll+9+0vad5L0iykTZrlpSKd9nrG9mxKt7HHM2OP" +
                                          "Z7PHM+MB+uLdHq/jfaYNlEhdoFKpIIUitfnVCqjSBUQFEioKQtBWrZCKKjaJ" +
                                          "tkJILKVS8wOoKFCOPXd79+Ul6g9Gsuf4+Dvfvpzz+cXvQ+fDACr5nr3RbS/a" +
                                          "V7Nof2VX96ONr4b7NFMdi0GoKoQthuEUzN2QH//i1f/40ceMa3vQhSV0r+i6" +
                                          "XiRGpueGrBp6dqIqDHT1eJa0VSeMoGvMSkxEOI5MG2bMMHqage44sTSCrjOH" +
                                          "LMCABRiwABcswK1jKLDodaobO0S+QnSjcA39PHSGgS74cs5eBD12MxJfDETn" +
                                          "AM24kABguJQ/z4BQxeIsgB49kn0n8y0Cf7wEP/8b77n2e2ehq0voqulyOTsy" +
                                          "YCICRJbQnY7qSGoQthRFVZbQ3a6qKpwamKJtbgu+l9A9oam7YhQH6pGS8snY" +
                                          "V4OC5rHm7pRz2YJYjrzgSDzNVG3l8Om8Zos6kPX+Y1l3EnbyeSDgFRMwFmii" +
                                          "rB4uOWeZrhJBbzq94kjG630AAJZedNTI8I5InXNFMAHds7OdLbo6zEWB6eoA" +
                                          "9LwXAyoR9NBtkea69kXZEnX1RgQ9eBpuvHsFoC4XisiXRNB9p8EKTMBKD52y" +
                                          "0gn7fH/49o++1+25ewXPiirbOf+XwKJHTi1iVU0NVFdWdwvvfAvz6+L9X/7w" +
                                          "HgQB4PtOAe9g/uB9L7/7rY+89NUdzBteAWYkrVQ5uiF/Wrrrm28knmqezdm4" +
                                          "5HuhmRv/JskL9x8fvHk680Hk3X+EMX+5f/jyJfbPhfd/Vv3eHnSFgi7Inh07" +
                                          "wI/ulj3HN2016KquGoiRqlDQZdVViOI9BV0EY8Z01d3sSNNCNaKgc3YxdcEr" +
                                          "noGKNIAiV9FFMDZdzTsc+2JkFOPMhyDoIrigM+CqQLvfo/ktgmaw4TkqLMqi" +
                                          "a7oePA68XP4QVt1IAro1YAl4vQWHXhwAF4S9QIdF4AeGevBCCkxFV4H9gZ/i" +
                                          "xXg/9y///w1zlst0LT1zBqj7jaeD3QZx0vNsRQ1uyM/HOPny5298fe/I+Q+0" +
                                          "EUFPAGL7O2L7BbH9HbH9E8SgM2cKGq/Pie7MCYxhgbAGCe/Op7ifo5/58ONn" +
                                          "gR/56blclVkRZw8WD2fBuqdun4Q7eQagiqwnA6d88L9GtvTcP/ywYPRkHs0R" +
                                          "7r2C459av4Rf/ORDxDu/V6y/DFJOBKTIo/mR0+F3U8TkcXhagSCTHuNFPuv8" +
                                          "+97jF/5sD7q4hK7JB2l6JtqxyqkgVV4xw8PcDVL5Te9vTjO7mHr6IJwj6I2n" +
                                          "+TpB9unDnJgLf/6k4cA4h87HVwonuKuAufvH4HcGXP+bX7kl8omdc99DHETY" +
                                          "o0ch5vvZmTMRdB7Zr++X8/WP5TY+reCcgXdw/qf+5i/+Bd2D9o7z9NUTlQ8o" +
                                          "4ekTuSFHdrXIAncfu8w0UHNl/f0nxr/28e9/6GcKfwEQT7wSwev5PecYFDpQ" +
                                          "MD7w1fXffufbn/7W3pGPnY1AcYwl25TBICzqFpBEM13RLhTyeAQ9sLLl64dS" +
                                          "z0AdA4xdX9n1QlX3gcpdsJZbZX+X/ItoAhxdv427nijYN+SPfesHr5v94I9f" +
                                          "vsVTb1bMQPSf3lmo4CoD6B84HUU9MTQAHPbS8Gev2S/9CGBcAowyyAThKADx" +
                                          "m92kxgPo8xf/7k/+9P5nvnkW2utAV2xPVDpiXltBhowMUI4NEPqZ/6537zJc" +
                                          "egncrhWxCRXyv2HHThHWdx0rgvFADfzIP37sG7/yxHcAHzR0Psl9GHBwQlvD" +
                                          "ON8WfPDFjz98x/Pf/UhhE5BPZ7/0u+gPc6yNgsCTxf2n81tpZ7F8+Nb89rb8" +
                                          "tn9opodyM3FF5mPEMBp4igm2BUphqVdNHePAdIC3JQc1D372nu9Yn/znz+3q" +
                                          "2ek8cQpY/fDzv/zj/Y8+v3diF/HELYX85JrdTqJg+nVHpnzs1agUKzr/9IVn" +
                                          "/+i3n/3Qjqt7bq6JJNjyfe6v/ucb+5/47tdeITWfs71Dp8zvyAHZ/K/62oaN" +
                                          "7vhGDwup1uGPmS1UJJXZzNFieFyXOBUpb1MZqdvkqGWjxHpGZRxZVmKUxNSN" +
                                          "jIUs11syW3RUl1F5WY+ryXKuJSFpT9brwKfYTicV+R6v1e31ZFGm+UmXmFkd" +
                                          "KurwDG9FZF/UI9IyebY8WdFjfTUZ284yURCpVGY0tMdtZXSojcfDJpw10W22" +
                                          "bTUXYmfMs/pmIVjWIszoFV72VyKLo7NwjmhGMB80bH0Aw2gDrwxRttJTmK4X" +
                                          "CL2IS6fCsoKZMRIMPRuRhDYe9kNRpnjNoYcEj3iTWBBFITPrXkWt0V5tuTZD" +
                                          "3p7Sy0zHowFfC7kBz6HBoM0YAwf3ZqlncROftiytjTQGfqXfFyo+PU7MSmts" +
                                          "BAK2ZDvwpiZ5Qp3HpU3LSuvTZpfth007NUWqba+tpLqYT2nepGmu7il1yxnR" +
                                          "3ZqIDWjcbnpwQ436GD8SBCpC2viAjrjtNOtJFVylHIsB26m1MPUChNWAlsnY" +
                                          "qOqtbAJ3eQWxOMZCCX9ZQ8bGjELL3sDfGmvCnQtZzR3xgdFqtyr8ICDTjJ8v" +
                                          "prOAauOp6PTj+qi1FZu+WrFnfsyPe2yr4c6yRhXV2moXcRQ2RpYDGSV5kmJw" +
                                          "WhrqfIcZkI6nzWZzc7umR61q2pyKZleZo8vmglsEKj/c4lmaIPI8iQ3BoLy6" +
                                          "NovxXplEa+Zq4HcXFdns62ivVBmxqDtRZHVRUX1samh4OpeGODGortqku4it" +
                                          "pY1tZ9QSMcolXhEyuK2vdLGHsCFFL5N10E0ZohU7HFUbrii6JhtNKm1YQ1Ek" +
                                          "KYL31MrMWdDSvGIuM9ThMJZcelbCMCK+7lCSzmarddsf0NOYsOscmeBathVK" +
                                          "QVrV4iFWFniWxx2b02t2vbFsJ/NO2y+bI56iqxTZQBgKbi4WcqNJ9zsEqdd1" +
                                          "jOWqQaKVes54otWDoLwWF8tw4g42KkZ6TH8ULpuJiratmtJTB2azozuS1HVn" +
                                          "JSOWzU3EhNsFQ7WERdDvgXhIo7ihxL7b3KJpT+sv+t21OOnN++tp1DH7w1HG" +
                                          "ZaJj1b3BnJqYhs3SldZqoLBsOC3hNaerlvXUnJVhR14tDbJmdDvlqOIn+pgO" +
                                          "PZxAaibtGwEb1stVY+ngUzKZAyxqYppELx1TmutX02F70HCIOcfSQRcH48xy" +
                                          "fF/WtiFt0oMOkoncXFjVSiIbjQyWGHRdTsPpdg/nqLjatR3fc7FeiSpnZDaF" +
                                          "21iYVBOXjGR/gzDWxBRURMaQxYKySiMnMPoiPxMVS+pKW2Sm2liP1JulCm4N" +
                                          "6xjTJxMiNRgroTZZH99UWhYV14WNWZrVddbdkkOxVashbRLRRtsuOjDM9oih" +
                                          "5mJd97kNM1ZcA8a6ODWie6xbdRA3WVUYuFpeZiBOVTZp19rIsNtr60J7NWYi" +
                                          "UuwtaoBJB0SLEmMlN4ElbyVoY8LstoSw6XQaUnXUWuN4rNP98XSyzjRN1UrN" +
                                          "ppqwYdzKcG8VLPuddKBwrTDFF/MuORguAbXNGmlyY4wdtes9uG6PEqrT5YeK" +
                                          "h2B6syqvEIkiqp5JlaZit7QOlovlWp4jlcVwPpmsGamEjdaimjD0ZEvD8Wa9" +
                                          "lSab/kYawaVElkxZgZtNz5k6TctPZpnLpZOEp8ox0zeZpc57I2eGUNuNFCUz" +
                                          "FG6krlGiPd/jazojjTorF9cwb8uPfX60VJQuSk/WsG6XtqXJwHWSiVDpiDSR" +
                                          "icY8tstxWxUIb7FRPLGMt+1qOxU7Ww2ebXqG1LQnGpyM0bIl92UCENZVEa3w" +
                                          "dIRx2jTpb+abkhZbY7fNMI1mSc6CDBb8WW0EdkZ4GV1PuBmLie2VRzBrnuTW" +
                                          "Gl5RySBYtH2hbQ7TptTvj5N6Q4iX9qbeMVhZ9MR0s+mwaqgFhF1ReGNOJhvN" +
                                          "mLXnBOmSDjMfKZIbOtKc6oomXOuntDLqaoMJRZYbGZMYaqPdmWo9RkHDcJws" +
                                          "+2OcKWtzSsbIocx2VH4Kaxth2dBLmUEiWwxepT1PEXCy7vew7mQsBzFfdoc8" +
                                          "zVYNOFIbzeaI1hhUoybDpZEtxmyqwcO0U4KFdNJsjIOqBgv0EITiMPNKlcSw" +
                                          "QtePGlNL89lJIk/t/gL1g8pWUVO+2eoJU1FAEoaluel83dGCpQZipqQh3Spa" +
                                          "nXUSTOEYZePRFS51VFAmLLmGZiuE0Cdo2NDDUAYlbV1r+U2DtVplvV7ry9EW" +
                                          "a/p4vRVMJd7ERiKBZHSDWiFuMJhOtSqeyrLs4BtWaTbHdNCoNTSVHFqcPhzT" +
                                          "YwZjXYpvrLAJZZQJStls8HVtKgyVPg9v+EirN5pwDetY/rRuagTbndrKPNFo" +
                                          "DksIbzVpL5vqViovZHIbJiTDTZU0riSkqZHw2IV9ttzUVN9gMqFhd8mGSJYj" +
                                          "eLUgeKY7tiuWJ3GWm2jitJmBCi3Eo4mLj7x02i2baW3JE8k0iapIqHdXJRsx" +
                                          "carb2jKbeIBPl1LFssNpus7aBtfRxSq9lOAEa4xdRPTmIkluPMxDK9gkEmwv" +
                                          "86LBzOXBVqTe4YVOj+PFqpyg7YpvjRd1zN926tW17s5rvB1yfIQ2nK4wr3so" +
                                          "Slhyhgp4rV2tgp3vtqetK/MGnnVW+ro8QgV645b7fZC34ypXaUpw1ZTh+tKu" +
                                          "DzDRxGo6jfaJkQBXSzqBTSwqEPC5kXDR0q1XO1401FsTTE3xpq97kzIzHtio" +
                                          "lGKaUJ4zpsBqsNVLmikGR5qo1nAiJCMdKeNshkch8Jy2tS7jVQmkHW+hRdsh" +
                                          "OIU2YuBckTUb1Nkm3wrx0QjUb8ryU5uJLKM+j+meUDPBfs9opRvKnQQlwqfk" +
                                          "WgXvOsZWnydlsmbVSMdNq8KGdyZ43++3yRVWaQkMS3ggG9XdHl6qVRebGOyi" +
                                          "iEQlVDPUp0zFSsxsW7XDsretlRSHCeDqWlXtftlIqO7CbiwYHKV7s3VlY7E1" +
                                          "bxOiq9lCadQ6kkRglXqynMZ2i6n7c79HUfbGGnrzZmmLkGCr2lhQS7WrNRuD" +
                                          "EF6ASk0gDMZQvp6Oia2+UMEujcXJRVd3tmsJ8XS2POpT6WrSaA4Qm0oVkLvA" +
                                          "dpvAFjy6nPuNhlepNmrNRhwgTdHQ27Ox1/Fb/UpfNHg109QSJwueR6CTeTQP" +
                                          "kHnLJnGinnLrRstrC6pBm7AszJRFb4TYtlL1Gr0JRi4nqGJGE06IyZVvjjxp" +
                                          "PbHNbVJhsmws1XoDdTPRtYbNt5QRN2SnqMSFfLYuB/3GNgichJjVVrSVkmD3" +
                                          "LGsBI4TrHqhoDCp5tDfiObB7f0e+rad+spPV3cUB+KgVCg5U+YvyT3CiyF6N" +
                                          "YARdEqUwCsCxM4IuH/Vmd9RPdIDOHB64H7ldq2nXZcoPVA/frhlaHKY+/dzz" +
                                          "Lyijz1Tyw1SOsw3oRp7/NltNVPsmigH0ltsfHAdFL/i4ufOV5/71oek7jWeK" +
                                          "7sYtTScGupKvHOct96PW+ptO8Xka5e8MXvxa983yr+5BZ49aPbd0qW9e9PTN" +
                                          "DZ4rgRrFgTs9avME0OO3nDY9WVXiQD2m+5ZHxS/d+PKz1/egcyf7XzmGh091" +
                                          "k+7QvMAR7ZzAYVv8SmQEIOkezZxsLQG1Xsmd4j5wlQ76psV//vZeP7+/Pjt2" +
                                          "rVt8Zu/ISdkDDwmgNx93NQjPtlW50Pp13nWKJoAo2WreYfzvq09WvvRvH722" +
                                          "OyLbYObQDG99bQTH8z+FQ+//+nv+85ECzRk5/9Bw3Kc5Btt1r+89xtwKAnGT" +
                                          "85H94l8+/JtfET91FjpDQedCc6sW7eTzhXznD738yVf38oOvK4fQ9+bQKSrv" +
                                          "K56zn39SUt1COusQ4LFb0OlJtN8NRN8w5XDoKTtbvetEKBN5J8z2xKhQtFHM" +
                                          "ycVdLwJ816PNn4vJGxF0hxyoYqQWLd9DwruukJhG+8fTRcJ45rVaECepZAD5" +
                                          "iU5yrtoHb/kstfuUIn/+hauXHniB/+vCeY8+d1xmoEtabNsnm58nxhf8QNXM" +
                                          "QprLO3/1i7/3RdADt7FEBF3YDQpu37uD/4UIunYaHuix+D8J91wEXTmGA6h2" +
                                          "g5MgH4igswAkH34w77GeyEwHGbXQ4z2vpcejJSebpHk2Kz7/HWaeePcB8Ib8" +
                                          "hRfo4Xtfrn1m16SVbXG7LT4XMdDFXagfZa/HbovtENeF3lM/uuuLl588zLR3" +
                                          "7Rg+ju8TvL3plYOQdPyoCJvtHz7w+2//rRe+XTQK/w8xUGkolx0AAA==");
}
