package org.apache.batik.bridge;
public class SVGTitleElementBridge extends org.apache.batik.bridge.SVGDescriptiveElementBridge {
    public SVGTitleElementBridge() { super(); }
    public java.lang.String getLocalName() { return SVG_TITLE_TAG; }
    public org.apache.batik.bridge.Bridge getInstance() { return new org.apache.batik.bridge.SVGTitleElementBridge(
                                                            ); }
    public static final java.lang.String jlc$CompilerVersion$jl7 =
      "2.7.0";
    public static final long jlc$SourceLastModified$jl7 = 1471188907000L;
    public static final java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Ye2wcRxmfO79f8SOJHZLYcRzHKK+7Rm2AyqHUduzE6fmh" +
                                                              "2LWEQ3OZ252723hvdzM7a59dCm0l1CBEiULahkr1X66qotJUiAqQaGVUibYq" +
                                                              "ILVEQEENSPxTHhGNkMof4fXNzO7t3t6doyDESTu398033zffY37fN/fSDVRj" +
                                                              "U9RDDBZjyxaxY6MGm8bUJuqIjm17FmhJ5Zkq/LczH07eG0W182hTFtsTCrbJ" +
                                                              "mEZ01Z5H3ZphM2woxJ4kROUrpimxCV3ETDONebRVs8dzlq4pGpswVcIZ5jBN" +
                                                              "oHbMGNVSDiPjrgCGuhOwk7jYSXwoPD2YQM2KaS377NsC7COBGc6Z83XZDLUl" +
                                                              "zuFFHHeYpscTms0G8xQdsEx9OaObLEbyLHZOP+K64GTiSIkL+l5p/fjWxWyb" +
                                                              "cMFmbBgmE+bZp4ht6otETaBWnzqqk5x9Hn0JVSVQU4CZof6EpzQOSuOg1LPW" +
                                                              "54LdtxDDyY2YwhzmSaq1FL4hhnYXC7EwxTlXzLTYM0ioZ67tYjFY21uwVlpZ" +
                                                              "YuJTB+KXnznT9t0q1DqPWjVjhm9HgU0wUDIPDiW5FKH2kKoSdR61GxDsGUI1" +
                                                              "rGsrbqQ7bC1jYOZA+D23cKJjESp0+r6COIJt1FGYSQvmpUVCub9q0jrOgK2d" +
                                                              "vq3SwjFOBwMbNdgYTWPIO3dJ9YJmqAztCq8o2Nj/ADDA0rocYVmzoKrawEBA" +
                                                              "HTJFdGxk4jOQekYGWGtMSEDK0PaKQrmvLaws4AxJ8owM8U3LKeBqEI7gSxja" +
                                                              "GmYTkiBK20NRCsTnxuTRJx82ThhRFIE9q0TR+f6bYFFPaNEpkiaUwDmQC5v3" +
                                                              "J57Gna9diCIEzFtDzJLn+1+8ef/BnvW3JM+OMjxTqXNEYUllLbXp3Z0j++6t" +
                                                              "4tuot0xb48Evslycsml3ZjBvAcJ0FiTyyZg3uX7qJ59/9Nvkz1HUOI5qFVN3" +
                                                              "cpBH7YqZszSd0OPEIBQzoo6jBmKoI2J+HNXBe0IziKROpdM2YeOoWhekWlP8" +
                                                              "BhelQQR3USO8a0ba9N4tzLLiPW8hhOrgQc3w7ETyI74ZOhvPmjkSxwo2NMOM" +
                                                              "T1OT22/HAXFS4NtsPAVZvxC3TYdCCsZNmoljyIMscSdSVFMzJD4zd3xWYzrh" +
                                                              "kABLhwU1xjPN+j/oyHM7Ny9FIhCCnWEA0OHsnDB1ldCkctkZHr35cvIdmVz8" +
                                                              "QLgeYugQqI1JtTGhNibVxsqqRZGI0LaFq5fBhlAtwKEH1G3eN/PQybMX+qog" +
                                                              "y6ylavAzZ+0rqj4jPjJ4cJ5Urna0rOy+fviNKKpOoA6sMAfrvJgM0QzAlLLg" +
                                                              "nuTmFNQlvzz0BsoDr2vUVIgK6FSpTLhS6s1FQjmdoS0BCV7x4sc0Xrl0lN0/" +
                                                              "Wr+y9Njcl++KomhxReAqawDM+PJpjuMFvO4PI0E5ua1PfPjx1acfMX1MKCox" +
                                                              "XmUsWclt6AvnQ9g9SWV/L341+doj/cLtDYDZDMMZAzjsCesogpxBD765LfVg" +
                                                              "cNqkOazzKc/HjSxLzSWfIhK1XbxvgbRo4mewF57d7qEU33y20+Jjl0xsnmch" +
                                                              "K0R5+OyM9dyvf/7Hu4W7vUrSGmgBZggbDKAXF9YhcKrdT9tZSgjwfXBl+ptP" +
                                                              "3XjitMhZ4NhTTmE/H0cAtSCE4OavvHX+/d9dX7sW9fOcQfl2UtAF5QtGcjpq" +
                                                              "3MBI0Dbg7wfQTwd04FnT/6AB+amlNZzSCT9Y/2jde/jVvzzZJvNAB4qXRgdv" +
                                                              "L8Cnf2IYPfrOmb/3CDERhVdf32c+m4T0zb7kIUrxMt9H/rH3ur/1Jn4OigMA" +
                                                              "sq2tEIGxSPgAiaAdEfbfJcZ7QnOf5sNeO5j8xecr0CUllYvXPmqZ++j1m2K3" +
                                                              "xW1WMNYT2BqU6cWHgTyI7wqD0wlsZ4HvnvXJL7Tp67dA4jxIVAB07SkKAJkv" +
                                                              "ygyXu6buNz9+o/Psu1UoOoYadROrY1gcMtQA2U3sLGBr3vrc/TK4S/UwtAlT" +
                                                              "UYnxJQTu4F3lQzeas5hw9soPur539IXV6yLLLCljR1DgJ/lwoJBv4lMbrnTB" +
                                                              "fCuSQFF3pWZENFJrj19eVaeePyxbho7iAj8K/et3fvnPn8au/P7tMjWlgZnW" +
                                                              "IZ0sEj2gM8pVFtWCCdGn+Xj0waZLf/hhf2b4TsoAp/XcBuj5711gxP7KsB7e" +
                                                              "ypuP/2n77H3Zs3eA6LtC7gyLfHHipbePDyiXoqIplWBe0swWLxoMOhaUUgLd" +
                                                              "t8HN5JQWkfZ7CgnQwQPbA8+AmwAD5VG1TO4UsKrS0g1O9ewGc3N8mGKoOQMt" +
                                                              "m6lgfRKsEZzb4NImDgBvyGOyIRcTn+HDtMzwwf/ydHHCkCXoDxS7pxueQ66N" +
                                                              "h+7cPZWWbuACZYM5EcYzDDWBe7yYe97pqdSXyUbM91Xyf+GrPFxayjZ8HKm2" +
                                                              "ldwt5X1IeXm1tb5r9cFfiQNbuLM0w9FLO7oeyNxgFtdalKQ1YX+zBG5LfJkM" +
                                                              "dVWwGapryrfakPzQp7SF+RmqEd9BPoehRp8PRMmXIAtYXwUs/HXZ8gJw9waN" +
                                                              "8TFiK1SzmLZY7K18pBSmRZC23i5IAVzeUwRT4vrvQYoj/wCAjnn15OTDNz/1" +
                                                              "vGyBFB2vrIjrItx+ZTdWgKXdFaV5smpP7Lu16ZWGvVE3K9vlhv3TsCOQskPQ" +
                                                              "7Fg8KbaH+gO7v9AmvL929PWfXah9DyrDaRTBDG0+Hbh8y5smNBkO1IPTCb8i" +
                                                              "BP4+Eo3L4L5nl+87mP7rb0UFRPI2sbMyf1K59sJDv7i0bQ0anKZxVANFjOTn" +
                                                              "UaNmH1s2ThFlkc6jFs0ezcMWQYqG9XFU7xjaeYeMqwm0iecv5jgk/OK6s6VA" +
                                                              "5Q00Q30l/wCUuXZAt7BE6LDpGKoAaighPqXofwkP2R3LCi3wKYVQbim1Pakc" +
                                                              "+2rrjy52VI3BGSwyJyi+znZShaoR/KvCLyNtEuz+DZ8IPP/iDw86J/BvhjpG" +
                                                              "3Gt7b+HeDm2JnKtKJiYsy+OtuWrJU/Q1Pnw9z+kMRfa7VA4/Edk2858Xhf5v" +
                                                              "iFc+XPoPZCrlIbYUAAA=");
    public static final java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    public static final long jlc$SourceLastModified$jl5 =
      1471188907000L;
    public static final java.lang.String jlc$ClassType$jl5 =
      ("H4sIAAAAAAAAAL1Zeazr2Fn3u2/eOtN5b147C8PMm+11YCadaztO4oTXLXHi" +
       "bHbsJM5maN94X+ItthM7LkMXCbqJMqJvyiC181croJouICqQUNEgBG3VCqmo" +
       "YpNoK4REoVTq/EGpKFCOnXtv7r1vqUYgIvnYOec73/m28zufP7/8PehU4EM5" +
       "z7XWmuWGu0oc7ppWcTdce0qw26GKrOAHikxYQhBwoO+a9PjnL/zgR8/rF3eg" +
       "0zz0esFx3FAIDdcJBkrgWitFpqAL296GpdhBCF2kTGElwMvQsGDKCMKrFHTn" +
       "oakhdIXaFwEGIsBABDgTAa5uqcCk1ynO0ibSGYITBgvol6ATFHTak1LxQuix" +
       "o0w8wRfsPTZspgHgcDb9PwZKZZNjH3r0QPeNzjco/EIOvv4b77z4eyehCzx0" +
       "wXCGqTgSECIEi/DQXbZii4ofVGVZkXnoHkdR5KHiG4JlJJncPHQpMDRHCJe+" +
       "cmCktHPpKX625tZyd0mpbv5SCl3/QD3VUCx5/98p1RI0oOt9W103GpJpP1Dw" +
       "vAEE81VBUvan3DE3HDmEHjk+40DHK11AAKaesZVQdw+WusMRQAd0aeM7S3A0" +
       "eBj6hqMB0lPuEqwSQg/ekmlqa0+Q5oKmXAuhB47TsZshQHUuM0Q6JYTuPU6W" +
       "cQJeevCYlw7553u9N3/kXU7L2clklhXJSuU/CyZdPjZpoKiKrziSspl419PU" +
       "x4T7vviBHQgCxPceI97Q/MEvvvr2N11+5csbmp++CQ0jmooUXpM+Kd799YeI" +
       "pyonUzHOem5gpM4/onkW/uzeyNXYAzvvvgOO6eDu/uArgz+fvefTynd3oPNt" +
       "6LTkWksbxNE9kmt7hqX4TcVRfCFU5DZ0TnFkIhtvQ2fAM2U4yqaXUdVACdvQ" +
       "HVbWddrN/gMTqYBFaqIz4NlwVHf/2RNCPXuOPQiCzoALugtcD0GbX3YPoWdh" +
       "3bUVWJAEx3BcmPXdVP8AVpxQBLbVYRFE/RwO3KUPQhB2fQ0WQBzoyt6A6Buy" +
       "psDDcZMzQktJAQJMrWW9u2mkef8Pa8SpnhejEyeACx46DgAW2Dst15IV/5p0" +
       "fVlrvPrZa1/dOdgQexYKoWfAsrubZXezZXc3y+7edFnoxIlstTeky2+cDVw1" +
       "B5sewOFdTw3f0Xn2A4+fBFHmRXcAO6ek8K1RmdjCRDsDQwnEKvTKi9F7x+9G" +
       "dqCdo/Caigy6zqfT2RQUD8DvyvFtdTO+F97/nR987mPPudsNdgSv9/b9jTPT" +
       "ffv4ceP6rqTIAAm37J9+VPjCtS8+d2UHugOAAQDAUAABC7Dl8vE1juzfq/tY" +
       "mOpyCiisur4tWOnQPoCdD3XfjbY9mdfvzp7vATa+Mw3oR8H12F6EZ/d09PVe" +
       "2r5hEyWp045pkWHtW4beJ/7mL/4Zy8y9D8sXDh10QyW8eggKUmYXsk1/zzYG" +
       "OF9RAN3fv8h+9IXvvf/nswAAFE/cbMEraUsACAAuBGb+5S8v/vZb3/zkN3a2" +
       "QROCs3ApWoYUHyiZ9kPnb6MkWO3JrTwASiyw1dKouTJybFc2VEMQLSWN0v+8" +
       "8Eb0C//6kYubOLBAz34YveknM9j2/1QNes9X3/nvlzM2J6T0KNvabEu2wcfX" +
       "bzlXfV9Yp3LE7/3Lh3/zS8InANICdAuMRMkAC8psAGVOgzP9n87a3WNjaNo8" +
       "EhwO/qP761DKcU16/hvff934+3/8aibt0ZzlsK9pwbu6Ca+0eTQG7O8/vtNb" +
       "QqADusIrvV+4aL3yI8CRBxwlgGAB4wO0iY9Exh71qTN/9yd/et+zXz8J7ZDQ" +
       "ecsVZFLINhl0DkS3EugAqGLvbW/fODc6C5qLmarQDcpvguKB7N9JIOBTt8YX" +
       "Mk05tlv0gf9gLPF9//DDG4yQIctNTtpj83n45Y8/SLz1u9n87RZPZ1+Ob0Rg" +
       "kJ5t5+Y/bf/bzuOn/2wHOsNDF6W93G8sWMt04/Ag3wn2E0KQHx4ZP5q7bA7q" +
       "qwcQ9tBxeDm07HFw2SI/eE6p0+fzh/Hkx+B3Alz/nV6pudOOzYl5idg7th89" +
       "OLc9Lz4Bduup/C6+i6Tz35ZxeSxrr6TNz2zclD7+LNjWQZZ0ghmq4QhWtvDb" +
       "QxBilnRln/sYJKHAJ1dMC8/Y3AvS7iycUu13N5nbBtDSNp+x2IRE8Zbh83Mb" +
       "quzkunvLjHJBEvjhf3z+a7/2xLeATzvQqVVqb+DKQyv2lmle/Csvv/Dwnde/" +
       "/eEMpQBEjT/4u9gPU67U7TROm0bakPuqPpiqOswOfEoIQjoDFkXOtL1tKLO+" +
       "YQP8Xe0lffBzl741//h3PrNJ6I7H7TFi5QPXP/Tj3Y9c3zmURj9xQyZ7eM4m" +
       "lc6Eft2ehX3osdutks0g/+lzz/3Rbz/3/o1Ul44mhQ3wzvOZv/qvr+2++O2v" +
       "3CQPucNy/xeODe/8WqsQtKv7PwqdKflIGsS2yuAVtTxkOi2emkmDpNXt5vCB" +
       "na+uF62RvEwaJdXW89Sk0ccYPl/M43lMX8kJjQvFikzYiIUStYYxogR97qPT" +
       "Umnhhp2RUV30heZ4ZIizRZsaN/qNRm/IxlxLb/bmtKsW1GkvYfAQC0uyu643" +
       "htwSq5QRDEtUdYbhag9Wh/XxwBxVBvV6jTfXsRDPSnTTLoujznLRNm0UJ229" +
       "U+TnC5iSkhaCK01kgpbzOkeGAUf4Ysdu8AjKF1sY7+l0PnLjTmE+YEa+Z9gx" +
       "McYaXJ3pKeJgHJTlxFoUvKYXRGOpzRfNWs9tiXSzNx7WDdb0NaK51Jlojpuz" +
       "4TRy2Xp+1qfzXWGI4XgvIHCCqTWlEl/GpnydGlnJkiRbLWXmBRJnB0izHPfl" +
       "oBFXGIERqYa4plo8w+a6pQJIH4ftOZWzih6smpN4shYlmrTFmmY3ciLvFfSw" +
       "5IYNTqhNnGSxmBfjSstBOuPhuD8qELyrlhpe0meGS0ZDKXZSLFByGNfr61l+" +
       "FumJPRQWKEkVdN2ZTQm8EcWcNU0obkYjhsuX8HBmkrM8uozGlsfPlh2ulutO" +
       "ncThKiGyQOsLdmKOTd2utLQREo3qbbZuTIpkt5Wfd92hPCihzbgeNEdt1G8G" +
       "vrjo4yKBmjOGr+bqeUzqdszG0ENyfolg2p0QJZuzYX9le6MxsRQrC8T0Ga2b" +
       "l1cLbBiZJFOLaLEnazNuwrYZTO5UZh17UU1CYlF28z0TrtbrVQTklLOxnbhd" +
       "X4gatWqL65ByM54XTKavzGfNSTOkh416F2GFbt+3V5QQBYVq3Cm7EV0eYVRX" +
       "qS0abVwbxqbQtGfc3Kh180hvQAScEy+5QScu5zldH5DtBhCQG+TUkjgjSVbo" +
       "Nby5IYyiut0niiusU8SbjlCRDaLdSMiwnnQoJ4fmyooK15zVBOvQOYY2Y24x" +
       "7TVmI8uixKmH8YiZy5XCQrh0QyQWC+XGKrDWUmBbGG/WVlWpg5AGt17zGrac" +
       "4otOsQJXeqt5grZGTLu4IMc9TPJqLXy24INkKCMM22jX+onrlsya3XXb+U6u" +
       "1ZvWFKSdGN0B48l0fqYw7kRX5hOLLdd0xer3B9hoyJQFRBQqvUKYUJTBTsq6" +
       "zvhaX8IivMGt23iBZ/QVa5vzYRwB09MMzaEMl8/DreqUHBZ6YcBWx/wqJjBu" +
       "JhNEwPds1zLXbTqQhvJwTNJJp15IZCyezBJfn1drlB6N0NhkezkTdtctGu+t" +
       "K2RbJwhn0qgiTCtw6jXUkom5FM75lo8VpVVbtsdJuU9pymyp9RdttBNyTb1n" +
       "iGOAd4sB32wjlEAuimpNt6ph1G200Cam9GC2vxbpaW7hauvS2hJW1YTPIf7C" +
       "LJis2SlIneLIdwTEZ9Y5dWX0ul2PcaulgK6q/qqj0Ug/qVoUpTlLziZ7fWuV" +
       "JEgtcOt+fjUat7VuiRx6HKUPSwFK9k1bdodIjRjjcSGQkKlvIVYPgSd+bl3p" +
       "mZKVy3VdW48HSnUhRHU6x3Y8c0mTK6bAtpFGcSmgrMqaMSpIKj1F6S7hxlN7" +
       "FExAxlKqrpx+RasMJ2OYwgpoTnZNWKLC+qzO12maryZmQCiBq3lxrY6XipQ6" +
       "1qTeYs4ISdKV4JY5jKlkOFHbehedivFKEwduwVYisojL+KIxwrB1Hsl1TAuJ" +
       "A8eW9C4yKOaYNV2R1ysVxlvLwgRfjfxh09ZqvKaJ9S7wfGWmS11fBuDADzUz" +
       "Uqc1K+eFLDY1jZDW+UJP5zi7AbcQqRoOiUaBEVar1jQHyxV5igeTispIfdXK" +
       "j8IqWeyHTcn0FhhdayN1UcMjtc9FMlIgHQ4uVWs5wbZ6fDIkuMoMzpuyAptj" +
       "4Au+s+pVa4XFdKDJK6pMOGq+PWNVn7FFGCPqjYE+llUsL+XsAockIj5vj/yY" +
       "Dist2G9hSx9GO06BMTS6GizyYaPdjIesVjWEqtxQRbUj8XjfYdRi0FOYolmO" +
       "FclHCLB5Z6spay/4XM5E7XwXRDU6oXszLl9bjErSpKWlWyZa1JHICvhCa+Ws" +
       "ph0K57wSLlcLZtweV2sIPpx3q535aq2tp8uSuOwllZwLs8ESHbmMOxPkAePP" +
       "UE2iw341P8ICqlnzsZUvwVy3MIRHUVi1uNHMiTt9blkgMaufKEJQ1KNK4LJL" +
       "v4hV2tNxaU1RFGGZA7SudWArcju1VcGiRd/haiqxHPZJEvMmfKNHdnwTrShj" +
       "QVHYdSzqLm5UzXIXVkJMXTmsUxaWMIuHtDmxNN6ZtHkkaJh5jS57YzKcEITc" +
       "dHJTE4kEnlJhXVfzYoEL3KoHT6Xa0iziKKrFLN4Nariy9pYsnHdwHJzAAaZU" +
       "S1RI4NqaUlstwxMVtr42pu6i7VkTAFtBNKFil2Z0YTTSwDlWbvWKnf5krvI4" +
       "oTn9qM+K1XKuakfVenHcRDmmMAq6/hDRUKaiRE0J65XtZtdl+nRolyxNHXSD" +
       "Bp+IhV7brmu11brJrNsDiXNyrXpIJ1Gkwmu51SLmxNStx0Pci5dKv1Tq6Tlc" +
       "YvnJRFxWCX5GFxvSLKnXgYD4eqZUcG8hD6frkUhX0OlazTV9loyFtcmXW107" +
       "b8lRWJyibWVqo6FY9CsSqRr9nrikaCSqkBSDu8q6F2tkKAtWt4/Oprmk1gTb" +
       "tzOn5fEkagqev/ZVYc4mfQ8fkrmBvWjIlRrrKvrAK7MD2p62q+FsGo0CuDXl" +
       "y1onqkRCr8yRRhcdJjbFz/AuWvZqQ3vAE3nMKLar40QZRQOusPJX/RnAkYio" +
       "mo6DFhmu3ktgdNVc18hafuW3Tb8dxjmekydadwpePsfFwPZYnFqiJX7SXI0b" +
       "WLeysvQVxgUE0w/mbB8ntXJXFFo5jcFXlSo4cCv5CjtRp4Jeqa/9ujDgavUm" +
       "kmuJenkNuPVqcwZtsxwhlo0aW8g1XIwqUEXHypVxm8V9ERmRA7adD0R6raLd" +
       "YiXo1Fe4gYh9RHC6fDyu9kiT4ZyR0LNbaADOatKaSyWTDBAlkehJf7ZoVqbk" +
       "CAfnuzJT6EVkI4YirYqmNoeZbikojavFPoL0McQCdhgtp3w1xGuNElX3QOhU" +
       "BUPT2cXUVaM5mx9gFGFgUXc27ouGjbLCXMrlfd9cF/PjNlZrDqN1Z23kEocf" +
       "6oI7gLsrglr3wsYyydX5cptlYaMelUsduLbSTa+JNUNczLWUup3vON2w2zFm" +
       "wTrHhMuJ3xnBfZR1okqSm9MDVcDH1QLckOf5crE81dXiyiCl3JR1WZ7wrbY4" +
       "G4Hs/S1pWv+O1/ZmdU/2EnnwLQC8UKUDrdfwRrEZeixt3nhQeMp+p4/Xjw8X" +
       "nrbVCCh9S3r4ViX+7A3pk++7/pLMfArd2aviTEPoXOh6z1jKSrEOsdoBnJ6+" +
       "9dsgnX3h2FYXvvS+f3mQe6v+7GuomT5yTM7jLH+HfvkrzSelX9+BTh7UGm74" +
       "9nJ00tWjFYbzvhIuAUIfqTM8fGDZS6nFLoPryT3LPnnzuuVNo+BEFgUb39+m" +
       "SBbcZmyZNk4I3aUpIeVKgtXbE721DRf3J72AHmaadcyP6vcwuJ7Z0++Z/3v9" +
       "3n2bsfemTRJCdwL99j20X1G5fKui/6bKvzXAu16LAeIQuvemXw3SEugDN3yg" +
       "3HxUkz770oWz9780+uuscH7w4escBZ1Vl5Z1uGJ16Pm05yuqkel5blO/8rLb" +
       "h0Lo/lvoFkKnxa12H9zQ/2oIXTxOH0KnsvthuudD6PyWDrDaPBwm+WgInQQk" +
       "6eN1b9/Q2G2+rtSVQPINL62gHLFWfOIophw449JPcsYhGHriCHhk35D3N/py" +
       "8xX5mvS5lzq9d71a+tSm9C9ZIMFOuZyloDObrxAHYPHYLbnt8zrdeupHd3/+" +
       "3Bv3ge3ujcDbED8k2yM3r7M3bC/MKuPJH97/+2/+rZe+mRXb/gcoYygH3B8A" +
       "AA==");
}
