package org.apache.batik.transcoder.keys;
public class Rectangle2DKey extends org.apache.batik.transcoder.TranscodingHints.Key {
    public boolean isCompatibleValue(java.lang.Object v) { return v instanceof java.awt.geom.Rectangle2D;
    }
    public Rectangle2DKey() { super(); }
    public static final java.lang.String jlc$CompilerVersion$jl7 =
      "2.7.0";
    public static final long jlc$SourceLastModified$jl7 = 1445630120000L;
    public static final java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAMVYa2wUxx2fO9vnR4yfwVAIBpsDlddtaB4oMm0Bg7HhjE+2" +
                                                              "g1rT5pjbm/Mt3ttddmfts1OXEKkBRSqKgpPSKvgTUR4iIaoaJWoV5KpVkyhN" +
                                                              "ETRK81CTVv2Q9IEUvsStaJv+Z2b39nG2aT/1pJvbm/m/5v/4zX/24nVUZZmo" +
                                                              "08BaFifopEGsRIo9p7BpkWy3ii1rGGbT8qN/PHti/re1J6MoNoIa8tjql7FF" +
                                                              "ehSiZq0RtEbRLIo1mViHCMkyjpRJLGKOY6ro2gharlh9BUNVZIX261nCCA5j" +
                                                              "M4maMaWmkrEp6XMEULQ2ya2RuDXS7jBBVxLVy7ox6TGsCjB0+9YYbcHTZ1HU" +
                                                              "lDyGx7FkU0WVkopFu4om2mLo6uSoqtMEKdLEMfUexxEHkveUuaHzpcbPbz6W" +
                                                              "b+JuaMWaplO+RWuQWLo6TrJJ1OjN7lNJwTqOvosqkug2HzFF8aSrVAKlEih1" +
                                                              "9+tRgfXLiGYXunW+HepKihkyM4iijqAQA5u44IhJcZtBQg119s6ZYbfrSrt1" +
                                                              "wx3a4hNbpJkfPND04wrUOIIaFW2ImSODERSUjIBDSSFDTGt3NkuyI6hZg4AP" +
                                                              "EVPBqjLlRLvFUkY1TG1IAdctbNI2iMl1er6CSMLeTFumulnaXo4nlfOvKqfi" +
                                                              "Udhrm7dXscMeNg8brFPAMDOHIfcclsoxRcvyPApylPYYPwgEwFpdIDSvl1RV" +
                                                              "ahgmUItIERVro9IQJJ82CqRVOqSgyXNtEaHM1waWx/AoSVO0MkyXEktAVcsd" +
                                                              "wVgoWh4m45IgSqtCUfLF5/qhnWce1Hq1KIqAzVkiq8z+24CpPcQ0SHLEJFAH" +
                                                              "grF+c/JJ3Pba6ShCQLw8RCxoXvnOjV1b2+feEDSrF6AZyBwjMk3LFzINV+/o" +
                                                              "3nRfBTOjxtAthQU/sHNeZSlnpatoANK0lSSyxYS7ODf4q28+9Dz5axTV9aGY" +
                                                              "rKt2AfKoWdYLhqIScz/RiIkpyfahWqJlu/l6H6qG56SiETE7kMtZhPahSpVP" +
                                                              "xXT+H1yUAxHMRXXwrGg53X02MM3z56KBEKqGL6qH71okPvyXIkPK6wUiYRlr" +
                                                              "iqZLKVNn+2cB5ZhDLHjOwqqhSxnI/7Ft2xM7JEu3TUhISTdHJQxZkSdiUaIm" +
                                                              "1iwZIMmUxsikJQ2CLEg0lXxl70EymWCZZ/wfdBaZH1onIhEI0R1hgFChtnp1" +
                                                              "FfjT8oy9Z9+NF9NvieRjBeN4kCKmOCEUJ7jihKc4wRQngopRJML13c4MEOkA" +
                                                              "wRwDWABcrt809O0DR093VkAeGhOVEAlGurHsnOr28MMF/bR88erg/JW3656P" +
                                                              "oihATAbOKe+wiAcOC3HWmbpMsoBWix0bLnRKix8UC9qB5s5NnDx84k5uhx//" +
                                                              "mcAqgC7GnmKoXVIRD9f9QnIbT336+aUnp3UPAQIHinsOlnEyYOkMRze8+bS8" +
                                                              "eR1+Of3adDyKKgGtAKEphooC8GsP6wgATJcL1mwvNbDhnG4WsMqWXISto3lT" +
                                                              "n/BmeNo1s2G5yECWDiEDOc5/dcg4/95v/nwX96R7JDT6zvIhQrt8MMSEtXDA" +
                                                              "afaya9gkBOh+fy519onrp47w1AKK9QspjLOxG+AHogMe/N4bx9//+KML70S9" +
                                                              "dKRwDtsZaGmKfC+3fwGfCHz/zb4MOtiEgJCWbgfH1pWAzGCaN3q2AaSpUB0s" +
                                                              "OeL3a5B8Sk7BGZWwWvhn44btL//tTJMItwozbrZsvbUAb/5Le9BDbz0w387F" +
                                                              "RGR2pHr+88gETrd6knebJp5kdhRPXlvzw9fxeUB8QFlLmSIcOBH3B+IBvJv7" +
                                                              "QuLjXaG1e9kQt/w5HiwjX+uTlh9757Nlhz+7fINbG+yd/HHvx0aXyCIRBVB2" +
                                                              "H3KGAJCz1TaDjSuKYMOKMOj0YisPwu6eO/StJnXuJqgdAbUyAKo1YAKCFQOp" +
                                                              "5FBXVX/w81+0Hb1agaI9qE7VcbYH84JDtZDpxMoDahaNr+8SdkzUwNDE/YHK" +
                                                              "PMScvnbhcO4rGJQHYOrVFT/Z+czsRzwLRdqtdtj5nw18/DIbtogkZY9biyXX" +
                                                              "8E9sCdcEZZpozWJtCG+hLjw8M5sdeHq7aBZagkf7PuhcX3j3X79OnPvDmwuc" +
                                                              "FrVUN7apZJyoPp0M4zvKML6fd2kePu24Nl/x4eMr68vhnUlqXwS8Ny8O3mEF" +
                                                              "rz/8l1XDX8sf/R9we23IUWGRz/VffHP/RvnxKG80BWSXNahBpi6/y0CpSaCj" +
                                                              "1ti22MwynvWdpdC2spDF4dvhhLYjnPUCYHmesKG7xMqjXbcEa6ioI06s2P+V" +
                                                              "cKXiWcva5YToDbmm4SWQ4BtsGKCoWbE4xFIFgOowVm3C0cEXf3ZZHLIzFk2Z" +
                                                              "SgGQfdxpZS+1zR//ZfXUXrdNXYhFUB60+q/8tPeTNI9lDUuWkgd9ibLbHPWd" +
                                                              "SE1s2Mbyf9MSV8OgRdJ0y8djT336grAo3ImHiMnpmUe/SJyZEXUhrivry24M" +
                                                              "fh5xZQlZ17GUFs7R88ml6Z89O30q6nh+P0XVGV1XCdbKwsma85AfhbWx7ef/" +
                                                              "ceKR9wagH+hDNbamHLdJXzaYndWWnfE51rvjeLnq2M2ORYoimw0HwXawISWe" +
                                                              "u/47qGQTu4oUNQQbSgahK8tut+JGJr8421izYvb+3/GmpnRrqoecyNmq6tuJ" +
                                                              "f1cxwyQ5hVtfL04Zg/8UKFp3q26XQmDhh1uvCjaAvdVLsFEAltIfPx97bxHm" +
                                                              "o6iK//rpxkGCRwcNinjwk0xSVAEk7HHKcCv4zqX2Muw8wj24F67aVhw8XYyU" +
                                                              "Hz47RBt3izj6zpb1gdriLy/c1LPF6wuo89kDhx68ce/Tou+TVTw1xS+7kHCi" +
                                                              "uywBcMei0lxZsd5NNxteqt3g1kKg7/TbxtMLKoL3aKtCjZAVL/VD71/Yefnt" +
                                                              "07FrUMVHUART1HrE9+pAYCF0UzacDkeSC5UWHE+8R+uq+9PRK3//INLCD3an" +
                                                              "GNuX4kjLZy9/mMoZxo+iqLYPVUGpk+IIqlOsvZMaVMW4GajUWEa3tdJ7jgaW" +
                                                              "/Zi92OCecRy6rDTLrgQUdZbjUfk1CXqeCWLuYdKdyg8cWbZh+Fe5Z4mAAdEZ" +
                                                              "V6ST/YbhdMo173LPGwYv8O+zIfcfIt9+UqEUAAA=");
    public static final java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    public static final long jlc$SourceLastModified$jl5 =
      1445630120000L;
    public static final java.lang.String jlc$ClassType$jl5 =
      ("H4sIAAAAAAAAAMU5a6zjWHmeOztPlp3ZXVi2y75md6BdAtdx3tEA3cRxYsd2" +
       "HnbsOC5l8NuOn7Gd2And8qgKtLQUtQulEuwvUFu0PFQVtVJFtVXVAgJVokJ9" +
       "SQVUVSotRWJ/lFalLT127r25987MrlB/NFJOTs75vu98b3/n8/Pfg85FIVQI" +
       "fGdtOH68r6Xx/typ7sfrQIv2+1R1JIWRpqKOFEUTsHZTeeLzV37www+bV/eg" +
       "8yJ0v+R5fizFlu9FjBb5zkpTKejKbhVzNDeKoavUXFpJ8DK2HJiyovgGBb3i" +
       "GGoMXacOWYABCzBgAc5ZgFs7KID0Ss1bumiGIXlxtIB+HjpDQecDJWMvhq6d" +
       "JBJIoeQekBnlEgAKF7P/PBAqR05D6PEj2bcy3yLwRwrws7/59qu/dxa6IkJX" +
       "LI/N2FEAEzE4RITudjVX1sKopaqaKkL3epqmslpoSY61yfkWofsiy/CkeBlq" +
       "R0rKFpeBFuZn7jR3t5LJFi6V2A+PxNMtzVEP/53THckAsj6wk3UrYTdbBwJe" +
       "tgBjoS4p2iHKXbblqTH02GmMIxmvkwAAoF5wtdj0j466y5PAAnTf1naO5Bkw" +
       "G4eWZwDQc/4SnBJDD92RaKbrQFJsydBuxtCDp+FG2y0AdSlXRIYSQ68+DZZT" +
       "AlZ66JSVjtnne4M3f+idHu7t5TyrmuJk/F8ESI+eQmI0XQs1T9G2iHe/gfqo" +
       "9MAXP7AHQQD41aeAtzB/8HMvPv3GR1/48hbmtbeBGcpzTYlvKp+U7/n6w+hT" +
       "zbMZGxcDP7Iy45+QPHf/0cHOjTQAkffAEcVsc/9w8wXmz2fv/rT23T3oMgGd" +
       "V3xn6QI/ulfx3cBytLCneVooxZpKQJc0T0XzfQK6AOaU5Wnb1aGuR1pMQHc5" +
       "+dJ5P/8PVKQDEpmKLoC55en+4TyQYjOfpwEEQRfAF7obfB+Dtp/8N4YC2PRd" +
       "DZYUybM8Hx6FfiZ/ZlBPleBYi8BcBbuBD8vA/+03Ift1OPKXIXBI2A8NWAJe" +
       "YWrbTTgOJS9SfFULYVtbRzADaAFHc7RSh9TW+5nnBf8PZ6aZHq4mZ84AEz18" +
       "OkE4ILZw3wH4N5Vnl23sxc/e/OreUcAcaDCGsoP3twfv5wfv7w7ezw7eP3kw" +
       "dOZMft6rMga27gCMaYO0ABLm3U+xP9t/xweeOAv8MEjuApbIQOE75210l0iI" +
       "PF0qwJuhFz6WvId/V3EP2juZgDOmwdLlDH2Upc2j9Hj9dODdju6V93/nB5/7" +
       "6DP+LgRPZPSDzHArZhbZT5xWb+grmgpy5Y78Gx6XvnDzi89c34PuAukCpMhY" +
       "Ai4Nss+jp884EeE3DrNlJss5ILDuh67kZFuHKe5ybIZ+slvJ7X5PPr8X6LgJ" +
       "HQwnYiDbvT/Ixldt/SQz2ikp8mz8Fjb4xN/8xT+Xc3UfJu4rxx6FrBbfOJYs" +
       "MmJX8rRw784HJqGmAbi//9joNz7yvff/TO4AAOLJ2x14PRtRkCSACYGaf/HL" +
       "i7/91jc/+Y29ndPE4Gm5lB1LSbdC/gh8zoDv/2TfTLhsYRvo96EH2ebxo3QT" +
       "ZCe/fscbSDwO8OHMg65znuurlm5JsqNlHvtfV16HfOFfP3R16xMOWDl0qTe+" +
       "PIHd+k+0oXd/9e3//mhO5oySPfh2+tuBbbPp/TvKrTCU1hkf6Xv+8pHf+pL0" +
       "CZCXQS6MrI2Wpzco1weUG7CY66KQj/CpvVI2PBYdD4STsXasQLmpfPgb338l" +
       "//0/fjHn9mSFc9zutBTc2LpaNjyeAvKvOR31uBSZAK7ywuBtV50XfggoioCi" +
       "AjJaNAxBCklPeMkB9LkLf/cnf/rAO75+FtrrQpcdX1K7Uh5w0CXg6VpkgrSV" +
       "Bj/99Nabk4tguJqLCt0i/NZBHsz/nQUMPnXnXNPNCpRduD74n0NHfu8//Mct" +
       "SsizzG2ey6fwRfj5jz+EvvW7Of4u3DPsR9Nb8zEo5na4pU+7/7b3xPk/24Mu" +
       "iNBV5aBS5CVnmQWRCKqj6LB8BNXkif2Tlc72sX7jKJ09fDrVHDv2dKLZPQfA" +
       "PIPO5pd3Bn8qPQMC8Vxpv75fzP4/nSNey8fr2fCTW61n058CERvlFSfA0C1P" +
       "cnI6T8XAYxzl+mGM8qACBSq+PnfqOZlXg5o7945MmP1t2bbNVdlY3nKRz2t3" +
       "9IYbh7wC69+zI0b5oAL84D9++Gu/9uS3gIn60LlVpj5gmWMnDpZZUfy+5z/y" +
       "yCue/fYH8wQEss/oo9jVpzOq5EtJnA2dbMAORX0oE5XNn+eUFMV0nic0NZf2" +
       "JT1zFFouSK2rg4oPfua+b9kf/85nttXcaTc8Bax94Nlf/tH+h57dO1ZDP3lL" +
       "GXscZ1tH50y/8kDDIXTtpU7JMbr/9Lln/uh3nnn/lqv7TlaEGLjwfOav/vtr" +
       "+x/79lduU2Tc5fj/B8PGdz+MVyKidfih+ZlUSrg0LenD5spjKms94VtEO4g6" +
       "jqrGUrvi026xbdRxc44VSgYSTqrBXHZhOi7Hsaq6ehwhQwEj7TbDLkgjGLHk" +
       "yphwTMUiJF/qT32+Sga8vTYH2IQhGwg64VelcZPAuFUE7lX9VUEsyeWm1ytJ" +
       "ExgJ+itA24WrK7iyEeBSxeM5UXT9YqMtdS3dD7BexBB+M6i3A3u6LlsWEvZ6" +
       "8qSxGMAjPLbgUEP6Ndof+ITUiOcLp97taiZriYsiE2MyQxE+4vIWjtL2eh4w" +
       "fapHDme10C8ZphQ6ZrPNDXiREEo1xEPRVnVOV1yJlqauHWJBTaAxjhqX1lKJ" +
       "WXYEtj5vt/mU4td1P61NehE6bxcLzdlMVvCJiOCc01n30nrX5opT3vaD7rLi" +
       "uyWX8mtL1l/ENEaqFEbrnJamGG6vNG4p4ZtAkUfypjaVC/2lRE+lwBkWmOly" +
       "PAVok7DfR4bzQd0Z9JPJYrjyo4W9NEr4ptttSGzIt0gHs0ykWYgZQxcoqzcT" +
       "lt60gGsBaZn2mq5Y1nzRGreqy0qFMPuKGLfHBoI0o5o4k/WQDWMkSctSxRzI" +
       "Qd/WR4NOsZKE3JAgpO60RLjssIMxLDcn2h2W7XYmvbg8sJdromaKRqU1wvhR" +
       "ezGnHIZadTl7hkx6CNFSlVgeECWLdhAtrKEsTWmT7tJdOp4k+BXP0YcrcqFb" +
       "nGqGbl0VIoXWBkZDDrujFt0Z4oSuKE7kp4yyWo9awdoZzWajxMCSbqASHXbl" +
       "IAwvmYbLETGBMXzoN4lxv98ooQuGHy5YYy0MYkzCaSSRpinc8ll+WASmFzA7" +
       "bvFKpCa84U/NilupEga7iFFOp7pVeGF6U0VD8AVCEovWhretRWNTKFXQYKSM" +
       "iyxOYf1uCzfCbkGB+/3ySJZqrImOqaTBoKkvrLzhnEfkUkHXsA4bdmstcd1O" +
       "5rRdprobYsAXYL/sMXp7MpyncSs2xxwc4QNNZB0PXMj81oAsOiy7TmdsfdjR" +
       "K4tSo9DsbKpSOuGbUm8WknGppZP+VJ1R5oJglQ3MWIQdrHXJnC76zhJ2anht" +
       "0avWWAubYHWbjkVzJJlswI9SYVLAkTXXSnGaEYQk7BnVslAs0XR5U62RbYxc" +
       "9KjaAq8jvj1arQXCHpG1hLNmjBNaC5Ei+YFXKCntqmh2KHw+TBYLk009Aq53" +
       "41JK1/vYsjzhTIKdqHh/nIo2q1qcRLiIlYgE7XJpZNn9cQmlMKPoCKlTL2Jr" +
       "d4qKIpzoalsSccT3CBMjigxiGl3UjL0A6erzScNfN8VmYdBtDlaWxszb2qBi" +
       "o6Q7RDGuX59bJqlUEmbsGT4IappCykqFxoZ2K2GSzrTVVsK4UWwOix2m2Czz" +
       "dkvrmUMeazm9ZYhH3jAsNWi6C8tMo6GBq2N/Wq5VayPfMluTljwktUJitZQh" +
       "WsanrhzQkd+eWmlRpjyGtNIGhzYX7WpUHXidtFGxq0szhWFXaS0MtN7zXNIX" +
       "eILpNPXm2CPkSblcK0icF5S5UWtM4JYXDR0PW8+GNs1stEZBZhsagxSGellS" +
       "O2uSNHpxi8QC0/fRRi8a1RKjNekrFOImq4HcMb1eZRrRi6lAsLFfdiYe3Ha1" +
       "gY9EpV51jaHTjoV1hkoVVhWjAjdBVvUSoVlj6v3OpLZZEeYYKIamWSwWOi1J" +
       "l9ZS07DbQ7Ogr6tI0/fCoFJPkBZJNsdRMKeGaa/Qwn2D1uBBRU6bMFwgaape" +
       "ZJsqCRQdR6LUc0kdLZT1pKej+AbeyBV6GFuY0UensqHjSDBtbXqoNCgvSi2J" +
       "Dbh2MRpqVFmqthusXW/3xGkyXZlepSLHFAzHkz5NxIm/kUMxWslcS4arlNZs" +
       "d+RNMSk36l2mx5QCPCw0GgY2CdWa7WlyP6jaqsmMBGe1SZp6qnHtxrjrUC5L" +
       "KMM2Xm4XiPaqv6qPl9RckHqI1rTHMZxUcSuZC4XlBDwG6tX6wDE3hbpODORe" +
       "Ya3COL5Ki5KwRgmmzbdLeJnstfroBplInTm7JGf0kKSH8+LMikbJsqYNYTbu" +
       "e8KyvzDUlsytW6SPzFok2h0Pg2q3LfACnDSQQhGXEcmQiOYCq/OKPMMblX4n" +
       "FjtBSvsdyZQGQDJWtTdcMuhg8AwnRzSrrDzZVIaVsNcf47NhyHcnsFhQNhGz" +
       "SShGXcRqPK96CdKAO4Qc+4YtzpqytRaEBtaMUFXBRDHwN9N+jPYKJjVPGnQ1" +
       "UjV8UZfaomTYen20NBWhPC8L9ebQG606brJUuiHPDepSIPbX/igo0pXNCli+" +
       "pqslWxstS5WBA6cVjQ5rDWA8zlkICdsYrBvDsot1ww3ccBChIzQiHWaaiVYq" +
       "E9y0x2xgXtfxEcysvJTsNYrtKSsMJLMdWDV4XUQDVkLnSGyVSnSy9lZTNVDR" +
       "UhR0uhV1ZZrUbO6NOHSGu1pE9uopvZgLsoJJNcsnirWoNCrwCilYU2UlVWcT" +
       "vyO7boWdjivtOOqRqD+VsUraJbrG0E94t4wWFUzQy6KIU8Sma5dE1uiNdXBv" +
       "EtkCsmFgWNQFTgjVgTAzu1y7Viws4EY80iYDoul0uOXUNtSmJVMyPpqqLAbC" +
       "j5bXepNm+cbQYNR+cd1Q51nsG2HLLxMubtFe4HIazPbXIiZwZmitwnWpQutm" +
       "NRXHjojUe1w3qoOE5Do1sdEclouLmmcWRkWB7/GIgKoymUSu1Ki2dFOepnVN" +
       "hxWNBNqVDLxgdgay5OKU2hc20sxTp1NPx6pIuJprlLco0aUhM/MtNyniiSAl" +
       "BDvVlnClvuiNJ6BG4Qbjscwakkk24mVc6Pf6YaNSQqzNbCUXynDPDTwmXPia" +
       "sh64i1q87OuIkibrcdXkY50qVkQDbnBkNwARXhPGbsc0keUKnUutlcpTURdk" +
       "3ZjQR2mzLqe469csEobDILV7KJMoA8ubJ3YxZfkWZtdxnFTQVWWzEEr0Mmkk" +
       "81KlW6tLvJk0hNmawzeVOtOOy9ZmXtsEMmKooUWtYQWhRt1asvQbTbtjprWG" +
       "osETf1mY8JMESdlC3cZRa7lO2qDUsIpOKkZqdTBIY20Rlw3EJo06PJHTmKZI" +
       "H+QlMkbnYounYL5TR+CZpntxsd4NOZrHuRYzQfAQaxaC1gztFrmNpHRsjUWr" +
       "3BTHCg2msFwUmiOGLMMwMaDQTlnyeoOlULHnlLhuwi7ti6lfsBbUbMRzvcAu" +
       "EMTCGUYrkZZ4elrpSXNuiknlWAVPOEOawqLVLA1RTWHWtbAzoUJjzKmiPOd0" +
       "G0GFhYZOqeVMJdW10VCmsmgWulpVrLitloqJfI2dwDPZVGkfqZepUS+ZrRrD" +
       "wgbUVzoRNwvcAuPAbeAt2TXhbT/eTe3e/FJ69GIBXNCyjd6PcUPZbl3Lhtcd" +
       "NeLyz/mXaMQda1ZA2a3rkTu9L8hvXJ9877PPqcNPIXsHTZ5pDF2K/eBNjrbS" +
       "nGOkspvvG+58u6Tz1yW75sOX3vsvD03ear7jx2ivPnaKz9Mkf5d+/iu91yu/" +
       "vgedPWpF3PIi5yTSjZMNiMuhFi9Db3KiDfHIkWbvzzR2HXyvHWj22u1bnLf1" +
       "gjO5F2xtf6qHduZAgbc2I7adlRwpfInG2yobXOBRWcfGBaWwJTta3qjJwZlj" +
       "fsTH0AXZ9x1N8nY+5r3cLfhEsyuG7jnZjc/aiQ/e8mpw+zpL+exzVy6+5jnu" +
       "r/OG9NErp0sUdFFfOs7x7s+x+fkg1HQrl+3SthcU5D/vjqHHX+5VAbjoZz85" +
       "3+/aov1CDL32JdBi4G1Hf47jvQ8Y4zReDJ3Lf4/D/RKgsIOLofPbyXGQX4mh" +
       "swAkm/5qcGjp4kvJMjmYWp4Bqt04ug40nZ45GbxHFrzv5Sx4LN6fPBGl+Zvf" +
       "w4habt/93lQ+91x/8M4Xa5/atuMVR9psMioXKejC9s3AUVReuyO1Q1rn8ad+" +
       "eM/nL73uMIPcs2V4FyvHeHvs9v1uzA3ivEO9+cPX/P6bf/u5b+Zdsv8Fx7No" +
       "8ZIfAAA=");
}
