package org.apache.batik.bridge;
public interface GenericBridge extends org.apache.batik.bridge.Bridge {
    void handleElement(org.apache.batik.bridge.BridgeContext ctx, org.w3c.dom.Element e);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1Xe2wcxRmfu/MbO36E2GlCnNclwgFuFQFF1KEldmPs9Bxf" +
                                          "44CETbnM7c75Nt7bnczO2mfTlIfUEoEUIWIKVI3/CiogXkJFIFVEqZB4iBZE" +
                                          "iloeKrTqH31GIv80rdKWfjOze7u39qX/1dKNZ2e++eZ7/7557jxqdBnaRrFt" +
                                          "4AxfoMTN5MQ8h5lLjGELu+4hWM3rD/3+5L0Xf9V6fxI1TaE1JeyO69glIyax" +
                                          "DHcKbTJtl2NbJ+4BQgxxIseIS9gc5qZjT6F1pjtWppapm3zcMYgguAOzLOrG" +
                                          "nDOz4HEy5jPgaHNWSqNJabS9cYLBLGrXHboQHthQc2A4sidoy+F9Lkdd2SN4" +
                                          "DmseNy0ta7p8sMLQNdSxFmYsh2dIhWeOWDf6htifvXGFGba91Pn3S4+UuqQZ" +
                                          "1mLbdrhU0T1IXMeaI0YWdYar+yxSdo+i76FUFl0RIeYonQ0u1eBSDS4N9A2p" +
                                          "QPoOYnvlYUeqwwNOTVQXAnG0tZYJxQyXfTY5KTNwaOG+7vIwaLulqm3g7piK" +
                                          "j12jLT1+d9fLKdQ5hTpNe1KIo4MQHC6ZAoOScoEwd69hEGMKddvg8EnCTGyZ" +
                                          "i763e1xzxsbcgxAIzCIWPUqYvDO0FXgSdGOezh1WVa8og8r/aixaeAZ07Q11" +
                                          "VRqOiHVQsM0EwVgRQ+z5RxpmTduQcVR7oqpj+ltAAEeby4SXnOpVDTaGBdSj" +
                                          "QsTC9ow2CcFnzwBpowMhyGSs1WEqbE2xPotnSJ6j9XG6nNoCqlZpCHGEo3Vx" +
                                          "MskJvLQh5qWIf84f2HPiHnvUTqIEyGwQ3RLyXwGH+mOHDpIiYQTyQB1s35X9" +
                                          "Ie59/XgSISBeFyNWNK9+98Kt1/affVvRbFyFZqJwhOg8r58urPngquGBm1NC" +
                                          "jBbquKZwfo3mMsty/s5ghUKl6a1yFJuZYPPswTfvvO9Z8tckahtDTbpjeWWI" +
                                          "o27dKVPTIuw2YhOGOTHGUCuxjWG5P4aaYZ41baJWJ4pFl/Ax1GDJpSZHfoOJ" +
                                          "isBCmKgN5qZddII5xbwk5xWKEGqGH0rAbwCpv81i4KiolZwy0bCObdN2tBxz" +
                                          "hP7CobLmEBfmBuxSRytA/M9etztzk+Y6HoOA1Bw2o2GIihJRm1qBmcYM0aRC" +
                                          "pj4kvzIi3uj/7aaK0HntfCIB7rgqXgwsyKNRxzIIy+tL3tC+Cy/k31WBJpLD" +
                                          "txZHO+C6jLouI6/LqOsyNdehRELecqW4Vjkc3DULiQ+Vt31g8jv7Dx/floJI" +
                                          "o/MNwtgVmYkbgw84GBNP5vwtk/TUR+/9+fokSobloTNS1ycJH4yEpODZI4Ov" +
                                          "O5TjECME6H77RO7kY+cfnJZCAMX21S5Mi3EYQhHqK9Sp77999OPPPzv9YbIq" +
                                          "eIpDTfYKAG8cteACFDSsc45aq5VJKXbll/CXgN9/xE/oKBZUlPUM+6G+pRrr" +
                                          "lEbMkZDz9Rz117O8Mrmw2qZ6tUPWvdMPLC0bE0/tVhneU5uP+wBunv/1v3+R" +
                                          "eeJ376zi9lbu0OssMkesGtEY2rqigRiXpTUA4rx+07mLqU8fXd8uvdZegN4h" +
                                          "BPB0DYCr/oM5OjEAQepBeQBnu+qDd1yEtx74y4ZDXy8dliJE4VjwagQkESdz" +
                                          "AkSr3DfHTBln+cz4c+/ctlN/NCnxQ9TiVXCn9tBg1KhwKSMAlLZQS6x0VEQ3" +
                                          "FkvKuC3y+q4t+JX868fSSdQAgAIgyjEUPcCn/vjlNRgwGCSMuKoFjFB0WBlb" +
                                          "YisAwTZeYs58uCKrRbeKX3C2TM0b4He1XyXlf7HbS8XYp6qLpO+X41YxpGWk" +
                                          "JMV0hxh2SrKrIXJ2hjkJZd2Cgic8kr7dBmebRRMXLCKqxb86d+x+5W8nulRQ" +
                                          "WrASuOja/80gXP/KELrv3bsv9ks2CV20FWHdCMkUVq0NOe9lDC8IOSr3n9v0" +
                                          "5Fv4FKAeII1rLhIJHkmlX5CkdcujSlK/lwqo1wrq+ev1jOGUM6JlJDaX9hmS" +
                                          "FLfIca+ws18ZxfeoGG7mqKME6WIR/xhIPXCZbpaZZSiJc34/oB3r+Xz2x396" +
                                          "XlWCePMQIybHlx76MnNiSTlAdVjbVzQ50TOqy5LCdklvV2ShuMwt8sTIH188" +
                                          "9rOnjz2Y9BXNcNQw55gGHE7XUS3SM+f1Rz78ouOOL85ckILWNt1RkBjHVMnW" +
                                          "LYavCdn64jA1it0S0N1w9sBdXdbZS8BxCjjqALfuBAOIrNRAik/d2PzJz9/o" +
                                          "PfxBCiVHUJvlYGMEi/YWmhRILeKWAF0r9Bu3qvSZb4GhS3oVrfCzCMLNq4f3" +
                                          "vjLlMiAXX+v76Z6fLH8m0agC8VCDwILD+hUNv2pS9ReWO1v6lm//jSwi1Uay" +
                                          "HaCz6FlWpEZF61UTZaRoSsu1K/tR+e8ujvrqRD2go5pIBacVPfTIXXF6jhrl" +
                                          "/yhdgaO2kA5YqUmUBFZTQCKmRUoridouQnx8Wwzr1PxQXdNHGo/tNZEmH1YB" +
                                          "AnjqaZXXX1zef+CeC199SvUh8CRbXJSNOLwrVFmtosjWutwCXk2jA5fWvNS6" +
                                          "Iwj6biVwWEs3RlL/TsBcKjy7IVag3HS1Tn18es+ZXx5vOgcxO40SGIrMdORZ" +
                                          "o3p4qHIeBNh0Ngrekee5rJ2DbX84/P4/Pkn0yADz4b7/cify+skzn+bAEz9K" +
                                          "otYx1Ag5TSpT8E5zv7lgHyT6HKRCi2ebRz0yBk/ApoLj2dU32BoRhlg8uqRl" +
                                          "fIN2VFcFFnK0bWXhWdkuQO7NEzYkuEtkjeGuR2l0tyLeJqtoBb7Zfeqf9/7g" +
                                          "owlIkxrBo9yaXa9QhfDoE0/xjtRA1e6l8tlxSv32L/Gw9CqlEkFVlM4pakHB" +
                                          "UWIXpf8Fos53p6oRAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05aazsVnl+9+0vy3tJIEkDSUh4QQTD9Xj20WMbezwznvHY" +
                                          "M+NZPG7Li5fjbTzePfYMDYJIlKhIFLWBUgnyC9QWhUVVUStVVKmqFhCoEhXq" +
                                          "JhVQVakLRSI/uqi0pceeu7378oj406trz/E5374dn88v/RA5HwYI6rn2Rrfd" +
                                          "aB+k0b5lV/ajjQfC/R5TGUpBCFTSlsJwAuduKk9++eq///jjxrU95IKIPCA5" +
                                          "jhtJkek64RiErr0GKoNcPZ6lbLAKI+QaY0lrCYsj08YYM4xuMMhdJ1Aj5Dpz" +
                                          "KAIGRcCgCFguAtY8hoJI9wAnXpEZhuREoY98ADnDIBc8JRMvQp64lYgnBdLq" +
                                          "gMww1wBSuJQ9z6BSOXIaIG860n2n820KfwLFXviN91373bPIVRG5ajp8Jo4C" +
                                          "hYggExG5ewVWMgjCpqoCVUTucwBQeRCYkm1uc7lF5P7Q1B0pigNwZKRsMvZA" +
                                          "kPM8ttzdSqZbECuRGxypp5nAVg+fzmu2pENdHzzWdadhO5uHCl4xoWCBJing" +
                                          "EOXc0nTUCHn8NMaRjtf7EACiXlyByHCPWJ1zJDiB3L/znS05OsZHgenoEPS8" +
                                          "G0MuEfLIHYlmtvYkZSnp4GaEPHwabrhbglCXc0NkKBHy+tNgOSXopUdOeemE" +
                                          "f37IvvNj73e6zl4uswoUO5P/EkR67BTSGGggAI4Cdoh3v435pPTgV5/fQxAI" +
                                          "/PpTwDuY3/+lV9779sde/voO5g2vAsPJFlCim8pn5Xu//Uby6cbZTIxLnhua" +
                                          "mfNv0TwP/+HByo3Ug5n34BHFbHH/cPHl8Z8tPvh58IM95AqNXFBcO17BOLpP" +
                                          "cVeeaYOgAxwQSBFQaeQycFQyX6eRi3DMmA7YzXKaFoKIRs7Z+dQFN3+GJtIg" +
                                          "icxEF+HYdDT3cOxJkZGPUw9BkIvwQs7A62lk9/d4dosQDTPcFcAkRXJMx8WG" +
                                          "gZvpnznUUSUsAiEcq3DVczEZxv/yHfh+DQvdOIABibmBjkkwKgywW8TkwFR1" +
                                          "gOUKmQqRP+1n8eb9v3FKM52vJWfOQHe88XQxsGEedV1bBcFN5YWYoF754s1v" +
                                          "7h0lx4G1IuQpyG5/x24/Z7e/Y7d/CzvkzJmcy+sytjuHQ3ctYeLDknj30/wv" +
                                          "9p55/smzMNK85Fxm7DTPxIfzh7MQ7+k7l+l2ViPovC4qMGwf/i/Olp/7+//M" +
                                          "RT1ZaTOCe6+SGqfwReylTz9CvvsHOf5lWJQiCQYRzPfHTifoLTmVZeppE8Ja" +
                                          "e0y3+PnVv+09eeFP95CLInJNOSjkM8mOAQ9gMb1ihofVHRb7W9ZvLUS7rLtx" +
                                          "kPAR8sbTcp1ge+OwambKnz/pOjjOoLPxlTwM7s1h7vsJ/DsDr//NrswT2cQu" +
                                          "/O8nD3LwTUdJ6HnpmTMRcr64X9svZPhPZD4+beBMgHfx3mf++s//ubSH7B1X" +
                                          "8qsn9kZohBsnqkdG7GpeJ+47DplJADJj/d2nhr/+iR9+5OfzeIEQb341htez" +
                                          "eyYx3ArhlvLhr/t/873vfvY7e0cxdjaC22cs26YCB2G+s0FNNNOR7NwgT0bI" +
                                          "Q5atXD/UegZ3OijYdcuu5aZ6Pdzbc9Eyr+zvtoc8n6BE1+8Qrie29JvKx7/z" +
                                          "o3tmP/qjV26L1FsNM5C8GzsP5VKlkPxDp7OoK4UGhCu/zP7CNfvlH0OKIqSo" +
                                          "wGoQcgHM4PQWMx5An7/4t3/8Jw8+8+2zyF4buWK7ktqWst0X1tDIgBu2AZM/" +
                                          "9d7z3l0NTC7B27U8N5Fc/zfsxMnT+t5jQzAu3CU/+g8f/9avvvl7UI4ecn6d" +
                                          "xTCU4IS12Dh7cfjllz7x6F0vfP+juU9gxR1+krr23oxqPWfwVH5/a3ZDdx7L" +
                                          "hm/Pbu/IbvuHbnokcxOfVz9GCqOBq5rwxUHNPfVTS8cwMFcw2tYHuyL27P3f" +
                                          "W376n76w2/FO14lTwOD5F37lJ/sfe2HvxHvGm2/b6k/i7N41cqHvOXLlEz+N" +
                                          "S47R/scvPfuHv/3sR3ZS3X/rrknBl8Iv/OX/fGv/U9//xqsU53O2exiU2b14" +
                                          "wDb7qby2Y6O7Hu6WQ7p5+MfgAigmSjpeaTE2kLlSlSp2bNJhFTvR23F71G7j" +
                                          "fcpWV8OwQaRauUxSE9kZ1JRahY1qsqNsueJKm9i0NqVcakrP6f6MLmGk6erC" +
                                          "stem2zPKF4mySYiUabugH0z8bgnv0Ot6IVD7c83itqAWlxq+gOFqnxWLAEWB" +
                                          "WMNqlUrNSn2VcKRx0I7KzVRzBxO2MhjVjYrNWB2KidGyMR+UghZWQitMQdAa" +
                                          "s6qW0vhEovAe2HDVhm7TGyltdZW+POlFdpGVe2iZGOlpSoeA5hu6UvFFa1Jt" +
                                          "454VzT1P8lalrTJY6Hrc5LYMF3ScFrctd6lNxRrqUped8z7bk2S+oSwYgukE" +
                                          "Qld2R93IGCnFZjk0VXeDthvMUlWLPFturULAbgqRVPPq4YAZsSqftleL0Ciq" +
                                          "tDEH3LylVY3I1NZCp92RpQY+dEp8GZ3G/kjEV4ysBsa0MMFpYQAkurCYqwsp" +
                                          "QDcpr7qoWau2p227MKbBwnVGhRgHBN/iy2yjWfRGQ5dbOGt7MQV+krDcZDYS" +
                                          "mk6nEImLXjraCNpkUelP2ETiOmhtTScSE9v+qqTXPLNv4UWLmeCo2tCYvjqq" +
                                          "GBOPBXifdsuDUZesik2X4xWXStRqw6A6g76qrvU65ZCTzkaEQpUAnm7TUFb0" +
                                          "tElvSXo+nPqLdYsrtAWdVzsc2Br4fCbVXb0eYJKZSqApFmojHJ+Nfc7szkbh" +
                                          "oEAlM308QreVceqtJmo8Umbjmut7FmpHzSYF5E2ZFxzOm7UmUodQeWsUTsiG" +
                                          "mxRJpe1sE8Jzk4Gx6fAhPqd8mSqmQzdy+F7VagidqsO6pG+LHtntUG5plg7C" +
                                          "ZW/NjIyKP6e1elkrdodm11lPJz5NbTrJqDRmNkLS6aIrrtvyaHMxmmxGBB6W" +
                                          "KkKDBpUGBvWieQK0N+yc7TfQRr0f4ZikabP1WG5v2qLfSwwOalupx8EQ5m3c" +
                                          "IVY4S1qE7Md9MdHc0moQRhssrOjGtG9XJXzT7sXiYjgMk4m2XnMNsR7Bs4UR" +
                                          "tSayZ4H5nHaLNbU/G07oOCkuDK7DTbqdKRmn1rxTGZYlaSGWcVnqzXtlr21j" +
                                          "zRTvtHoeL3Y1l+uZIUGu+joL415VabqSysmyks77VMfvdAtBU05Ib13HzXLf" +
                                          "dG0x2RRkkpNVthgR6dYY1khXZlYUoa2IOOXHm6iJDRog2kbbJbqodl2uiRNJ" +
                                          "0S12aNPojVe4T6yUxaAgjUnPKi/XW9osxRZWk6R+oetEGkkTtUD3BT0JN312" +
                                          "nG5peoNGTCkiUXKDLUv4nOh5TCtKxS6HklWLcWO6ijE+F25YFRhjigGKPy/P" +
                                          "rKVSak0Zc4TOohKu1611rZVimu32aBcbsEmkz1aLpawn9XKHYIeVdRItscl0" +
                                          "jGINVHOXvCvb7oTl8Y3S65Y3lMe1RLrMrbnKxKLIAVXt1mpjrrZcoIrm9ESy" +
                                          "ORCKOF8ZmCVqMTK6fr/Be7Vao9HghsPhdt1YyLQPaK810Rb9ZqeuRKBJtlt8" +
                                          "qJQrkl+Z9fqCbNsYKehsA0spzO0T4tQeTgdotYN64yCwKXmwFFvbxniL4zWu" +
                                          "PghWSdEXq9F0OF+rgyFDFmSqgEUzwwHTSjxEEyJ21hi+LqFjAHqlWnVrNmw5" +
                                          "LnBhOFiCsBNRi2Lgm/rYFLzJtFkOUrRQWzH+tK4Jaj1eqyLQ2bJBDIlCa0EG" +
                                          "mDuocBbVHAGPACPCiVG/peIbKkpr5U1ZbAmbumqbPQoaPpH00ZLi1W1zyQel" +
                                          "ltadELaDKtuygmJKZLMYSzrpqDExZwLpNCJCx/tG0ucHTZsRR3w1LcyoUam9" +
                                          "XPdjsrRB/XKE9oR6ta7xvDpq6k1a31jUdKiQDra2bHasJx2SH8R9t221icKc" +
                                          "sOWFGTaTiQgWIUwwsh+MZdAXSmRxMijI5S7AhY1ga7WuzNeFhVf1GY9DhTK+" +
                                          "SL3OfNkbzApGahT5oB/QQq9oWMueqBZJ3VTqy6CmEisgj8cDgSH7firXqyqa" +
                                          "opV53Ynt8WgeNPmYsySsXtCFIdanmGBdksN1YxkWyVmx0J53VXKwnM78AsuB" +
                                          "ht0i6zQHTeQ01oVKe11u95uApvGAMehed7myhQq5VJXY4u0+Zie+iyeBj4I1" +
                                          "bnGd6aDas3stSWgYK77NaLQioUmI18VUA26nU1v5fRijc3qMpQY9FEhR9iRR" +
                                          "5M2eUipjLlEKUGFbTEuNqmDPSTAcjOiN3LXTWnXgsCY/sZvqzJJn21GlMOH8" +
                                          "TYUh1aW9nhV5Ix4kUT2c0F28Xm8EnGNti4sGIbAKO0oqFb3TpWrClC/xA1TD" +
                                          "x9ta3Y05jqlXlCXNzNkIHy8JqzsbOHNmIa1J1amWrSZuRgW+wOJJIyRUQZVF" +
                                          "vk6kpGX5TUaLiSZHB+y4CU+3anG47W0bmDvUUoI0Z91pD+5nnQFlYov5yhjT" +
                                          "DOjPm+1C0CDikr/mRbncMfiSOws0cksOGNYva6W1xdgDsykI6LpWFasa062v" +
                                          "CvD8UJ+RrYRmWqgxZddFj2+MwZzD11V7hWEWn5j4VNp0JXJbbdtzjxLbVXw6" +
                                          "EaWxy4cx3seiMQrqsbUO/HGrqLsVjyYkZTbUJrQgtKuWEdjYxlB1iSsum5WF" +
                                          "P11NibY4GZH91XjqwnOzG4+ctD5PtgE+TEeCynY7LhaxIrXq4gui6Vi+JAqC" +
                                          "gG+BhpKAxBsNfj016uRYFno8yzFJMGuvIje05nGUkMKyaDUr2nzN8lU6saqy" +
                                          "OUvmVFga2ww2CQmlb21q9EzSS10enzh4HYSoKKSVNacrKVcu8B06GKjcWHRL" +
                                          "Xtnv0oBgjQKrB2AJQCXoFVuyUC9jQ/i/dAqbZmtblmuYYmobNFxuHVRuUttG" +
                                          "340WKd7UKxPem9SpynZds/XuZlLt9sekWYQ5tC1siCXW9FzGKqrTUpFwx4at" +
                                          "12N/bGs0W5y1lXbb6RfkuWDM1WU84mostV0sYypaWqATj4t2IdowoOdHLiHX" +
                                          "RA34WgOr6W5i08s0INzGRhKkxsjQWi6si6kVjZs4qNr1yE75danIYJ2kAXd9" +
                                          "atme2YOyJy27xHROC55Wb7thpeRV3TF8E35X9opM/2ynlPvyw+RR4xEeTrKF" +
                                          "ws/wdp7+NIYRckmSwyiAR7gIuXzUCd1xP9FNOXN4eH3sTo2bXccmO5w8eqfW" +
                                          "Y34w+exzL7yocp/Ds4NJRrMF+Uau9w4brIF9C8cAedudD2GDvPN63Cj52nP/" +
                                          "8sjk3cYzeafgtgYOg1zJMIdZg/uokf34KTlPk/ydwUvf6LxF+bU95OxR2+S2" +
                                          "nvCtSDdubZZcCUAUB87kqGUSIE/ednJzFaDGATjm+7Y3SV+5+dVnr+8h5072" +
                                          "kjIKj57qzNylucFKsjMGh03oK/AU7ibHMyfbNNCseZ+sDK+3HnQp899s9QEv" +
                                          "u78uPQ6t22Jm7yhIxwcREiBvOe4QkK5tAyW3+vWps8oP1JJsg6xb999Xn8K/" +
                                          "8q8fu7Y7btpw5tANb39tAsfzP0cgH/zm+/7jsZzMGSVr6x/3PI7Bdr3iB44p" +
                                          "N4NA2mRypB/6i0d/82vSZ84iZ2jkXGhuQd683dvpdxjld2xP7qL84FvGIfQD" +
                                          "GXRSUvZVd7WffcABTpTbx8ghlPyu53m5a1Nmz3mv6maE3GNIjmqDA7Qc9D0n" +
                                          "UpqEx/G1a6rHuf7Ma53ET3JKIYNbWqqZXR6+7QvO7quD8sUXr1566MXpX+WR" +
                                          "d/Rl4DKDXNJi2z7ZBTwxvuAFQDNznS7vgs3LfyDrh+5gxgi5sBvk8iY7+PdH" +
                                          "yLXT8BFyPv89CfeBCLlyDAdJ7QYnQT4UIWchSDZ8Lms2nigrB+Uwt+T9r2XJ" +
                                          "I5ST3cKsFOVfyg7LRrz7VnZT+dKLPfb9r1Q/t+tWKra03eZfVhjk4i5Pj0rP" +
                                          "E3ekdkjrQvfpH9/75ctPHZbJe3cCHyfnCdkef/UMolZelMf89g8e+r13/taL" +
                                          "3807Zv8He1ONJsIcAAA=");
}
