package org.apache.batik.bridge.svg12;
public interface BindingListener extends java.util.EventListener {
    void bindingChanged(org.w3c.dom.Element bindableElement, org.w3c.dom.Element shadowTree);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1XaWwbxxUekroj63IsuXYsX7RROzEXapoGqZw2FiPFcimJ" +
                                          "kJwUkZtQw90hudZyd7w7pCilbg6gjZEfRhArbVrU+uWgB3KhSJAAQQwXBZoE" +
                                          "6YG4QZsDTVr0R08D8Z+6hdum782Q3OVKcv+VAIfDmTdv3v29eeYSafZcsotT" +
                                          "26AJsciZl0jjPE1djxlJi3reUVjN6I/9/syDV37V/nCUtMySrgL1JnTqsTGT" +
                                          "WYY3S7aZtieorTNvkjEDT6Rd5jG3TIXp2LNkk+mNF7ll6qaYcAyGBPdQN0V6" +
                                          "qRCumS0JNl5lIMj2lJRGk9Joh8IEwynSqTt80T+wpeFAMrCHtEX/Pk+QntRx" +
                                          "WqZaSZiWljI9MVxxyY3csRbzliMSrCISx61bqoY4krpllRl2vdD996uPF3qk" +
                                          "GTZS23aEVNGbZp5jlZmRIt3+6qjFit4J8jUSS5HrAsSCxFO1SzW4VINLa/r6" +
                                          "VCD9BmaXiklHqiNqnFq4jgIJsrORCacuLVbZpKXMwKFNVHWXh0HbHXVta+4O" +
                                          "qfjkjdryt+7v+VGMdM+SbtOeQXF0EELAJbNgUFbMMtc7ZBjMmCW9Njh8hrkm" +
                                          "tcylqrf7PDNvU1GCEKiZBRdLnLnyTt9W4EnQzS3pwnHr6uVkUFX/Necsmgdd" +
                                          "+31dlYZjuA4KdpggmJujEHvVI03zpm3IOGo8Udcx/iUggKOtRSYKTv2qJpvC" +
                                          "AulTIWJRO6/NQPDZeSBtdiAEXRlr6zBFW3Oqz9M8ywiyOUyXVltA1S4NgUcE" +
                                          "2RQmk5zAS1tCXgr459LkwdMP2IftKImAzAbTLZT/Ojg0GDo0zXLMZZAH6mDn" +
                                          "/tQ3af9rp6KEAPGmELGiefmrl++4afDCG4pm6xo0U9njTBcZ/Vy26+0bkvtu" +
                                          "i6EYbdzxTHR+g+Yyy9LVneEKh0rTX+eIm4na5oXpn9770A/ZX6OkY5y06I5V" +
                                          "KkIc9epOkZsWc+9iNnOpYMY4aWe2kZT746QV5inTZmp1KpfzmBgnTZZcanHk" +
                                          "fzBRDligiTpgbto5pzbnVBTkvMIJIa3wJRH47iHqsx0HQWyt4BSZRnVqm7aj" +
                                          "pV0H9UeHyprDPJgbsMsdLQvxP39gKHGr5jklFwJSc9y8RiEqCkxtalnXNPJM" +
                                          "88r5oc9oIxCGEF5Yh1DBBMYd/7/fWEEbbFyIRMA9N4SLgwV5ddixDOZm9OXS" +
                                          "yOjl5zJvqcDDZKlaT5ADcG1CXZuQ1ybUtQl5bSJ0LYlE5G3X4/UqEMCN81AQ" +
                                          "gKBz38x9R+ZO7YpBBPKFJnRCRWbo1tofOBgSU9aC22f42Xd/8eeboyTql43u" +
                                          "QL2fYWI4EKrIs08GZa8vx1GXMaD77VPpM09eevSYFAIodq91YRzHJIQo1F2o" +
                                          "X19/48R7H3147p1oXfCYgFpdygLsCdJGs1DoqC4Eaa9XLKXY9Z/AJwLf/+AX" +
                                          "dcQFFX19yWoK7KjnAOcBc0TkfLMgA74Oo2Vmi5qt0Vzb1ismshCee2R5xZh6" +
                                          "ekilfF9jgo4C/jz763//LPHU795cw+/twuEHLFZmVoNMLtm5qqOYkLW2hswZ" +
                                          "/daLV2IfPLG5U7qrMwvNhI/o8QZEVw2J6+jMAEhZD9tr+LZ/fTQPi/D6I3/Z" +
                                          "cvQLhTkpQhCfkVczQAueTCOq1rlvD5kyzPIHE8+8edde/YmoBBQszmsAUeOh" +
                                          "4aBR4VKXAXLaqBaubKhgexbKyrAtMvr+HfSlzGsn41HSBAgDqCooVEEArMHw" +
                                          "5Q2gMFzLFLyqDYyQc9witXCrhoodouA6C/6KLBe9KnDB2TIn74RvvFo25S/u" +
                                          "9nMcB1R5kfSDctyJQ1xGShSne3DYK8k+DZGz1w9kqPMWVD70SPxuG5xt5kya" +
                                          "tRjG9r+69wy99LfTPSooLVipueim/83AX//UCHnorfuvDEo2ER37DL9g+GQK" +
                                          "vDb6nA+5Ll1EOSoPX9z27dfpWYBBgB7PXGISTaJKv1p2bsT6uHCznjCcYgK7" +
                                          "QshQ3EpKtUck2e1yPITmq1Y6/D+Gw22CdGVVDU0WoC9hBkiz7xptq2sWocaV" +
                                          "q8Cvnez7aP67f3pWZXi4SwgRs1PLj32SOL2sDKtaqd2rupngGdVOSWl7pBcr" +
                                          "sgBc4xZ5YuyPz5989fsnH41WNU0I0lR2TFQtvo5qgeY4oz/+zscb7vn4/GUp" +
                                          "aGN3Haz6E5Qr2Xpx+DzKNhDGncPUKwDdZy9MfqXHunAVOM4CRx3w1JtyAfsq" +
                                          "DRhRpW5uff/HP+mfeztGomOkw3KoMUaxj4VuBFKGeQWAzQr/4h0qLRbaYOiR" +
                                          "biWrHI3BtX3tsB0tciEDbemVgRcPfm/lQwkvFdAxBKrIY/Oq3l71o/pzK91t" +
                                          "Ayt3/0aWh3rP2AlomCtZVqD6BCtRC3dZzpS261QW5PJnVpBt18R7AY9K/JV6" +
                                          "3qsO3QcQtc4hQEk1CdLPwVstTA985W+QDlK2w6cDVmoSJMkJEgMSnOY5r0Qa" +
                                          "uwn8M4XDJjWfXtdjgQZkd0OAyodXDRBK6umV0Z9fOTL5wOXPPa36EXiyLS3J" +
                                          "Rh3eHarK1kFl57rcarxaDu+72vVC+55arvQqgf3SujVQMr4MEMwxHLaE6pUX" +
                                          "r5et984dPP/zUy0XIdSPkQiFCnUs8OxRPT4UvRLE5bFUEMsDz3dZSoc7/jD3" +
                                          "y3+8H+mTcVlF/8FrncjoZ85/kM5x/p0oaR8nzRDGrDIL7zjvzkV7mullyKC2" +
                                          "km2eKLFxeCK2ZJ2SXX+jdWHsUnyUSctUDbqhvorQKMiu1fVqdfcAKbvA3BHk" +
                                          "LoE2BMMlzoO7FXy7rKEV+Gbo7D8f/Ma7U5BbDYIHubV6pWwd0YNPQMU7UDpV" +
                                          "2xfLpCY4r7aB0UnpVc4loC5KpRcUNVIIEtnP+X8B+6BOucoRAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczkVn3eb+/NsZsEkjSQhIQNahjyecaeGY+1HPE1pz2H" +
                                          "PePxuC0bj6/x+Bz7eS5IC6laUJEoagOlEuQvUFsUDlVFrVRRpapaQKBKVKiX" +
                                          "VIKqSj1oJPJHD5W29Nmz37HfZhPxT0ea5+f3fuf7He+9n198BTmbxEghCr2N" +
                                          "7YVg31yD/blX2QebyEz223ylr8WJaTCeliRDOHZdf/wrl//9R5+YXdlDzqnI" +
                                          "fVoQhEADThgkopmE3tI0eOTy0SjnmX4CkCv8XFtqaAocD+WdBFzjkTuOoQLk" +
                                          "Kn8gAgpFQKEIaC4CSh1BQaS7zCD1mQxDC0CyQH4eOcUj5yI9Ew8gj91MJNJi" +
                                          "zb9Bpp9rAClcyN5lqFSOvI6Rtx3qvtP5FoU/WUCf/433X/nd08hlFbnsBFIm" +
                                          "jg6FAJCJitzpm/7UjBPKMExDRe4JTNOQzNjRPGeby60i9yaOHWggjc3DRcoG" +
                                          "08iMc55HK3ennukWpzoI40P1LMf0jIO3s5an2VDX+4903WlYz8ahgpccKFhs" +
                                          "abp5gHLGdQIDII+exDjU8WoHAkDU874JZuEhqzOBBgeQe3e287TARiUQO4EN" +
                                          "Qc+GKeQCkIduSzRb60jTXc02rwPkwZNw/d0UhLqYL0SGApA3nwTLKUErPXTC" +
                                          "Ssfs80r33R//QNAM9nKZDVP3MvkvQKRHTiCJpmXGZqCbO8Q738l/Srv/ax/d" +
                                          "QxAI/OYTwDuY3//gq0+/65GXvrGDectrwPSmc1MH1/XPTe/+zluZJ8nTmRgX" +
                                          "ojBxMuPfpHnu/v0bM9fWEYy8+w8pZpP7B5MviX82+dAXzB/sIZdayDk99FIf" +
                                          "+tE9euhHjmfGDTMwYw2YRgu5aAYGk8+3kPOwzzuBuRvtWVZighZyxsuHzoX5" +
                                          "O1wiC5LIlug87DuBFR70Iw3M8v46QhDkPPwjp+D/CWT3ezRrABKgs9A3UU3X" +
                                          "AicI0X4cZvpnBg0MDQVmAvsGnI1CdAr9332qtE+gSZjG0CHRMLZRDXrFzNxN" +
                                          "otPYMWwTTZZ2CUNp6IbQvbIEkSm4n/ld9P/OcZ2twZXVqVPQPG89mRw8GFfN" +
                                          "0DPM+Lr+fEpzr37p+rf2DoPlxuoB5CnIdn/Hdj9nu79ju5+z3T/BFjl1Kuf2" +
                                          "poz9zhGgGV2YECDAnU9KP9d+5qOPn4YeGK3OZEZY5xH6YP5yGuI9efv0Xc9y" +
                                          "RyvPlzp05wf/q+dNn/v7/8xFPp6BM4J7rxEyJ/BV9MXPPMS89wc5/kWYrIAG" +
                                          "nQvmgUdOBu5NsZZF8MmlhDn4iC72Bf/f9h4/96d7yHkVuaLfSPCy5qWmZMIk" +
                                          "e8lJDrI+3ARumr85Qe2i8dqNRACQt56U6xjbawfZNFP+7HETwn4GnfUv5e5w" +
                                          "dw5zz4/h7xT8/2/2zyyRDezC4l7mRmy+7TA4o2h96hRAzmL7xH4xw38ss/HJ" +
                                          "Bc4EeI8Uffav//yf8T1k7yjDXz62Z8JFuHYsq2TELuf5454jlxnGZrZYf/fp" +
                                          "/q9/8pWP/EzuLxDi7a/F8GrWZhLDLRJuNb/0jcXfvPy9z31379DHTgO4raZT" +
                                          "z9FhJ8l3PKiJ5QSaly/I4wB5YO7pVw+0luEOCAW7OveIfKneDPf8XLTMKvu7" +
                                          "bSOPKyjR1du467Gt/rr+ie/+8C75h3/06i2eevPCCFp0bWehXKo1JP/AyShq" +
                                          "askMwpVf6v7sFe+lH0GKKqSow+yQ9GIYyeublvEG9Nnzf/vHf3L/M985jezV" +
                                          "kUteqBl1LduVYW4FM7iRz2ASWEfve3qXG1cXYHMlj00k1/8tO3HysL77aCH4" +
                                          "EO6eH/uHT3z7V9/+MpSjjZxdZj4MJTi2Wt00O1D88ouffPiO57//sdwmMBP3" +
                                          "P8VdeTqjWssZPJG3P501hZ3Fsu67suaprNk/MNNDmZmkPBvyWgKE0HDggcLI" +
                                          "LfW6qaMfOz70tuWN3RJ99t6X3c/80xd3O+HJPHEC2Pzo87/y4/2PP7937Pzx" +
                                          "9luOAMdxdmeQXOi7Dk352OtxyTHq//jlZ//wt5/9yE6qe2/eTTl4WPziX/7P" +
                                          "t/c//f1vvkaSPuOFB06ZtdgNttmj8saGBXfUmuWkRR38+JKijVfT9XpkunCH" +
                                          "quKtJFUmiUKIYm/LKXB3aizUFVZ3+nXd8dtuezVyVTBYkcVZaqgbg1gREeN4" +
                                          "U7tqz1XOEmdUPJXjUSEd2zTemUltihoMVgqthlx10igP1IQdynFRLNbYmlqo" +
                                          "zozUJ2rYAO/JHX1ZkKmWxfpDY4kvMdI0J5JmqXoSgiFWpdqJ7qhecT7vcyVj" +
                                          "vvbaDh6bI3nerbZQEk02rIwTMhowIyBspNjmS+1guEiGjeF4MsElQlOBY4bx" +
                                          "sLt05xw7rIpGZd7Ahy0lwviu6xb8bp3wvOpCm+jUpkH3jUG3KFcXIpP6UrHd" +
                                          "9SpeS5hjXltsuGQ7nNVa3GoTSIshqBWHhVVk1ikhZpqAU9C+WxgEQFyPF6om" +
                                          "qc7Ym7dIQV6vNxNcT8Tp1nMEKWZa0rpami7CSdmNI88TPWxpsCRZTft1fOE2" +
                                          "hqqE4RondxtTNarMPdUXWwAvVBfzugPK7dp8JEmVZkwlErOu90rSdlyWW11e" +
                                          "Q+OqzLAk7WuK43rNhdNdBPVFeW632kncExlNT3kZkuwowqpT78rNsTIrNqdN" +
                                          "RQZaodxbWHN3bsQbUCCgNRqCIRSkKeiZA6Ve5Dieak+79qg+FQSgEyo9F3xm" +
                                          "THbns9osdn2gb7xFbBF9trsclRoM13FUWjT4gA82Q0COy1ww2Ep4tAqacTWV" +
                                          "3VFdQbumnvi2YRTwkuFN1HlKlTtGZNt+O51zzaXcKuLbyMdbvUZYGxn6GnVG" +
                                          "tt3pAVGadIZLbNGOlgyVesPWuC32qmh30GdVU6KB4VCcInpxdUvXx3hvsSWF" +
                                          "2mblbHqjjSJ7gCpJZaiIzmHiwHcrW0oqAUax43KF5N2VIfSxlgU6LZ/aUtMh" +
                                          "rw7R3twuNtiwuFV4QVWpZtVnAxQMcM0i46ja4ah+w+f4hmNafuwVCmXNYplG" +
                                          "OfKr67A4IoP5kIaHEHmDVQvFqbsEqVPlJlNjux42xYJdmGw2JC8HJteZFeOh" +
                                          "UjBbfjnQKqESBSRBFClUVao9d1LZFKutitxxWzppRj1XTcZ6gXS6QS+aCJOy" +
                                          "NjYxVx0S5epArjjBUPWjUieytj5twxcVnkObrrWlRdZzbGcY2VMQVqLtNJDp" +
                                          "obsUWu2Whq/aYrNMOM1Fsi42B+MNKNOSKgbywie0eSQXm+TIbG6imO237Wki" +
                                          "JAY/WK77OGl3mo24Mne9+qot6eSmJjrcgnHXQPMCpdtvC7VaXAl1MmytmQZX" +
                                          "r0xmJZamhYmBEqg15rjptL5piQJFdssSb6/kimE4a7an+mRPkTY9mOC37eVC" +
                                          "Z1m142nDCsXqjRKjqOmgtJmOwMCrTKV2kZ94XKWBK2V0tOAEplsrUQO7Q2/x" +
                                          "2poUC2qPmEQ03e/U24HIiONpWAKh1aNtaURqDIZZZUwx0JppTsPNcOGV8XTA" +
                                          "Y9Zk3CpznbiVFGsNVast16WGImgsQcj9SCjCFLWUJnWqFRoLsjQRt812axCW" +
                                          "6liolEi0XBOJJl4qE1EpVCxmYtcjY2PzCWO0G0mJDRdMmdM0UuE7yoRUUaq9" +
                                          "4i20QCmGPqjXIYHNOOwQnXlA9XRaLw5dixdsiij3Qkz2ncoCFOXttOQkfjJj" +
                                          "TBMTK2t1VjVdx7Pq5NwOyww63xJVHEX5fnNEkBV9VUDBKuWafF315bAr8MCv" +
                                          "LBa9icuPsVmyUuFthJeh4/f5RmVELGJhtezOWmhYG6icvMLa1cJcoLiZypIg" +
                                          "LvAqag0HfQdlqy0cVfXlgJ8N3WgwYyxX1rcDKjWHTG9Rir0lW3E3236rydUK" +
                                          "NdMwTHTihzQ9SLZ+Qo3M3qys0WJZ7iiUwmsLWkunnZltrqedTUwBYRkXmpbk" +
                                          "bRtJUC41JZqy2QUThjLHUbHQXFUGmC3Ut3yd3yzYyWagkysHKEw8C0MjTKkq" +
                                          "g1Y7PG2SnYClsWErIMriclkPsYqEpmQg6HRJrLiWxOpg0x6U1g1pJgUmzk46" +
                                          "NbfAqo1taUW6i74wllmiKPXXaaOyBlAdDYjzBhkXquRqQ5K8NexLYcjLTpSa" +
                                          "jo/WcEpB0RHTDMLYSpcsF2KciBMsT9qFxqCzZKfVgCpUeK/E9aSwr5BbjDCs" +
                                          "aDyhaZsm+kqjJQ21dmdZirBpMqymTWYbzBl9YneIQTIb4FzUASPdxczSpt8a" +
                                          "+ovSpIqyhcYKwxijIcvsqDgOGXJGu86WgCeGBZaMQ12TFzVmGZhbQutXCQuP" +
                                          "xqrilKWVLSalPj/HManHYwnbAdrCwOI0CuyGIfeksUdEtB4nNq2X12plkm76" +
                                          "2wpZI60kaJZL4+6o2Cp6IjasD8AyrCxsc1IOt2hhm+hTYhmU0cYo0hpdvKlt" +
                                          "q1xlEGNKtC6w2053xjYCvT/qrFh4iiAFa6E004CSe0KZEdf4qtQGG8pKFqw4" +
                                          "E6NxJbUstNkv+Ja5BY3Q77krvBMKI209L8spXe80zMGY2g5itDwrLnhxqk16" +
                                          "jjh1xnGzhdNAwUFCF4HucOzU9GVb1PuWj3qDlbusG9SahvE9QXsL3CNKIRpt" +
                                          "O2QJUBuAo0VtPMPjPkZ5oc8AVV6wVZoBIoMb6jaSsGppMK7024Ec0aAEY52a" +
                                          "kB20LVfxRdLDB/oA6OXZgHNLjMH3V3IChhRZq4wLA9brYKuqzsp+KLUFt83Z" +
                                          "ghT0JpW4ONDSVVATygrbno8tBRhze6C6RrFHbUJDYUW6U019uaiSVm/IV1Y9" +
                                          "pd/X8CqnOBtewtviDDebWtwpuXWvQsS6Fq81Ni0Q2FJmCpWKFi8HC9vCpXQu" +
                                          "D4S4LHDCat3kNa4ajZS4YgKyVjb6fXQ72hSVliH13YFTZ4JRUuutxf6wPFqK" +
                                          "PFeZ1keckLBbuAZSqBPonMU3eKHWLPhDXfbqaK0eB/o8VGsV1BUqazQqhppY" +
                                          "C7Yi24jZFk9s58utKxN+6nmbDoO5PmZ2+PraZDqY2sYkRSnMjXEzGQWbkaSD" +
                                          "ETtdzJZhPOgITlqy5IVh6VRnuqRwuunyIYfRguBtwx5RVzZE3OHkQmMaEmzN" +
                                          "gjcsYlShp+yk1UyncjUar4zipNsfCCNixEYytrb4iJmUY0Kji6MgkvWyFzKV" +
                                          "TiTqo67canEg6BeUGl2o0r1UD0V4Un5PdoRu/WS3mHvyy+ZhwRJeXrKJ4k9w" +
                                          "el+/HkOAXNCmCYjhFQ8gFw8rqDvux6otpw4ut8cumdzSDMBBKSe7tTx8u1pl" +
                                          "fmP53HPPv2D0Pl/KbiwZMRYyBGH0lGcuTe8mVjHyztvfzoS8VHtUQfn6c//y" +
                                          "0PC9s2fyEsItlR0euZRh9rOK+GHl+9ETcp4k+TvCi99svEP/tT3k9GE95ZYi" +
                                          "8s1I126uolyKTZDGwfCwlhIjj99ypQt100hj84jvO9+mffX61569uoecOV5k" +
                                          "yig8fKJkc4cVxr7mZQwOqtaX4PU8XB2NHK/fwGXNC2gs/F+9UdbMn9nsfVHW" +
                                          "vml95FO3OMveoXeKN1wjRt5x5AlM6Hmmnq/61VHg5zdtbeqZmXP89+UnSl/9" +
                                          "149f2d1DPThyYIZ3vTGBo/GfopEPfev9//FITuaUnn0HOCqGHIHtisv3HVGm" +
                                          "4ljbZHKsP/wXD//m17XPnkZOtZAzibM182rv3k6/A/e+L6tfrnB93wj9/ewb" +
                                          "DnTxbMrJ1Z7lYHre2nmc7cqS2XtefL8OkLunuxonM9MC29x9U3jfsRhl4P17" +
                                          "GTrGUfA+80ZX7+Os1gC5fKKKmmn84C0fc3YfIPQvvXD5wgMvjP4q96nDjwQX" +
                                          "eeSCBRPo8cLfsf65KDatncoXd24U5Y8lQB5+3QIvQM7mz1zsdIe0gUnjNkgA" +
                                          "ObfrHIf/IECunISHdPPncbhfAMilIzhIatc5DvIcQE5DkKz7i1lR8liWuZEW" +
                                          "cwPc+0YGOEQ5XlXMMlP+pe0gi6S7b23X9S+/0O5+4NXq53dVTd3Tttv8ywyP" +
                                          "nN+F7WEmeuy21A5onWs++aO7v3LxiYOsefdO4KNYPSbbo68dUJwfgTwEtn/w" +
                                          "wO+9+7de+F5eWfs/qmJuHwIdAAA=");
}
