package org.apache.batik.gvt.event;
public interface GraphicsNodeChangeListener extends java.util.EventListener {
    void changeStarted(org.apache.batik.gvt.event.GraphicsNodeChangeEvent gnce);
    void changeCompleted(org.apache.batik.gvt.event.GraphicsNodeChangeEvent gnce);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAMVYaWwbxxUekhJ1RLIO25Jrx/JFG7WckHAaJ0jltLFZyZZD" +
                                          "SYTkJI3chB7uDsW1lrvj3SFFKXVzIY2RH0YQK20S1PrloAdyoWjQAkUMtwWa" +
                                          "BOmBuEGbA01a9EdPA/GfuoXbpu/NLMnlSnRa9EcF7HB35s2bd39v9NxF0uw6" +
                                          "ZCunlk7jYp4zN57G9zR1XKYnTeq6h2E2oz3229P3X/5F24NhEp0mq/LUHdOo" +
                                          "y0YMZuruNNloWK6glsbcccZ03JF2mMucEhWGbU2TtYY7WuCmoRlizNYZEtxJ" +
                                          "nRTpoUI4RrYo2KjHQJBNKSlNQkqT2BckGEqRDs3m87UN6+s2JH1rSFuonecK" +
                                          "0p06Rks0URSGmUgZrhgqO2QXt835GdMWcVYW8WPmHs8Qh1J7lplh60tdf73y" +
                                          "eL5bmmE1tSxbSBXdSebaZonpKdJVmx02WcE9Tr5EIilyjY9YkFiqcmgCDk3A" +
                                          "oRV9a1QgfSezioWkLdURFU5RrqFAgmypZ8KpQwsem7SUGTi0Ck93uRm03VzV" +
                                          "tuLugIpP7kosfvXe7m9HSNc06TKsKRRHAyEEHDINBmWFLHPcfbrO9GnSY4HD" +
                                          "p5hjUNNY8Lzd6xozFhVFCIGKWXCyyJkjz6zZCjwJujlFTdhOVb2cDCrvqzln" +
                                          "0hnQta+mq9JwBOdBwXYDBHNyFGLP29I0a1i6jKP6HVUdY7cDAWxtKTCRt6tH" +
                                          "NVkUJkivChGTWjOJKQg+awZIm20IQUfGWgOmaGtOtVk6wzKCrAvSpdUSULVJ" +
                                          "Q+AWQdYGySQn8NL6gJd8/rk4vvfUfdZBK0xCILPONBPlvwY2DQQ2TbIccxjk" +
                                          "gdrYMZj6Cu175WSYECBeGyBWNN/94qXbrhs4/5qi2bACzUT2GNNERjubXfXm" +
                                          "tcmdt0RQjFZuuwY6v05zmWVpb2WozKHS9FU54mK8snh+8sd3P/At9ucwaR8l" +
                                          "Uc02iwWIox7NLnDDZM4BZjGHCqaPkjZm6Um5Pkpa4D1lWEzNTuRyLhOjpMmU" +
                                          "U1FbfoOJcsACTdQO74aVsyvvnIq8fC9zQkgLPCQEzy6i/jbiIEgpkbcLLEE1" +
                                          "ahmWnUg7NuqPDpU1h7nwrsMqtxNZiP/Z63fHb064dtGBgEzYzkyCQlTkmVpM" +
                                          "zJQgV0vMEokDDuV5Q3PHoT4l8xBsDOsRKhrH+OP/t5PLaJPVc6EQuOvaYLEw" +
                                          "Ic8O2qbOnIy2WNw/fOmFzBsqEDF5PGsKsgeOj6vj4/L4OBwfl8fHGx9PQiF5" +
                                          "6hoUQwUIuHcWCgUQdOycuufQ0ZNbIxCZfK4JnVOWmbuh8gEbA+LKGnHrFD/z" +
                                          "9s/++KkwCdfKSZcPB6aYGPKFMPLslcHaU5PjsMMY0P36qfTpJy8+ekQKARTb" +
                                          "VjowhmMSQhfqMdS1R147/s4H7599K1wVPCKghhezAIeCtNIsFECqCUHaqpVM" +
                                          "KbbmI/gLwfMvfFBHnFBR2Zv0UmNzNTc495kjJN/XCdJf02EYzV+xNZprY6Mi" +
                                          "Iwvk2YcWl/SJZ3erUtBbn7jDgEvP//KfP4k/9ZvXV/B/m7D59Sb42/TJFIYj" +
                                          "tyzrNMZkDa4gdka7+cLlyHtPrOuQ7urIQpNRQ/pYHdKrRsWxNaYD1DTC/Aru" +
                                          "DTZG+aAIrz70p/WHP5M/KkXw4zbyagbIwZ1pRNsq900BUwZZfnPsudcP7NCe" +
                                          "CEugwaK9AkDVbxryGxUOdRggqoVq4UxnGdu2QHYGbZHRBjfTlzOvnIiFSRMg" +
                                          "D6CtoFAdAcgGgofXgcVQJVPwqFYwQs52CtTEpQpatou8Y8/VZmTZ6FGBC86W" +
                                          "OXkjPDGvnMpfXO3jOParMiPpB+S4BYeYihR83Y7DDkn2SYicHbVAhvpvQiVE" +
                                          "j8TusMDZRs6gWVPWkX90bd/98l9OdaugNGGm4qLrPp5Bbf4T+8kDb9x7eUCy" +
                                          "CWnYf9QKRo1MgdrqGud9jkPnUY7ygxc2Pv0qPQPwCJDkGgtMokyoPjtv+K/q" +
                                          "pExgaZD9ksGtctyHhvVqIH6P4HCLIJ2a3ATtmwPVAcTceZU+1zEKUPxKXqeQ" +
                                          "ONH7wezX/vC8Sv1gWxEgZicXH/sofmpRWVz1XtuWtT/+Par/ksJ2S/eWZWW4" +
                                          "yilyx8jvXzzx/W+ceDTsKRoXpKlkG6harIFqvm46oz3+1oedd3547pIUtL4d" +
                                          "98PBGOVKth4cPo2y9QcB6SB180B34/nxL3Sb568Ax2ngqAHwuhMOgGO5Djw8" +
                                          "6uaWd3/wo76jb0ZIeIS0mzbVRyg2vtC+QC4xNw+4WuafvU3ly1wrDN3Sq2SZ" +
                                          "nzHqNq0cz8MFLmQELnyv/zt7v770vsQdyeGG+uy8CZ5BLzsH/6fsrA9GL8bx" +
                                          "MykJ7rlKtGZw+Dx4QEUrwprJIF5x+na5YwKHuxUkTv5n1sGJu8rQrTfuNdCC" +
                                          "65ZdhVT7rr2w1NXav3THr2TVrLbYHdAk5Iqm6SvK/gId5Q7LGVKpDhU/XP7k" +
                                          "QI7GaS5Is/yVSjC1wxBkzUo7BInA6KcEFOkOUgJH+eunswVpr9FB+6Fe/CSA" +
                                          "CREgwVeX83KovreqOmLtxznC145tq8tKeT2twGNRXVAz2otLh8bvu3TTs6o7" +
                                          "g4vtwoK8zsDtTGFOFWK3NORW4RU9uPPKqpfatlcKRI8SuBbKG3yBdxeEKMco" +
                                          "WB+o3m6sWsTfObv33E9PRi9Afh8hISrI6iO+y6G6CQEEFCEZj6T8nY3vnxwS" +
                                          "WIbaf3f05397N9Qrk1EiANbVq+zIaKfPvZfOcf5MmLSNkmaof6w8Dbdd93Pz" +
                                          "1iTTSlA2WouWcbzIRuEiHc3aRat6k12FIUvx6iot4xm0szqLjYIgW5cX6eW9" +
                                          "FNSpOebsR+6y7Qg0JUXO/atlvOGtoBX4ZveZv9//5bcnIKXqBPdza3GL2Wp/" +
                                          "478oK94+vFBNcCSTGuPca4qjP5Re5Vxm/yNS6YcVNVIIEhrk/N+M1DfC8BIA" +
                                          "AA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAMU5e8zrVn3+vvu+fdzbAm1XaKHtBa0NfM7TSXR5JY7jOHYc" +
                                          "J07sxGzc+p3Ez/gds05QCaiGVNDWMiZB/wJtQ+WhaWiTJqZO0wYINIkJ7SUN" +
                                          "0DRpD4ZE/9hDYxs7dr5H7nd7W1X7Y5HsHB//3q9zzs8v/hg653tQwXXMjW46" +
                                          "wYGaBAcrs3YQbFzVP+hTNUb0fFVBTdH3J2DuhvzoV6/8208/tbi6D50XoDeI" +
                                          "tu0EYrB0bH+s+o4ZqQoFXTmZxUzV8gPoKrUSIxEOg6UJU0s/uE5Bd+ygBtA1" +
                                          "6kgEGIgAAxHgXAS4dQIFkO5S7dBCMwzRDvw19MvQHgWdd+VMvAB65GYiruiJ" +
                                          "1iEZJtcAULiYPXNAqRw58aC3Heu+1fkWhZ8vwM/9+gev/s4Z6IoAXVnabCaO" +
                                          "DIQIABMButNSLUn1/JaiqIoA3WOrqsKq3lI0l2kutwDd6y91WwxCTz02UjYZ" +
                                          "uqqX8zyx3J1yppsXyoHjHaunLVVTOXo6p5miDnS970TXrYbdbB4oeHkJBPM0" +
                                          "UVaPUM4aS1sJoLeexjjW8RoJAADqBUsNFs4xq7O2CCage7e+M0Vbh9nAW9o6" +
                                          "AD3nhIBLAD14W6KZrV1RNkRdvRFAD5yGY7avANSl3BAZSgC96TRYTgl46cFT" +
                                          "Xtrxz4/pdz/7Ibtn7+cyK6psZvJfBEgPn0Iaq5rqqbasbhHvfIL6tHjf15/Z" +
                                          "hyAA/KZTwFuY3/ull9//zodf+uYW5s2vADOUVqoc3JA/L9393begjzfPZGJc" +
                                          "dB1/mTn/Js3z8GcO31xPXJB59x1TzF4eHL18afyn8w9/Uf3RPnSZgM7Ljhla" +
                                          "II7ukR3LXZqqh6u26omBqhDQJdVW0Pw9AV0AY2ppq9vZoab5akBAZ8186ryT" +
                                          "PwMTaYBEZqILYLy0Nedo7IrBIh8nLgRBF8AF7YGrAG1/D2W3AIrghWOpsCiL" +
                                          "9tJ2YMZzMv0zh9qKCAeqD8YKeOs6sATi33hX6aAO+07ogYCEHU+HRRAVC3X7" +
                                          "EtYjkKuRagcw7onuYin7tKOo6AIEm5oVikzRgyz+3P83zklmk6vx3h5w11tO" +
                                          "FwsT5FnPMRXVuyE/F7axl79849v7x8lzaM0AqgH2B1v2Bzn7A8D+IGd/cHv2" +
                                          "0N5ezvWNmRjbAAHuNUChAAB3Ps7+Yv/JZx49AyLTjc9mzknyzH0gfzgD8B6/" +
                                          "fVnvZjWFyOuoDML8gf8cmtLTf/cfuei7lTkjuP8KqXQKX4Bf/OyD6Ht/lONf" +
                                          "AkUsEEHQgfrw8OmEvikHs8w+bVJQm0/olr9o/ev+o+f/ZB+6IEBX5cPCz4lm" +
                                          "qLIqKL6Xl/7RagAWh5ve31y4tll6/bBABNBbTsu1w/b6UZXNlD+360owzqCz" +
                                          "8eU8LO7OYe75Gfjtget/sivzRDaxTZd70cOcfdtx0rpusrcXQOfKB/WDYob/" +
                                          "SObj0wbOBHgP637ur/7snyr70P5J5b+ys5YCI1zfqTYZsSt5XbnnJGQmnpoZ" +
                                          "628/w/za8z/++AfyeAEQj70Sw2vZPZMYLJ1gCfroN9d//YPvf/57+8cxdiYA" +
                                          "y20omUsZDPx8JQSaaEtbNHODPBpA969M+dqR1hxYGYFg11ZmPTfVm8BeIBct" +
                                          "88rBdjnJ8wtIdO024bqzBbghf+p7P7mL+8kfvnxLpN5smIHoXt96KJcqAeTv" +
                                          "P51FPdFfALjqS/QvXDVf+imgKACKMqgW/tADGZ3cZMZD6HMX/uaP/vi+J797" +
                                          "BtrvQpdNR1S6YrZag5obLMACvwDFIHHf9/5tzYwvgtvVPDehXP83b8XJ0/ru" +
                                          "E0NQDlhVP/H3n/rOJx/7AZCjD52LshgGEuxYiw6zjcbHXnz+oTue++Encp+A" +
                                          "Cs18Grv6/oxqI2fw9vz+89mtsPVYNnxndntXdjs4ctODmZvYvDpSoh8MHGUJ" +
                                          "NhpK7qlXLR2Mt7RAtEWHqyj81L0/MD77j1/arpCn68QpYPWZ537lZwfPPre/" +
                                          "sy957JatwS7Odm+SC33XsSsfeTUuOUb3H77y1B/81lMf30p1782rLAY2kV/6" +
                                          "i//+zsFnfvitVyjWZ03nKCize/mQbfZXe23HBnd8uFf1idbRb8DNRT6WkmSq" +
                                          "Got+aUwRw3Kt7yVwv4vXednotcR+cWUGVFfYCEKHnU+MPlGRF+162PH5kulF" +
                                          "qwrb7ZIzLiXm5XGvOB+R5SJbYjzTaSkbh1+NWsZ0EMS82B5a7RDDpVaxJDYx" +
                                          "hWnBuBY6M8kNYZoa2CZrj8G83K332pWaX5aUSjNq0km3GMaIgIa2adRXc7ea" +
                                          "0rU63kzHpRk5tyfqGlmUsbKTVsrlJlOZwbVuuUovMLdorWFq2lOGzqY4Hwih" +
                                          "F9K06fAkopu+JMuyUKz0u2VrEMrYgselaXkSzOd1PkQtZwz2xvRcwIKkb48n" +
                                          "rjMlqmNv7pTJVW/Ub9Mka9IjYz0pt2UDx9bjjl+xGvUpjRT8cr9X8thu6Niq" +
                                          "TBbdIjI2/OJ0zOLWVBe8hb4elkezoFGp4cqAl7k53+AZq+c3RotSv2665gIp" +
                                          "BopWr2xUqiZZFlYK2ERi2zOwZZdEwbFdUulzVlIs8zLWnHg1jFiam9W8OTe6" +
                                          "y7Vs6WjHqLScMdcUSyNdY9V06fAGpUzH3Wlt7K27Ld3auEKDdEexr1p1dopP" +
                                          "lkXUaFbCsVWscCkXhFSoEy5TNxxfi2Zq3Wr2WFouIhPSJ8fjXmuDYb0OQbct" +
                                          "vkv1GFmTvGETt9l5tddxa4vVlKbnDSpVkMRJuwuuixI4yc/QzaZvrFIkFdBV" +
                                          "3A9XZneiLIacVJY7qBetU9MuLuxRIBasdbMft4dKO57NO+0eveniFFNuEkWx" +
                                          "tERWJIP0uKkyr8udFp8E5AQdB0jQozlj2jeWEbrAJ/xq2CdHekGMBcIqF4nR" +
                                          "VMN5fWiJeDAMOAOJUxL1WhHrKlN2SnH9UaHFj5Q5vmFHdoOmEL2vNGDPqEaR" +
                                          "NtUUoU0WE5SgmCHdZswonpc7o1F5IhGynKwMXfFAYK0QNCzVazw7x9C2im/a" +
                                          "PE3Dzep6JnkLvwrX1suy1ELT6aSM0zQ2XoXSTJtZgWwpQXE8WnWFMIznSFSs" +
                                          "pRbPuVKZd1KyxzaBw6oW2fDtRaHhKxUGbgXNUI7FccOcysXyMuYJJ6nTlN3p" +
                                          "CINqW1jhPXQtMsZKsJCpVWMMV6x2SiaPpfQkHG+oxXDlDqzptNSVNGfYl/0W" +
                                          "OlFGw3pV5PxNFNnEuqGhzXRk6BSDjrB0gyzhlbQkMN01JJmiMKwkLizenup1" +
                                          "OlwzHXdaWtTt2PMH6yChhSUDC0hF60lFpKoEeFvH0nlqbNCROTEszh2k/ZHO" +
                                          "FaMB5hidTsjVRhWm50yqZiNp+52hPyYXXq8wZOCgxlBin+FkBBuFw0icU1hM" +
                                          "yI1heS0NbWJT5ukY1oZWN237a6zTrTG4T/q6Olwh0aoKU9VhO9bMhtbDkyYz" +
                                          "WnZryMKZjuIpEfZkHtWnI2W4kcNQGxUFWiISVNDIat/mhrwlhYuGjkmtAkXi" +
                                          "ds/rduC06cOFAmnEqKKRrCAzbUSc4wzZHTCUb8o9cVpjVv5gMC8yFWStTdz+" +
                                          "plFQjRHZGk8kbuXEC2vAjhbaeqCwpXGpCjb71V691mySpZhjUFJfLNS0Raho" +
                                          "QBN+F0PX6LQnrl1uQEqSRcA6FWuDSOu2e3a3PS4LUXFq0cCZcrVZM1Z9Gp6h" +
                                          "Sl8rlrF5yhWAB1xvjgyWRBwZ5bnMg71XX6io3jRoS3Z91dGxiIFhUmOqBtwU" +
                                          "ohkHt2Gr3qk1Walahif9LjFfBZvUoweC0RGrumKI9YJMmZtewHjDcFQPPWLk" +
                                          "0uMR7M57CumNfT6hxXmn1JmgcMsLOxMBL4gtwkvrRRfme0xtAJPGLK6m0kbU" +
                                          "JSIWSu6Y9tfNYrE9jQVBsxk/VGSmTqMqioV6LJLNltHhpMTb4Ml0qIx1fe1w" +
                                          "6+o0sXElLI96c1wSeuP2SpuY6RDE67LLjgd6B0EDp9tSWrKO644202Vu1OeY" +
                                          "eN2dxyO/VkaDCeaOwNHRCRvzBswJ1kRAungbbSD8cGasmA4e2QNXmw0rqyEj" +
                                          "eoMl47YLbLU9V+fLxbhRmdc7HcMus/Ol3JO41iJyo9GSw1aNSegPOsLYR3Se" +
                                          "Y3hj1ixKCtxsmM2hIoY6jeNWdU15jFtrS1p1UmgYHamZ1NUpukF5e641R+TY" +
                                          "KQ1ADVnjodJcGYw9ndc3eiKXmai4ZkZMjPY7Bq6DrY+xcZhVEBVIeO1iiS4K" +
                                          "nabh44EcbHqLiFsTPYSp9lCK6JfFSmsSWDHDteSJrArTQinFyCmTkLO1OhrS" +
                                          "vXqspjM4QhtsVNL5BNOFpTzrgVOoZrljnktLsyDkgwlcAKaADb9fZmGVF3i+" +
                                          "ugHrTNJYRbM0TWC+IKudCVgPnJlLmgaOLMDppLuOrCoC1uFCyVEVpVKr1l1i" +
                                          "GlBVpdlg2viQI4NFVWac8qY5ktsI2y41iu1KFbYTqsJKNaTRSspgX9PqxeFi" +
                                          "MNTxYa2zihtIKPJKBY6dOrKSigKhEmzRSiVuvNHLUYAWRmg1oeNClQ9FLZpW" +
                                          "zE0p9jp0hV2XWcFOe2t6XZTTxqBLWSOMsjcRnAb1qF4vRv5I2ag4Xgg3DVSo" +
                                          "tanU78GI5nutJk41pGSwMfp1zyQDXIgLnaQ6wqZe7Hp9oltLCrZYm8dkL0ym" +
                                          "xiSq2SUf74cNb+RNtJBWUBSpCcqCm9Q9rxyX6JkYVSY9rzzhPEoCudMyasTa" +
                                          "QtiIhHVCqY3qFM6RbmcxhWdg1R0RdVxka4QPbzh2hZbipG2kU6feJuwWQspY" +
                                          "d2gMp3q/V1BD248512t22wWkq8Io20LHmB5z6qxRIZ3IU9dDiwqS1EZL1Vqw" +
                                          "bgSkOikHMU6PZ1wrLTsBtWhIUViZTHzEqevVKIgdspH6nWCCd4ddnqzQwzFf" +
                                          "HU+bIcOQa1cTA1Mmx0SDDdsSiVc2bSVRMXIgO3y74FQsxOf9iTaUokoFazLj" +
                                          "ZbOlLRoLgvUIZDksbBAcAcsK1kUxsGJOGva8EtlJzPKEJGoVrVirNOt0c+QZ" +
                                          "JWzZoiVuXUgJEZSrSNCGslYbWBRLG5boaEjc6EiK0qwwaWk5mbBmC6yYIS9L" +
                                          "KTEOsWVProhjMUCMUrlLTKMEWTpBNbGKfrqmVnNC52vyDFH5Zpdm3aEq+eMC" +
                                          "sqmP9GJ/OhvCQMNoiAdOe1YVIlWImjBck2SbANnTZpRUrOBUmXfhar3hkM1q" +
                                          "Ieq2aRllJ3jIyGJ1vWJqY7XGJRa8oVlkLnM0RxDYwjNgujAodTS00c623e95" +
                                          "T7YVJ17faeie/NB63BAFh6DsRfF1nAKSV2MYQBdFyQ88cFQMoEvHHdot952u" +
                                          "zd7RIXnnsIplXaKjllB2+nnodr3Q/OTz+aefe0EZfqGUnXwyYh3AMHDcd5lq" +
                                          "pJo7rPYBpSduf8ob5K3gk07MN57+5wcn7108mbcibukQUdDlDJPJOu7HnfW3" +
                                          "npLzNMnfHrz4Lfwd8q/uQ2eO+zK3NKlvRrp+czfmsqcGoWdPjnsyHvToLUdD" +
                                          "R1aV0FNP+D7xNvFrN77+1LV96Oxusyqj8NCp1s8dmuNZopkxOOqKXwbHfCc+" +
                                          "mdntAwGz5o24KriuHbZN8//s7Rvc7P7G5CSmbgmW/ePoHB+Ghge94yQSUMc0" +
                                          "VTm3+rWpbeUndlEy837hf115e+lr//Ls1e151gQzR25452sTOJn/uTb04W9/" +
                                          "8N8fzsnsydl3hpOmygnYtnn9hhPKLc8TN5kcyUf+/KHf+Ib4uTPQHgGd9Zep" +
                                          "mneT924O7/Lr6ofmGZAbZJETkPO7nmfgtvGZPedt/xsBdJecI7GB6AXq9mPG" +
                                          "+3aSFwUH/MhZKidZ/eRrne13OeUTH7jZ3Qi4njh09xP/J3ffrN2h0bLHZQ6w" +
                                          "eRX1P5TdQHW5slU/a8CZKjBANm2fKBu+HmWTAHrw9u3pLAQeuOXr2faLj/zl" +
                                          "F65cvP+F6V/mSXb8VeYSBV3UQtPc7ajujM+7nqptVb20zSs3/3sayHH7iAmg" +
                                          "c/l/Lv5HthgfDaA3vhJGAJ0B913IZwLo6mlIQDH/34X7RABdPoELoPPbwS7I" +
                                          "s4A6AMmGn8yavDvV9jBwchfc+1ouOEbZ7dJmFTr/onlUTcPtN80b8lde6NMf" +
                                          "ehn5wrZLLJtimmZULlLQhW35Oq7Ij9yW2hGt873Hf3r3Vy+9/Wj1uHsr8EkQ" +
                                          "78j21lcuLJjlBnkpSH///t9992++8P28U/m/khaK+GoeAAA=");
}
