package org.apache.batik.bridge;
public interface FilterBridge extends org.apache.batik.bridge.Bridge {
    org.apache.batik.ext.awt.image.renderable.Filter createFilter(org.apache.batik.bridge.BridgeContext ctx,
                                                                  org.w3c.dom.Element filterElement,
                                                                  org.w3c.dom.Element filteredElement,
                                                                  org.apache.batik.gvt.GraphicsNode filteredNode);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1XbWwcxRmeu/N3nPgjxE4T4sThEjUGbhtRiqhDS+LaidOz" +
                                          "fY1DVBzgMrc7d7fJ3u5kd9Y+m7YQpLZRfyBEQoFK8a+gqggoqkD0D1GqSgVE" +
                                          "P0SKWj7El/gFbSTyp2mVfr3vzO7d3tpH/9XSjWdn3nnn/X7eeeYyafVcsp1T" +
                                          "26AZsciZl8nhPEddjxljFvW8w7Ca13/00ZkHrv6x81SStM2RdWXqTenUYxMm" +
                                          "swxvjmwxbU9QW2feNGMGnsi5zGPuPBWmY8+RDaY3WeGWqZtiyjEYEhyhbpb0" +
                                          "USFcs+ALNhkwEGRrVkqjSWm0vXGC0Szp1h2+WD+wqeHAWGQPaSv1+zxBerPH" +
                                          "6TzVfGFaWtb0xGjVJTdyx1osWY7IsKrIHLduDQxxMHvrCjNsf77nb9ceKfdK" +
                                          "M6yntu0IqaJ3iHmONc+MLOmpr45brOKdJN8jqSxZEyEWJJ0NL9XgUg0uDfWt" +
                                          "U4H0a5ntV8YcqY4IObVxHQUSZLiRCacurQRsclJm4NAhAt3lYdB2W03b0N0x" +
                                          "FR+7UTv7+H29v0iRnjnSY9qzKI4OQgi4ZA4MyioF5np7DYMZc6TPBofPMtek" +
                                          "lrkUeLvfM0s2FT6EQGgWXPQ5c+WddVuBJ0E319eF49bUK8qgCr5aixYtga4D" +
                                          "dV2VhhO4Dgp2mSCYW6QQe8GRlhOmbcg4ajxR0zH9TSCAo+0VJspO7aoWm8IC" +
                                          "6VchYlG7pM1C8NklIG11IARdGWtNmKKtOdVP0BLLC7IxTpdTW0DVKQ2BRwTZ" +
                                          "ECeTnMBLm2Jeivjn8vSeh++3D9hJkgCZDaZbKP8aODQUO3SIFZnLIA/Uwe6R" +
                                          "7I/pwMunk4QA8YYYsaJ56TtX7rxp6OKrimbzKjQzheNMF3n9fGHdG9eP7bo9" +
                                          "hWJ0cMcz0fkNmsssywU7o1UOlWagxhE3M+HmxUO/ufvBp9lfkqRrkrTpjuVX" +
                                          "II76dKfCTYu5+5nNXCqYMUk6mW2Myf1J0g7zrGkztTpTLHpMTJIWSy61OfIb" +
                                          "TFQEFmiiLpibdtEJ55yKspxXOSGkHX4kAT+NqL9tOAjCtLJTYRrVqW3ajpZz" +
                                          "HdQfHSprDvNgbsAud7QCxP+Jm3dnbtM8x3chIDXHLWkUoqLM1KZWcE2jxLQJ" +
                                          "04Jw2ic/Mhhu/P91URU1Xr+QSIAzro+XAguy6IBjGczN62f9feNXnsu/rsIM" +
                                          "UyOwFRQvuC2jbsvI2zLqtkz0NpJIyEuuw1uVt8FXJyDroex275q99+Cx09tT" +
                                          "EGZ8oQUtXZVpuDn8gIMx6WTC3zHLz731+09uSZJkvTb0RIr6LBOjkXhEnv0y" +
                                          "8vrqchx2GQO6957InXns8g+PSiGA4obVLkzjOAZxCMUVitT3Xz359gfvn38z" +
                                          "WRM8JaAg+wXANkE6aAGqGdWFIJ21sqQUu+4/8JeA37/xhzriggqx/rEgzrfV" +
                                          "Ap3ziDkScr5RkKFmhlcmR6ttaVY4ZNE7/9DZZWPmqd0qvfsbk3EcsObZP/3r" +
                                          "t5knPnxtFa93CoffbLF5ZjWI5pLhFd3DlKyrIQrn9dsuXU29++jGbum17gI0" +
                                          "DnX0Tjegt2o+XEdnBsBHMxwPsWykOXLHRXjloU83Hf5a+ZgUIYrFyKsVYARP" +
                                          "5hBBa9y3xkwZZ/mzqWde279TfzQpwQML8Sqg03hoNGpUuNRlgJI2qoUra6vY" +
                                          "isVyMm6LvD6yjb6Yf/m76SRpATQBBBUUKh6A01D88gYAGA0TBq/qACMUHbdC" +
                                          "LdwKEbBLlF1nob4ii0Wfil9w9hoM10H4jQQlUv7H3QGO46AqLpJ+SI7DOKRl" +
                                          "pCRxugOHnZLsixA5O+s5CTXdgnKHHknfZYOzzaJJCxbDavHPnh27X/zrw70q" +
                                          "KC1YCV100/9mUF//wj7y4Ov3XR2SbBI69hT1ulEnU0C1vs55r+vSRZSjeurS" +
                                          "lidfoecA8gBmPHOJSeRokfq1hEm64/OTNGikQur1SL1wi54xnEoG+0VmS+3G" +
                                          "Q4LhFexK8yKz36W8bOreNGSFNOc+SX+HHPeiW4JCit8HcbhdQLflMiguqkqH" +
                                          "/L+0gj/mEl0QGbMCDUsG4gfwAC0ZlHcwTrpJ3kWa17z+yJufrT3y2YUr0tyN" +
                                          "3W+0YE9RPqriDIevYg0bjEPGAeqVge7LF6fv6bUuXgOOc8BRB+DzZlyQrtpQ" +
                                          "3gPq1vZ3fvXrgWNvpEhygnRZDjUmKPaZ0C1AmDOvDEBX5V+/U4XyQgcMvdJk" +
                                          "ZIURMSC2rh5q4xUuZHAs/XLwhT0/XX5fIkMVjB0FQ2SwcUXjrZpF/bnlno7B" +
                                          "5bv+LPO51tB1A4oVfcuKlIto6WjjLiua0nDdynxc/rtbkMEmAQhApSZSv28r" +
                                          "+nvgTRSnF6RV/o/SQU/bVacDVmoSJSkIkgISnOqcVxONgI4f0zhsUPNvNbV8" +
                                          "pAe4oSHQ5AMnLMa+euLk9Z8vH5y+/8pXnlItATyNlpZkQwz9vapwtYI+3JRb" +
                                          "yKvtwK5r657v3JEMMqdPCVwva5sjaXUE4I+jZzfFaoWXrpWMt8/vufC7022X" +
                                          "IGSPkgSFfD8aeV6oXhoKjg/xdTQbxdHIM1mWsdGuj4/94e/vJPplfAXIO/R5" +
                                          "J/L6mQvv5oqc/yRJOidJK8A/q87Be8n7xqJ9iOnzkAkdvm2e9NkkPMXaCo5v" +
                                          "195C6zAMKT5+pGUCg66trSIsCbJ9xStnFeSG1FuAPEDuEuRiEOhzHt2t4hth" +
                                          "Fa3AN7vP/eOBH7w1A2nSIHiUW7vnF2poGn1qKd449krwqarOK5XPTnEedGKJ" +
                                          "U9KrnEsw86XSnqJGCkESI5z/F3bw/aEyEQAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczk1l3eb+/NsZukTUKaO5uKxO1nz+kZbSn13PbY45nx" +
                                          "eA4D3fi2x/c5nmkDJQhaUalEsClFavNXKqBKDyEqkFBREIK2aoVUVHFJtBVC" +
                                          "4mgrNX9wiALl2fMds99mE/UfRrLn+b3ffT2/n1/9PnQ2DCDYc621ZrnRvpJG" +
                                          "+0ursh+tPSXcJ6nKUAhCRW5aQhhOwNx16ckvXP73H76oX9mDzvHQfYLjuJEQ" +
                                          "Ga4TjpXQtRJFpqDLx7NtS7HDCLpCLYVEQOLIsBDKCKNrFHTHDmoEXaUORUCA" +
                                          "CAgQAclFQPBjKIB0l+LEdjPDEJwo9KGfh05R0DlPysSLoCduJuIJgWAfkBnm" +
                                          "GgAKF7LnKVAqR04D6PEj3bc636LwSzBy4zfff+X3TkOXeeiy4bCZOBIQIgJM" +
                                          "eOhOW7FFJQhxWVZkHrrHURSZVQJDsIxNLjcP3RsamiNEcaAcGSmbjD0lyHke" +
                                          "W+5OKdMtiKXIDY7UUw3Fkg+fzqqWoAFd7z/WdathJ5sHCl4ygGCBKkjKIcoZ" +
                                          "03DkCHrsJMaRjlf7AACgnreVSHePWJ1xBDAB3bv1nSU4GsJGgeFoAPSsGwMu" +
                                          "EfTQbYlmtvYEyRQ05XoEPXgSbrhdAlAXc0NkKBH09pNgOSXgpYdOeGnHP98f" +
                                          "vOdjH3B6zl4us6xIVib/BYD06AmksaIqgeJIyhbxzmepjwv3f+kjexAEgN9+" +
                                          "AngL8wcffP1973r0ta9sYd7xBjCMuFSk6Lr0inj3Nx5uPlM/nYlxwXNDI3P+" +
                                          "TZrn4T88WLmWeiDz7j+imC3uHy6+Nv7zxYc+o3x3D7pEQOck14ptEEf3SK7t" +
                                          "GZYSdBVHCYRIkQnoouLIzXydgM6DMWU4ynaWUdVQiQjojJVPnXPzZ2AiFZDI" +
                                          "THQejA1HdQ/HnhDp+Tj1IAg6Dy7oFLgQaPt7PLtFkILorq0ggiQ4huMiw8DN" +
                                          "9M8c6sgCEikhGMtg1XMREcS/+e7CPoaEbhyAgETcQEMEEBW6sl1ExMCQNQXp" +
                                          "GBYIp0b+sJ+Fm/f/xSjNNL6yOnUKOOPhk6XAAlnUcy1ZCa5LN+JG+/XPXf/a" +
                                          "3lFqHNgKFC/AbX/LbT/ntr/ltr/LDTp1Kmfytozr1tvAVybIelAP73yG/Tny" +
                                          "uY88eRqEmbc6k1k6zdPwwfzhNMB75vY1upMVCCIvihKI2Qf/i7HEF/7hP3NJ" +
                                          "d8tsRnDvDfLiBD6PvPrJh5rv/W6OfxFUpEgAEQSS/dGT2XlTQmVpetKCoNAe" +
                                          "0y1+xv63vSfP/dkedJ6HrkgHVXwqWLHCKqCSXjLCw9IOKv1N6zdXoW3KXTvI" +
                                          "9gh6+KRcO2yvHZbMTPmzu54D4ww6G1/Ko+DuHOaeH4HfKXD9b3ZlnsgmtrF/" +
                                          "b/MgAR8/ykDPS0+diqCzxX1sH83wn8h8fNLAmQA/xXqf+pu/+JfSHrR3XMYv" +
                                          "72yMwAjXdkpHRuxyXiTuOQ6ZSaBkxvr7Twx/46Xvf/hn8ngBEE+9EcOr2T2T" +
                                          "GOyDYD/55a/4f/vtb73yzb2jGDsdgb0zFi1DAoMw39aAJqrhCFZukCcj6IGl" +
                                          "JV091HoKtjkg2NWlheWmejvY2HPRMq/sb/eGPJ2ARFdvE647+/l16cVv/uCu" +
                                          "6Q/++PVbIvVmw9CCd23roVyqFJB/4GQW9YRQB3Dl1wY/e8V67YeAIg8oSqAW" +
                                          "hEwAEji9yYwH0GfP/92f/On9z33jNLTXgS5ZriB3hGzrBQU00sFurYPcT72f" +
                                          "ft+2AK4ugNuVPDehXP93bMXJ0/ruY0NQLtgiP/qPL3791576NpCDhM4mWQwD" +
                                          "CXasNYizt4ZfefWlR+648Z2P5j4B5Xb48faV92VUazmDp/P7T2Y3eOuxbPiu" +
                                          "7Pbu7LZ/6KaHMjexee2jhDCiXdkAbw1y7qk3LR3DwLBBtCUHWyLy/L3fNj/5" +
                                          "z5/dbncn68QJYOUjN371R/sfu7G385Lx1C37/C7O9kUjF/quI1c+8WZccozO" +
                                          "P33++T/6nec/vJXq3pu3zDZ4I/zsX/3P1/c/8Z2vvkFtPmO5h0GZ3YsHbLO/" +
                                          "yls7Nrr0vV45JPDDH1WYi7OVlI5tJUYGJWeoLdN2eVIOJ3p7yXVFPRobvt5i" +
                                          "YUowZGajLgqtaWOj0YGEyZhKluKKKdcXsI0tRh7Fj9V1oz1yO/2aAGu+prm+" +
                                          "2UJbha7PatP2EGX7syXWthCtI7LAFkV7qgalZMNgcinyekh9zi5nslNyHAeZ" +
                                          "Y4qiLNaCOpVCrzApVnE+lAzeqjn6sC3Ly9RadpJZbYU1hUIJQVHe7AVJNa0V" +
                                          "WDaii2N5NvcnisMtUtoOV2mytFepyNVHs6KqDLp01wmNyqY7jIeNmb2oweOW" +
                                          "sCjNlO7M5yNjvWwv2vpaFz0R5diOFMI4NdDNVbs7Dqamv2RnNprMu02U3XgF" +
                                          "vQjPWvDKV3r4rDsaCmxSgDdpQwmGvepkM1W7HWEWiWjaXU7JibxOC244W2BE" +
                                          "2A+IHiXHrVGa0r0kaC4HoYphjliXlL4q9+nq2olilPAFsmT0bGYgwTTF2F5Q" +
                                          "rogB05fJQW3psynfXrdnJIkOqPpc4zQ0bqmziCv3UKEC9pnaQvIXZYIRp2lv" +
                                          "xLE8ZYybghQHo3EoWaRdHuA6HpWshdwoztCSiA7QtDOGMW6SYHCvWE9QY+ws" +
                                          "HXZR9zd9osyMNKPM42V6bbidiuNhrQXNS9XJsOGqQzpSTCswOYVKVBoNi51J" +
                                          "tT3qarP5cFSR4JksT+MGibZLhbrSKddFrl/ztWZQEYx0EWlCuSVPi1NdZ8ot" +
                                          "DUQF21zMqqORUuuOLZ2xRUkrC8t0jG569QnbxF0YnZKhx2CCO7NrRLM6lfSF" +
                                          "1cU8utCsDUyL6BYKBD6Wu7NoYPf7ESNPh2iDopoYkU48eTJDW9P+qNgYryZ8" +
                                          "u6lMHLpB2UVSMZKlU0tYRYfhUquuk6bW5FsCL/aHNYFpjTimxBId3qEIHOFW" +
                                          "SnWMEYi3omPHLI/w2mKxCAWyUp1EcyxIvSrTB0kvbvrL0UZXBnSn5NTVbk/u" +
                                          "1pUhJrp1fUaiEi1tUNUc2GEYrlcc5hY4xpoJWqq3SzTcs1OOQWI1aXh1SzX9" +
                                          "cWAGE28ZT+cEgVXlvtqcLOIKXHEG86a/oDmzas+K9FotkKiGbYKuuYkm3oTq" +
                                          "efSEJGbsulpgVEKcdEbtjm0YlGeIctQmK5V1P/TSOcN2zd68bOITeOBT9YjB" +
                                          "l82IIicLEPL+rCQsPX7Tk0dqj/WCVjLQxBCPZWzUTIcwaZdkR4zoWlqSdKI1" +
                                          "71Ezk3N9ii70+ZnULi5TakSiZXJVNCSE1vUYGdYL3JgrzAN4xBL4JnDhOa7F" +
                                          "6yrRWHalzaBaVOsgS+dOGCNBSNDcmll1xqMkbhaXYpgQxQ3lR+YGHXgksW7H" +
                                          "8aoQT6NaZ06uW4GrpEWs4tfrcDNF69Gk3eVr7oiL5vzUi1tOTSPotDqbNEub" +
                                          "HrXBSgUYrccsT5rJRETHRFClGszSnOttJ0HXtSTwJT0tdkdMtV7BCAdIVNPg" +
                                          "IWt08bIrTilzs2RwPm3S3NSIJqX5plSpa2rilGqb2ZiukQKuwas5PjDbVQHv" +
                                          "+l151iHIYiH0R1wMl5EaqeAlDEn1TWBomp8iQVvbBOoU90obo2WyUlAZm/2O" +
                                          "rVuSPa5GkTBdlPlBG0PqLZ6fDW1fRv1EDUWz1JZCRuSHSCmIKqYzdNKoI9RL" +
                                          "TXA+EqlOhV/OiIpH6R251LL664AYBU5dDuM5V6zD8LIrxnYB0wi05czRyVLR" +
                                          "oiJwSFt2GmGjR6erYThbm8yc6o3nS8vlaqWeWhFgXuOIRdAB0TNd4ONhRW80" +
                                          "hPq6lJornkfsjT+TlSJWn6ibkbca0VSN9TW0pLuDrsfFg7GlkUTRd7lAqCYL" +
                                          "I5yuabtKJa3qeilWFypiY1V27OGTUaPR4Li+XsXRQqtW0xZ4F0cnDR/xcWD0" +
                                          "nig3KXnVb4sNyuoUHFcsGwY6A4fB+qquu3QB7ZWXo5HFJVivNOoy5SruUx4J" +
                                          "swTWYvpjy2uO01hjeg5PhUaKVxg4rDQnc1lz+r2e6aj8gtlsBJJspmJLSHpD" +
                                          "Ry9ic2QTrDDU7zcLi+a0gKJI3eY6CLJaYusyk5Tm4yIrNohqXZ8UYqvtcGiz" +
                                          "kISVSgAn7Jhnl0ocsJYhq64i4TWtYQ97DMkqY9dU/YLetqtlhJkMuoY5ioMC" +
                                          "SxVWRqWcOm23C0qezcKl7qgM/Kik/dq6vylVZzWRCcB+xnYGjASzc7jXGyrG" +
                                          "rEw2jajWk0RdHlGqRRta7Jt+D6FgVFsidttCR12Rbra4sFvW1BXeRHmrJ60m" +
                                          "gUeWzJlQwDbwmozVYFJaFxdcgEbrQWkGo4t2fTz0A6NFKMlCQ8Vle9jFFX+q" +
                                          "KRjVqapJVeTiucYwUq0xbsCtDW+tR0HkjUra0C8kfElN5oE2GyQe2Fw1Z8y3" +
                                          "lpzdHwo8MBFut5ik1W7MK1MY4crz9UiT6EQmTZ7gxjTbLAZ6xS+nXMz38BCZ" +
                                          "Uyt9giLzeUUlTHq6bKCdUZFdSdx8GfBeBxEdy3GxRkVMYGrIVApRowASdqpK" +
                                          "cd8iIrc6Wy4pIxZQpyWvnVRCgkg06baNj3TcY3k2KdYC2Em0yZh1OtXxFHER" +
                                          "dsQh4lSQWlPbZUnWJEyNYB3Gl6YpM9CIsopu9JAbDpKBOK15uFJ22d6ogtMO" +
                                          "RQuwElNmna8lvcoaRmre3AFC4JP1wPJ4c7Ta1BPBW0ULAi6RY3HdT6JVvxJU" +
                                          "K1hSIts07cvD5nSVCJVwKcy5dpmAl/xG7YCtbx54MzqqIUmsNjG0WJwTXXZo" +
                                          "amxHbdUEZVp157rbX2pIKk9GYir3CLpgz0K5Gy/LSL2sIAk59CwVnxMMMq6Q" +
                                          "CFW1R0lScX0JWY9JxpDJfg1H/BrWUGoOlvpk3WCcjYmbcmIXlfrANIf0XGi6" +
                                          "laRQrzSrG5zuTyqw1+WaWrUaBSwRNkWynrKR01HYbqET48N2K27HY6PN6Jte" +
                                          "VIzKeqR3hBI+wJIhojCNHrYq4EWHJXoGN8MSp1P03K5T8PtyuVw3g5UvgDef" +
                                          "ynw4cdqK3O2TXL0fOO1wVavOWccnu02zzRKVDdIpiStEAG9GIxzPXnuJH+/k" +
                                          "cU9+QDzqJIIDR7aA/hhv3OmbMYygC4IYRgE4lkXQxaPW5pb7Tofk1OGB9NHb" +
                                          "9WK2XZjswPHI7XqJ+WHjlRduvCwzny5kh42MZgvwjVzv3ZaSKNZNHAPo2dsf" +
                                          "rOi8lXrc/PjyC//60OS9+nP56f+WpgwFXcowh1nH+qgz/dgJOU+S/F361a92" +
                                          "3yn9+h50+qgVckuT92akazc3QC4FShQHzuSoDRJAT95yGnMlRY4D5Zjvs48L" +
                                          "X7z+peev7kFndvtDGYVHTnRb7lDdwBasjMFhV/kSOFm7q+OZ3dYLMOsdWVA8" +
                                          "AK5nD9qO+X+2ep+X3d+WHofWLTGzdxSk44MICaB3Hp/6m65lKVJu9aucY+eH" +
                                          "ZEG0lKwD99+Xny588Xsfu7I9Qlpg5tAN73prAsfzP9GAPvS19//HozmZU1LW" +
                                          "pz/uYxyDbZu/9x1TxoNAWGdypL/4l4/81peFT52GThHQmdDYKHk39kyu35nD" +
                                          "KH/6zaP84OPEIfR9GfSqJO3Lrr2ffZFRnFw78xDgiVvIaUm03w0ETzekcODK" +
                                          "24TTc3gpv2t5Gm87ldlz7pzrEXSnFChCpGw7n4f00VvoZ/kirKJ9wxaA1IHi" +
                                          "yEqQWXJ/BzGvHM+91Vl9V5AU8N/tuWZGfvCW7zvbbxLS516+fOGBl7m/zsP4" +
                                          "6LvBRQq6oMaWtdsm3Bmf8wJFNXKNL24j18v/1hH0wG18EkHntoNc3HQL/8EI" +
                                          "unISPoLO5v+7cL8QQZeO4QCp7WAX5IUIOg1AsuEvZd3InRp1UFtzQ977VoY8" +
                                          "QtltJ2Z+yr+jHdagePsl7br0+ZfJwQder356286ULGGzyb+7UND5bdIf1bEn" +
                                          "bkvtkNa53jM/vPsLF58+rLl3bwU+zvQd2R5743Rs216UJ9DmDx/4/ff89svf" +
                                          "yltq/wcByqsN4BwAAA==");
}
