package org.apache.batik.ext.awt.image.renderable;
public interface DiffuseLightingRable extends org.apache.batik.ext.awt.image.renderable.FilterColorInterpolation {
    org.apache.batik.ext.awt.image.renderable.Filter getSource();
    void setSource(org.apache.batik.ext.awt.image.renderable.Filter src);
    org.apache.batik.ext.awt.image.Light getLight();
    void setLight(org.apache.batik.ext.awt.image.Light light);
    double getSurfaceScale();
    void setSurfaceScale(double surfaceScale);
    double getKd();
    void setKd(double kd);
    java.awt.geom.Rectangle2D getLitRegion();
    void setLitRegion(java.awt.geom.Rectangle2D litRegion);
    double[] getKernelUnitLength();
    void setKernelUnitLength(double[] kernelUnitLength);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1445630120000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAMUZa5AUxbl3733ccQ/kIY/jdRBB2Q0Go+SUCAfnnezB5U4x" +
                                          "OQJH72zv3sDszDDTe7dgEDVlJP4glmKiUa/ywJhY+EiMFU1KxUoiUkQt0Yqi" +
                                          "EaL8MAatkh8JGmPM93XP7MzO7i1acMlVTV9v99fd3/v7+ut975MK2yJzTKon" +
                                          "aIRvM5kd6cF+D7VslmjXqG1fBaMDyi1v3b7z1Ms1N4RJZT8ZP0jtboXarENl" +
                                          "WsLuJzNU3eZUV5i9hrEEruixmM2sIcpVQ+8nE1W7K21qqqLybiPBEGAdtWKk" +
                                          "iXJuqfEMZ13OBpzMjAlsogKb6PIgQFuM1CmGuc1bMDVvQbtvDmHT3nk2J42x" +
                                          "zXSIRjNc1aIx1eZtWYucbxratpRm8AjL8shm7SKHEVfGLipgw5xHGv758a2D" +
                                          "jYINE6iuG1yQaPcy29CGWCJGGrzRVRpL21vJdaQsRsb5gDlpjbmHRuHQKBzq" +
                                          "0utBAfb1TM+k2w1BDnd3qjQVRIiT2fmbmNSiaWebHoEz7FDNHdrFYqB2Vo5a" +
                                          "V9wBEu84P7rnBxsbf1VGGvpJg6r3IToKIMHhkH5gKEvHmWUvTyRYop806SDw" +
                                          "PmapVFO3O9JuttWUTnkGVMBlCw5mTGaJMz1egSSBNiujcMPKkZcUSuX8qkhq" +
                                          "NAW0TvJolRR24DgQWKsCYlaSgu45S8q3qHpC6FH+ihyNrasBAJZWpRkfNHJH" +
                                          "lesUBkizVBGN6qloHyifngLQCgNU0BK6NsqmyGuTKltoig1wMiUI1yOnAKpG" +
                                          "MAKXcDIxCCZ2AilNDUjJJ5/311y6+1q9Uw+TEOCcYIqG+I+DRS2BRb0sySwG" +
                                          "diAX1i2MfZ9OenJXmBAAnhgAljC/+dbJyy9o2f+chJlWBGZtfDNT+ICyNz7+" +
                                          "pentC5aWIRrVpmGrKPw8yoWV9TgzbVkTPM2k3I44GXEn9/c++43rH2AnwqS2" +
                                          "i1QqhpZJgx41KUbaVDVmXcF0ZlHOEl2khumJdjHfRaqgH1N1JkfXJpM2412k" +
                                          "XBNDlYb4DSxKwhbIolroq3rScPsm5YOinzUJIVXwkRB8CSL/5mPDyc7ooJFm" +
                                          "UapQXdWNaI9lIP0oUOFzmA39BMyaRjQO+r9l0eLIxVHbyFigkFHDSkUpaMUg" +
                                          "k5PCTukwj6ppUIYoCCcBhMU1Fl2pJpMZm8XU1CAHlevFwQgqovn/RyGLXJow" +
                                          "HAqBAKcH3YcGltdpaLDJgLIns2LVyYcGDknVRHNy+MvJMsAjIvGICDyEswU8" +
                                          "IgKPiIdHpBgeJBQSx5+D+EjdAclvAR8CTrxuQd+GKzftmlMGSmsOl6PcssKo" +
                                          "p7k/YGEAb+E+Lusz733thXe/FCZhz9M0+EJEH+NtPu3GPZuFHjd5eFxlMQZw" +
                                          "b97Zc/sd79+8XiABEHOLHdiKbTtoNbhqcHk3Pbf1yLGje18J5xAv4+DeM3GI" +
                                          "lJxU0zj4RqpwTmpyTk4Sds6n8BeC7z/4IY04IBW2ud2xmlk5szFNHztCoj+F" +
                                          "kxWfXSQdqgbng90ZVhdiArQJX4+cnTGaqxJudu+Ne0YSa+9bLB1Kc775r4Lo" +
                                          "9uCfP/lT5M6/HiyiMzXcMBdpbIhpPvTr4MjZBflKt/DkbtwfUC4+fKrsjdum" +
                                          "1AnJ1sUhVfHyhda8fEGmO5ahsAQErNEyBzd6Lhw9VwiicODGv0+9atngJoGC" +
                                          "P/rjXhUQuHBlD8bs3O4zA6wMbvmL7n0Hr5iv3BYW4Qpdf5Ewl7+ozc9UONRi" +
                                          "EJd1JAtH6rOY/AUsOsiLAWXhLPrYwJM7WsOkHOIXxGxOwcdCOGwJHp4Xctpc" +
                                          "o8KjqoEJScNKUw2n3JhbywctY9gbEa6mSeo4CHscqjR2FjpOWfzH2UkmtpOl" +
                                          "axLwLaKdjU2r0JQwdudhM1+AnQeaM9+zW9BmDdwoSqT1ah2ErSZVVHb0KP9u" +
                                          "mLf4sfd2N0ql1GDEFdEFp9/AGz93Bbn+0MZTLWKbkIJZjOdbPDAZGid4Oy+3" +
                                          "LLoN8cjecHjGXQfovRBkIbDZ6nYmYhVx/BoitUKQfZlolwfmVmKzFAwpxXif" +
                                          "jAeO7X/x89o+INg6iu77UtYB5dZXPqhf98FTJwXJ+Tmv37F2U7NNyhqbr6Af" +
                                          "mRx07Z3UHgS4JfvXfLNR2/8x7NgPOypAhL3WAuyyeW7Yga6oev2Z30/a9FIZ" +
                                          "CXeQWs2giQ6K2SXkCKBqzB6EUJU1v3q5VKfhamgaBb9IAQdRKDOLi3tV2uRC" +
                                          "QNsfn/zrS+8fOSo8uNjhwpzyil1a4Is6yhs9I+XNF3NI+nL82SEA1pXQg69j" +
                                          "8zXQAzunBxZZUOLaY6lpCHhDTuIY3dF8bMs9f3tQ+vBglhkAZrv23PJpZPce" +
                                          "aToyFZ9bkA3718h0XCDaKEjNChdf4hSxouOdh3f87uc7bg47REY4KR8yVJnO" +
                                          "d2LTK4Pl6s8mbRzoCYiwFqea4VviiHDJWRShX0Jqibkt2AAXq8GKRVLkGnHr" +
                                          "aYzYAxbsYGfMjpxGL3XYsXRsNDotAIZL8GQbNhCAqm2HJ/h7g0erfca0itAz" +
                                          "Fb5lDq3Lxkj03y4xdxM214HrRAeeEQlgn0I1JryxLwfCokpfBtLFgDE+POnU" +
                                          "1j9UbV/pXueKLZGQq+3uF3/b+c6AyFaqMWHK5Qi+VGi5lfLFadda8V+/r78R" +
                                          "ktiEAVksCwpX3AADSMjzKxff+9HO77y2FlKMLlKd0dWtGdaVyE9equxM3IeV" +
                                          "d5EWA36UMBvmJLTQNLOeTuw8O/q/CL52Ryfax0b/vysA7iqhGHdjswcUw85X" +
                                          "jIAZ3HF2zABXdDokd46RGdxXYu5+bH7ESQWYweqE4JBH44/PjljPha/bobF7" +
                                          "LMX6yxKEPorNPiDUdgn1CfPBMyZUAE+Hr9chtHeMhPlkibmnsXmckzoRzngv" +
                                          "S7mXIghp54p8C0NYihnpSC8kXFRPaezClR4fnjg7Ar8AvmscPlwzNgJ/RgAc" +
                                          "KsGM57F5Fphh+5gRkPuBM6Z3PE7Nhm+DQ++GMZL7qyXmjmBzmJMJaMTM0pl2" +
                                          "ta7yGNNTfNDGunSx4CRuQjJCPDHh3UcPbqo6ImNZ8fAXqHi+fe2hnxh/ORF2" +
                                          "U8RdOY5MczmS59Y4SYxJqQ11OdqeiauKW9L7n5yDefS80bN8H29Hfjb3hZ0j" +
                                          "c98Sd6xq1V5HLQj1RerQvjUf7Dt24nD9jIdEUaAcMwZkbn2wgF9Yn88ruwu5" +
                                          "NGBzNOs59vyUYVZBuUe8O3n1iffeuPv406d+WiVVo8TFJrBuyr/WavEb3/6w" +
                                          "4LKKOFQUuesE1vdH990ztX3ZCbHeq4vg6kuyhbVS4Kq39sIH0v8Iz6n8Y5hU" +
                                          "9ZNGxXnjWUe1DFYT+4FvtvvwEyP1efP5bxSyIN+WKwhND162fMcGKzL+7Kqc" +
                                          "52VSTVImISI8xIlSvgHiVVLVqSbdAyR/mjRq/BnIC8tAG7B73EnMUNBhuZUb" +
                                          "AmQdBEmLtGuGzqibR8KcLP+qRiT34gST2QKVEd7P06njxZEXLnreaX3aJyXm" +
                                          "PsXmI6BfQUwlYaODh8LSO/vcti9YfM+Xqr58dkLcJfApjoNTxibEvSkIqytB" +
                                          "9HhsqkCudqHfz490oerPT3YWlKLYgwEWb6YUPHXK5znloZGG6skjV78qXZf7" +
                                          "hFYHF59kRtP8NuHrV5oWS6qCH3XSQkxB30ROFnzmahrHCqz7A0kKnSN3AeVu" +
                                          "Kb0LaJn47181jZMpo60CY4PWD90CvCoGDZDQ+iFnc9IYhITzxX8/XCvQ48GB" +
                                          "5cuOH+QLsDuAYPc8uI5J48w9zOQ0fuLpRO97y5mb5+DFs7ebCGTkwzfcfEeu" +
                                          "XHPtyS/fJ592FI1u3467jIPwI6vQTvjxV5qCu7l7VXYu+Hj8IzXz3DSiSSLs" +
                                          "GdA0n0voAcMwUfumBuq5dmuurHtk76VPPb+r8jDEjfUkRME21hc69KyZscjM" +
                                          "9bFi92Vw6aLU3FZ7fNOLH74eahb1RydctpRaMaDc/tQbPUnT/GGY1HSBSoEy" +
                                          "ZkW0WblNh3R7yMq7flfGjYyei+Xj0VQoPokLzjgMrc+N4tMBJ3MKq32Fryu1" +
                                          "mjHMrBW4u5M25D1TZEzTPys4u1uGEpmolQ3Euk3TefWqrBGcN030CaGlwpv+" +
                                          "F1KaxWnbIgAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1445630120000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAMV6Ccwk11lgzeHxeGJ7xnbiOCZ2EnsSrVPJ30d1d3XJYFLV" +
                                          "XV1HV3VXV98NYVL30XUf3V3FZgmRIAGkEC0OCyx4tSLsLpEJ0Wqzu9pdVmFX" +
                                          "QBBsJKKI5U5ASBwhKEHiDNer6v+af8ZjosmIlt7rqve+973vfq++917+EnRf" +
                                          "HEFw4DuZ4fjJgbZLDmyneZBkgRYfsFxTkKJYUzuOFMcT0HZDeeYTV//iqx82" +
                                          "r52HLq2gxyTP8xMpsXwvFrXYdzaaykFXT1pJR3PjBLrG2dJGqqSJ5VQ4K06e" +
                                          "56DXnBqaQNe5IxIqgIQKIKFSklDBT6DAoIc0L3U7xQjJS+IQ+lfQOQ66FCgF" +
                                          "eQn0lpuRBFIkuYdohJIDgOFy8T4DTJWDdxH05mPe9zzfwvBH4MqL/+bbrv3n" +
                                          "C9DVFXTV8sYFOQogIgGTrKAHXc2VtSjGVVVTV9AjnqapYy2yJMfKS7pX0KOx" +
                                          "ZXhSkkbasZCKxjTQonLOE8k9qBS8RamS+NExe7qlOerR2326IxmA18dPeN1z" +
                                          "2CvaAYNXLEBYpEuKdjTk4try1AR609kRxzxe7wMAMPR+V0tM/3iqi54EGqBH" +
                                          "97pzJM+ojJPI8gwAep+fglkS6MlXRFrIOpCUtWRoNxLoibNwwr4LQD1QCqIY" +
                                          "kkCvOwtWYgJaevKMlk7p50uDb/zQt3u0d76kWdUUp6D/Mhj09JlBoqZrkeYp" +
                                          "2n7gg2/nflB6/Gc+eB6CAPDrzgDvYf7bv/zKu97x9Kc+vYf5htvADGVbU5Ib" +
                                          "ykflh3/ljZ3nsAsFGZcDP7YK5d/EeWn+wmHP87sAeN7jxxiLzoOjzk+JP798" +
                                          "38e0L56HrjDQJcV3UhfY0SOK7waWo0WU5mmRlGgqAz2geWqn7Geg+8EzZ3na" +
                                          "vnWo67GWMNBFp2y65JfvQEQ6QFGI6H7wbHm6f/QcSIlZPu8CCILuBwU6B4oK" +
                                          "7X9vK6oE+o6K6btaRVIkz/L8ihD5Bf+FQj1VqiRaDJ5V0Bv4FRnY//qdtQO0" +
                                          "EvtpBAyy4kdGRQJWYWr7ztJPpW1SsVxgDBWgHBUwJjtapWvpehprnGWYCTA5" +
                                          "sWg8KAwx+OcnYVdI6dr23DmgwDeeDR8O8DzadwCSG8qLKUF+5eM3fun8sTsd" +
                                          "yjeBXgB0HOzpOCjpKEMvoOOgpOPghI6D29EBnTtXTv/agp697QDNr0EMAdH1" +
                                          "wefG72bf88FnLgCjDbYXC73tSqd+ony5AMY998oRv1eEG6YMsQrwgCf+ZujI" +
                                          "7/+9vyp5OB20C4Tnb+NlZ8avKi//6JOdF75Yjn8AxLdEAvYIQsfTZ339Jvcs" +
                                          "nP6sbEHYPsFb/5j75+efufRz56H7V9A15XBNmElOqo01EJevWPHRQgHWjZv6" +
                                          "b45pewd+/jB2JNAbz9J1atrnjwJwwfx9p3UKngvo4vlKaR8PlzCP/AP4nQPl" +
                                          "74tSaKJo2HvSo51Dd37zsT8Hwe7cuQS6r36AHlSL8W8pdHxWwAUB3zQOfuzX" +
                                          "PvNHyHno/MmicPXUMguE8PypQFQgu1qGnEdOTGYSaYWwfvuHhB/4yJc+8C2l" +
                                          "vQCIZ2834fWiLigGqypYnb7r0+Gvf/53Pvq588c2diEBK3EqO5YCHuJykQSc" +
                                          "6JYnOaVAnkmg19uOcv2I6xlYNAFh120HLUX1OrBNKEkrtHKwX2lKRwMUXX8F" +
                                          "cz21O7ihfPhzX35o9uX//ZVbLPVmwfBS8PxeQyVVO4D+9We9iJZiE8A1PjX4" +
                                          "1mvOp74KMK4ARgXEj3gYAb/c3STGQ+j77v+Nn/2/j7/nVy5A53vQFceX1J5U" +
                                          "LOQgHCcmWPtNEBV2wTe/ax9Ot5dBda30Tajk/xv25JRu/fCJIDgfLLjf9/sf" +
                                          "/uXvf/bzgA4Wum9T2DCg4JS0BmmxB/nulz/y1Gte/ML3lToBwVv4QfLauwqs" +
                                          "7XKCt5b1vygqeK+x4vEdRfXOojo4UtOThZrGZbzkpDjhfdUCexC11NQdQ4cQ" +
                                          "WS6wts3hAlt576OfX//oH/7UfvE8GyfOAGsffPF7/+HgQy+eP7VlefaWXcPp" +
                                          "MfttS0n0Q8eqfMudZilH9P7gp9/7P//Tez+wp+rRmxdgEuwvf+pX/+6XD37o" +
                                          "C794m6h90fGPjLKo64fTFn/NV1dscvVv6UbM4Ec/frqSmvh0JzsIiiCKMqqs" +
                                          "mWXFVkWCqI+qlA+Ppx1c9zwtJ5rTxm44Ymm0nm+QuBvn3e5EQ1WD7M4cVmgY" +
                                          "jtu3plIl27LmEiYtvjet9XdT35quR0l1GVqkxLV5XErWZpulXIHHkIWA8vkQ" +
                                          "tWqSwjuzyQzbYJiuIpUNCqcJhjb5fj1j80nf9yRG3PDNtdpSenAXncWOay9C" +
                                          "qqYTEt/NrNoGkdG8xse1QUNkV5P2SqjaiewvpIgcOPOYS9l8MEW01XTWtDAz" +
                                          "IskotXYuX48ZJZiN4LZH1uZov14Lw5DLZEsgSApXk3l/bS3YNNRJflVDhkSQ" +
                                          "8zbuxL7Rl1sCY4x6KV/ruFSq1GS+O9uM5GTTdekJ4q3rbKO+yxdjRrQHSk1i" +
                                          "djVtlcyXqSLvQOQKRLeN21w7Nl103KfJmU5xVmBsmzua2qDNtlTv2ktmQLas" +
                                          "lKplI0lQsjrWoeYdlqKiXJyJAVevbVhVGsViLDeNrhPYskuLKT3qE3lYTRMC" +
                                          "1+XahIfX9W2N6HoqEtqjmchYk7ruyu5gbElzTaZ9Mkd73QGtRr1lSNRnflOa" +
                                          "YVuCTNsNAY08YhfLem1GUZuANVoRwkz8PsPT5ppuGn1yQ7vz6WaSiUs/aFdb" +
                                          "4+5WcKVg1hsiQ4xNk2Q+nXhrasYTTmfbdCeUxPJ5TTPGY2JgpbbCC/31SpmO" +
                                          "00U7XJvhAJ9XJxvWd0Sx3ugao3k/7iwdaWykjea4HSIhHXRaPRq2zGwQSTGB" +
                                          "s6t5IK71Ac3SjhZPibWVzwhq0Aodn84s3TO4UccYTKtEvzWIQzej0knfSXzL" +
                                          "qG15a8rUsqGH9wOKx/sLpcvsOp1VHbecQXdqs2yzgtRqWQuuhdh0C0/IYUdZ" +
                                          "MiEFM3BXHNcJUa7G2XhLqRa+qFl1Xl9hQ81jFy6B455p4I7dqcCqzGYZ5td1" +
                                          "WDFZZ05Qq0TvDiYw08kGOQoHmpd0mtKcEaNZ4FJRX9i2M38+wyZGLs/WE4Gv" +
                                          "rxGm0aAWpIdVFBhuIBFdx71tOK5btVFoBivW2DVq/akszbozd6H0qiuHHpJO" +
                                          "fW2mLqvatC5KoUHXBjV2rS/YgK83avX1ghh0naXc6I53/a0pM74T+SESjRUh" +
                                          "dpvLoeXlU5aZLbZrkWh3xlyl6QrdTEF9n+25UykYLdT5QGIwhxGq/nTYy10c" +
                                          "wQg+k0R7NIQjzKlqHLOb0XLWs4x1j+6O19NA4qfGuil0Jul6a7eCYMos/U5H" +
                                          "IUx+Wus59QDQtnLbi2mtgwNdbnrbkRH6G68iZhS3YP0tjYcE3ldoZKlQTqIG" +
                                          "EtdlDQ5sh+rcLANt3bU3E+lBBvMblo9xm9lQTKebkfF22maMvmAxKh0QhsYS" +
                                          "o/GuCXdh0lZxxdngYrsziXbpSIWpfq4nrsNTYzceOi1BieO+H6DrypIicRkm" +
                                          "YS6NcxAfE3OhVXqdlZljfBUmWZKGB4mQIpSwSnu0rTa13s7hR6utjKErpRKr" +
                                          "KAa3FxZOkPSQo1WrL08SfyCboUKvEQF4V8ZRtlZrs80dvmnAXY1HKMZhd9Nq" +
                                          "bjfEMNhO3CCbrBtjNW55bULroHmlwSyrDYaY11O1vnOddTPOewM6Tzq+DffW" +
                                          "u7m+GI/U0JA9A6uuZiaw0mjELhqw4gEnDHdsqqbwQKsuxxKMyRxR6yso2owa" +
                                          "nI+lHV2oOJMm36rQVmbx+ULhCTWQGTMQNpOowdsrQnf6SaW7lpOtPu00YL0f" +
                                          "xbaaujXcY2vx1JzpdGaqUlsnKXfYlMwYH5HRgMyIXG1x5habbS1LGXapTRXG" +
                                          "pMQzWJ/qCJXIXpjTUUoTTrctx8iwkeOtLS9vXA71qnTUtDYIsZw3RoGqN8mt" +
                                          "g8J+rmDT4UC0SFatsXhCt6LhsoJP42Fscfh8YXJCtNyyPDqPh2t6yCx21G64" +
                                          "VdTOkNqydNBYKEmg+O2+HfokO1YG/em27iGsKWdbJVlihkxKLXes+Y0OHSuh" +
                                          "LdZ7djCc6zldn67dJBg60o7bclJftaf1qMqOtmqqmnwNxr2RJvEYnM8xwu2q" +
                                          "W38cTmqSWSej8WoG3KLaF7DU5fRGrKv1QTV0alSX7KlkL8AqOJVjCCF7cJVf" +
                                          "Tbh5X14z7MoeqrLQxVeUpTaGGYxwnD9oK+BjgbapxUj3NyKxZuTuquUt3aU5" +
                                          "21UI30qm/ZG+cnxnq7szt5/38G2wW1i6jWtDdFHZtTEfZgYGWF1QdJosiaa6" +
                                          "WgihqWPt3oTdLlh44m4QtFefooNBZoZy1MJ1V9xV0RUypY1xg9U3C50biPVK" +
                                          "e4cODGGYBbjJIXM8zTJtji4NqeVrm/oKqVYkrMesOgttNI/rhjVq9evjxbrT" +
                                          "J8KcaJFTdgoW7rA56+um5BoSIWMMPlLFfnfIWUgyq6diZzSIda+SR2O4rQ/H" +
                                          "fjsd2OY2yDPLqUkNJm5lZowx8GLQQwYM7HHt+pjEa8FiZLQwu50vRniegnVs" +
                                          "tZoOOWnZcoIObXYnKbNE1F5b5mNMR5IRvCEMx1zjq2hTRwQ2WAmKJk38rLfC" +
                                          "5DWOoLW2WV10ulKftAcdU9Ub5njnp0PVRPQ2miqobDRQkVw2+mI7m7HeUK1z" +
                                          "k35DcFpx25XF3O8srW0v1KTGbGNZdJedi2NzUWVDS14ndRxfhG2qL864NeXR" +
                                          "kbTMl/hOjpeUztvBjuKQxTJeiPGg6yc4s+La1EgemB08dOs0WzFRo6pFuiJV" +
                                          "rQTPe3LT6YYIt1vbVSRr7NQdX6816EjENY0cOYZXZWpslAHL1Tv+OtCJhOsZ" +
                                          "XRIWht60ZmNTeVYJFqnW51bUKISRtIdUZFhp4VlPCvk53W+OLHhGWU1H53qS" +
                                          "Cpx8BlcitC2uE4vEZ+u4sw0WCI53x7yd93e6DmP0EEWzes/p85zTV6vqPKFU" +
                                          "aZaRmBamOx5htJnaJOc40pryxMZluclowA21SbptDythpcM162KmS7uqXNlk" +
                                          "MY5aoUnRqh1vlem23VzYDL5C6F49x4mF2vXXaqMlUupusUybsEyj5Hg0X261" +
                                          "kGywBN1oVATbsQVTqsi+3EM5ftHKdn1S8KOBYHWnquHVQPQDS9lqipMwHWGK" +
                                          "mdAabwrO2pJdL164yjr3xdwzNmPUXTCGGTQbQbtTHSwt0wvGnfZ60RMFScs7" +
                                          "jtjQPdtA8aiNb9xYEZxtPjDYimjgSj+m+Cbaa/YC04SbhrgWUoJvrRCBRAem" +
                                          "C3dHMEzxKw4Ns4Vru0Tusjwr8RO+Gjj1REIzajCY6IMulXrjXaMjpiOb7Qhd" +
                                          "2kSmiiCHfotxB6u2DmyKtmBdq5vezqwMReDLbVEdLpu8krvjJrZsjJc7NhzV" +
                                          "akM11Cwp7c8xEGqbWVfTx+2qPGjTdYzWbRkxV1VbwdpjtbULa7MmzY3smqhF" +
                                          "o4091dFuUm94XcxmVHIq4Qq/Xa1lr741etjSa7ejdJs2BxSRD4ZxE9tk0+Vs" +
                                          "RaRTrT1EvJql61oqbBrVlgrPrdnMb096bESkWVSZSxtSRiqtbYPr94e90TTV" +
                                          "YrK2UWkMq+bJAll1ZFoLGxujtU4zU56NG/0QwWKGrm7aTA6WyWXTnGKrAbVb" +
                                          "ePZ8qtW6veUEbvQ2yWazJTOhpulCU96NM2YAz8EmaNCtteo6r4A9AAej/VBp" +
                                          "1mfjyYxxmTHT3jHOeGPQgEJuFo5lFc/EimuLYYXwmE47wSmUQBHS46cDwkxX" +
                                          "Uxl3RypBulxCpVQOPFxs9xVOgEPRmiANYzypj/ozUkWFasuzdytywXmRJi0Q" +
                                          "iQX6FoCRMS1CH023zlIads02Nx5WNkpiYUudhxdh1Gyra05hdTyw/cFkZ8nk" +
                                          "ZrxmwiwhMNqMw3UnVUNazxtY1dciYYIs506fWxpbci63llOBXvSbuef4K4pq" +
                                          "xWt7hrbDxUpHzd6S7jWxtZgI7UFKR7OmPx+3wg6NgJ3EekcgVXHY83JXMiO6" +
                                          "E+YoXl33vfEAwbVZ2pernMR6DRAka/aKD/xWtbNsCPMuVu1sOj7VXQGTtnqe" +
                                          "gjFLk5nku0W7suhsRo02RTSVdEjDIy7upvhSUNop02Qb7S2WD0dVPeUCcYih" +
                                          "WdOVwZatF6Oa3KEm622uKzqppQtaSLJxRWebWL3H1FKk0UJtRtgyrc1osrF3" +
                                          "s2bYSVEHnYFoANM2MIxFjnTH1njMxZSKV73qxi8sdqqnLpGGTdVN04hO1mhr" +
                                          "JggyHLXtLmnr07XIk/WaqbSwfraKFZvH5J6F1WfblsRNkd4K1QdgX4c2NMmU" +
                                          "a2Kmgm2FKPFSV6kkI1mYepMKRS1r9JgY+2S2Ws+rc9kZmIiIZnyI6o5O2ctM" +
                                          "s+CFXZ2NfMFfc7lt8JECDxoJT7AIDyy73ouytObaNB8R80ba5OvNbm2yIvOJ" +
                                          "kMWNtJZSZOD6zggh0zUy0fR5GBGUMqgi1Y5EOdtgA/dqfWk392TGwPEiDcB8" +
                                          "bZmYR8qE2fE5je2gRUf1a8hA7O40YQJdluQ4iSQlSaAHjg+O9rOfyhifO0rQ" +
                                          "Ef/0rHXPcgC6ju/4EVMgDnynzMYVSZqnXuk0p0zQfPT9L76kDn+iViRoinm7" +
                                          "gLbED94Jvk805xRVDwJMb3/lZBRfHmadJIx/4f1//OTkBfM9Zcb0lkQ2B10p" +
                                          "RgrFmeHx2eCbztB5FuVP8i//IvU25V+fhy4cp49vOWa7edDzNyeNr0Rakkbe" +
                                          "5Dh1HEHP3JLB8hVNTSPtZN63v1n65I2fee/189DF0zn1AsNTZzLUr9H9yJWc" +
                                          "YoKjc70riRn525OW0+lqINbXFIbzWlDefnjwU/4XvY8FRf3a3Yn53WJX548N" +
                                          "WTy0ogh620mmFJiDoyml1K9PPbdMLBbWUpxa/O3Vt9Y++ScfurZPuzmg5UgN" +
                                          "73h1BCftbyCg9/3St/3l0yWac0pxUnqS+z0B2x+/PXaCGY8iKSvo2H3nZ5/6" +
                                          "4V+QfuwCdI6BLsZWrpXnYdDhQUpBlFmyrZS1cabPLqobwGQNLdnnUI+cp/q1" +
                                          "Os+Jh7/n1XKMp6koG77lWJ9l49OgVA71Wbkrfd7M+bl9fChe91n+zR1EU1Yh" +
                                          "EE18k2i++VQM6yTQxY1vqSesR3fB+pWi8VFQGoesN76OrJ/m7Lvu0PeBonof" +
                                          "CLXAIMozvCN7uP4q9nACXAriO78eNoAdCgK7NzbwPSXAD9xBGh8pqg8BacSH" +
                                          "0ije8xMuv/8uuCwj15OgvHDI5Qv3SN3/7g59/76ofiSBrhb+n5br6ViRnNua" +
                                          "+iXVT+XDrpL7f3u3On4nKJ1D7jv3Rsc/XgJ8/A4i+ERR/SQQQXyzCM6o+mN3" +
                                          "q+oClj5klr5Hqv4fd+j7X0X1yQS6D6i6r5ayOeHuv96tKt8ACn/IHX8vVfnz" +
                                          "d2Dx00X1s4DF+IjFUwr8P3fBYgn2RlDEQxbFe6TAz96h73NF9f8S6MEyNCei" +
                                          "ZhztB0F4fkO5NyjCsaH57oEI9g2SZzhavXsigc/crZLfAcr8UALze6PkXy0B" +
                                          "vnAHMfxeUf0mEEN8SgxndP1bd8Hpw0XjW0B59yGn775Huv6TO/T9aVH9QQI9" +
                                          "VjirFnmaM/WshNM8IzHBTvCtr/whUe4M94fUL/2HZz/zHS89+7vlhYDLVjyT" +
                                          "IjwybnM/7dSYL7/8+S9+9qGnPl5u1i/KUrzf6Z+92Hfrvb2bruOVPDx4LNJC" +
                                          "+qVcjUORlv8JlH1dr0bJkaUaWmU8o3pgh+1tiluKvJRE1q6416l5CVECHN3L" +
                                          "+uebvJTOjwdBAJ1Y7B/erW+2QVEOxavcG9/8sxLg71/ZbM+Vk/41MNv4VrM9" +
                                          "46J/87UwvEug197uYlnxVfTELVdi99c4lY+/dPXy61+a/v+9KR9dtXyAgy7r" +
                                          "qeOcvgt16vlSEGm6VTL6wP5TMyg5uz+BnvsnfxElxZfy0UvBzLlLeyxXEujp" +
                                          "O2MBi1f5f3rUQwn0xCuNSqALoD4NfQ3I6nbQABLUpyEfS6BrZyHB/OX/abjH" +
                                          "AT8ncGAjuH84DfIGgB2AFI9PFtfCSg0+cdpcS6U/+mpKPx5y+l5XwWp5Pfoo" +
                                          "sZHuL0jfUH76JXbw7V9p/cT+XpniSHleYLkMwtE+k3AYjk7ftDmL7QjXJfq5" +
                                          "rz78iQfeepTIeXhP8InrnKLtTbf/xifdICm/yvP//vr/8o3/8aXfKe82/SN5" +
                                          "YboDty4AAA==");
}
