package org.apache.batik.bridge.svg12;
public interface SVG12BridgeUpdateHandler extends org.apache.batik.bridge.BridgeUpdateHandler {
    void handleBindingEvent(org.w3c.dom.Element bindableElement, org.w3c.dom.Element shadowTree);
    void handleContentSelectionChangedEvent(org.apache.batik.bridge.svg12.ContentSelectionChangedEvent csce);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188907000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL1YfWwcRxWfu/N3/J3EDknjOIkT4TjcKimt1DqExo4dOz07" +
                                          "VpxEypnmMrc7d7fx3u5mdvZ8djEqlVBNEVEUXFpQ679cFVC/hKgAQasgJNqq" +
                                          "gNQSAQW1ReIPykdEIyT4I0B5M7N3u7f2uRJIWLq5vdk37/v93hs/exPVOhT1" +
                                          "EJPF2bxNnPiIyaYwdYg2bGDHOQN7KfXxGP7bhfcn74miuiRqzWFnQsUOGdWJ" +
                                          "oTlJtFM3HYZNlTiThGj8xBQlDqEFzHTLTKKtujOetw1d1dmEpRFOcA7TBOrA" +
                                          "jFE97TIy7jFgaGcCNFGEJsqx8OvBBGpWLXveJ98WIB8OvOGUeV+Ww1B74hIu" +
                                          "YMVluqEkdIcNFikasC1jPmtYLE6KLH7JuMtzwcnEXWtcsOfFtr/fvpprFy7Y" +
                                          "jE3TYsI85zRxLKNAtARq83dHDJJ3LqPPoVgCbQoQM9SXKAlVQKgCQkvW+lSg" +
                                          "fQsx3fywJcxhJU51tsoVYmh3JRMbU5z32EwJnYFDA/NsF4fB2t6ytdLKNSY+" +
                                          "NqAsP36h/dsx1JZEbbo5zdVRQQkGQpLgUJJPE+oc0zSiJVGHCcGeJlTHhr7g" +
                                          "RbrT0bMmZi6Ev+QWvunahAqZvq8gjmAbdVVm0bJ5GZFQ3q/ajIGzYGuXb6u0" +
                                          "cJTvg4FNOihGMxjyzjtSM6ubGkO7wifKNvbdDwRwtD5PWM4qi6oxMWygTpki" +
                                          "BjazyjSknpkF0loLEpAytL0qU+5rG6uzOEtSPCNDdFPyFVA1CkfwIwxtDZMJ" +
                                          "ThCl7aEoBeJzc/LIlQfNMTOKIqCzRlSD678JDvWEDp0mGUIJ1IE82Hwg8VXc" +
                                          "9fJSFCEg3hoiljTf/eyt+w72XH9N0uxYh+ZU+hJRWUpdTbe+ecdw/z0xrkaD" +
                                          "bTk6D36F5aLKprw3g0UbEKarzJG/jJdeXj/9k/MPfYv8OYqaxlGdahluHvKo" +
                                          "Q7Xytm4QeoKYhGJGtHHUSExtWLwfR/XwnNBNIndPZTIOYeOoxhBbdZb4DS7K" +
                                          "AAvuoiZ41s2MVXq2McuJ56KNEKqHD4rA5yCSf718YUhXclaeKFjFpm5ayhS1" +
                                          "uP2OAoiTBt/mlDRk/aziWC6FFFQsmlUw5EGOeC/SVNeyRHEK2UOHlelzJw4d" +
                                          "HhI7Z20NLBrDpgYGxnnK2f9PYUVu+ea5SASCckcYEgyopjHL0AhNqcvu0Mit" +
                                          "51NvyHTjJeL5jKG7QX5cyo8L+XEpPy7kx6vJR5GIELuF6yHzAKI4C3gAgNzc" +
                                          "P/3AyYtLe2KQgPZcDY9BURTojtIPOBjSV0DBp6btp3798z/eGUVRHzXaAnA/" +
                                          "TdhgIFM5z06Rkx2+HmcoIUD3zhNTX3ns5iMzQgmg2LuewD6+DkOGAuwCfH3h" +
                                          "tctvv/fu6o1oWfEYA6h209DxGGrAacA5rDKGGsuAJQ3b8iH8ReDzb/7hNvIN" +
                                          "mXydw14F9JZLwLYD7oiI520MDVQLxTr+5y7cWQ1fBDauPry8op16+pBEgc7K" +
                                          "mh2BlvTcL//10/gTv3t9naRoZJb9CYMUiBHQM8pFVgwXEwJ6S406pb7Teu33" +
                                          "3+/LDkVRTQJ1gqNcbPAx4RjNQgNSZz2Mbk7DxOE3/t5A4+cTC7VUokHfqTYA" +
                                          "eFwarAKhfJ+hLQEOpbGEA/CB6kNBWPVXH/7T9jNHcxdF5gXbPJdWCx2Kn5zi" +
                                          "zbnchHeF3B9m+c2JZ18/sV+9FhV9iWP8Ov2s8tBgMBAglBJowCY3h++0gNA9" +
                                          "4TIPeyulHujFL6VeXuwTUWiE5swwgCn0vZ6w8IreMliqOC6qAZyQsWgeG/xV" +
                                          "yeVNLEetOX9H4E+HLABIEFHbY/DZ56Gv+OZvu2y+dku8EvQ9Yt3Nlz6ZXfxx" +
                                          "H1/2C7KPQ7bt94sa2oUBKMoj0nfWhLDrGR2nDcLh5p9t+w699Jcr7TKRDdgp" +
                                          "hejgRzPw9z82hB5648I/egSbiMrHFR94fDLZAzf7nI9Riue5HsXPv7Xza6/i" +
                                          "p6CbQgdz9AUimlLUqx6vyjfzKp+7U41rVj7Oh0vIXf7quDB7WJAdFesQd5+H" +
                                          "mPz3Cb7cC4CSExgwBEUOg81IARiARv0bTMBUzwNeFrwZQlnsfG/2yfefk8gQ" +
                                          "HjhCxGRp+dEP41eWpXPlVLZ3zWAUPCMnM6Fxu4gkx6rdG0kRJ0b/8MLiD76x" +
                                          "+EjUszbOUE3B0jU43FfFtMCcnVKv3vig5dwHr9wSilYO6sEOMoFtqVsHXwa5" +
                                          "bt3hHjaGnRzQffL65Gfajeu3gWMSOKrQrZ1TFBpqsaLfeNS19b/50Y+7Lr4Z" +
                                          "Q9FR1GRYWBvFfCSGwQbKhjg56MVF+9P3ydKYa4ClXYQWrQn2mg2ecbvWz+WR" +
                                          "vM1E9i18r/s7R55ZeVf0LtlfDleW5iR8BrzSHPifSrMyRyOVbezejScKcQkx" +
                                          "2TTxTBiGbM4STaSxYJ/aoARUviQZ2iNLYCNenDIhmEzxZUZ6dfq/DADfOG8X" +
                                          "YTSuNhHxGG1bcy+Tdwn1+ZW2hu6Vs78SmFye95uhi2VcwwhAfhD+62xKMrqw" +
                                          "u1mmrC2+ZuFuvaGPGaoV38KMS/IQTPXdVQ7BiCMfgvSX4Z4dpge+4jtIB8NQ" +
                                          "k08HrORDkGSOoRiQ8EfIzGKkchQsR2jrR0UoMD3urUAEcWkudWFXXptT6gsr" +
                                          "JycfvHX303KYhOv2woK4ZMGdUba2ciffXZVbiVfdWP/t1hcb95XAqUMq7BfN" +
                                          "jkCSnodisHk6bA81Caev3CveXj3yys+W6t4CbJlBEQxtYSZwZZX3M+g0Loxc" +
                                          "Mwl/6Ar800V0r8H+r88fPZj5629F1YsqhKtAdfqUeuOZB35xbdsqdLlN46gW" +
                                          "cJcUk3D/do7Pm6eJWqBJ1KI7I0VQEbjo2BhHDa6pX3bJOFz1W3nmYn6dFn7x" +
                                          "3NlS3uXTCBTn2vawdqQDhJwjdMhyTU3MNoDZ/k7Fbb40DLm2HTrg75RDuWWt" +
                                          "7Sn1+Bfbfni1MzYK1VdhTpB9veOmy4NW8IIvJ69AN5NTfSyVmLDt0pRft+hB" +
                                          "7pKk4fsMRQ54uwGU5D+/JNg9Kh758uX/AOuZvfm7EwAA");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188907000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL1Ze8zrZnn39537aek5PYW2K7S05RStpHxO4iROdhhgx7c4" +
                                          "thMnzpWNU9/txLEdX2InrBPrLjDQWLeVjUnQv0DbULlsGtqkianTtAECTWJC" +
                                          "u0kDNCHtwpDoH9vQ2MZeO9/99JwKTVqkOG9eP+9zf36v38cvfgc6FwZQwfec" +
                                          "tel40Z6eRnszp7oXrX093GO5alcOQl1rOnIYSmDupvr4Z6/8+/efs67uQuen" +
                                          "0H2y63qRHNmeG/b00HNWusZBV45mSUdfhBF0lZvJKxmOI9uBOTuMbnDQXceW" +
                                          "RtB17kAFGKgAAxXgXAUYO6ICi16ju/Gima2Q3ShcQj8N7XDQeV/N1Iugx04y" +
                                          "8eVAXuyz6eYWAA4Xs/9DYFS+OA2gRw9t39p8i8EfLsDP/8a7r/7eGejKFLpi" +
                                          "u/1MHRUoEQEhU+juhb5Q9CDENE3XptC9rq5rfT2wZcfe5HpPoWuhbbpyFAf6" +
                                          "oZOyydjXg1zmkefuVjPbgliNvODQPMPWHe3g3znDkU1g6/1Htm4tpLJ5YOBl" +
                                          "GygWGLKqHyw5O7ddLYLeeHrFoY3X24AALL2w0CPLOxR11pXBBHRtGztHdk24" +
                                          "HwW2awLSc14MpETQQ7dlmvnal9W5bOo3I+jB03Td7S1AdSl3RLYkgl53mizn" +
                                          "BKL00KkoHYvPd4S3feg9LuPu5jpruupk+l8Eix45tainG3qgu6q+XXj3W7hf" +
                                          "l+///Pt3IQgQv+4U8ZbmD37q5Xc+9chLX9zSvP4VaDrKTFejm+rHlXu++obm" +
                                          "k40zmRoXfS+0s+CfsDxP/+7+nRupDyrv/kOO2c29g5sv9f588t5P6t/ehS63" +
                                          "oPOq58QLkEf3qt7Ctx09oHVXD+RI11rQJd3Vmvn9FnQBjDnb1bezHcMI9agF" +
                                          "nXXyqfNe/h+4yAAsMhddAGPbNbyDsS9HVj5OfQiCLoAvtAO+T0Hbz6PZJYJs" +
                                          "2PIWOiyrsmu7HtwNvMz+ENbdSAG+tWAFZP0cDr04ACkIe4EJyyAPLH3/hhLY" +
                                          "mqnD4cosleH+kC6V8Xxm4GvAIkZ2NWDgXpZy/v+nsDSz/GqyswOC8obTkOCA" +
                                          "amI8R9ODm+rzMU6+/OmbX949LJF9n0VQDcjf28rfy+XvbeXv5fL3bicf2tnJ" +
                                          "xb4202ObByCKc4AHACnvfrL/k+zT73/8DEhAPzmbxSDNC/TB/M8ZsO7J26M3" +
                                          "lUFHK4dLFWTzg//ZcZRn/+F7ue7HAThjuPsKFXNq/RR+8aMPNd/+7Xz9JYBV" +
                                          "kQxyC8DAI6fr9kSpZQV82qcAgo/4lj+5+Lfdx8//2S50YQpdVffxfSg7sd7X" +
                                          "AcZetsMD0Ad7wIn7J/FpW4w39nEggt5wWq9jYm8cgGlm/LnjsQTjjDobX87z" +
                                          "4p6c5t4fgM8O+P5P9s0ikU1sq+Jac780Hz2sTd9Pd3Yi6Fx5D90rZusfy2J8" +
                                          "2sGZAj/e9z/2N3/xz8gutHsE8FeObZnACTeOgUrG7EoOH/cepYwU6Jmz/v4j" +
                                          "3V/78Hfe9648XwDFm15J4PXsmmkMdkiw0/z8F5d/+42vf/xru4c5diYCu2qs" +
                                          "OLYKBmG+4QFLDNuVndwhj0fQAzNHvX5g9RBsgECx6zMHzV31OrDl56plUdnb" +
                                          "7hp5gQGNrt8mXY/t9DfV57723dcMv/vHL9+SqScdw8v+jW2Ecq1SwP6B01XE" +
                                          "yKEF6CovCT9x1Xnp+4DjFHBUAV6EnQCUdHrCjfvU5y783Z/86f1Pf/UMtEtB" +
                                          "lx1P1ig525QBtEYW2MctgAap/453bqExuQguV/PahHL7X79VJy/re44cwXlg" +
                                          "8/zgt577yi+/6RtADxY6t8pyGGhwzFtCnD1P/MKLH374rue/+cE8JgCIh7/4" +
                                          "u8j3Mq71XMAT+fVHs0thG7Fs+FR2eWt22TsI00NZmPo5PnJyGPGeZoPnCS2P" +
                                          "1B2hoxvYC5Btq/3NEn7m2jfmH/2nT203wtM4cYpYf//zH/jB3oee3z32+PGm" +
                                          "W54Ajq/ZPoLkSr/mMJSP3UlKvoL6x88880e//cz7tlpdO7mZkuBZ8VN/9d9f" +
                                          "2fvIN7/0Cmh91vEOkjK7lvfFZj/VVw9sdNe3mErYwg4+XGlijBK1l46MGBYQ" +
                                          "mEVIYu7OOq25VJFmatteRCViSaZeRetsiujQT8m17y74QEU11EiRuLrQVtO6" +
                                          "NiOXzhAXyCE5GFO+WEMbKjVswlbbxEQ5NFlhuTQFsY+Jo1JPb3XXc41sraVK" +
                                          "q4hXeVRAYtQoxz22NeKW1ZU2R1B41UAssGGm3WHHkkok26XKSiq4Xbu1lieJ" +
                                          "NjHLCk0wHVFA28Y4pbuoYhmqi1YWdmz3lpsR5YrhoENrI9aTHDaieISZTAVH" +
                                          "siWLntVTXHSAWdSGkTip3Y7iWUePkpJW0hak36M6KoZKeCfAZhTZQKXWGp1R" +
                                          "pkyrTYGiSTZcpvXOCsdpf8SNVzrbqI9aOJjp0AN9WBglJRytWK14wg+deEnO" +
                                          "tZYqUPZcDpulWXcRTTiy1uYYlI35aJOoLjkeRWrYMagogI2V7wfUGp3MSESa" +
                                          "hK16ddNLubaARVhvWUc0hmBZhFt2u97QbCqiJ/KN/riNOUOxbTbF+WpUcPqm" +
                                          "IYYpYqwTVk0tdlAtRaE3nCwshO3xyqC6QcpkwroTisBgIaQqBl6OautIA1L6" +
                                          "k4KwxMIuUrNgLUxL7JRUFK+60YY9UZzTos+ZA5btkgVPLW76NjukmaZK66wj" +
                                          "MVaAmj0lkIoKv5jaNXJVEEer2JUtbDldLevmbIEp2nC4KCpslZ5SIrKE5VmL" +
                                          "3kzoeKzU4qLKSiuzQgkd26L5dLbezKI+X4sVet5BE9toCytFI5JeEhHV7oiv" +
                                          "LO2al/KjtSn5cxufyZv1rD93/TlVdDyO9LF1xBWXg0I1oGvxpkNG/W5TIDSq" +
                                          "u6aGWKk5N5JWkkbElGclq+mgMunhOrtRYa7liIbAS512a9nc9Jw+UUPrLLEa" +
                                          "kYRfXNCDFltqkfUyk5j14VhtGGyfapImYnm2M5MMWF9HhQQtj5mGUIzTiVWY" +
                                          "DgoW2xuBpyZJ0Qu6qiXwppgGc5lQpHmNQGpUVebafpAgZnGgkG052LA0PGM1" +
                                          "fTyDG3OY7xqTVb0zWcqpQ2uy5cTMqu2J6HgdLSqi7rUnFs3SEcMM+mQajbjE" +
                                          "6MHjxBVwoeVq3anU6kz0jpdauKJNlQrRR9sYtoo9e1ophWV+OF6WeTVmq7W2" +
                                          "QLaXDFEJsOq62TfQUn0ysMbgdKq3qRnlL6ry2uqX4m65g3m2hEfwwiF6c1je" +
                                          "2KNmjaIoMVw4g6RK0h29CR5XBX3dY8h2edBhHN3ZsElFY6wWOi0XBQ4PCN+c" +
                                          "0KnrtstGozsZDOOCLlf7WL+pztUJaa49f8ZwRcwSluoqLvJ2VC0JqzUjzVid" +
                                          "q87aNCqOq+raq3OFMel31+g8ra3YXpVukVxM1dbMBmu3Kk3ExExho3ZhBFtP" +
                                          "Ik4vt0WzO1WJSQMf9CRvFrW6HXzWHxYJ3K8pkY+gjfoG1unBsMdsxjLmYrCk" +
                                          "WWaL4qubYq03T8sFZqF6rQGBbCxBGiNuWLX5jWguzDIX6wlRKxDzDo3FSdNg" +
                                          "ECtSo9UKNuKaV/JGBjnBala52CBSmg4wWcWqAdGm6TDGWBFR6jZT7+nERoFR" +
                                          "S1i1hMV4rSWlCtVgp1zCTQjUs1vVcpEnhiKXSkGhukbVkVgycEKOu8G67vml" +
                                          "WsHHSVNF2wurjDsrSeVguFSETWmFRA1X7nlTVmk0J/zAxhmRr/vU0EzGAAZq" +
                                          "/Uqx5iuopMcIghRgjpgPe5LIlsyloCpdLK30ZoJoCv3ppswrc5RIOyQCR1Ws" +
                                          "UlClJjoceHPGWEoTTKcSOcDalsEWLE4kO75CkxjcxGtzAR91h2MGRqXGTGDU" +
                                          "VKOq5ljpstqomZbbbnVjbxRwImJ0CsEbi4JaZqelOhwOCw3KGjbsURcAazms" +
                                          "R7jJ45jp4KyXNCeIVSgUTQFrVKRWV1/HDhPPKK421MdxIg1GNlkNk8RsusXV" +
                                          "tJbUW4HOO/ay06wtselaDEemTsPpcK0PBY7Uo864wVTIAsNheIukGGUCE9Nq" +
                                          "jV4VOtNVXF4XtHlcJ1diYxIhgrOpTcdGmjIluNxE210RVaJGJZTL3gBv896s" +
                                          "6BojiyMCuld2CZWzqn4DYEKt0WDVAJXaPUIzfUufmb1NN2ls6mULr9Yq9Ras" +
                                          "m33F5gOG6jUqBsFNsY2Buq1Gz471KhOOuyt0vJFrsO3XAOyb2qaBDeyFww2W" +
                                          "IPnXM2PT9gvooFIKhjO0YxVXrbGBLmMCR0csplF6KGpVkL7dDdJUULVZaQK4" +
                                          "MBOcHHTMeqmF9WystyoqEo8PNomgU0EyFR03NGi4vDZ0Y143RWZmNVO65xc0" +
                                          "slsp6SN/3HWG3BTZjLBBt8m7fI1K44oJajHQ6OK8xxYVuM5zNoHW0gI5G4Qb" +
                                          "pTMgEbw4G1QQCux1fFN1h+0VsrLNqpYwQSPp286kUwvJDu9R0XIYMuNErioR" +
                                          "YjEzmXZ7G9EwuFqVNuQZSFZzxPc77UAMpiWJwv1lKHOGLvRLDQWuFicFlAsq" +
                                          "U7FB9Up0bzLCV5TR7NOJqLStmVmt8UOq0Ogia609kStNZzwRR4HolkEl66qy" +
                                          "Gm0Ko96KL5ENu1QP4BDtVatTfWgUucgxCEcfVe1eHQ82faZrG/2AX/fWnaGi" +
                                          "b/RZX22rIkAKSUol3KYVvtKX5H46YWHZw3qDlS1Oy7bATZqC7hIta0Fu0ulg" +
                                          "WtOMJUxghNGh6+OJ1I8FiwE4UVLUdUHSErdUmI7KVlwbhmi9v6DWeqMaW3Z5" +
                                          "qCaJhRkWUaiV0zYfLJO4tFgEzXJhGlPxSqa7tOwNkXqb78MtUeqOtaGI4naT" +
                                          "N8xVf1yZVjTf1AsVAIR4XRDnxToTdHrEnO53vJ4t1kmjtaHbc9USw155FvSK" +
                                          "A48nkDgYYKQ6msfaiBqP/UiqmWHArlVjxYyRIgL2I1CsideuTHlaGyhyWbUN" +
                                          "YzwdKvbQ0EZdOCpZqtKojrHlgF+iuCHM5s2+C57tQ2ZeU7B6qSnrK6S5Avsf" +
                                          "sl6HhVEtqjQV1sFJMY0m/WkynY4RvmAWOS9V+cSBa1hQLxaHxaDOFIJ63ehO" +
                                          "Z9VauUGVJuHSakcY8O1AjztTHKmmihYuNc4RKjVzpLLqYI4QsOah3UVNZ0dL" +
                                          "nC21W2irOBRJZeaVcYsh5Jo/RhS2Q21KI8RdTNyaRrloClCgj8RjqYlLbnkl" +
                                          "J9pSJCw2mWm8tZYGCC94xBSeo5SiVIoEtygzUmCi1R4Rj0YR2gfxxA3FcO0S" +
                                          "v5m0S0PNkny8sdI7i3VFGNVbrRVba2BCVZCM/nq44Iio6PeMqGDhqN+eV4yQ" +
                                          "74nVSpzQgypRgFnBbLQttFqPxzDWiacrY4GSCYZlj/utH+7EdW9+MD7srYKD" +
                                          "Vnaj+EOcNNI7CYygi7ISRgE4jkbQpcNm71b6sc7QzsFBvHC7rtQrtKKyU9fD" +
                                          "t2u15ieujz/7/Ata5xOl7MSVCSCAEpHnv9XRV7pzTPwu4PSW258u+bzTfNQB" +
                                          "+sKz//KQ9Hbr6bwFcktnioMuZyu7WUP/sHH/xlN6nmb5O/yLX6LfrP7qLnTm" +
                                          "sB90Sw/85KIbJ7tAlwM9igNXOuwFBdDjtxxJPVXX4kA/kvuWR+XP3fz8M9d3" +
                                          "obPHm2QZh4dPtZzuMrxgITuZgIOm++XICrzkaOZ4/wm4NW8AMuD7xH5XNv/N" +
                                          "7t7nZ9fXpkd5dksC7R5mbG8/XQLozUetj6bnOLqae/36wF3knQJZcfSsDflf" +
                                          "V54ofe5fP3R1e452wMxBGJ56dQZH8z+CQ+/98rv/45GczY6avcY4auYckW17" +
                                          "4/cdccaCQF5neqQ/85cP/+YX5I+dgXZa0NnQ3uh5s3p3P+f2U/6+LOUTRN3T" +
                                          "vMVe9gpKd3N97dxsKydT86uZ1962rZr9z98d3Iyga1ZeEDjIeNs1yZW+/7rp" +
                                          "HcdqtxlBZ1eerR0V9dOv1j44Li6feNfJyArgW9iPbOH/FNmTJu6chIQfu3Oj" +
                                          "On+35UZ9fT8cTeAMU9dyL+Ts13fw4DPZBUDT41sP3olXRukeeS/+YbyXRtCD" +
                                          "t2uoZ8nz4C2v9bavotRPv3Dl4gMvDP46L8/D10WXOOiiETvO8R7wsfF5P9CN" +
                                          "bfZc2lakn//8XAQ9fEdfRtC5/DfX/2e3i94XQQ/cZlEEnd8OjtN/IIKunqYH" +
                                          "fPPf43S/FEGXj+gAq+3gOMlzEXQGkGTDX8n608cAez8h80hce7VIHC453mDO" +
                                          "QD5/53oAyPH2retN9TMvsMJ7Xq59YtvgBufhzSbjcpGDLmwR8BDUH7sttwNe" +
                                          "55knv3/PZy89cbAB3bNV+Kg4jun2xlfGJnLhRzmabP7wgd9/22+98PW8yfq/" +
                                          "nlClNwwfAAA=");
}
