package org.apache.batik.parser;
public interface TimingSpecifierListHandler extends org.apache.batik.parser.TimingSpecifierHandler {
    void startTimingSpecifierList();
    void endTimingSpecifierList();
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188908000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAAL0Ya2wcR3nuzu/4ncQOSePYiR3hNNyphSIVh9DYtWuHs+PG" +
                                          "bksdksvc7tzdxnu7m9k5++wS1JZCAz+iKLi0IOpfrvpQX0JUgKBVEBJtVUBq" +
                                          "iYCC2iLxg/KIaIQEPwKU75vZu91b+1IEEpZ2bvebb773a/z0ZVLrctLDLBEX" +
                                          "Sw5z46OWmKbcZfqISV13FmAp7eEY/euJd6dujpK6OdKao+6kRl02ZjBTd+fI" +
                                          "TsNyBbU05k4xpuOJac5cxheoMGxrjmw13Im8YxqaISZtnSHCnZQnSQcVghvp" +
                                          "gmATHgFBdiZBkoSUJHEovD2UJM2a7Sz56NsC6COBHcTM+7xcQdqTp+gCTRSE" +
                                          "YSaShiuGipxc79jmUta0RZwVRfyUeZNngsPJm9aZYPfzbX+7ej7XLk2wmVqW" +
                                          "LaR67lHm2uYC05OkzYeOmizvniafJ7Ek2RRAFqQ/WWKaAKYJYFrS1scC6VuY" +
                                          "VciP2FIdUaJU52gokCB9lUQcymneIzMtZQYKDcLTXR4GbXvL2iot16n40PWJ" +
                                          "lYdPtH8rRtrmSJthzaA4GgghgMkcGJTl04y7h3Sd6XOkwwJnzzBuUNNY9jzd" +
                                          "6RpZi4oCuL9kFgQWHMYlT99W4EfQjRc0YfOyehkZUN5XbcakWdC1y9dVaTiG" +
                                          "cFCwyQDBeIZC3HlHauYNSxdkV/hEWcf+TwMCHK3PM5Gzy6xqLAoA0qlCxKRW" +
                                          "NjEDoWdlAbXWhgDkgmyvShRt7VBtnmZZCiMyhDettgCrURoCjwiyNYwmKYGX" +
                                          "toe8FPDP5akD5+6xxq0oiYDMOtNMlH8THOoJHTrKMowzyAN1sHlf8mu068Wz" +
                                          "UUIAeWsIWeF853NXbtnfc/EVhbNjA5wj6VNMEyltLd36+nUjgzfHUIwGx3YN" +
                                          "dH6F5jLLpr2doaIDFaarTBE346XNi0d/fPe9T7E/RUnTBKnTbLOQhzjq0Oy8" +
                                          "Y5iM38Ysxqlg+gRpZJY+IvcnSD28Jw2LKeiRTMZlYoLUmBJUZ8tvMFEGSKCJ" +
                                          "muDdsDJ26d2hIiffiw4hpB4eEoFnL1F/O3ARhCVydp4lqEYtw7IT09xG/d0E" +
                                          "VJw02DaXSEPUzydcu8AhBBM2zyYoxEGOeRsO5hdPzBp5iKQZh2kGxDfH2jNO" +
                                          "LR2Ui2O4Of8vRkXUePNiJALOuC5cCkzIonHb1BlPaSuF4dErz6ZeU2GGqeHZ" +
                                          "SpAbgXdc8Y5L3nHFO16dN4lEJMstKIPyPXhuHmoA4DQPzhw/fPLs7hgEnbNY" +
                                          "g3YvyqTcUfqAgyFZZfp/csZ59Fc/+8NHoyTqV4q2QImfYWIoEJ1Is1PGYYcv" +
                                          "xyxnDPDeemT6qw9dfvCYFAIw9mzEsB/XEYhKKLVQsr74yuk333l77VK0LHhM" +
                                          "QHkupKHLCdJA01DbqCYEaSwXKaXYlvfhLwLPv/BBHRGgAq5zxIv63nLYO07A" +
                                          "HBH5vk2Q+H/oBs8FaMWd1cqKLIlr96+s6kceu0Elf2dlqo5CJ3rmF//8SfyR" +
                                          "3766QUw0Ctv5iMkWmBkQNYosK2aKSVlxS/05pb3VeuF33+vPDkdJTZJ0gq0K" +
                                          "1MTp4BDPQt/R5r3S3JyGQcPv972Bfo+DCrc1pkO7qdb3PSoN9gLjCBdkS4BC" +
                                          "aRrBuruv+iwQFv3l+/+4ffZg7qQMvmB3R2610Jjw5DT25HLv3RUyf5jkk5NP" +
                                          "v3rbXu1CVLYjLO0btLHKQ0NBRwBTzqDvWqgOQlqA6e5wloetldL29dIXUi+e" +
                                          "6ZdeaISeLCjUUGh3PWHmFS1lqJR0yKoBjJCxeZ6auFUyeZPIcXvRh8jy06Fy" +
                                          "AAJEpvceeHq9oit/cbfLwbVblSuJ3yPXPlz6VXTh6wAueyXahyHa9vp5DV3C" +
                                          "hAKKHum/wwK3QzLQtMmw4vyjbeCGF/58rl0FsgmQkov2fzABH/6hYXLvayf+" +
                                          "3iPJRDScUvza46Op1rfZp3yIc7qEchTve2Pn11+mj0IThcblGstM9iLi1T0U" +
                                          "akSqfVCuw6G9UVw+AT0XHMnFBtUX2A5eY7rlcEIYC958kDjT+c78N999RqV/" +
                                          "eJgIIbOzK195P35uRVlQTVx71g09wTNq6pJyt0t3YUHquxYXeWLs98+d+f4T" +
                                          "Zx6MejrHBalZsA0dDvdXUS0wQ6e085fea7nzvZeuSEErh/Bgp5ikjpKtA5ch" +
                                          "lK073KvGqZsDvI9dnPpsu3nxKlCcA4oadGP3CIemWazoKx52bf2vf/ijrpOv" +
                                          "x0h0jDSZNtXHKI67MLRAbjA3B/226HzqFhX/iw2wtEsHk3UuXwfAsNq1ccCO" +
                                          "5h0hQ2z5u93fPvD46tuyR6k+cmNl/vXBM+Dl38D/lH/VI/X4NfZSuHwGkgeG" +
                                          "uA1iGHcPy4NTuNytzHD7f2kxBNzlFGGSrz6soFm3rbsmqdFee3a1raF79Y5f" +
                                          "ylpZHr+bobtkCqYZKMXBslzncJYxpLbNKsoc+ZMVpLtKF8dBQr5IHTIK/xTc" +
                                          "YMP4gtTK3yBeXpAmHw9IqZcgCvTsGKDg62nHKUYqB66yubd+kLkDM9qeinyU" +
                                          "19FSoyuoC2lKe2718NQ9Vz7+mBrZ4CK7vCyvL3AbU92j3Cz7qlIr0aobH7za" +
                                          "+nzjQKk0dCiB/ZDdEYiyu2ByctCz20N12O0vl+M31w689NOzdW9AZh8jESrI" +
                                          "5mOBy6C6+UAxL8BUcyzpzzWBf2fIBjE0+I2lg/szf/mNzDk5ssGwXR0/pV16" +
                                          "/PjPL2xbg0ayaYLUQtVjxTm42bq3LllHmbbA50iL4Y4WQUSgAlftCdJQsIzT" +
                                          "BTYBl+hWDEKKF1VpF8+cLWUoNnxBdq8vzuunJqhPi4wP2wVLl+MDVEwfUnFP" +
                                          "Ls0bBccJHfAhZVduWa97Srv1y20/ON8ZG4NEqlAnSL7eLaTLs0zw6qyGm0Av" +
                                          "UbNzLJWcdJzSLE1mvYJ3n8JBuCCRfR4U60JEjdT4+YAk9wX5isuX/g18Bmvx" +
                                          "FRMAAA==");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188908000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAAL05eczj2F2eb46dnd3uzG7b3WXb3e4xW7FN+9mxEyfR9Iqd" +
                                          "w06c03ESu9BZx36OnfiKz9hloSzQUyoVbKFI7f7VCqi2B4gKJFS0CEFbtUIq" +
                                          "qrgk2gohcZRK3T84RIHy7HzXfDOzS4VEpLy8vPe7r+f38wvfQ877HlJwHTNZ" +
                                          "mk6wD7bB/sos7weJC/z9Dlceyp4PVNqUfX8C164rj3/h8r/+4KP6lT3kgoS8" +
                                          "WrZtJ5ADw7H9MfAdMwIqh1w+Xm2awPID5Aq3kiMZDQPDRDnDD65xyF0nUAPk" +
                                          "KncoAgpFQKEIaC4CWj+GgkivAnZo0RmGbAf+Bvlp5AyHXHCVTLwAeexGIq7s" +
                                          "ydYBmWGuAaRwMfs/hUrlyFsPefRI953ONyn8sQL63K+++8pvn0UuS8hlw+Yz" +
                                          "cRQoRACZSMjdFrAWwPPrqgpUCbnXBkDlgWfIppHmckvIfb6xtOUg9MCRkbLF" +
                                          "0AVezvPYcncrmW5eqASOd6SeZgBTPfx3XjPlJdT1/mNddxq2snWo4CUDCuZp" +
                                          "sgIOUc6tDVsNkDecxjjS8WoXAkDUOywQ6M4Rq3O2DBeQ+3a+M2V7ifKBZ9hL" +
                                          "CHreCSGXAHnotkQzW7uyspaX4HqAPHgabrjbglB35obIUALktafBckrQSw+d" +
                                          "8tIJ/3yv/9aPvMdm7L1cZhUoZib/RYj0yCmkMdCAB2wF7BDvfhP3K/L9X/rA" +
                                          "HoJA4NeeAt7B/O5PvfTONz/y4ld2MK+7BcxgsQJKcF351OKeb7yefqp2NhPj" +
                                          "ouv4Rub8GzTPw394sHNt68LMu/+IYra5f7j54vhPxPd+Bnx3D7nEIhcUxwwt" +
                                          "GEf3Ko7lGibw2sAGnhwAlUXuBLZK5/sscgecc4YNdqsDTfNBwCLnzHzpgpP/" +
                                          "hybSIInMRHfAuWFrzuHclQM9n29dBEHugF/kDPy+Edl9XpcNAQJQ3bEAKiuy" +
                                          "bdgOOvScTH8fBXawgLbV0QWM+jXqO6EHQxB1vCUqwzjQwcGGm+WXh04MC0YS" +
                                          "7wLFgPHtZUWBkW0VKrefhZv7/8Vom2l8JT5zBjrj9adLgQmziHFMFXjXledC" +
                                          "qvnS565/be8oNQ5sFSA45L2/472f897f8d6/PW/kzJmc5WsyGXa+h55bwxoA" +
                                          "Ye5+iv/JztMfePwsDDo3PpfZfZsn5YP5n7MQ76nbV+xWVi7YvEQqMIIf/I+B" +
                                          "uXj2b/89l/tk0c0I7t0iS07hS+gLn3iIfvt3c/w7YX0KZBhPMPUfOZ2rN6RX" +
                                          "lrSn7QnL7jFd/DPWv+w9fuGP95A7JOSKclDTp7IZAh7AunrJ8A8LPaz7N+zf" +
                                          "WJN2CXjtIPcD5PWn5TrB9tphAc2UP3/Sj3CeQWfzS3lM3JPD3PtD+DkDv/+d" +
                                          "fTNPZAu7TLiPPkjHR4/y0XW3Z84EyHl8v7KPZfiPZT4+beBMgLfx7if/8k//" +
                                          "kdhD9o6L+uUTxyQ0wrUThSQjdjkvGfceh8zEA5mx/ubjw1/+2Pfe/648XiDE" +
                                          "E7dieDUbM4nhqQhPl1/4yuavvv2tT31z7yjGzgbwJA0XpqHAiZ8fclATzbBl" +
                                          "MzfI4wHywMpUrh5qPYWHHhTs6sqs5KZ6LTzmc9Eyr+zvToo8uaBEV28TridO" +
                                          "9+vKR7/5/VdNv/8HL90UqTcapie713YeyqXaQvIPnM4iRvZ1CFd6sf8TV8wX" +
                                          "fwApSpCiAuuEP/BgOm9vMOMB9Pk7/voP/+j+p79xFtlrIZdMR1ZbcnYQw3Ia" +
                                          "6PDs1mEl2LrveOeuHMYX4XAlz00k1/91O3HytL7n2BCcAw/MD//dR7/+i098" +
                                          "G8rRQc5HWQxDCU5Yqx9mzxDve+FjD9/13Hc+nPsEFt/pB3+r8p2MajVn8GQ+" +
                                          "/ng2FHYey6Zvzoa3ZMP+oZseytzE53WRk/2g56hZ+VFzT71s6Rh6sGAFRnRw" +
                                          "QKLP3Pft9Sf+4bO7w+90nTgFDD7w3Id+uP+R5/ZOPHI8cdOpfxJn99iRC/2q" +
                                          "I1c+9nJccozW33/+md//jWfev5PqvhsP0CZ8Pvzsn//X1/c//p2v3qJSnzOd" +
                                          "w6DMRvyAbfZTfmXHBnf9PFPy2frhh8NEGY+VMWGHaYiWbGU04MFQNMaE3u8n" +
                                          "rs6zU73WEINZyPiFYXux9tW1HymVIFW3dlixautyoRDzxY5E19OC0eUMjB24" +
                                          "mhe5oznWEZZdatqkOsFUoDaGSNO4wW2XaJeV2VFzGHeFSjmSwlpxUSiyzaYr" +
                                          "4YsILBaVCiGjKSZNOU8JuAZHNed8XE5L5GBmdReKpG1YflokWlbdrYCmiIKw" +
                                          "o5JquHK75EDtyk6BXI9NDJdW1EQtaOzE7yfUQsDK69LWDQcdWSkrWx04vfbW" +
                                          "W1lxkWCtqrjdyCwvBTbP0LY0svmRMl3qkbu06hNm2aJUQ6LWDi90mKYTNXCh" +
                                          "08PlCp+Wyb5Pk/SAYpRJr1DZKiN1M3ELS3oy5psiL/O6EbYNd6tUaitLCGRs" +
                                          "LMXTsZYIQOrbS3/YsWqyJA61dDEvVMCqMufWeGxNNzNOHpMVk7HwUKSx8mCd" +
                                          "imBgGWlkG7LWqTTX+Hhcb21G6GzWletdsSO2PL7oKzQ5DcWpYgzxFqsKckco" +
                                          "40tnTVM1UxgpiQWfodJeII3EbkPhJvNxqb2YRxxuOEGRtEvYcNYxRXUYMFVv" +
                                          "HHgW3wn0VK6X2sulvuytlXZnYmKlpKITvErOB+s47thpSoVCvy/WVqlKjl3J" +
                                          "KDl0yNXWreVoxvREc1KrzUpNbbQaK5ioDRKgryWhX54vFHk9U+liUlOn8sRo" +
                                          "Ky06TkYNCrASTTAmI4din9+q6ymqN2eKVpjEPZrpEsNeuZ0m5HbD1Z06tjHp" +
                                          "bXc866+aDWemmvXFfKYvG+ullUS8Pg4qUyqwLUmijV6iN0AQLGlPGDv0KjaS" +
                                          "vhhbXbE9DxxQbQ0bw7K8bpQL5Ha7wRxDbPQGQb9nMtUJM3A6zMTr9pw4Ter9" +
                                          "os+YWtUKMbI6SwWBrYOZz85Aq1om+vNFYGsK2pzqi/6qXo5X5LTfayZmwKkE" +
                                          "WbCF1TLVGIGN21tC7KsM2SqvOM71cNWR2UZLlr0J1SRK5LxvYCqqDUFtUmmi" +
                                          "Y8GeUF17suAGIz1dbbBBUhXLRo+oiv52Yy4LS2j0jlhgI8XmG3i1E+NcFxjj" +
                                          "SU8yRYcTLKojSNUg6rWabb5Ld6ywofqNDk6quM4ammbEJd2lSqDptGyu2EIH" +
                                          "RH2s09NEdUvmpikGcYWdYLVtG1Wx5rQTY3hDnvPNoZAmqhJW6zpF9fA0EZ1t" +
                                          "sz0AY39Q1tVhSrllozuSdHzd3jY0Bl/1B9wYFwx8UBpo1Wi8ngtg2Dc6dW4Q" +
                                          "0mWFXqesYzOLImUOZT5sldSml5ISEPB2ewMYiXfri+VcVaDiHGEzrUGRVPsl" +
                                          "s9np+UGXHSbDuR4yllMvNUbDVI+h7Ti/oi+b9qIvLgkxSjYTRdA29WXSkiTN" +
                                          "RRVfKtdaClqo9hknmWympQ0+Yi1NnLFOs1Nk/eKwLYpKtE22dmPYAMCakJu4" +
                                          "pmoRLbbqbFyz0qZPofOmqHe73HTke5VSEq4JgjArlWkX4xi9N2LWodtlOFrt" +
                                          "1LFiY7GhxabMx/OuPBfNSNO5mBtGKEUx4/ayvimnWzYiCZsTB1ilzlBMOVrj" +
                                          "owKDOpRfbcm9mVpUNl2ONb0aWfDJtQJCrGlquGpunDLdITyrhaJVXkvGRIUk" +
                                          "R0KM0UEEo2Q9s6j1qC86fheXu/zU3PIoVnYXxBSELYIoRMPGWu1MpA623GDd" +
                                          "Ym/ilqjGcBSg47JH8EQnaY+UYVSr4JTmFBq0pxTd9aCyURfEkHf6tSW3oil1" +
                                          "zZcoWh57VOiFUcGIR62IMAtooaRp0rKyGfUiiyLGOFnEOqu43JjgZYaLiLGQ" +
                                          "aOXVel3uDyPCW8zDIj3lxBU3wBYBx3RHWJ8ax9Qk3TSi2WY5GJmbOgnKsemA" +
                                          "wFQ5vKayc8EoAFJSASzcgKNXgtDWieGMsVp80dx0xljSdahVh94CiZTDlpAA" +
                                          "acgq82isV1cJRraSer3TdCMFAGZTc4wAVRYaFy+mC5MPOwSMqqGZktP5RCfj" +
                                          "egiSuawnjFyL3HJjStB6vdtlQguN4y4xSrlR0LPiUpSsFoBut9By1TOxlr+0" +
                                          "RmsnwrW0TjEoqYtzLpITrUAYw864wStClMrwTHOLnia5RMIqlU1T0ScRwId2" +
                                          "sViwVhg70ZWF2YaPPzWDM4oTTJDX/Eab0mFMtmvCNC7UJ9ic6dktKhDmeL0M" +
                                          "xIpnKk1WpGvl6rqxmhSUSrVfq9XGmykKOkuWXQzSbrFWHhLlcDw1R5PptlJc" +
                                          "YrV40t+QbicJsIAQBWYTbsU5mHF+rVqAR2hpIm3JHlh5DCWbkl/H1EakzgUe" +
                                          "i0ckwKplDcgVO40kEPLNpqej1BJWgDU8j4N6WdHNLlYhulF7I/mNiK2p9tD1" +
                                          "Q8Ledk1aqZfgI2p7SNAssGZy6nS3ZXyh4ZGGGivPHURbTMdWDV7qB3Omy5KV" +
                                          "HjeuL1Z1gkJxnGTSTUufo0aMx0HTZ9aEEM5jre73N0VFoWEtwvQRnpbDGqEN" +
                                          "o0aJDMJkTK4LitU30WhO9QoNk6g2UJNBpyw6L/U1iQ+ZuL1egnZYLxptRhkm" +
                                          "pf4k7CdByjQqGr7eUv3UbLXbPCxQvtOyYOT61kZtAUDIRU9uVWpiWUtMV2K8" +
                                          "wsJZBGt6I0rd3pzyzdRWOuLW5Rb9ru8oBak3dbmg26qq1Mgrs8yE7aLbiSL2" +
                                          "hqVlMOkSCQXmbt1i4hq7kZQlHU38drexJHGb6QrihiLJJFyohTW3bvRqG2DY" +
                                          "iVCstXgnCR0aN7sArxSr/VFtmlYKFuVJJbpbiegk4oj6QqjhK4JOKxuT9TDZ" +
                                          "WTCVVC7Y6WrUXWMqbVCo1FCbopGEOJUoAZ3iWL+ID7DILPSIYkxWa/1Bqs5q" +
                                          "dQkmUpP32LI1oBKSJgtCfctVKUFJUjdNZ5SGayy1amIFFjeXqJ9qqNVPG+uy" +
                                          "77fj+RhD3WmRRIerIYdvF0tMTmSRE0bBdLWdWCV8sSE4Ez4ALRb1MmZwJbE0" +
                                          "Gwn8sm5qAaypI59NJ9REpMyCPms0u91Wceq2qgWFmwlO395S6qYapWFodzb6" +
                                          "0CjFQzyeclD+xrQZa4LdgicEtqAUpcNodV2aquFMrlV4LyomOIYO+lWpXeo3" +
                                          "N2bd5rkKvH9MIHgak5ukbWH1SFj0U64zU9ROynPNohWJHcKudqiQpsfauCSQ" +
                                          "WKe5Uielglhf1+J52fDDObosVikr2rbGPfjQ/ba3ZY/j7I92I7o3v7ge9Tvh" +
                                          "RSjbwH6Em8D25RgGyEV54QcevC4GyJ1HDdgd9xOdmzOHF+X9/2XH6KBblF2M" +
                                          "Hr5dBzS/FH3q2eeeVwefLmaXooxHA8oROO5bTBAB84QEe5DSm25/AezlDeDj" +
                                          "Js2Xn/2nhyZv15/OuxQ3NY845FKGOcz67Ef99DeckvM0yd/svfDV9huVX9pD" +
                                          "zh61bG5qTd+IdO3GRs0lDwShZ0+O2jUe8vhNt0ZHAWrogWO+b3pU/uL1Lz1z" +
                                          "dQ85d7KPlVF4+FRX6C7N8SzZzBgc9sIvBbrnxMcrJ1tE0Kx5j+4J+H30oFma" +
                                          "/2a7r3az8TXb41C7KYb2joJ2fBAxHvLG4+4E7ZgmUHKrXxVsK7/MywsTZJ3C" +
                                          "/7z8ZPGL//yRK7urrglXDt3w5lcmcLz+YxTy3q+9+98eycmcUbK3C8f9lmOw" +
                                          "Xcv61ceU654nJ5kc25/9s4d/7cvyJ88iZ1jknG+kIO8hIwfNy0woPVdbycfl" +
                                          "qb1VNmRvCaCzvOAWXdMc6x0ncpSGd/nIMdTj5H36la7xJ5nmC++60X2Pwe+T" +
                                          "B+578v/kvtsrGr/MXpINHrQ9sNVbmCDbNY/V9X8UdbcB8tDte9GZUx+86S3Y" +
                                          "7s2N8rnnL1984HnhL/K0OXq7cieHXNRC0zzZPj0xv+B6QDNyre7cZYqb/7w3" +
                                          "QB64TeXLmo/5JBf+Z3bwPxcgV07DB8j5/Pck3PsC5NIxHCS1m5wE+WCAnIUg" +
                                          "2fRDWZf2RE08CIfcrPe9klmPUE62WbM6mr9tPKx54e5943Xl8893+u95ifz0" +
                                          "rs2rmHKaZlQucsgduyJzVDcfuy21Q1oXmKd+cM8X7nzysMbfsxP4ODRPyPaG" +
                                          "W6d/03KDPGHT33vgd976689/K281/g9e8vHKBh4AAA==");
}
