package org.w3c.dom.events;
public interface CustomEvent extends org.w3c.dom.events.Event {
    public java.lang.Object getDetail();
    public void initCustomEventNS(java.lang.String namespaceURI, java.lang.String typeArg,
                                  boolean canBubbleArg,
                                  boolean cancelableArg,
                                  java.lang.Object detailArg);
    java.lang.String jlc$CompilerVersion$jl7 = "2.7.0";
    long jlc$SourceLastModified$jl7 = 1471188907000L;
    java.lang.String jlc$ClassType$jl7 = ("H4sIAAAAAAAAALVYfWwcRxWfu/P3t53YSZPYiZ1LhNNwpya0ojiExo6dXDg7" +
                                          "h51G1CG5zO3N3a29t7vZnbXPDimlEqpBIgrB/ULUf7lqQf0SogIErYKQaKsW" +
                                          "pJaIUlBbJJAoHxGNkOCPAOW9mb27vT07lUBE2vHezJv3/X7vbZ66Rmpti/Qx" +
                                          "nUf4gsnsyKjOE9SyWXpEo7Z9AvaSysMh+rcz703cGSR106QtR+1xhdpsTGVa" +
                                          "2p4mvapuc6orzJ5gLI03EhazmTVHuWro06RbtWN5U1MVlY8baYYEJ6kVJ52U" +
                                          "c0tNOZzFXAac9MZBk6jQJHrIfzwUJy2KYS6UyTd7yEc8J0iZL8uyOemIz9A5" +
                                          "GnW4qkXjqs2HCha51TS0haxm8Agr8MiMdrvrgmPx26tcMPBc+99vXMp1CBds" +
                                          "oLpucGGePclsQ5tj6ThpL++OaixvnyP3klCcNHuIOQnHi0KjIDQKQovWlqlA" +
                                          "+1amO/kRQ5jDi5zqTAUV4qS/kolJLZp32SSEzsChgbu2i8tg7Y6StdLKKhMf" +
                                          "vDW6/PCZju+ESPs0aVf1KVRHASU4CJkGh7J8iln2oXSapadJpw7BnmKWSjV1" +
                                          "0Y10l61mdcodCH/RLbjpmMwSMsu+gjiCbZajcMMqmZcRCeX+qs1oNAu29pRt" +
                                          "lRaO4T4Y2KSCYlaGQt65V2pmVT3NyXb/jZKN4U8DAVytzzOeM0qianQKG6RL" +
                                          "pohG9Wx0ClJPzwJprQEJaHGyZV2m6GuTKrM0y5KYkT66hDwCqkbhCLzCSbef" +
                                          "THCCKG3xRckTn2sTBy6e14/qQRIAndNM0VD/ZrjU57s0yTLMYlAH8mLLnvhD" +
                                          "tOeFpSAhQNztI5Y03/v89bv29l15WdJsXYPmeGqGKTyprKbaXt82MnhnCNVo" +
                                          "MA1bxeBXWC6qLOGeDBVMQJieEkc8jBQPr0z+9J77vs3+HCRNMVKnGJqThzzq" +
                                          "VIy8qWrMOsJ0ZlHO0jHSyPT0iDiPkXp4j6s6k7vHMxmb8Rip0cRWnSF+g4sy" +
                                          "wAJd1ATvqp4xiu8m5TnxXjAJIfXwkAA8HyfyXy8unHwmmjPyLEoVqqu6EU1Y" +
                                          "BtpvRwFxUuDbXDQFWT8btQ3HghSMGlY2Or9fiaaNfJTNARGkiGNzIz+KPyKY" +
                                          "Wub/g2kBLdkwHwiAk7f5S1yD6jhqaGlmJZVlZ3j0+jPJV2X6YMq7PuCkD+RE" +
                                          "QE4E5ESknIhHDgkEBPuNKE/GD7w/C3UMQNoyOHX62NmlgRAkjjlfg74riMLa" +
                                          "WvwBF316iRL+5JT52K9+/sf9QRIsV3u7B6anGB/yZBjy7BK51FnW44TFGNC9" +
                                          "/Uji6w9ee+CUUAIodq4lMIzrCGQWwCXAzpdePvfWu++sXg2WFA9xgFgnBZ2K" +
                                          "kwaaAnyiCueksQQ00rCNH8C/ADz/xgdtxA2ZNF0jbubuKKWuaXrcERDvm6Fa" +
                                          "1nC5cDb6q3c9EBAAtnr/8kr6+OO3yVLtqiysUegbT//yX69FHvntK2tEupEb" +
                                          "5kc1kKd5lAqiyIoJYFzgY7GbJpW32y7/7gfh7HCQ1MRJF3jFoRr28kNWFrqE" +
                                          "MusCaUsKxoJyd97h6c44VliGwtLQHNbr0i6XBmOOWbjPyUYPh+LsgCi5Z/3O" +
                                          "7Vf9pfv/tOXEwdxZkWbeXozSaqGN4M0EdtBSp9zuc7+f5bfGn3rlyG7lclA0" +
                                          "DwTiNZpO5aUhbyBAqMWgS+poDu60gtABf+36vZVU9uygzydfuBAWUWiEDsop" +
                                          "IB40pz6/8IoGMFQsLxTVAE7IGFaeanhUdHkTz1nGfHlHgEqnzHZIkC5M7q3w" +
                                          "9LsQKf7iaY+J6yYJQoK+T6z9uIRlduHrLlx2C7KPQLbtLlcwYLoGEIgRCd+t" +
                                          "Q9jVjEpTGkNs+Wf7rtue/8vFDpnIGuwUQ7T3wxmU928ZJve9euYffYJNQMGZ" +
                                          "oowyZTLZqDaUOR+yLLqAehS++Ebvoy/Rx6DlQZux1UUmOgdxEQ6VGhFmHxTr" +
                                          "sO9sFJdPQPFlGT/MIGhaEQU6hDCcOCKyvYIC4XVy2zMgJpVLV99vPfn+i9eF" +
                                          "SZUTphdCx6k5JGOJyxBiyyY/iB+ldg7oPnZl4nMd2pUbwHEaOCrQfuzjFnSO" +
                                          "QgXgutS19b/+8U96zr4eIsEx0qQZND1GcZaDjgypxOwcNJ2C+am7ZLrMN8DS" +
                                          "IfxBqjxUtYFR2L52fEfzJhcRWfz+pu8eeGLlHQHeEmD3ldK1Gdnsh+cON133" +
                                          "/U/pWhnYWkFVu0YE5cyI+/eABQNlQEXkmnKgnyQsNQ+9bM6dy/YlzipL4cTv" +
                                          "JZDfssYFSdf9ZPSrJ9+ceU1AWANibAk4PAgKWOwp3g6hOwZ88CZfOZX6RC90" +
                                          "vTv7zfeelvr4h0ofMVta/soHkYvLsjbl5L2zavj13pHTt0+7/ptJETfG/vDs" +
                                          "hR8+eeGBoFtNEU7qU4ahMaqXghJwmyuMGpVelLoe/nL7jy51hcYAOGOkwdHV" +
                                          "cw6LpSshud52Uh63lod1CdAerbHbw0y0xzTF7mlcjojXz94EBGZwmeKkU9VV" +
                                          "7hmuJqYE+RnXI/gnxUnNnKHK75MYLifkQfy/LCjcmDQLnDR7BGOZba76JpTf" +
                                          "McozK+0Nm1buflO0mtK3RgukX8bRNI/bvC6sMy2WUYW1LRJ1pIccmIuqxx0Y" +
                                          "tuSL0JdLUtTRQ8pJCFYvwXmIvksAh7B6D++FLTjE1y9AdAKVc2jJm90f5k3P" +
                                          "6LqzonrEl3YxvRz5rZ1Unl05NnH++h2Py0kWvtEXF8WXGSSVbLWlyaJ/XW5F" +
                                          "XnVHB2+0Pde4q5jtnVLhMmBt9eTUJOS8iXHc4mtadrjUu95aPfDiz5bq3oA6" +
                                          "PUUClJMNpzzfubLrQOdzYAQ8Fa8uHpjLRDcdGvzGwsG9mb/+RiCuW2zb1qdP" +
                                          "KlefOP2Ly5tXoes2x0gtFDIrTMNHu314QZ9kypw1TVpVe7QAKgIXlWoVldmG" +
                                          "KUcRT4VfXHe2lnZxOuJkoBpvqkdM6E7zzBo2HD3t1nZzeafivwCKw5ljmr4L" +
                                          "5R0PxGZkycrBP5SMj5tm8UOgPmOKosv6EUpsituXxCsuX/sPygRol4UTAAA=");
    java.lang.String jlc$CompilerVersion$jl5 =
      "2.7.0";
    long jlc$SourceLastModified$jl5 = 1471188907000L;
    java.lang.String jlc$ClassType$jl5 = ("H4sIAAAAAAAAALU5eezk1lne396bNLvZNgdpc28rUqc/ey7PjLaXx+PxjMdz" +
                                          "eGY8hwvd+LbH5/iYsV2CSkRpoFJaQQJFavNXK6BKDxAVSKgoCEFbtUIqqrgk" +
                                          "2gohcZRKjcRRUaA8e37H7G83iSrESH7z/N73vvv73nufX/oedDbwIdhzrUSz" +
                                          "3HBficP9pVXZDxNPCfZppjIU/ECRCUsIggkYuyE99oXL//7Dj+lX9qBzPPRG" +
                                          "wXHcUAgN1wlGSuBaa0VmoMvHo6Sl2EEIXWGWwlpAotCwEMYIwusMdMfO0hC6" +
                                          "xhyygAAWEMACkrOA4MdQYNEbFCeyiWyF4ITBCvpZ6BQDnfOkjL0QevRmJJ7g" +
                                          "C/YBmmEuAcBwIXufAqHyxbEPPXIk+1bmWwR+AUae/7X3X/md09BlHrpsOOOM" +
                                          "HQkwEQIiPHSnrdii4ge4LCsyD93tKIo8VnxDsIw055uHrgaG5ghh5CtHSsoG" +
                                          "I0/xc5rHmrtTymTzIyl0/SPxVEOx5MO3s6olaEDWe49l3UrYysaBgJcMwJiv" +
                                          "CpJyuOSMaThyCD18csWRjNe6AAAsPW8roe4ekTrjCGAAurq1nSU4GjIOfcPR" +
                                          "AOhZNwJUQuiBV0Wa6doTJFPQlBshdP9JuOF2CkBdzBWRLQmhe06C5ZiAlR44" +
                                          "YaUd+3yv/87nPuC0nb2cZ1mRrIz/C2DRQycWjRRV8RVHUrYL73w786vCvV96" +
                                          "dg+CAPA9J4C3ML/3M6+898mHXv7KFubNt4EZiEtFCm9InxLv+sZbiCfqpzM2" +
                                          "LnhuYGTGv0ny3P2HBzPXYw9E3r1HGLPJ/cPJl0d/uvjgZ5Tv7kGXOtA5ybUi" +
                                          "G/jR3ZJre4al+JTiKL4QKnIHuqg4MpHPd6DzoM8YjrIdHahqoIQd6IyVD51z" +
                                          "83egIhWgyFR0HvQNR3UP+54Q6nk/9iAIOg8e6BR4atD292DWhBCL6K6tIIIk" +
                                          "OIbjIkPfzeQPEMUJRaBbHRGB15tI4EY+cEHE9TVkU5IQ2bURZQ2AgItEQeja" +
                                          "ZPayn7mW9/+BNM4kubI5dQoo+S0nQ9wC0dF2LVnxb0jPRw3ylc/d+Nrekcsf" +
                                          "6CCEHgJ09gGdfUBnf0tnf4cOdOpUjv5NGb2t/YD2TRDHIMPd+cT4p+mnnn3s" +
                                          "NHAcb3Mm012cB9b9+ctpsO6JV8+6rSzkO3mak4AX3v+fA0t85u9+kPO4mzgz" +
                                          "hHu38fQT63nkpU88QLz7u/n6iyDHhALwCRC+D52Mt5tCJAu8k7oDqfMYb/Ez" +
                                          "9r/tPXbuT/ag8zx0RTrIy1PBipSxAnLjJSM4TNYgd980f3Ne2QbR9YP4DaG3" +
                                          "nORrh+z1wySYCX9212agn0Fn/Uu5/e/KYe7+EfidAs//ZE9miWxg681XiYOQ" +
                                          "euQopjwvPnUqhM4W96v7aLb+0czGJxWcMfCusffJv/qzfyrtQXvHifnyzlYH" +
                                          "lHB9JxlkyC7nYX/3sctMfCVT1t9+fPgrL3zvw+/L/QVAPH47gteyNuMY7Gxg" +
                                          "h/jQV1Z//e1vfeqbe0c+djoEu2EkWoYEOkG+UQFJVMMRrFwhj4XQfUtLunYo" +
                                          "9RRsXICxa0urmqvqHrBV56xlVtnfZvs8kABH117FXXd26BvSx775/TdMv/+H" +
                                          "r9ziqTcrpid417cWyrmKAfr7TkZRWwh0AFd+uf9TV6yXfwgw8gCjBOI/GPgg" +
                                          "dOOb1HgAffb83/zRH9/71DdOQ3st6JLlCnJLyDZTkBJDHey/Ooj62HvPe7cp" +
                                          "bXMBNFfy2IRy+d+8ZScP67uOFcG4YNP7yN9/7OsfffzbgA8aOrvOfBhwsKOt" +
                                          "fpSdA37hpRcevOP573wktwlIoNNf/O3SDzKstZzAW/P2J7MG3los6z6ZNe/I" +
                                          "mv1DMz2QmWmc5ztGCMKeKxvgHCDnlnrN1DH0DRt42/pgk0Oevvpt8xP/+Nnt" +
                                          "BnYyT5wAVp59/pd+tP/c83s7x4bHb9m5d9dsjw450284MuWjr0UlX9H6h88/" +
                                          "/Qe/+fSHt1xdvXkTJMEZ77N/8d9f3//4d756m6x8xnIPnTJriwdks7/K6xs2" +
                                          "vONf2+Wggx/+mOlCnW2kUTxTI2RYCiulxZgfLgy+wOj9/sZLBNRdGmTsYvK8" +
                                          "qVX1SoEqEFQlHZT6JaFYD6tr3hHnw6ZhW+TKa3Q0v4FwDKdWrRWromNX65D+" +
                                          "ossK3WDm0UKHsxoiTeNuO6b65oAY4oNZ3RaL1fUErVpcgyyu20pKr0vIvLoW" +
                                          "eQwb2V5oIGzscGpZC5wg6S4HZH2czOYe6Vb5Or4WxknQ02FfSqtoSaLGowKK" +
                                          "seEILsS67AUTaioUvbINdtlIwlw/pSsa00FLpC6k9mTajma+i2IjMZz1K1yh" +
                                          "N7UWNVFYLEgaM6d0pchJaNgf8GlrjgtSvcc3TGzJ0m2/o6Ybjk6K3cUY45KJ" +
                                          "XE1IqUajBs/UomSg2J20jlcoZ1ZemfPlKii2CV2oFCZjVBdiu4Zrfq1n9GR/" +
                                          "7Wv2MC5iodQbNiS4Xl/Pe16BaMiBywB+KUoZSlbAVsIlNtE9BoYHghGvnWRY" +
                                          "Mi1C6rejzoB12gbaXXaabJd11zNrZeFwQbAHiDliK8umUUlXE5yblldjxHQt" +
                                          "muG9UnE8JtOA0DUxKhq1UKsusHEoM92u3lPXzRkGLgv8MoLJ8TBAhala6E5H" +
                                          "bXzMlQnapPQqXTMsp+jOx4InyLS3qTYcuzsbL6cFdFFALaxgy5IrE21kxIhL" +
                                          "z+5txr0ggrWlQYi8sJR6vZXNSyNCmcOroOD28ahY90ahNRIG5Ul5UeyOiYUl" +
                                          "UGyIVaZFz55OSv1kLiJLvtsvc7UmPk3CNB0oPXRlCA7bpbARiE+dqs9ilLDo" +
                                          "YbqhPZ8laaFNJfy0aGNUNOn6PTSpdBfmBMP05oZYmaJOMCkxFhV10iaILlWK" +
                                          "R5I5cYrBpJFgSqGMrNhRB3fkfg+dNhHeX3KVaoAmE6a3sPB2zWYYZ603w4HS" +
                                          "8sa4zvbTsFNZoCVkXauL62LdKlRmMh3MF0NboVZUF4S93xWFeVgr9hzdIfpT" +
                                          "t4cXxFhpzGcEtmIGlNJsTHssbSikKdWWDXbooylcp6vVdVCC28So35t2HYpe" +
                                          "TfQ0XU07SW0183uDgEZ5qz1Al+1xMpygRtMYmnOvvMQCzKyu273YFmsjw0Ol" +
                                          "0cwZt2CtHCQbnJYL+GS98sqxEdXsysSJ50uc7qjzjYnjtXaiJvOkFjntjW0v" +
                                          "hwlDutPVKsJIrrBohN56tGnFXNQU5022NZvUxJAttTV93KOsRXHg11VDEPoq" +
                                          "PenjI8o0qH7aSeHuMOkuZpGIaEWzwcjmpr0xcLOqVsaFpIkt9ZVAWTbNTy2+" +
                                          "tETh5ZCeFufYoreqDiPCbMIjkiXLZIUcm05Hbzc1k2wMo36XRKhmdYMQJa7H" +
                                          "9t1k0J5jxb5taSPcXC4tVauWfaPHCLP1ptEqFTBjxMAVelIpduswEqh1YN9g" +
                                          "WoqqDUxwqAaS8I1lUm10K4UWCNrypEX1iTrCLQ1sU1cUmOA4vOPKq7LV66Q+" +
                                          "QbGzDTHHU09Whmt1FsFwMNeKsxZej7WW5jT4YtfcCALuJAYRKWbAsijqE/12" +
                                          "jUDwZorEmhzGeJHvt9ClGIlRtzuLhLkvkaPm2sZaQsEhKlJTxFYlqU42cDx0" +
                                          "fKRm+hg8GJSSKROujCTgFE2cIEgyx+qt9toJu8WQjDxSrJhSwezKFQsHUB2X" +
                                          "XrRSbVGlRNqblYpJFalqql5tE2yhN6JbpWXLHfnFmtmftfwV2YsCQuCCbuzS" +
                                          "iVyv6phULk8tg9qEDNvuiz5qYPOGPRjMROAY3GKow0ygEUaFR0qD6lSte+oa" +
                                          "CQdzciPHvDkTlbmbjoUV1S/3UFIOG2OvnkZSFVYroko5Jd9KqKolWTja3EyM" +
                                          "Pu8NKgKni0kDX/Vm2hj23GaEoVqIN1S4hK35KVePEi1NZDVq4DNuZpDNwPU6" +
                                          "jTLqpRhS67hUr8UGTDyZ4mS1Q7UERXB0Tm6bk7TgUGrbamvkyknbfMckKr3q" +
                                          "qrSpMwHbVauGsIBpLFnQrNuFJ1hajzojS47aPmPFRaLaHbKMGDKWtFkwLkV2" +
                                          "tBEhwyFbX06XpDehzH4Az9SqH0YKUlu3mp7ToaINx1YnpU1sc/VijafXSl2J" +
                                          "Fqq6oPtsj+Jdd5PwE4ZfNQVuMIIThlnhij6GYVJcuwkyirGmxfJRXOA4e6DJ" +
                                          "McliU0pv2e144geDetCi5SE7bFnUBOl1KF0gWQ7kNUIaEN1kvegQ5fk0KaY9" +
                                          "jfamzBTsKUPVgY260hrz3MTTZSLGzApNDegkbhhJskCMBmzJWtUdOrxVdnpy" +
                                          "0ePETZsUBoTPqlG6bDnjAavNtSgcF+oiAte4Opb6ZaUTkDG6Yvl+s0BJvNBc" +
                                          "aokXDzZSny4SsGBXecbv9WvNcUeNG6tlzIWL1qjIVIoqqaa0DpKSmsJeVFMU" +
                                          "irHabFsh7WbJkrsFSnYCHZYG/UKphHCIN9OdxcxsTSN0QVakpAMjCt5g+xZL" +
                                          "zk3b6WpOwgZ9Fq6LPUxOkIWVGh5TliZrmm+qQbBojWW1zg/HPl2HJYUr4DO8" +
                                          "b4i4WR7iWnc22HglDdMHG75WI3h1wM+xEVFH15N1NVUVxVr7ZR111d40FMD1" +
                                          "u20u1kywFK0KU0yF9bJQ8tqTEIWriBfS5ESlkHUz0Ec1GAjVcFthn+SqK64s" +
                                          "gKP5aq7p9MZOoh7lTRWLcRXEYarLpFLQpQU+oAbmRm5PpQ3GeONAj2Rw+NCx" +
                                          "kuXKBULGFV9sixs0QeN00qralrR0l/O0XiYbFL+xla7J1afTqm5H9GpBwiNn" +
                                          "3kE0J+acvtNtd6uV3oIxVJNVE4QhlpLdZBmnOao2qAEvClWM9iZqT3LTLoz2" +
                                          "7YIYqdYAtcNuaaRF5rwmjvodRFwTWNBLijNuMSswI7rgdSTJ7kSrOEYXYTRm" +
                                          "UFpmuHAyYmseTbQW683c7qzNANdBhm3CcIuZLMlCUsdlvDuVikvarqNqxSwN" +
                                          "MWaVuo5PWqVFvB6lFZ8vcI6FVvpOG4b14jBBzdk6JOet2mxOjcdTkZlZiUAj" +
                                          "81mlNXem7UYRRoeyUl5VlqEzZfSe3QjryoSjB+OaMW9LZTsUZLB/R/WKMFSb" +
                                          "RloRVyUXx4YcB44Lvb6XpmokMj47kNMFztZaQi1qe0tm1JRkap1Sm4AC51ME" +
                                          "HoFMPiumYmElD7uWog6GRSaphHNXCYoxyFKtZsef9MCJrFQos3zdTLxNYTIF" +
                                          "hq6yeFfrzK2ZO7Vkm+py0mhSnqrztlK0HD4eRLTpNrz1ypR7GFlN04ZbbDdL" +
                                          "YcHhU0VQjfWG6G4q1tL2y0xlhA5jijcTyW8MK+PeshLaNW6gDe1B1w3WYI/2" +
                                          "wD07msdEEM2RYJhoI9cqcxNwyn9Xdvzv/Hg3sLvzi/JRjRRcvLIJ9Me4ecSv" +
                                          "RTCELghiEPrgehpCF4+KtlvqO5WiU4cX8/tvU43K61DZlevBV6uP5tetTz3z" +
                                          "/Ivy4NOF7LqVYWsCiqHrvcMCaKwdWnsA09tf/WrZy8vDx+WfLz/zzw9M3q0/" +
                                          "ldc/bilLMdClbOUwq8IfVdsfPsHnSZS/1Xvpq9TbpF/eg04fFYNuKVzfvOj6" +
                                          "zSWgS74SRr4zOSoE+dBjt9xHXUmRI185pvv2R4Qv3vjS09f2oDO7FbIMw4Mn" +
                                          "6k13qK5vC1ZG4LBSfinUfXdzPLJbfAJqvZq5w5vB8+hBKTX/z2bf6GXtm+Jj" +
                                          "p7rFW/aO3HN04Bs+9LbjugfhWpYi5Vq/xjl2XiYQREvJapD/dfmthS/+y3NX" +
                                          "tpdoC4wcmuHJ10dwPP4TDeiDX3v/fzyUozklZd8ejis5x2DbgvYbjzHjvi8k" +
                                          "GR/xz/35g7/+ZeGTp6FTHehMYKRKXmGGDsqiGVN6LraUt9qJuWXW3AAuqylh" +
                                          "UwGGsW5Tq9pWEI/j8qnXqwjsUskH3ndkrzuywRJ4sAN7Ff9P9rpZsrM51Nmj" +
                                          "XILmM+/ZySVECJ0XXdcCB7jsdZM12/Ld+jW09IGsWYG0ZThGuFOl7o9vR+DM" +
                                          "2jXkY235P4624hC6Y4dAZvX7b/mItv3wI33uxcsX7nuR+8s8ro4+zlxkoAtq" +
                                          "ZFm7ldud/jnPV1Qjl+riNpS8/O9DIXT11iQYQue2nZzRn9+CPgt43AENodOg" +
                                          "3QX4CFDyAQCYBO3u5HNgCExm3Y9m5eCdFHngLLnWrr6e1o6W7NZzs7Saf5o8" +
                                          "TIHR9uPkDenzL9L9D7yCfXpbT5YsAVx2AZYLDHR+m3OO0uijr4rtENe59hM/" +
                                          "vOsLF996mPLv2jJ87Lg7vD18+2xA2l6Yx2/6+/f97jt/48Vv5TXN/wUBLtYY" +
                                          "Mx4AAA==");
}
